Repository google/fonts, pull requests merged in 2020-10, with the labels that each got.

#2718 Ballet: metadata fixed
  ofl/ballet/METADATA.pb
Labels: Ready to push

#2378 HindGuntur, InknutAntiqua, Khula, Padauk Hinting
  ofl/hindguntur/HindGuntur-Bold.ttf
  ofl/hindguntur/HindGuntur-Light.ttf
  ofl/hindguntur/HindGuntur-Medium.ttf
  ofl/hindguntur/HindGuntur-Regular.ttf
  ofl/hindguntur/HindGuntur-SemiBold.ttf
  ofl/inknutantiqua/InknutAntiqua-Black.ttf
  ofl/inknutantiqua/InknutAntiqua-Bold.ttf
  ofl/inknutantiqua/InknutAntiqua-ExtraBold.ttf
  ofl/inknutantiqua/InknutAntiqua-Light.ttf
  ofl/inknutantiqua/InknutAntiqua-Medium.ttf
  ofl/inknutantiqua/InknutAntiqua-Regular.ttf
  ofl/inknutantiqua/InknutAntiqua-SemiBold.ttf
  ofl/khula/Khula-Bold.ttf
  ofl/khula/Khula-ExtraBold.ttf
  ofl/khula/Khula-Light.ttf
  ofl/khula/Khula-Regular.ttf
  ofl/khula/Khula-SemiBold.ttf
  ofl/padauk/Padauk-Bold.ttf
  ofl/padauk/Padauk-Regular.ttf
Labels: Ready to push

#2738 Ballet: METATDA.pb updated with registry_default_override
  ofl/ballet/METADATA.pb
Labels: Ready to push

#2721 Libre Franklin: Version 2.000 added
  ofl/librefranklin/LibreFranklin-Black.ttf
  ofl/librefranklin/LibreFranklin-BlackItalic.ttf
  ofl/librefranklin/LibreFranklin-Bold.ttf
  ofl/librefranklin/LibreFranklin-BoldItalic.ttf
  ofl/librefranklin/LibreFranklin-ExtraBold.ttf
  ofl/librefranklin/LibreFranklin-ExtraBoldItalic.ttf
  ofl/librefranklin/LibreFranklin-ExtraLight.ttf
  ofl/librefranklin/LibreFranklin-ExtraLightItalic.ttf
  ofl/librefranklin/LibreFranklin-Italic.ttf
  ofl/librefranklin/LibreFranklin-Italic[wght].ttf
  ofl/librefranklin/LibreFranklin-Light.ttf
  ofl/librefranklin/LibreFranklin-LightItalic.ttf
  ofl/librefranklin/LibreFranklin-Medium.ttf
  ofl/librefranklin/LibreFranklin-MediumItalic.ttf
  ofl/librefranklin/LibreFranklin-Regular.ttf
  ofl/librefranklin/LibreFranklin-SemiBold.ttf
  ofl/librefranklin/LibreFranklin-SemiBoldItalic.ttf
  ofl/librefranklin/LibreFranklin-Thin.ttf
  ofl/librefranklin/LibreFranklin-ThinItalic.ttf
  ofl/librefranklin/LibreFranklin[wght].ttf
  ofl/librefranklin/METADATA.pb
  ofl/librefranklin/OFL.txt
  ofl/librefranklin/static/LibreFranklin-Black.ttf
  ofl/librefranklin/static/LibreFranklin-BlackItalic.ttf
  ofl/librefranklin/static/LibreFranklin-Bold.ttf
  ofl/librefranklin/static/LibreFranklin-BoldItalic.ttf
  ofl/librefranklin/static/LibreFranklin-ExtraBold.ttf
  ofl/librefranklin/static/LibreFranklin-ExtraBoldItalic.ttf
  ofl/librefranklin/static/LibreFranklin-ExtraLight.ttf
  ofl/librefranklin/static/LibreFranklin-ExtraLightItalic.ttf
  ofl/librefranklin/static/LibreFranklin-Italic.ttf
  ofl/librefranklin/static/LibreFranklin-Light.ttf
  ofl/librefranklin/static/LibreFranklin-LightItalic.ttf
  ofl/librefranklin/static/LibreFranklin-Medium.ttf
  ofl/librefranklin/static/LibreFranklin-MediumItalic.ttf
  ofl/librefranklin/static/LibreFranklin-Regular.ttf
  ofl/librefranklin/static/LibreFranklin-SemiBold.ttf
  ofl/librefranklin/static/LibreFranklin-SemiBoldItalic.ttf
  ofl/librefranklin/static/LibreFranklin-Thin.ttf
  ofl/librefranklin/static/LibreFranklin-ThinItalic.ttf
  ofl/librefranklin/upstream.yaml
Labels: Ready for Review

#2669 Caveat: Version 2.000 added
  ofl/caveat/Caveat-Bold.ttf
  ofl/caveat/Caveat-Regular.ttf
  ofl/caveat/Caveat[wght].ttf
  ofl/caveat/METADATA.pb
  ofl/caveat/static/Caveat-Bold.ttf
  ofl/caveat/static/Caveat-Regular.ttf
  ofl/caveat/upstream.yaml
Labels: Ready for Review

#2729 Big Shoulders Display: Version 1.101 added
  ofl/bigshouldersdisplay/BigShouldersDisplay-Black.ttf
  ofl/bigshouldersdisplay/BigShouldersDisplay-Bold.ttf
  ofl/bigshouldersdisplay/BigShouldersDisplay-ExtraBold.ttf
  ofl/bigshouldersdisplay/BigShouldersDisplay-Light.ttf
  ofl/bigshouldersdisplay/BigShouldersDisplay-Medium.ttf
  ofl/bigshouldersdisplay/BigShouldersDisplay-Regular.ttf
  ofl/bigshouldersdisplay/BigShouldersDisplay-SemiBold.ttf
  ofl/bigshouldersdisplay/BigShouldersDisplay-Thin.ttf
  ofl/bigshouldersdisplay/DESCRIPTION.en_us.html
  ofl/bigshouldersdisplay/upstream.yaml
Labels: Ready to push

#2727 Big Shoulders Text: Version 1.101 added
  ofl/bigshoulderstext/BigShouldersText-Black.ttf
  ofl/bigshoulderstext/BigShouldersText-Bold.ttf
  ofl/bigshoulderstext/BigShouldersText-ExtraBold.ttf
  ofl/bigshoulderstext/BigShouldersText-Light.ttf
  ofl/bigshoulderstext/BigShouldersText-Medium.ttf
  ofl/bigshoulderstext/BigShouldersText-Regular.ttf
  ofl/bigshoulderstext/BigShouldersText-SemiBold.ttf
  ofl/bigshoulderstext/BigShouldersText-Thin.ttf
  ofl/bigshoulderstext/DESCRIPTION.en_us.html
  ofl/bigshoulderstext/upstream.yaml
Labels: Ready to push

#2733 ofl/poppins/METADATA.pb Credit Jonny
  ofl/poppins/METADATA.pb
Labels: Ready to push

#2732 dmsans/METADATA.pb Add credit for ITF
  ofl/dmsans/METADATA.pb
Labels: Ready to push

#2746 Big Shoulders Display: Version 1.101 added
  ofl/bigshouldersdisplay/DESCRIPTION.en_us.html
Labels: Ready to push

#2739 volume.textproto added to axisregistry
  axisregistry/volume.textproto
Labels: Needs Dave's opinion, Ready for Review

#2740 flair.textproto added to axisregistry
  axisregistry/flair.textproto
Labels: Needs Dave's opinion, Ready for Review

#2743 Big Shoulders Stencil Text: Version 1.000 added
  ofl/bigshouldersstenciltext/BigShouldersStencilText-Black.ttf
  ofl/bigshouldersstenciltext/BigShouldersStencilText-Bold.ttf
  ofl/bigshouldersstenciltext/BigShouldersStencilText-ExtraBold.ttf
  ofl/bigshouldersstenciltext/BigShouldersStencilText-Light.ttf
  ofl/bigshouldersstenciltext/BigShouldersStencilText-Medium.ttf
  ofl/bigshouldersstenciltext/BigShouldersStencilText-Regular.ttf
  ofl/bigshouldersstenciltext/BigShouldersStencilText-SemiBold.ttf
  ofl/bigshouldersstenciltext/BigShouldersStencilText-Thin.ttf
  ofl/bigshouldersstenciltext/DESCRIPTION.en_us.html
  ofl/bigshouldersstenciltext/METADATA.pb
  ofl/bigshouldersstenciltext/OFL.txt
  ofl/bigshouldersstenciltext/upstream.yaml
Labels: Needs Dave's opinion, Ready to push

#2744 Big Shoulders Stencil Display: Version 1.000 added
  ofl/bigshouldersstencildisplay/BigShouldersStencilDisplay-Black.ttf
  ofl/bigshouldersstencildisplay/BigShouldersStencilDisplay-Bold.ttf
  ofl/bigshouldersstencildisplay/BigShouldersStencilDisplay-ExtraBold.ttf
  ofl/bigshouldersstencildisplay/BigShouldersStencilDisplay-Light.ttf
  ofl/bigshouldersstencildisplay/BigShouldersStencilDisplay-Medium.ttf
  ofl/bigshouldersstencildisplay/BigShouldersStencilDisplay-Regular.ttf
  ofl/bigshouldersstencildisplay/BigShouldersStencilDisplay-SemiBold.ttf
  ofl/bigshouldersstencildisplay/BigShouldersStencilDisplay-Thin.ttf
  ofl/bigshouldersstencildisplay/DESCRIPTION.en_us.html
  ofl/bigshouldersstencildisplay/METADATA.pb
  ofl/bigshouldersstencildisplay/OFL.txt
  ofl/bigshouldersstencildisplay/upstream.yaml
Labels: Needs Dave's opinion, Ready to push

#2747 Big Shoulders Inline Text: Version 1.000 added
  ofl/bigshouldersinlinetext/BigShouldersInlineText-Black.ttf
  ofl/bigshouldersinlinetext/BigShouldersInlineText-Bold.ttf
  ofl/bigshouldersinlinetext/BigShouldersInlineText-ExtraBold.ttf
  ofl/bigshouldersinlinetext/BigShouldersInlineText-Light.ttf
  ofl/bigshouldersinlinetext/BigShouldersInlineText-Medium.ttf
  ofl/bigshouldersinlinetext/BigShouldersInlineText-Regular.ttf
  ofl/bigshouldersinlinetext/BigShouldersInlineText-SemiBold.ttf
  ofl/bigshouldersinlinetext/BigShouldersInlineText-Thin.ttf
  ofl/bigshouldersinlinetext/DESCRIPTION.en_us.html
  ofl/bigshouldersinlinetext/METADATA.pb
  ofl/bigshouldersinlinetext/OFL.txt
  ofl/bigshouldersinlinetext/upstream.yaml
Labels: Needs Dave's opinion, Ready to push

#2748 Big Shoulders Inline Display: Version 1.000 added
  ofl/bigshouldersinlinedisplay/BigShouldersInlineDisplay-Black.ttf
  ofl/bigshouldersinlinedisplay/BigShouldersInlineDisplay-Bold.ttf
  ofl/bigshouldersinlinedisplay/BigShouldersInlineDisplay-ExtraBold.ttf
  ofl/bigshouldersinlinedisplay/BigShouldersInlineDisplay-Light.ttf
  ofl/bigshouldersinlinedisplay/BigShouldersInlineDisplay-Medium.ttf
  ofl/bigshouldersinlinedisplay/BigShouldersInlineDisplay-Regular.ttf
  ofl/bigshouldersinlinedisplay/BigShouldersInlineDisplay-SemiBold.ttf
  ofl/bigshouldersinlinedisplay/BigShouldersInlineDisplay-Thin.ttf
  ofl/bigshouldersinlinedisplay/DESCRIPTION.en_us.html
  ofl/bigshouldersinlinedisplay/METADATA.pb
  ofl/bigshouldersinlinedisplay/OFL.txt
  ofl/bigshouldersinlinedisplay/upstream.yaml
Labels: Needs Dave's opinion, Ready to push

#2751 Patric King info for Catalog
  catalog/designers/patricking/bio.html
  catalog/designers/patricking/info.pb
  catalog/designers/patricking/patric_king.png
Labels: Ready for Review

#2769 Arefruqaa: v1.002 metadata.pb fixed
  ofl/arefruqaa/METADATA.pb
Labels: Ready to push

#2754 [hotfix] ofl/elsie/Elsie-Regular.ttf updated
  ofl/elsie/Elsie-Regular.ttf
Labels: Needs confirmation, Ready for Review

#2767 Texturina: Version 1.002 added
  ofl/texturina/DESCRIPTION.en_us.html
  ofl/texturina/METADATA.pb
  ofl/texturina/OFL.txt
  ofl/texturina/Texturina-Italic[opsz,wght].ttf
  ofl/texturina/Texturina[opsz,wght].ttf
  ofl/texturina/static/Texturina-Black.ttf
  ofl/texturina/static/Texturina-BlackItalic.ttf
  ofl/texturina/static/Texturina-Bold.ttf
  ofl/texturina/static/Texturina-BoldItalic.ttf
  ofl/texturina/static/Texturina-ExtraBold.ttf
  ofl/texturina/static/Texturina-ExtraBoldItalic.ttf
  ofl/texturina/static/Texturina-ExtraLight.ttf
  ofl/texturina/static/Texturina-ExtraLightItalic.ttf
  ofl/texturina/static/Texturina-Italic.ttf
  ofl/texturina/static/Texturina-Light.ttf
  ofl/texturina/static/Texturina-LightItalic.ttf
  ofl/texturina/static/Texturina-Medium.ttf
  ofl/texturina/static/Texturina-MediumItalic.ttf
  ofl/texturina/static/Texturina-Regular.ttf
  ofl/texturina/static/Texturina-SemiBold.ttf
  ofl/texturina/static/Texturina-SemiBoldItalic.ttf
  ofl/texturina/static/Texturina-Thin.ttf
  ofl/texturina/static/Texturina-ThinItalic.ttf
  ofl/texturina/static/Texturina72pt-Black.ttf
  ofl/texturina/static/Texturina72pt-BlackItalic.ttf
  ofl/texturina/static/Texturina72pt-Bold.ttf
  ofl/texturina/static/Texturina72pt-BoldItalic.ttf
  ofl/texturina/static/Texturina72pt-ExtraBold.ttf
  ofl/texturina/static/Texturina72pt-ExtraBoldItalic.ttf
  ofl/texturina/static/Texturina72pt-ExtraLight.ttf
  ofl/texturina/static/Texturina72pt-ExtraLightItalic.ttf
  ofl/texturina/static/Texturina72pt-Italic.ttf
  ofl/texturina/static/Texturina72pt-Light.ttf
  ofl/texturina/static/Texturina72pt-LightItalic.ttf
  ofl/texturina/static/Texturina72pt-Medium.ttf
  ofl/texturina/static/Texturina72pt-MediumItalic.ttf
  ofl/texturina/static/Texturina72pt-Regular.ttf
  ofl/texturina/static/Texturina72pt-SemiBold.ttf
  ofl/texturina/static/Texturina72pt-SemiBoldItalic.ttf
  ofl/texturina/static/Texturina72pt-Thin.ttf
  ofl/texturina/static/Texturina72pt-ThinItalic.ttf
  ofl/texturina/upstream.yaml
Labels: Needs confirmation, Ready to push

#2775 ETC: typo in catalog fixed
  catalog/designers/etc/bio.html
Labels: to_sandbox
