Repository google/fonts, pull requests merged in 2020-12, with the labels that each got.

#2850 Libre Barcode EAN13 Text: Version 1.005; ttfautohint (v1.8.3) added
  ofl/librebarcodeean13text/LibreBarcodeEAN13Text-Regular.ttf
Labels: - Ready for Review

#2841 Eben and Sorkin Type information added
  catalog/designers/ebensorkin/bio.html
  catalog/designers/ebensorkin/eben_sorkin.png
  catalog/designers/ebensorkin/info.pb
  catalog/designers/sorkintype/bio.html
  catalog/designers/sorkintype/info.pb
  catalog/designers/sorkintype/sorkin_type.png
Labels: -- Ready to push

#2852 Libre Barcode EAN13 Text: Version 1.005; ttfautohint (v1.8.3) added
  ofl/librebarcodeean13text/LibreBarcodeEAN13Text-Regular.ttf
Labels: --- to_sandbox

#2539 Saira: Version 1.010 added
  ofl/saira/DESCRIPTION.en_us.html
  ofl/saira/METADATA.pb
  ofl/saira/OFL.txt
  ofl/saira/Saira-Black.ttf
  ofl/saira/Saira-Bold.ttf
  ofl/saira/Saira-ExtraBold.ttf
  ofl/saira/Saira-ExtraLight.ttf
  ofl/saira/Saira-Italic[wdth,wght].ttf
  ofl/saira/Saira-Light.ttf
  ofl/saira/Saira-Medium.ttf
  ofl/saira/Saira-Regular.ttf
  ofl/saira/Saira-SemiBold.ttf
  ofl/saira/Saira-Thin.ttf
  ofl/saira/Saira[wdth,wght].ttf
  ofl/saira/static/Saira-Black.ttf
  ofl/saira/static/Saira-BlackItalic.ttf
  ofl/saira/static/Saira-Bold.ttf
  ofl/saira/static/Saira-BoldItalic.ttf
  ofl/saira/static/Saira-ExtraBold.ttf
  ofl/saira/static/Saira-ExtraBoldItalic.ttf
  ofl/saira/static/Saira-ExtraLight.ttf
  ofl/saira/static/Saira-ExtraLightItalic.ttf
  ofl/saira/static/Saira-Italic.ttf
  ofl/saira/static/Saira-Light.ttf
  ofl/saira/static/Saira-LightItalic.ttf
  ofl/saira/static/Saira-Medium.ttf
  ofl/saira/static/Saira-MediumItalic.ttf
  ofl/saira/static/Saira-Regular.ttf
  ofl/saira/static/Saira-SemiBold.ttf
  ofl/saira/static/Saira-SemiBoldItalic.ttf
  ofl/saira/static/Saira-Thin.ttf
  ofl/saira/static/Saira-ThinItalic.ttf
  ofl/saira/upstream.yaml
Labels: -- Ready to push

#2862 Axis registry : optical size: 16pt fallback added
  axisregistry/optical_size.textproto
Labels: -- Ready to push

#2863 designers: jetbrains team bio added
  catalog/designers/jetbrains/bio.html
  catalog/designers/jetbrains/info.pb
  catalog/designers/jetbrains/jetbrains.png
  catalog/designers/konstantinbulenkov/bio.html
  catalog/designers/konstantinbulenkov/info.pb
  catalog/designers/konstantinbulenkov/konstantinbulenkov.png
  catalog/designers/philippnurullin/bio.html
  catalog/designers/philippnurullin/info.pb
  catalog/designers/philippnurullin/philippnurullin.png
Labels: -- Ready to push

#2867 Slackside One: Version 1.000 added
  ofl/slacksideone/DESCRIPTION.en_us.html
  ofl/slacksideone/METADATA.pb
  ofl/slacksideone/OFL.txt
  ofl/slacksideone/SlacksideOne-Regular.ttf
  ofl/slacksideone/upstream.yaml
Labels: - Ready for Review

#2864 Daruma Drop One: Version 1.000 added
  ofl/darumadropone/DESCRIPTION.en_us.html
  ofl/darumadropone/DarumaDropOne-Regular.ttf
  ofl/darumadropone/METADATA.pb
  ofl/darumadropone/OFL.txt
  ofl/darumadropone/upstream.yaml
Labels: - Ready for Review

#2866 Monomaniac One: Version 1.000; ttfautohint (v1.8.3) added
  ofl/monomaniacone/DESCRIPTION.en_us.html
  ofl/monomaniacone/METADATA.pb
  ofl/monomaniacone/MonomaniacOne-Regular.ttf
  ofl/monomaniacone/OFL.txt
  ofl/monomaniacone/upstream.yaml
Labels: - Ready for Review

#2860 Libre Barcode EAN13 Text: Version 1.006; ttfautohint (v1.8.3) added
  ofl/librebarcodeean13text/LibreBarcodeEAN13Text-Regular.ttf
  ofl/librebarcodeean13text/upstream.yaml
Labels: -- Ready to push

#2805 Imbue: Version 1.102 added
  ofl/imbue/DESCRIPTION.en_us.html
  ofl/imbue/Imbue[opsz,wght].ttf
  ofl/imbue/METADATA.pb
  ofl/imbue/OFL.txt
  ofl/imbue/static/Imbue100pt-Black.ttf
  ofl/imbue/static/Imbue100pt-Bold.ttf
  ofl/imbue/static/Imbue100pt-ExtraBold.ttf
  ofl/imbue/static/Imbue100pt-ExtraLight.ttf
  ofl/imbue/static/Imbue100pt-Light.ttf
  ofl/imbue/static/Imbue100pt-Medium.ttf
  ofl/imbue/static/Imbue100pt-Regular.ttf
  ofl/imbue/static/Imbue100pt-SemiBold.ttf
  ofl/imbue/static/Imbue100pt-Thin.ttf
  ofl/imbue/static/Imbue10pt-Black.ttf
  ofl/imbue/static/Imbue10pt-Bold.ttf
  ofl/imbue/static/Imbue10pt-ExtraBold.ttf
  ofl/imbue/static/Imbue10pt-ExtraLight.ttf
  ofl/imbue/static/Imbue10pt-Light.ttf
  ofl/imbue/static/Imbue10pt-Medium.ttf
  ofl/imbue/static/Imbue10pt-Regular.ttf
  ofl/imbue/static/Imbue10pt-SemiBold.ttf
  ofl/imbue/static/Imbue10pt-Thin.ttf
  ofl/imbue/static/Imbue50pt-Black.ttf
  ofl/imbue/static/Imbue50pt-Bold.ttf
  ofl/imbue/static/Imbue50pt-ExtraBold.ttf
  ofl/imbue/static/Imbue50pt-ExtraLight.ttf
  ofl/imbue/static/Imbue50pt-Light.ttf
  ofl/imbue/static/Imbue50pt-Medium.ttf
  ofl/imbue/static/Imbue50pt-Regular.ttf
  ofl/imbue/static/Imbue50pt-SemiBold.ttf
  ofl/imbue/static/Imbue50pt-Thin.ttf
  ofl/imbue/upstream.yaml
Labels: -- Needs confirmation, -- Ready to push

#2874 Chokokutai: Version 1.000; ttfautohint (v1.8.3) added
  ofl/chokokutai/Chokokutai-Regular.ttf
  ofl/chokokutai/DESCRIPTION.en_us.html
  ofl/chokokutai/METADATA.pb
  ofl/chokokutai/OFL.txt
  ofl/chokokutai/upstream.yaml
Labels: - Ready for Review

#2833 Bodoni Moda: Version 2.004 added
  ofl/bodonimoda/BodoniModa-Italic[opsz,wght].ttf
  ofl/bodonimoda/BodoniModa[opsz,wght].ttf
  ofl/bodonimoda/DESCRIPTION.en_us.html
  ofl/bodonimoda/METADATA.pb
  ofl/bodonimoda/OFL.txt
  ofl/bodonimoda/upstream.yaml
Labels: -- Needs confirmation, -- Ready to push

#2837 Newsreader: Version 1.003 added
  ofl/newsreader/METADATA.pb
  ofl/newsreader/Newsreader-Italic[opsz,wght].ttf
  ofl/newsreader/Newsreader[opsz,wght].ttf
  ofl/newsreader/OFL.txt
  ofl/newsreader/static/Newsreader16pt-Bold.ttf
  ofl/newsreader/static/Newsreader16pt-BoldItalic.ttf
  ofl/newsreader/static/Newsreader16pt-ExtraBold.ttf
  ofl/newsreader/static/Newsreader16pt-ExtraBoldItalic.ttf
  ofl/newsreader/static/Newsreader16pt-ExtraLight.ttf
  ofl/newsreader/static/Newsreader16pt-ExtraLightItalic.ttf
  ofl/newsreader/static/Newsreader16pt-Italic.ttf
  ofl/newsreader/static/Newsreader16pt-Light.ttf
  ofl/newsreader/static/Newsreader16pt-LightItalic.ttf
  ofl/newsreader/static/Newsreader16pt-Medium.ttf
  ofl/newsreader/static/Newsreader16pt-MediumItalic.ttf
  ofl/newsreader/static/Newsreader16pt-Regular.ttf
  ofl/newsreader/static/Newsreader16pt-SemiBold.ttf
  ofl/newsreader/static/Newsreader16pt-SemiBoldItalic.ttf
  ofl/newsreader/static/Newsreader6pt-Bold.ttf
  ofl/newsreader/static/Newsreader6pt-BoldItalic.ttf
  ofl/newsreader/static/Newsreader6pt-ExtraBold.ttf
  ofl/newsreader/static/Newsreader6pt-ExtraBoldItalic.ttf
  ofl/newsreader/static/Newsreader6pt-ExtraLight.ttf
  ofl/newsreader/static/Newsreader6pt-ExtraLightItalic.ttf
  ofl/newsreader/static/Newsreader6pt-Italic.ttf
  ofl/newsreader/static/Newsreader6pt-Light.ttf
  ofl/newsreader/static/Newsreader6pt-LightItalic.ttf
  ofl/newsreader/static/Newsreader6pt-Medium.ttf
  ofl/newsreader/static/Newsreader6pt-MediumItalic.ttf
  ofl/newsreader/static/Newsreader6pt-Regular.ttf
  ofl/newsreader/static/Newsreader6pt-SemiBold.ttf
  ofl/newsreader/static/Newsreader6pt-SemiBoldItalic.ttf
  ofl/newsreader/static/Newsreader72pt-Bold.ttf
  ofl/newsreader/static/Newsreader72pt-BoldItalic.ttf
  ofl/newsreader/static/Newsreader72pt-ExtraBold.ttf
  ofl/newsreader/static/Newsreader72pt-ExtraBoldItalic.ttf
  ofl/newsreader/static/Newsreader72pt-ExtraLight.ttf
  ofl/newsreader/static/Newsreader72pt-ExtraLightItalic.ttf
  ofl/newsreader/static/Newsreader72pt-Italic.ttf
  ofl/newsreader/static/Newsreader72pt-Light.ttf
  ofl/newsreader/static/Newsreader72pt-LightItalic.ttf
  ofl/newsreader/static/Newsreader72pt-Medium.ttf
  ofl/newsreader/static/Newsreader72pt-MediumItalic.ttf
  ofl/newsreader/static/Newsreader72pt-Regular.ttf
  ofl/newsreader/static/Newsreader72pt-SemiBold.ttf
  ofl/newsreader/static/Newsreader72pt-SemiBoldItalic.ttf
  ofl/newsreader/upstream.yaml
Labels: -- Needs confirmation, -- Ready to push

#2885 ringoromei changed to ringorseeber
  catalog/designers/ringorseeber/bio.html
  catalog/designers/ringorseeber/info.pb
  catalog/designers/ringorseeber/ringorseeber.png
Labels: -- Ready to push

#2890 Typeland bios
  catalog/designers/alessiamazzarella/AlessiaMazzarella.png
  catalog/designers/alessiamazzarella/bio.html
  catalog/designers/alessiamazzarella/info.pb
  catalog/designers/typeland/Typeland.png
  catalog/designers/typeland/bio.html
  catalog/designers/typeland/info.pb
Labels: --- to_sandbox

#2891 Libre Barcode EAN13 Text: Version 1.007; ttfautohint (v1.8.3) added
  ofl/librebarcodeean13text/LibreBarcodeEAN13Text-Regular.ttf
Labels: -- Ready to push

#2897 designers/konstantinbulenkov : info fixed
  catalog/designers/konstantinbulenkov/info.pb
Labels: -- Ready to push

#2896 ofl/andikanewbasic/DESCRIPTION.en_us.html typo
  ofl/andikanewbasic/DESCRIPTION.en_us.html
Labels: -- Ready to push

#2894 Designer's bio for Ibarra Real and Sofia Sans added
  catalog/designers/josemariaribagorda/bio.html
  catalog/designers/josemariaribagorda/info.pb
  catalog/designers/josemariaribagorda/josemariaribagorda.png
  catalog/designers/lettersoup/bio.html
  catalog/designers/lettersoup/info.pb
  catalog/designers/lettersoup/lettersoup.png
  catalog/designers/octaviopardo/bio.html
  catalog/designers/octaviopardo/info.pb
  catalog/designers/octaviopardo/octaviopardo.png
Labels: -- Ready to push

#2901 Castoro: Version 1.20 Build 014 added
  ofl/castoro/Castoro-Italic.ttf
  ofl/castoro/Castoro-Regular.ttf
  ofl/castoro/upstream.yaml
Labels: - Ready for Review

#2603 Update width.textproto min from 50 to 25
  axisregistry/width.textproto
Labels: -- Ready to push

#2925 designers/khaledhosny: Add bio and update avatar
  catalog/designers/khaledhosny/bio.html
  catalog/designers/khaledhosny/info.pb
  catalog/designers/khaledhosny/khaled_hosny.png
  catalog/designers/khaledhosny/khaledhosny.png
Labels: -- Ready to push

#2926 Benne: Version 1.000 added
  ofl/benne/Benne-Regular.ttf
  ofl/benne/DESCRIPTION.en_us.html
  ofl/benne/METADATA.pb
  ofl/benne/OFL.txt
  ofl/benne/upstream.yaml
Labels: - Ready for Review

#2919 Castoro: Version 1.20 Build 015 added
  ofl/castoro/Castoro-Italic.ttf
  ofl/castoro/Castoro-Regular.ttf
Labels: -- Ready to push
