Repository google/fonts, pull requests merged in 2020-11, with the labels that each got.

#2791 Castoro's designers information added
  catalog/designers/johnhudson/JohnHudson.jpg
  catalog/designers/johnhudson/bio.html
  catalog/designers/johnhudson/info.pb
  catalog/designers/johnhudson/john_hudson.png
  catalog/designers/kajaslojewska/KajaSlojewska.jpg
  catalog/designers/kajaslojewska/bio.html
  catalog/designers/kajaslojewska/info.pb
  catalog/designers/paulhanslow/PaulHanslow.jpg
  catalog/designers/paulhanslow/bio.html
  catalog/designers/paulhanslow/info.pb
  catalog/designers/tirotypeworks/TiroLogo.jpg
  catalog/designers/tirotypeworks/bio.html
  catalog/designers/tirotypeworks/info.pb
Labels: Ready to push

#2790 Castoro: Version 1.19 Build 011; ttfautohint (v1.8.3) added
  ofl/castoro/Castoro-Italic.ttf
  ofl/castoro/Castoro-Regular.ttf
  ofl/castoro/DESCRIPTION.en_us.html
  ofl/castoro/METADATA.pb
  ofl/castoro/OFL.txt
  ofl/castoro/upstream.yaml
Labels: Ready to push

#2521 Nunito Version 3.600
  ofl/nunito/METADATA.pb
  ofl/nunito/Nunito-Black.ttf
  ofl/nunito/Nunito-BlackItalic.ttf
  ofl/nunito/Nunito-Bold.ttf
  ofl/nunito/Nunito-BoldItalic.ttf
  ofl/nunito/Nunito-ExtraBold.ttf
  ofl/nunito/Nunito-ExtraBoldItalic.ttf
  ofl/nunito/Nunito-ExtraLight.ttf
  ofl/nunito/Nunito-ExtraLightItalic.ttf
  ofl/nunito/Nunito-Italic.ttf
  ofl/nunito/Nunito-Light.ttf
  ofl/nunito/Nunito-LightItalic.ttf
  ofl/nunito/Nunito-Regular.ttf
  ofl/nunito/Nunito-SemiBold.ttf
  ofl/nunito/Nunito-SemiBoldItalic.ttf
  ofl/nunito/OFL.txt
  ofl/nunito/upstream.yaml
Labels: Ready to push

#2789 Lexend: version 1.002 added (bug fix)
  ofl/lexenddeca/LexendDeca-Regular.ttf
  ofl/lexendexa/LexendExa-Regular.ttf
  ofl/lexendgiga/LexendGiga-Regular.ttf
  ofl/lexendmega/LexendMega-Regular.ttf
  ofl/lexendpeta/LexendPeta-Regular.ttf
  ofl/lexendtera/LexendTera-Regular.ttf
  ofl/lexendzetta/LexendZetta-Regular.ttf
Labels: Ready to push

#2770 Karla: Version 2.002 added
  ofl/karla/DESCRIPTION.en_us.html
  ofl/karla/Karla-Italic[wght].ttf
  ofl/karla/Karla[wght].ttf
  ofl/karla/METADATA.pb
  ofl/karla/OFL.txt
  ofl/karla/static/DESCRIPTION.en_us.html
  ofl/karla/static/Karla-Bold.ttf
  ofl/karla/static/Karla-BoldItalic.ttf
  ofl/karla/static/Karla-ExtraBold.ttf
  ofl/karla/static/Karla-ExtraLight.ttf
  ofl/karla/static/Karla-Italic.ttf
  ofl/karla/static/Karla-Light.ttf
  ofl/karla/static/Karla-Medium.ttf
  ofl/karla/static/Karla-Regular.ttf
  ofl/karla/static/METADATA.pb
  ofl/karla/static/OFL.txt
  ofl/karla/upstream.yaml
Labels: Ready to push

#2794 designers: converted jpg to png
  catalog/designers/johnhudson/info.pb
  catalog/designers/johnhudson/john_hudson.jpg
  catalog/designers/johnhudson/johnhudson.png
  catalog/designers/kajaslojewska/KajaSlojewska.jpg
  catalog/designers/kajaslojewska/info.pb
  catalog/designers/kajaslojewska/kajaslojewska.png
  catalog/designers/paulhanslow/PaulHanslow.jpg
  catalog/designers/paulhanslow/info.pb
  catalog/designers/paulhanslow/paulhanslow.png
  catalog/designers/tirotypeworks/TiroLogo.jpg
  catalog/designers/tirotypeworks/info.pb
  catalog/designers/tirotypeworks/tirotypeworks.png
Labels: --- to_sandbox

#2798 Nerko One: Version 1.101 added
  ofl/nerkoone/DESCRIPTION.en_us.html
  ofl/nerkoone/FONTLOG.txt
  ofl/nerkoone/METADATA.pb
  ofl/nerkoone/NerkoOne-Regular.ttf
  ofl/nerkoone/OFL.txt
  ofl/nerkoone/upstream.yaml
Labels: - Ready for Review

#2797 Added Nermin’s bio
  catalog/designers/nerminkahrimanovic/bio.html
  catalog/designers/nerminkahrimanovic/info.pb
  catalog/designers/nerminkahrimanovic/nermin_kahrimanovic.png
Labels: - Ready for Review

#2800 designers/yellowtype : bio added
  catalog/designers/yellowtype/bio.html
  catalog/designers/yellowtype/yellowtype.png
Labels: --- to_sandbox

#2749 Josefin Slab: Version 2.000 added
  ofl/josefinslab/JosefinSlab-Bold.ttf
  ofl/josefinslab/JosefinSlab-BoldItalic.ttf
  ofl/josefinslab/JosefinSlab-Italic.ttf
  ofl/josefinslab/JosefinSlab-Italic[wght].ttf
  ofl/josefinslab/JosefinSlab-Light.ttf
  ofl/josefinslab/JosefinSlab-LightItalic.ttf
  ofl/josefinslab/JosefinSlab-Regular.ttf
  ofl/josefinslab/JosefinSlab-SemiBold.ttf
  ofl/josefinslab/JosefinSlab-SemiBoldItalic.ttf
  ofl/josefinslab/JosefinSlab-Thin.ttf
  ofl/josefinslab/JosefinSlab-ThinItalic.ttf
  ofl/josefinslab/JosefinSlab[wght].ttf
  ofl/josefinslab/METADATA.pb
  ofl/josefinslab/OFL.txt
  ofl/josefinslab/static/JosefinSlab-Bold.ttf
  ofl/josefinslab/static/JosefinSlab-BoldItalic.ttf
  ofl/josefinslab/static/JosefinSlab-Italic.ttf
  ofl/josefinslab/static/JosefinSlab-Light.ttf
  ofl/josefinslab/static/JosefinSlab-LightItalic.ttf
  ofl/josefinslab/static/JosefinSlab-Regular.ttf
  ofl/josefinslab/static/JosefinSlab-SemiBold.ttf
  ofl/josefinslab/static/JosefinSlab-SemiBoldItalic.ttf
  ofl/josefinslab/static/JosefinSlab-Thin.ttf
  ofl/josefinslab/static/JosefinSlab-ThinItalic.ttf
  ofl/josefinslab/upstream.yaml
Labels: - Upstream is working on it

#2818 Xanh Mono: designer info update
  catalog/designers/yellowtype/info.pb
  ofl/xanhmono/METADATA.pb
Labels: -- Ready to push

#2817 JetBrains Mono: Version 2.211 added
  ofl/jetbrainsmono/DESCRIPTION.en_us.html
  ofl/jetbrainsmono/JetBrainsMono-Italic[wght].ttf
  ofl/jetbrainsmono/JetBrainsMono[wght].ttf
  ofl/jetbrainsmono/METADATA.pb
  ofl/jetbrainsmono/OFL.txt
  ofl/jetbrainsmono/static/JetBrainsMono-Bold.ttf
  ofl/jetbrainsmono/static/JetBrainsMono-BoldItalic.ttf
  ofl/jetbrainsmono/static/JetBrainsMono-ExtraBold.ttf
  ofl/jetbrainsmono/static/JetBrainsMono-ExtraBoldItalic.ttf
  ofl/jetbrainsmono/static/JetBrainsMono-ExtraLight.ttf
  ofl/jetbrainsmono/static/JetBrainsMono-ExtraLightItalic.ttf
  ofl/jetbrainsmono/static/JetBrainsMono-Italic.ttf
  ofl/jetbrainsmono/static/JetBrainsMono-Light.ttf
  ofl/jetbrainsmono/static/JetBrainsMono-LightItalic.ttf
  ofl/jetbrainsmono/static/JetBrainsMono-Medium.ttf
  ofl/jetbrainsmono/static/JetBrainsMono-MediumItalic.ttf
  ofl/jetbrainsmono/static/JetBrainsMono-Regular.ttf
  ofl/jetbrainsmono/static/JetBrainsMono-Thin.ttf
  ofl/jetbrainsmono/static/JetBrainsMono-ThinItalic.ttf
  ofl/jetbrainsmono/upstream.yaml
Labels: -- Ready to push

#2826 Calistoga: fixed typo
  ofl/calistoga/METADATA.pb
Labels: -- Ready to push

#2834 designers/owenearl: bio updated
  catalog/designers/owenearl/bio.html
Labels: -- Ready to push

#2838 Langar: Version 1.001; ttfautohint (v1.8.3) added
  ofl/langar/DESCRIPTION.en_us.html
  ofl/langar/Langar-Regular.ttf
  ofl/langar/METADATA.pb
  ofl/langar/OFL.txt
  ofl/langar/upstream.yaml
Labels: - Ready for Review

#2821 AndikaNewBasic: Version 5.500; ttfautohint (v1.8.3) added
  ofl/andikanewbasic/AndikaNewBasic-Bold.ttf
  ofl/andikanewbasic/AndikaNewBasic-BoldItalic.ttf
  ofl/andikanewbasic/AndikaNewBasic-Italic.ttf
  ofl/andikanewbasic/AndikaNewBasic-Regular.ttf
  ofl/andikanewbasic/DESCRIPTION.en_us.html
  ofl/andikanewbasic/METADATA.pb
  ofl/andikanewbasic/OFL.txt
  ofl/andikanewbasic/upstream.yaml
Labels: -- Ready to push
