Repository google/fonts, pull requests merged in 2020-09, with the labels that each got.

#2627 jost: v3.51 added
  ofl/jost/DESCRIPTION.en_us.html
  ofl/jost/Jost-Italic[wght].ttf
  ofl/jost/Jost[wght].ttf
  ofl/jost/static/Jost-Black.ttf
  ofl/jost/static/Jost-BlackItalic.ttf
  ofl/jost/static/Jost-Bold.ttf
  ofl/jost/static/Jost-BoldItalic.ttf
  ofl/jost/static/Jost-ExtraBold.ttf
  ofl/jost/static/Jost-ExtraBoldItalic.ttf
  ofl/jost/static/Jost-ExtraLight.ttf
  ofl/jost/static/Jost-ExtraLightItalic.ttf
  ofl/jost/static/Jost-Italic.ttf
  ofl/jost/static/Jost-Light.ttf
  ofl/jost/static/Jost-LightItalic.ttf
  ofl/jost/static/Jost-Medium.ttf
  ofl/jost/static/Jost-MediumItalic.ttf
  ofl/jost/static/Jost-Regular.ttf
  ofl/jost/static/Jost-SemiBold.ttf
  ofl/jost/static/Jost-SemiBoldItalic.ttf
  ofl/jost/static/Jost-Thin.ttf
  ofl/jost/static/Jost-ThinItalic.ttf
Labels: Check Font Files

#2653 Piazzolla: version 2.001 added
  ofl/piazzolla/DESCRIPTION.en_us.html
  ofl/piazzolla/METADATA.pb
  ofl/piazzolla/OFL.txt
  ofl/piazzolla/Piazzolla-Italic[opsz,wght].ttf
  ofl/piazzolla/Piazzolla[opsz,wght].ttf
  ofl/piazzolla/static/Piazzolla-Black.ttf
  ofl/piazzolla/static/Piazzolla-BlackItalic.ttf
  ofl/piazzolla/static/Piazzolla-Bold.ttf
  ofl/piazzolla/static/Piazzolla-BoldItalic.ttf
  ofl/piazzolla/static/Piazzolla-ExtraBold.ttf
  ofl/piazzolla/static/Piazzolla-ExtraBoldItalic.ttf
  ofl/piazzolla/static/Piazzolla-ExtraLight.ttf
  ofl/piazzolla/static/Piazzolla-ExtraLightItalic.ttf
  ofl/piazzolla/static/Piazzolla-Italic.ttf
  ofl/piazzolla/static/Piazzolla-Light.ttf
  ofl/piazzolla/static/Piazzolla-LightItalic.ttf
  ofl/piazzolla/static/Piazzolla-Medium.ttf
  ofl/piazzolla/static/Piazzolla-MediumItalic.ttf
  ofl/piazzolla/static/Piazzolla-Regular.ttf
  ofl/piazzolla/static/Piazzolla-SemiBold.ttf
  ofl/piazzolla/static/Piazzolla-SemiBoldItalic.ttf
  ofl/piazzolla/static/Piazzolla-Thin.ttf
  ofl/piazzolla/static/Piazzolla-ThinItalic.ttf
Labels: Ready to push

#2658 Sansita swashed: version 1.003 added
  catalog/designers/omnibustype/bio.html
  catalog/designers/omnibustype/info.pb
  ofl/sansitaswashed/DESCRIPTION.en_us.html
  ofl/sansitaswashed/METADATA.pb
  ofl/sansitaswashed/OFL.txt
  ofl/sansitaswashed/SansitaSwashed[wght].ttf
  ofl/sansitaswashed/static/SansitaSwashed-Black.ttf
  ofl/sansitaswashed/static/SansitaSwashed-Bold.ttf
  ofl/sansitaswashed/static/SansitaSwashed-ExtraBold.ttf
  ofl/sansitaswashed/static/SansitaSwashed-Light.ttf
  ofl/sansitaswashed/static/SansitaSwashed-Medium.ttf
  ofl/sansitaswashed/static/SansitaSwashed-Regular.ttf
  ofl/sansitaswashed/static/SansitaSwashed-SemiBold.ttf
Labels: Ready to push

#2660 Update Cabin metadata
  ofl/cabin/DESCRIPTION.en_us.html
  ofl/cabin/METADATA.pb
  ofl/cabincondensed/DESCRIPTION.en_us.html
Labels: Ready to push

#2680 Modification of 2342 PR: kantamruy, kdam thmor: name tables
  catalog/designers/tepsovichet/bio.html
  catalog/designers/tepsovichet/info.pb
  ofl/kantumruy/DESCRIPTION.en_us.html
  ofl/kantumruy/Kantumruy-Bold.ttf
  ofl/kantumruy/Kantumruy-Light.ttf
  ofl/kantumruy/Kantumruy-Regular.ttf
  ofl/kdamthmor/DESCRIPTION.en_us.html
  ofl/kdamthmor/KdamThmor-Regular.ttf
Labels: Ready for Review

#2679 Handjet: version 2.000 added
  ofl/handjet/DESCRIPTION.en_us.html
  ofl/handjet/Handjet[EGRD,ESHP,wght].ttf
  ofl/handjet/METADATA.pb
  ofl/handjet/OFL.txt
Labels: Ready to push

#2594 Delete /axisregistry/expression.textproto
  axisregistry/expression.textproto
Labels: Ready for Review

#2703 XanhMono: version 3.101 added
  catalog/designers/yellowtype/info.pb
  catalog/designers/yellowtype/yellowtype.png
  ofl/xanhmono/DESCRIPTION.en_us.html
  ofl/xanhmono/DESCRIPTION.vi_vn.html
  ofl/xanhmono/METADATA.pb
  ofl/xanhmono/OFL.txt
  ofl/xanhmono/XanhMono-Italic.ttf
  ofl/xanhmono/XanhMono-Regular.ttf
Labels: Ready to push

#2696 Ballet: version 1.100 added
  ofl/ballet/Ballet[opsz].ttf
  ofl/ballet/DESCRIPTION.en_us.html
  ofl/ballet/METADATA.pb
  ofl/ballet/OFL.txt
  ofl/ballet/static/Ballet16pt-Regular.ttf
  ofl/ballet/static/Ballet72pt-Regular.ttf
Labels: Ready to push

#2700 Trispace: version 1.210 added
  ofl/trispace/DESCRIPTION.en_us.html
  ofl/trispace/METADATA.pb
  ofl/trispace/OFL.txt
  ofl/trispace/Trispace[wdth,wght].ttf
  ofl/trispace/static/Trispace-Bold.ttf
  ofl/trispace/static/Trispace-ExtraBold.ttf
  ofl/trispace/static/Trispace-ExtraLight.ttf
  ofl/trispace/static/Trispace-Light.ttf
  ofl/trispace/static/Trispace-Medium.ttf
  ofl/trispace/static/Trispace-Regular.ttf
  ofl/trispace/static/Trispace-SemiBold.ttf
  ofl/trispace/static/Trispace-Thin.ttf
  ofl/trispace/static/TrispaceCondensed-Bold.ttf
  ofl/trispace/static/TrispaceCondensed-ExtraBold.ttf
  ofl/trispace/static/TrispaceCondensed-ExtraLight.ttf
  ofl/trispace/static/TrispaceCondensed-Light.ttf
  ofl/trispace/static/TrispaceCondensed-Medium.ttf
  ofl/trispace/static/TrispaceCondensed-Regular.ttf
  ofl/trispace/static/TrispaceCondensed-SemiBold.ttf
  ofl/trispace/static/TrispaceCondensed-Thin.ttf
  ofl/trispace/static/TrispaceExpanded-Bold.ttf
  ofl/trispace/static/TrispaceExpanded-ExtraBold.ttf
  ofl/trispace/static/TrispaceExpanded-ExtraLight.ttf
  ofl/trispace/static/TrispaceExpanded-Light.ttf
  ofl/trispace/static/TrispaceExpanded-Medium.ttf
  ofl/trispace/static/TrispaceExpanded-Regular.ttf
  ofl/trispace/static/TrispaceExpanded-SemiBold.ttf
  ofl/trispace/static/TrispaceExpanded-Thin.ttf
  ofl/trispace/static/TrispaceSemiCondensed-Bold.ttf
  ofl/trispace/static/TrispaceSemiCondensed-ExtraBold.ttf
  ofl/trispace/static/TrispaceSemiCondensed-ExtraLight.ttf
  ofl/trispace/static/TrispaceSemiCondensed-Light.ttf
  ofl/trispace/static/TrispaceSemiCondensed-Medium.ttf
  ofl/trispace/static/TrispaceSemiCondensed-Regular.ttf
  ofl/trispace/static/TrispaceSemiCondensed-SemiBold.ttf
  ofl/trispace/static/TrispaceSemiCondensed-Thin.ttf
  ofl/trispace/static/TrispaceSemiExpanded-Bold.ttf
  ofl/trispace/static/TrispaceSemiExpanded-ExtraBold.ttf
  ofl/trispace/static/TrispaceSemiExpanded-ExtraLight.ttf
  ofl/trispace/static/TrispaceSemiExpanded-Light.ttf
  ofl/trispace/static/TrispaceSemiExpanded-Medium.ttf
  ofl/trispace/static/TrispaceSemiExpanded-Regular.ttf
  ofl/trispace/static/TrispaceSemiExpanded-SemiBold.ttf
  ofl/trispace/static/TrispaceSemiExpanded-Thin.ttf
Labels: Ready to push

#2704 syne: description updated
  ofl/syne/DESCRIPTION.en_us.html
Labels: Ready to push

#2706 Syne Tactile: version 2.100 added
  ofl/synetactile/DESCRIPTION.en_us.html
  ofl/synetactile/METADATA.pb
  ofl/synetactile/OFL.txt
  ofl/synetactile/SyneTactile-Regular.ttf
Labels: Ready to push

#2705 Syne Mono: version 2.000 added
  ofl/synemono/DESCRIPTION.en_us.html
  ofl/synemono/METADATA.pb
  ofl/synemono/OFL.txt
  ofl/synemono/SyneMono-Regular.ttf
Labels: Ready to push
