Repository google/fonts, pull requests merged in 2021-06, with the labels that each got.

#3454 WindSong: Version 1.010; ttfautohint (v1.8.3) added
  ofl/windsong/DESCRIPTION.en_us.html
  ofl/windsong/METADATA.pb
  ofl/windsong/OFL.txt
  ofl/windsong/WindSong-Medium.ttf
  ofl/windsong/WindSong-Regular.ttf
  ofl/windsong/upstream.yaml
Labels: - Ready for Review, II New Font

#3463 Updating Robert Leuschke directory
  catalog/designers/robertleuschke/bio.html
  catalog/designers/robertleuschke/info.pb
  catalog/designers/robertleuschke/robertleuschke.png
  catalog/designers/robleuschke/info.pb
  catalog/designers/robleuschke/rob_leuschke.png
Labels: --- to_sandbox, II Catalog

#3464 Playball: Version 1.010 added
  ofl/playball/Playball-Regular.ttf
Labels: --- to_sandbox, II Font Upgrade

#3465 Kumbh Sans: Version 1.003 added
  ofl/kumbhsans/DESCRIPTION.en_us.html
  ofl/kumbhsans/KumbhSans-Bold.ttf
  ofl/kumbhsans/KumbhSans-Light.ttf
  ofl/kumbhsans/KumbhSans-Regular.ttf
  ofl/kumbhsans/KumbhSans[wght].ttf
  ofl/kumbhsans/METADATA.pb
  ofl/kumbhsans/upstream.yaml
Labels: - Ready for Review, II Font Upgrade, III VF Replacement

#3472 Theodore Petrosky added as designer of Atkinson
  catalog/designers/elliottscott/bio.html
  catalog/designers/elliottscott/elliottscott.png
  catalog/designers/elliottscott/info.pb
  catalog/designers/theodorepetrosky/bio.html
  catalog/designers/theodorepetrosky/info.pb
  catalog/designers/theodorepetrosky/theodorepetrosky.png
Labels: - Ready for Review, II Catalog

#3466 Braille Institute added as designer of Atkinson Hyperlegible
  catalog/designers/brailleinstitute/bio.html
  catalog/designers/brailleinstitute/brailleinstitute.png
  catalog/designers/brailleinstitute/info.pb
Labels: - Ready for Review, II Catalog

#3469 Megan Eiswerth added as designer of Atkinson
  catalog/designers/meganeiswerth/bio.html
  catalog/designers/meganeiswerth/info.pb
  catalog/designers/meganeiswerth/meganeiswerth.png
Labels: - Ready for Review, II Catalog

#3467 Applied Design Works added as designer of Atkinson
  catalog/designers/applieddesignworks/applieddesignworks.png
  catalog/designers/applieddesignworks/bio.html
  catalog/designers/applieddesignworks/info.pb
Labels: - Ready for Review, II Catalog

#3471 Linus Boman added as designer of Atkinson
  catalog/designers/linusboman/bio.html
  catalog/designers/linusboman/info.pb
  catalog/designers/linusboman/linusboman.png
Labels: - Ready for Review, II Catalog

#3483 Allura: Version 1.100 added
  ofl/allura/Allura-Regular.ttf
  ofl/allura/DESCRIPTION.en_us.html
  ofl/allura/METADATA.pb
  ofl/allura/OFL.txt
  ofl/allura/upstream.yaml
Labels: - Ready for Review, II Font Upgrade

#3487 Designer: Displaay added (Azeret Mono)
  catalog/designers/displaay/bio.html
  catalog/designers/displaay/displaay.png
  catalog/designers/displaay/info.pb
Labels: - Ready for Review, II Catalog

#3488 Designer: Martin Vácha added (Azeret Mono)
  catalog/designers/martinvacha/bio.html
  catalog/designers/martinvacha/info.pb
  catalog/designers/martinvacha/martinvacha.png
Labels: - Ready for Review, II Catalog

#3485 Ruthie: Version 1.012 added
  ofl/ruthie/DESCRIPTION.en_us.html
  ofl/ruthie/METADATA.pb
  ofl/ruthie/OFL.txt
  ofl/ruthie/Ruthie-Regular.ttf
  ofl/ruthie/upstream.yaml
Labels: --- to_sandbox, II Font Upgrade

#3489 Designer: Carolina Giovagnoli added (Andada Pro)
  catalog/designers/carolinagiovagnoli/bio.html
  catalog/designers/carolinagiovagnoli/carolinagiovagnoli.png
  catalog/designers/carolinagiovagnoli/info.pb
Labels: --- to_sandbox, II Catalog

#3475 Azeret: Version 1.002 added
  ofl/azeret/AzeretMono-Italic[wght].ttf
  ofl/azeret/AzeretMono[wght].ttf
  ofl/azeret/DESCRIPTION.en_us.html
  ofl/azeret/METADATA.pb
  ofl/azeret/OFL.txt
  ofl/azeret/upstream.yaml
Labels: -- Ready to push, II New Font

#3335 Mulish: Version 3.602 added
  ofl/mulish/METADATA.pb
  ofl/mulish/Mulish-Italic[wght].ttf
  ofl/mulish/Mulish[wght].ttf
  ofl/mulish/OFL.txt
  ofl/mulish/static/Mulish-Black.ttf
  ofl/mulish/static/Mulish-BlackItalic.ttf
  ofl/mulish/static/Mulish-Bold.ttf
  ofl/mulish/static/Mulish-BoldItalic.ttf
  ofl/mulish/static/Mulish-ExtraBold.ttf
  ofl/mulish/static/Mulish-ExtraBoldItalic.ttf
  ofl/mulish/static/Mulish-ExtraLight.ttf
  ofl/mulish/static/Mulish-ExtraLightItalic.ttf
  ofl/mulish/static/Mulish-Italic.ttf
  ofl/mulish/static/Mulish-Light.ttf
  ofl/mulish/static/Mulish-LightItalic.ttf
  ofl/mulish/static/Mulish-Regular.ttf
  ofl/mulish/static/Mulish-SemiBold.ttf
  ofl/mulish/static/Mulish-SemiBoldItalic.ttf
  ofl/mulish/upstream.yaml
Labels: - Needs Dave's opinion, II Font Upgrade

#3518 Red Hat Mono: Version 1.010 added
  catalog/designers/mckl/bio.html
  catalog/designers/mckl/info.pb
  ofl/redhatmono/DESCRIPTION.en_us.html
  ofl/redhatmono/METADATA.pb
  ofl/redhatmono/OFL.txt
  ofl/redhatmono/RedHatMono-Italic[wght].ttf
  ofl/redhatmono/RedHatMono[wght].ttf
  ofl/redhatmono/upstream.yaml
Labels: - Ready for Review, II New Font

#3528 Great Vibes: Version 1.010; ttfautohint (v1.8.3) added
  ofl/greatvibes/DESCRIPTION.en_us.html
  ofl/greatvibes/GreatVibes-Regular.ttf
  ofl/greatvibes/METADATA.pb
  ofl/greatvibes/OFL.txt
  ofl/greatvibes/upstream.yaml
Labels: - Ready for Review, II Font Upgrade

#3538 Hiroki-Chan : bio added
  catalog/designers/hirokichan/bio.html
  catalog/designers/hirokichan/hirokichan.png
  catalog/designers/hirokichan/info.pb
Labels: - Ready for Review, II Catalog

#3537 FONTDASU : bio added
  catalog/designers/fontdasu/bio.html
  catalog/designers/fontdasu/fontdasu.png
  catalog/designers/fontdasu/info.pb
Labels: - Ready for Review, II Catalog

#3536 Nontynet : bio added
  catalog/designers/nonty/bio.html
  catalog/designers/nonty/info.pb
  catalog/designers/nonty/nonty.png
  ofl/hachimarupop/METADATA.pb
Labels: - Ready for Review, II Catalog

#3535 Font Zone 108 : bio added
  catalog/designers/fontzone108/bio.html
  catalog/designers/fontzone108/fontzone108.png
  catalog/designers/fontzone108/info.pb
Labels: - Ready for Review, II Catalog

#3534 Satsuyako : bio added
  catalog/designers/satsuyako/bio.html
  catalog/designers/satsuyako/info.pb
  catalog/designers/satsuyako/satsuyako.png
Labels: - Ready for Review, II Catalog

#3532 fontworksinc : bio added
  catalog/designers/fontworksinc/bio.html
  catalog/designers/fontworksinc/fontworksinc.png
  catalog/designers/fontworksinc/info.pb
Labels: - Ready for Review, II Catalog

#3559 Alumni Sans: Version 1.014 added
  ofl/alumnisans/AlumniSans-Italic[wght].ttf
  ofl/alumnisans/AlumniSans[wght].ttf
  ofl/alumnisans/DESCRIPTION.en_us.html
  ofl/alumnisans/METADATA.pb
  ofl/alumnisans/OFL.txt
  ofl/alumnisans/upstream.yaml
Labels: - Ready for Review, II New Font

#3553 Glory: Version 1.011 added
  ofl/glory/DESCRIPTION.en_us.html
  ofl/glory/Glory-Italic[wght].ttf
  ofl/glory/Glory[wght].ttf
  ofl/glory/METADATA.pb
  ofl/glory/OFL.txt
  ofl/glory/upstream.yaml
Labels: - Ready for Review, II New Font

#3527 IBM Plex Mono: Version 2.1 added
  ofl/ibmplexmono/DESCRIPTION.en_us.html
  ofl/ibmplexmono/IBMPlexMono-Bold.ttf
  ofl/ibmplexmono/IBMPlexMono-BoldItalic.ttf
  ofl/ibmplexmono/IBMPlexMono-ExtraLight.ttf
  ofl/ibmplexmono/IBMPlexMono-ExtraLightItalic.ttf
  ofl/ibmplexmono/IBMPlexMono-Italic.ttf
  ofl/ibmplexmono/IBMPlexMono-Light.ttf
  ofl/ibmplexmono/IBMPlexMono-LightItalic.ttf
  ofl/ibmplexmono/IBMPlexMono-Medium.ttf
  ofl/ibmplexmono/IBMPlexMono-MediumItalic.ttf
  ofl/ibmplexmono/IBMPlexMono-Regular.ttf
  ofl/ibmplexmono/IBMPlexMono-SemiBold.ttf
  ofl/ibmplexmono/IBMPlexMono-SemiBoldItalic.ttf
  ofl/ibmplexmono/IBMPlexMono-Thin.ttf
  ofl/ibmplexmono/IBMPlexMono-ThinItalic.ttf
  ofl/ibmplexmono/METADATA.pb
  ofl/ibmplexmono/OFL.txt
  ofl/ibmplexmono/upstream.yaml
Labels: - Ready for Review, II Font Upgrade

#3544 IBM Plex Serif: Version 2.6 added
  ofl/ibmplexserif/DESCRIPTION.en_us.html
  ofl/ibmplexserif/IBMPlexSerif-Bold.ttf
  ofl/ibmplexserif/IBMPlexSerif-BoldItalic.ttf
  ofl/ibmplexserif/IBMPlexSerif-ExtraLight.ttf
  ofl/ibmplexserif/IBMPlexSerif-ExtraLightItalic.ttf
  ofl/ibmplexserif/IBMPlexSerif-Italic.ttf
  ofl/ibmplexserif/IBMPlexSerif-Light.ttf
  ofl/ibmplexserif/IBMPlexSerif-LightItalic.ttf
  ofl/ibmplexserif/IBMPlexSerif-Medium.ttf
  ofl/ibmplexserif/IBMPlexSerif-MediumItalic.ttf
  ofl/ibmplexserif/IBMPlexSerif-Regular.ttf
  ofl/ibmplexserif/IBMPlexSerif-SemiBold.ttf
  ofl/ibmplexserif/IBMPlexSerif-SemiBoldItalic.ttf
  ofl/ibmplexserif/IBMPlexSerif-Thin.ttf
  ofl/ibmplexserif/IBMPlexSerif-ThinItalic.ttf
  ofl/ibmplexserif/METADATA.pb
  ofl/ibmplexserif/OFL.txt
  ofl/ibmplexserif/upstream.yaml
Labels: - Ready for Review, II Font Upgrade

#3439 IBM Plex Sans: Version 3.2 added
  ofl/ibmplexsans/DESCRIPTION.en_us.html
  ofl/ibmplexsans/IBMPlexSans-Bold.ttf
  ofl/ibmplexsans/IBMPlexSans-BoldItalic.ttf
  ofl/ibmplexsans/IBMPlexSans-ExtraLight.ttf
  ofl/ibmplexsans/IBMPlexSans-ExtraLightItalic.ttf
  ofl/ibmplexsans/IBMPlexSans-Italic.ttf
  ofl/ibmplexsans/IBMPlexSans-Light.ttf
  ofl/ibmplexsans/IBMPlexSans-LightItalic.ttf
  ofl/ibmplexsans/IBMPlexSans-Medium.ttf
  ofl/ibmplexsans/IBMPlexSans-MediumItalic.ttf
  ofl/ibmplexsans/IBMPlexSans-Regular.ttf
  ofl/ibmplexsans/IBMPlexSans-SemiBold.ttf
  ofl/ibmplexsans/IBMPlexSans-SemiBoldItalic.ttf
  ofl/ibmplexsans/IBMPlexSans-Thin.ttf
  ofl/ibmplexsans/IBMPlexSans-ThinItalic.ttf
  ofl/ibmplexsans/METADATA.pb
  ofl/ibmplexsans/OFL.txt
  ofl/ibmplexsans/upstream.yaml
Labels: - Ready for Review, II Font Upgrade

#3566 Better website link
  catalog/designers/mooniak/info.pb
Labels: - Ready for Review, II Catalog

#3567 Gemunu Libre: Version 1.100 added
  ofl/gemunulibre/DESCRIPTION.en_us.html
  ofl/gemunulibre/GemunuLibre-Bold.ttf
  ofl/gemunulibre/GemunuLibre-ExtraBold.ttf
  ofl/gemunulibre/GemunuLibre-ExtraLight.ttf
  ofl/gemunulibre/GemunuLibre-Light.ttf
  ofl/gemunulibre/GemunuLibre-Medium.ttf
  ofl/gemunulibre/GemunuLibre-Regular.ttf
  ofl/gemunulibre/GemunuLibre-SemiBold.ttf
  ofl/gemunulibre/GemunuLibre[wght].ttf
  ofl/gemunulibre/METADATA.pb
  ofl/gemunulibre/OFL.txt
  ofl/gemunulibre/upstream.yaml
Labels: - Ready for Review, II New Font

#3519 Red Hat Text: Version 1.010 added
  ofl/redhattext/DESCRIPTION.en_us.html
  ofl/redhattext/METADATA.pb
  ofl/redhattext/OFL.txt
  ofl/redhattext/RedHatText-Bold.ttf
  ofl/redhattext/RedHatText-BoldItalic.ttf
  ofl/redhattext/RedHatText-Italic.ttf
  ofl/redhattext/RedHatText-Italic[wght].ttf
  ofl/redhattext/RedHatText-Medium.ttf
  ofl/redhattext/RedHatText-MediumItalic.ttf
  ofl/redhattext/RedHatText-Regular.ttf
  ofl/redhattext/RedHatText[wght].ttf
  ofl/redhattext/upstream.yaml
Labels: - Ready for Review, II Font Upgrade, III VF Replacement

#3520 Red Hat Display: Version 1.010 added
  ofl/redhatdisplay/DESCRIPTION.en_us.html
  ofl/redhatdisplay/METADATA.pb
  ofl/redhatdisplay/RedHatDisplay-Black.ttf
  ofl/redhatdisplay/RedHatDisplay-BlackItalic.ttf
  ofl/redhatdisplay/RedHatDisplay-Bold.ttf
  ofl/redhatdisplay/RedHatDisplay-BoldItalic.ttf
  ofl/redhatdisplay/RedHatDisplay-Italic.ttf
  ofl/redhatdisplay/RedHatDisplay-Italic[wght].ttf
  ofl/redhatdisplay/RedHatDisplay-Medium.ttf
  ofl/redhatdisplay/RedHatDisplay-MediumItalic.ttf
  ofl/redhatdisplay/RedHatDisplay-Regular.ttf
  ofl/redhatdisplay/RedHatDisplay[wght].ttf
  ofl/redhatdisplay/upstream.yaml
Labels: - Ready for Review, II Font Upgrade, III VF Replacement

#3570 Yaldevi: Version 1.100 added
  ofl/yaldevi/DESCRIPTION.en_us.html
  ofl/yaldevi/METADATA.pb
  ofl/yaldevi/OFL.txt
  ofl/yaldevi/Yaldevi[wght].ttf
  ofl/yaldevi/upstream.yaml
Labels: - Ready for Review, II New Font

#3571 Stick No Bills: Version 2.000 added
  ofl/sticknobills/DESCRIPTION.en_us.html
  ofl/sticknobills/METADATA.pb
  ofl/sticknobills/OFL.txt
  ofl/sticknobills/StickNoBills[wght].ttf
  ofl/sticknobills/upstream.yaml
Labels: - Ready for Review, II New Font
