Repository google/fonts, pull requests merged in 2021-09, with the labels that each got.

#3632 CrimsonPro v1.003 (stat fix)
  ofl/crimsonpro/CrimsonPro-Italic[wght].ttf
  ofl/crimsonpro/CrimsonPro[wght].ttf
  ofl/crimsonpro/METADATA.pb
Labels: I VF, - Ready for Review, II Font Upgrade

#3787 Rubik Beastly: Version 2.103; ttfautohint (v1.8.3) added
  ofl/rubikbeastly/DESCRIPTION.en_us.html
  ofl/rubikbeastly/METADATA.pb
  ofl/rubikbeastly/OFL.txt
  ofl/rubikbeastly/RubikBeastly-Regular.ttf
  ofl/rubikbeastly/upstream.yaml
Labels: - Ready for Review, II New Font

#3591 Gluten: Version 1.204 added
  ofl/gluten/DESCRIPTION.en_us.html
  ofl/gluten/Gluten[wght].ttf
  ofl/gluten/METADATA.pb
  ofl/gluten/OFL.txt
  ofl/gluten/upstream.yaml
Labels: - Ready for Review, II New Font

#3806 Faustina: Version 1.200 added
  ofl/faustina/Faustina-Italic[wght].ttf
  ofl/faustina/Faustina[wght].ttf
  ofl/faustina/METADATA.pb
  ofl/faustina/upstream.yaml
Labels: I VF, - Ready for Review, II Font Upgrade

#3786 Updating to Fira Code 5.2
  ofl/firacode/DESCRIPTION.en_us.html
  ofl/firacode/FiraCode[wght].ttf
  ofl/firacode/METADATA.pb
  ofl/firacode/OFL.txt
Labels: I VF, - Ready for Review, II Font Upgrade

#3438 Big Shoulders Inline Display: Version 2.000 added
  ofl/bigshouldersinlinedisplay/BigShouldersInlineDisplay-Black.ttf
  ofl/bigshouldersinlinedisplay/BigShouldersInlineDisplay-Bold.ttf
  ofl/bigshouldersinlinedisplay/BigShouldersInlineDisplay-ExtraBold.ttf
  ofl/bigshouldersinlinedisplay/BigShouldersInlineDisplay-Light.ttf
  ofl/bigshouldersinlinedisplay/BigShouldersInlineDisplay-Medium.ttf
  ofl/bigshouldersinlinedisplay/BigShouldersInlineDisplay-Regular.ttf
  ofl/bigshouldersinlinedisplay/BigShouldersInlineDisplay-SemiBold.ttf
  ofl/bigshouldersinlinedisplay/BigShouldersInlineDisplay-Thin.ttf
  ofl/bigshouldersinlinedisplay/BigShouldersInlineDisplay[wght].ttf
  ofl/bigshouldersinlinedisplay/DESCRIPTION.en_us.html
  ofl/bigshouldersinlinedisplay/METADATA.pb
  ofl/bigshouldersinlinedisplay/upstream.yaml
Labels: - Ready for Review, II Font Upgrade

#3432 Big Shoulders Text: Version 2.000 added
  ofl/bigshoulderstext/BigShouldersText-Black.ttf
  ofl/bigshoulderstext/BigShouldersText-Bold.ttf
  ofl/bigshoulderstext/BigShouldersText-ExtraBold.ttf
  ofl/bigshoulderstext/BigShouldersText-Light.ttf
  ofl/bigshoulderstext/BigShouldersText-Medium.ttf
  ofl/bigshoulderstext/BigShouldersText-Regular.ttf
  ofl/bigshoulderstext/BigShouldersText-SemiBold.ttf
  ofl/bigshoulderstext/BigShouldersText-Thin.ttf
  ofl/bigshoulderstext/BigShouldersText[wght].ttf
  ofl/bigshoulderstext/DESCRIPTION.en_us.html
  ofl/bigshoulderstext/METADATA.pb
  ofl/bigshoulderstext/upstream.yaml
Labels: - Ready for Review, II Font Upgrade

#3434 Big Shoulders Display: Version 2.000 added
  ofl/bigshouldersdisplay/BigShouldersDisplay-Black.ttf
  ofl/bigshouldersdisplay/BigShouldersDisplay-Bold.ttf
  ofl/bigshouldersdisplay/BigShouldersDisplay-ExtraBold.ttf
  ofl/bigshouldersdisplay/BigShouldersDisplay-Light.ttf
  ofl/bigshouldersdisplay/BigShouldersDisplay-Medium.ttf
  ofl/bigshouldersdisplay/BigShouldersDisplay-Regular.ttf
  ofl/bigshouldersdisplay/BigShouldersDisplay-SemiBold.ttf
  ofl/bigshouldersdisplay/BigShouldersDisplay-Thin.ttf
  ofl/bigshouldersdisplay/BigShouldersDisplay[wght].ttf
  ofl/bigshouldersdisplay/DESCRIPTION.en_us.html
  ofl/bigshouldersdisplay/METADATA.pb
  ofl/bigshouldersdisplay/upstream.yaml
Labels: - Ready for Review, II Font Upgrade

#3437 Big Shoulders Inline Text: Version 2.000 added
  ofl/bigshouldersinlinetext/BigShouldersInlineText-Black.ttf
  ofl/bigshouldersinlinetext/BigShouldersInlineText-Bold.ttf
  ofl/bigshouldersinlinetext/BigShouldersInlineText-ExtraBold.ttf
  ofl/bigshouldersinlinetext/BigShouldersInlineText-Light.ttf
  ofl/bigshouldersinlinetext/BigShouldersInlineText-Medium.ttf
  ofl/bigshouldersinlinetext/BigShouldersInlineText-Regular.ttf
  ofl/bigshouldersinlinetext/BigShouldersInlineText-SemiBold.ttf
  ofl/bigshouldersinlinetext/BigShouldersInlineText-Thin.ttf
  ofl/bigshouldersinlinetext/BigShouldersInlineText[wght].ttf
  ofl/bigshouldersinlinetext/DESCRIPTION.en_us.html
  ofl/bigshouldersinlinetext/METADATA.pb
  ofl/bigshouldersinlinetext/upstream.yaml
Labels: - Ready for Review, II Font Upgrade

#3512 Fasthand: Version 8.000; ttfautohint (v1.8.3) added
  ofl/fasthand/DESCRIPTION.en_us.html
  ofl/fasthand/Fasthand-Regular.ttf
  ofl/fasthand/METADATA.pb
  ofl/fasthand/OFL.txt
  ofl/fasthand/upstream.yaml
Labels: - Ready for Review, II New Font

#3511 Koulen: Version 8.000; ttfautohint (v1.8.3) added
  ofl/koulen/DESCRIPTION.en_us.html
  ofl/koulen/Koulen-Regular.ttf
  ofl/koulen/Koulen.ttf
  ofl/koulen/METADATA.pb
  ofl/koulen/OFL.txt
  ofl/koulen/upstream.yaml
Labels: --- to_sandbox, II Font Upgrade

#3510 Freehand: Version 8.000; ttfautohint (v1.8.3) added
  ofl/freehand/DESCRIPTION.en_us.html
  ofl/freehand/Freehand-Regular.ttf
  ofl/freehand/Freehand.ttf
  ofl/freehand/METADATA.pb
  ofl/freehand/OFL.txt
  ofl/freehand/upstream.yaml
Labels: --- to_sandbox, II Font Upgrade

#3509 Moul: Version 8.000; ttfautohint (v1.8.3) added
  ofl/moul/DESCRIPTION.en_us.html
  ofl/moul/METADATA.pb
  ofl/moul/Moul-Regular.ttf
  ofl/moul/Moul.ttf
  ofl/moul/OFL.txt
  ofl/moul/upstream.yaml
Labels: --- to_sandbox, II Font Upgrade

#3508 Bokor: Version 8.000; ttfautohint (v1.8.3) added
  ofl/bokor/Bokor-Regular.ttf
  ofl/bokor/DESCRIPTION.en_us.html
  ofl/bokor/METADATA.pb
  ofl/bokor/OFL.txt
  ofl/bokor/upstream.yaml
Labels: --- to_sandbox, II Font Upgrade

#3506 Koh Santepheap: Version 2.000; ttfautohint (v1.8.3) added
  ofl/kohsantepheap/DESCRIPTION.en_us.html
  ofl/kohsantepheap/KohSantepheap-Black.ttf
  ofl/kohsantepheap/KohSantepheap-Bold.ttf
  ofl/kohsantepheap/KohSantepheap-Light.ttf
  ofl/kohsantepheap/KohSantepheap-Regular.ttf
  ofl/kohsantepheap/KohSantepheap-Thin.ttf
  ofl/kohsantepheap/METADATA.pb
  ofl/kohsantepheap/OFL.txt
  ofl/kohsantepheap/upstream.yaml
Labels: - Ready for Review, II New Font

#3505 Angkor: Version 8.000; ttfautohint (v1.8.3) added
  ofl/angkor/Angkor-Regular.ttf
  ofl/angkor/DESCRIPTION.en_us.html
  ofl/angkor/METADATA.pb
  ofl/angkor/OFL.txt
  ofl/angkor/upstream.yaml
Labels: --- to_sandbox, II Font Upgrade

#3501 Metal: Version 8.000; ttfautohint (v1.8.3) added
  ofl/metal/DESCRIPTION.en_us.html
  ofl/metal/METADATA.pb
  ofl/metal/Metal-Regular.ttf
  ofl/metal/Metal.ttf
  ofl/metal/OFL.txt
  ofl/metal/upstream.yaml
Labels: --- to_sandbox, II Font Upgrade

#3498 Bayon: Version 8.001; ttfautohint (v1.8.3) added
  ofl/bayon/Bayon-Regular.ttf
  ofl/bayon/DESCRIPTION.en_us.html
  ofl/bayon/METADATA.pb
  ofl/bayon/OFL.txt
  ofl/bayon/upstream.yaml
Labels: --- to_sandbox, II Font Upgrade

#3495 Suwannaphum: Version 8.000; ttfautohint (v1.8.3) added
  ofl/suwannaphum/DESCRIPTION.en_us.html
  ofl/suwannaphum/METADATA.pb
  ofl/suwannaphum/OFL.txt
  ofl/suwannaphum/Suwannaphum-Black.ttf
  ofl/suwannaphum/Suwannaphum-Bold.ttf
  ofl/suwannaphum/Suwannaphum-Light.ttf
  ofl/suwannaphum/Suwannaphum-Regular.ttf
  ofl/suwannaphum/Suwannaphum-Thin.ttf
  ofl/suwannaphum/upstream.yaml
Labels: --- to_sandbox, II Font Upgrade

#3507 Dangrek: Version 8.000; ttfautohint (v1.8.3) added
  ofl/dangrek/DESCRIPTION.en_us.html
  ofl/dangrek/Dangrek-Regular.ttf
  ofl/dangrek/Dangrek.ttf
  ofl/dangrek/METADATA.pb
  ofl/dangrek/OFL.txt
  ofl/dangrek/upstream.yaml
Labels: --- to_sandbox, II Font Upgrade

#3491 Battambang: Version 8.000; ttfautohint (v1.8.3) added
  ofl/battambang/Battambang-Black.ttf
  ofl/battambang/Battambang-Bold.ttf
  ofl/battambang/Battambang-Light.ttf
  ofl/battambang/Battambang-Regular.ttf
  ofl/battambang/Battambang-Thin.ttf
  ofl/battambang/DESCRIPTION.en_us.html
  ofl/battambang/METADATA.pb
  ofl/battambang/OFL.txt
  ofl/battambang/upstream.yaml
Labels: --- to_sandbox, II Font Upgrade

#3504 Taprom: Version 8.000; ttfautohint (v1.8.3) added
  ofl/taprom/DESCRIPTION.en_us.html
  ofl/taprom/METADATA.pb
  ofl/taprom/OFL.txt
  ofl/taprom/Taprom-Regular.ttf
  ofl/taprom/Taprom.ttf
  ofl/taprom/upstream.yaml
Labels: --- to_sandbox, II Font Upgrade

#3496 Hanuman: Version 8.000; ttfautohint (v1.8.3) added
  ofl/hanuman/DESCRIPTION.en_us.html
  ofl/hanuman/Hanuman-Black.ttf
  ofl/hanuman/Hanuman-Bold.ttf
  ofl/hanuman/Hanuman-Light.ttf
  ofl/hanuman/Hanuman-Regular.ttf
  ofl/hanuman/Hanuman-Thin.ttf
  ofl/hanuman/METADATA.pb
  ofl/hanuman/OFL.txt
  ofl/hanuman/upstream.yaml
Labels: --- to_sandbox, II Font Upgrade

#3500 Odor Mean Chey: Version 8.000; ttfautohint (v1.8.3) added
  ofl/odormeanchey/DESCRIPTION.en_us.html
  ofl/odormeanchey/METADATA.pb
  ofl/odormeanchey/OFL.txt
  ofl/odormeanchey/OdorMeanChey-Regular.ttf
  ofl/odormeanchey/OdorMeanChey.ttf
  ofl/odormeanchey/upstream.yaml
Labels: --- to_sandbox, II Font Upgrade

#3502 Moulpali: Version 8.000; ttfautohint (v1.8.3) added
  ofl/moulpali/DESCRIPTION.en_us.html
  ofl/moulpali/METADATA.pb
  ofl/moulpali/Moulpali-Regular.ttf
  ofl/moulpali/Moulpali.ttf
  ofl/moulpali/OFL.txt
  ofl/moulpali/upstream.yaml
Labels: - Ready for Review, --- to_sandbox, II Font Upgrade

#3436 Big Shoulders Stencil Display: Version 2.000 added
  ofl/bigshouldersstencildisplay/BigShouldersStencilDisplay-Black.ttf
  ofl/bigshouldersstencildisplay/BigShouldersStencilDisplay-Bold.ttf
  ofl/bigshouldersstencildisplay/BigShouldersStencilDisplay-ExtraBold.ttf
  ofl/bigshouldersstencildisplay/BigShouldersStencilDisplay-Light.ttf
  ofl/bigshouldersstencildisplay/BigShouldersStencilDisplay-Medium.ttf
  ofl/bigshouldersstencildisplay/BigShouldersStencilDisplay-Regular.ttf
  ofl/bigshouldersstencildisplay/BigShouldersStencilDisplay-SemiBold.ttf
  ofl/bigshouldersstencildisplay/BigShouldersStencilDisplay-Thin.ttf
  ofl/bigshouldersstencildisplay/BigShouldersStencilDisplay[wght].ttf
  ofl/bigshouldersstencildisplay/DESCRIPTION.en_us.html
  ofl/bigshouldersstencildisplay/METADATA.pb
  ofl/bigshouldersstencildisplay/upstream.yaml
Labels: --- to_sandbox, II Font Upgrade

#3435 Big Shoulders Stencil Text: Version 2.000 added
  ofl/bigshouldersstenciltext/BigShouldersStencilText-Black.ttf
  ofl/bigshouldersstenciltext/BigShouldersStencilText-Bold.ttf
  ofl/bigshouldersstenciltext/BigShouldersStencilText-ExtraBold.ttf
  ofl/bigshouldersstenciltext/BigShouldersStencilText-Light.ttf
  ofl/bigshouldersstenciltext/BigShouldersStencilText-Medium.ttf
  ofl/bigshouldersstenciltext/BigShouldersStencilText-Regular.ttf
  ofl/bigshouldersstenciltext/BigShouldersStencilText-SemiBold.ttf
  ofl/bigshouldersstenciltext/BigShouldersStencilText-Thin.ttf
  ofl/bigshouldersstenciltext/BigShouldersStencilText[wght].ttf
  ofl/bigshouldersstenciltext/DESCRIPTION.en_us.html
  ofl/bigshouldersstenciltext/METADATA.pb
  ofl/bigshouldersstenciltext/upstream.yaml
Labels: --- to_sandbox, II Font Upgrade

#3503 Preahvihear: Version 8.000; ttfautohint (v1.8.3) added
  ofl/preahvihear/DESCRIPTION.en_us.html
  ofl/preahvihear/METADATA.pb
  ofl/preahvihear/OFL.txt
  ofl/preahvihear/Preahvihear-Regular.ttf
  ofl/preahvihear/Preahvihear.ttf
  ofl/preahvihear/upstream.yaml
Labels: --- to_sandbox, II Font Upgrade

#3809 RocknRoll One: Version 1.100 added
  ofl/rocknrollone/METADATA.pb
  ofl/rocknrollone/RocknRollOne-Regular.ttf
Labels: I CJK, --- to_sandbox, II Font Upgrade

#3796 Grechen Fuemen: Version 1.010; ttfautohint (v1.8.3) added
  ofl/grechenfuemen/DESCRIPTION.en_us.html
  ofl/grechenfuemen/GrechenFuemen-Regular.ttf
  ofl/grechenfuemen/METADATA.pb
  ofl/grechenfuemen/OFL.txt
  ofl/grechenfuemen/upstream.yaml
Labels: --- to_sandbox, II New Font

#3795 Grey Qo: Version 2.010 added
  ofl/greyqo/DESCRIPTION.en_us.html
  ofl/greyqo/GreyQo-Regular.ttf
  ofl/greyqo/METADATA.pb
  ofl/greyqo/OFL.txt
  ofl/greyqo/upstream.yaml
Labels: --- to_sandbox, II New Font

#3794 Fleur De Leah: Version 1.010; ttfautohint (v1.8.3) added
  ofl/fleurdeleah/DESCRIPTION.en_us.html
  ofl/fleurdeleah/FleurDeLeah-Regular.ttf
  ofl/fleurdeleah/METADATA.pb
  ofl/fleurdeleah/OFL.txt
  ofl/fleurdeleah/upstream.yaml
Labels: --- to_sandbox, II New Font

#3792 Birthstone: Version 1.013; ttfautohint (v1.8.3) added
  ofl/birthstone/Birthstone-Regular.ttf
  ofl/birthstone/DESCRIPTION.en_us.html
Labels: --- to_sandbox, II New Font

#3793 Birthstone Bounce: Version 1.010; ttfautohint (v1.8.3) added
  ofl/birthstonebounce/BirthstoneBounce-Medium.ttf
  ofl/birthstonebounce/BirthstoneBounce-Regular.ttf
  ofl/birthstonebounce/DESCRIPTION.en_us.html
  ofl/birthstonebounce/METADATA.pb
  ofl/birthstonebounce/OFL.txt
  ofl/birthstonebounce/upstream.yaml
Labels: --- to_sandbox, II New Font

#3499 Nokora, manual commit because Apache->OFL change
  apache/nokora/DESCRIPTION.en_us.html
  apache/nokora/LICENSE.txt
  ofl/nokora/DESCRIPTION.en_us.html
  ofl/nokora/METADATA.pb
  ofl/nokora/Nokora-Black.ttf
  ofl/nokora/Nokora-Bold.ttf
  ofl/nokora/Nokora-Light.ttf
  ofl/nokora/Nokora-Regular.ttf
  ofl/nokora/Nokora-Thin.ttf
  ofl/nokora/OFL.txt
  ofl/nokora/upstream.yaml
Labels: --- to_sandbox, II Font Upgrade

#3601 Fix STAT table in Spartan variable
  ofl/spartan/Spartan[wght].ttf
Labels: --- to_sandbox, II Font Upgrade

#3821 Dosis: Version 3.002 added
  ofl/dosis/Dosis[wght].ttf
  ofl/dosis/METADATA.pb
  ofl/dosis/OFL.txt
  ofl/dosis/upstream.yaml
Labels: - Ready for Review, II Font Upgrade

#3814 Removed from this repo deprecated fonts which are not in sandbox
  ofl/amaticasc/AmaticaSC-Bold.ttf
  ofl/amaticasc/AmaticaSC-Regular.ttf
  ofl/amaticasc/DESCRIPTION.en_us.html
  ofl/amaticasc/METADATA.pb
  ofl/amaticasc/OFL.txt
  ofl/andada/Andada-Regular.ttf
  ofl/andada/DESCRIPTION.en_us.html
  ofl/andada/FONTLOG.txt
  ofl/andada/METADATA.pb
  ofl/andada/OFL.txt
  ofl/andadasc/AndadaSC-Bold.ttf
  ofl/andadasc/AndadaSC-BoldItalic.ttf
  ofl/andadasc/AndadaSC-Italic.ttf
  ofl/andadasc/AndadaSC-Regular.ttf
  ofl/andadasc/DESCRIPTION.en_us.html
  ofl/andadasc/METADATA.pb
  ofl/andadasc/OFL.txt
  ofl/archivovfbeta/ArchivoVFBeta-Italic.ttf
  ofl/archivovfbeta/ArchivoVFBeta.ttf
  ofl/archivovfbeta/DESCRIPTION.en_us.html
  ofl/archivovfbeta/EARLY_ACCESS.category
  ofl/archivovfbeta/OFL.txt
  ofl/butchermancaps/ButchermanCaps-Regular.ttf
  ofl/butchermancaps/DESCRIPTION.en_us.html
  ofl/butchermancaps/METADATA.pb
  ofl/butchermancaps/OFL.txt
  ofl/cabinvfbeta/CabinVFBeta-Italic.ttf
  ofl/cabinvfbeta/CabinVFBeta.ttf
  ofl/cabinvfbeta/DESCRIPTION.en_us.html
  ofl/cabinvfbeta/EARLY_ACCESS.category
  ofl/cabinvfbeta/OFL.txt
  ofl/cherrybomb/CherryBomb-Regular.ttf
  ofl/cherrybomb/DESCRIPTION.en_us.html
  ofl/cherrybomb/METADATA.pb
  ofl/cherrybomb/OFL.txt
  ofl/eatercaps/DESCRIPTION.en_us.html
  ofl/eatercaps/EaterCaps-Regular.ttf
  ofl/eatercaps/METADATA.pb
  ofl/eatercaps/OFL.txt
  ofl/faustinavfbeta/DESCRIPTION.en_us.html
  ofl/faustinavfbeta/EARLY_ACCESS.category
  ofl/faustinavfbeta/FaustinaVFBeta-Italic.ttf
  ofl/faustinavfbeta/FaustinaVFBeta.ttf
  ofl/faustinavfbeta/OFL.txt
  ofl/josefinsansstdlight/DESCRIPTION.en_us.html
  ofl/josefinsansstdlight/JosefinSansStd-Light.ttf
  ofl/josefinsansstdlight/METADATA.pb
  ofl/josefinsansstdlight/OFL.txt
  ofl/stalinone/DESCRIPTION.en_us.html
  ofl/stalinone/METADATA.pb
  ofl/stalinone/OFL.txt
  ofl/stalinone/StalinOne-Regular.ttf
Labels: - In Progress, II No push needed

#3835 sourcesanspro: v2.045 added.
  ofl/sourcesanspro/METADATA.pb
  ofl/sourcesanspro/SourceSansPro-Black.ttf
  ofl/sourcesanspro/SourceSansPro-BlackItalic.ttf
  ofl/sourcesanspro/SourceSansPro-Bold.ttf
  ofl/sourcesanspro/SourceSansPro-BoldItalic.ttf
  ofl/sourcesanspro/SourceSansPro-ExtraLight.ttf
  ofl/sourcesanspro/SourceSansPro-ExtraLightItalic.ttf
  ofl/sourcesanspro/SourceSansPro-Italic.ttf
  ofl/sourcesanspro/SourceSansPro-Light.ttf
  ofl/sourcesanspro/SourceSansPro-LightItalic.ttf
  ofl/sourcesanspro/SourceSansPro-Regular.ttf
  ofl/sourcesanspro/SourceSansPro-SemiBold.ttf
  ofl/sourcesanspro/SourceSansPro-SemiBoldItalic.ttf
Labels: - Ready for Review, II Font Upgrade

#3848 Estonia: Version 1.012; ttfautohint (v1.8.3) added
  ofl/estonia/Estonia-Regular.ttf
Labels: - Ready for Review, II New Font

#3847 Corinthia: Version 1.011; ttfautohint (v1.8.3) added
  ofl/corinthia/Corinthia-Bold.ttf
  ofl/corinthia/Corinthia-Regular.ttf
Labels: --- to_sandbox, II New Font

#3855 Allura: Version 1.101 added
  ofl/allura/Allura-Regular.ttf
  ofl/allura/OFL.txt
Labels: - Ready for Review, II Font Upgrade

#3853 Are You Serious: Version 1.100 added
  ofl/areyouserious/DESCRIPTION.en_us.html
Labels: - Ready for Review, II Description/Metadata/OFL

#3858 Montagu Slab: Version 1.000 added
  ofl/montaguslab/DESCRIPTION.en_us.html
  ofl/montaguslab/METADATA.pb
  ofl/montaguslab/MontaguSlab[opsz,wght].ttf
  ofl/montaguslab/OFL.txt
  ofl/montaguslab/upstream.yaml
Labels: - Ready for Review, II New Font

#3831 Jost: Version 3.710 added
  ofl/jost/Jost-Italic[wght].ttf
  ofl/jost/Jost[wght].ttf
  ofl/jost/METADATA.pb
  ofl/jost/upstream.yaml
Labels: - Ready for Review, II Font Upgrade

#3846 Comforter Brush: Version 1.010; ttfautohint (v1.8.3) added
  ofl/comforterbrush/ComforterBrush-Regular.ttf
  ofl/comforterbrush/DESCRIPTION.en_us.html
  ofl/comforterbrush/METADATA.pb
  ofl/comforterbrush/OFL.txt
  ofl/comforterbrush/upstream.yaml
Labels: - In Progress, II New Font

#3783 Signika Negative: Version 2.001 added
  ofl/signikanegative/METADATA.pb
  ofl/signikanegative/OFL.txt
  ofl/signikanegative/SignikaNegative-Bold.ttf
  ofl/signikanegative/SignikaNegative-Light.ttf
  ofl/signikanegative/SignikaNegative-Regular.ttf
  ofl/signikanegative/SignikaNegative-SemiBold.ttf
  ofl/signikanegative/SignikaNegative[wght].ttf
  ofl/signikanegative/upstream.yaml
Labels: III VF Replacement, --- to_sandbox, II Font Upgrade

#3444 Mplus 2: Version 1.000; Mplus 1: Version 1.000
  ofl/mplus1/DESCRIPTION.en_us.html
  ofl/mplus1/METADATA.pb
  ofl/mplus1/Mplus1[wght].ttf
  ofl/mplus1/OFL.txt
  ofl/mplus1/upstream.yaml
  ofl/mplus2/DESCRIPTION.en_us.html
  ofl/mplus2/METADATA.pb
  ofl/mplus2/Mplus2[wght].ttf
  ofl/mplus2/OFL.txt
  ofl/mplus2/upstream.yaml
Labels: I CJK, - Ready for Review, II New Font

#3862 M PLUS 2: Version 1.001 added; M PLUS 1: Version 1.001 added
  ofl/mplus1/Mplus1[wght].ttf
  ofl/mplus1/upstream.yaml
  ofl/mplus2/Mplus2[wght].ttf
  ofl/mplus2/upstream.yaml
Labels: I CJK, - Ready for Review, II Small Fix

#3764 Rosario: Version 1.201 added
  ofl/rosario/METADATA.pb
  ofl/rosario/OFL.txt
  ofl/rosario/Rosario-Italic[wght].ttf
  ofl/rosario/Rosario[wght].ttf
  ofl/rosario/upstream.yaml
Labels: - Ready for Review, II Font Upgrade

#3864 Manrope: subsets added to metadata
  ofl/manrope/METADATA.pb
Labels: --- to_sandbox, II Description/Metadata/OFL

#3810 Bakbak One: Version 1.002; ttfautohint (v1.8.3) added
  ofl/bakbakone/BakbakOne-Regular.ttf
  ofl/bakbakone/DESCRIPTION.en_us.html
  ofl/bakbakone/METADATA.pb
  ofl/bakbakone/OFL.txt
  ofl/bakbakone/upstream.yaml
Labels: - Ready for Review, II New Font

#3822 Yuji Hentaigana Akira+Akebono : japanese subset added to metadata.pb
  ofl/yujihentaiganaakari/METADATA.pb
  ofl/yujihentaiganaakebono/METADATA.pb
Labels: I CJK, - Ready for Review, II Description/Metadata/OFL, -- API Tofu

#3878 Yuji Hentaigana Akebono: Version 3.002 added; Yuji Hentaigana Akari: Version 3.002 added
  ofl/yujihentaiganaakari/YujiHentaiganaAkari-Regular.ttf
  ofl/yujihentaiganaakari/upstream.yaml
  ofl/yujihentaiganaakebono/YujiHentaiganaAkebono-Regular.ttf
  ofl/yujihentaiganaakebono/upstream.yaml
Labels: I CJK, - Ready for Review, II Small Fix

#3781 Updating Inter to 3.019
  ofl/inter/Inter[slnt,wght].ttf
  ofl/inter/METADATA.pb
  ofl/inter/OFL.txt
Labels: - Ready for Review, II Font Upgrade

#3886 Comforter Brush: Version 1.013 added
  ofl/comforterbrush/ComforterBrush-Regular.ttf
  ofl/comforterbrush/DESCRIPTION.en_us.html
Labels: - Ready for Review, II New Font

#3845 Comforter: Version 1.010; ttfautohint (v1.8.3) added
  ofl/comforter/Comforter-Regular.ttf
  ofl/comforter/DESCRIPTION.en_us.html
  ofl/comforter/METADATA.pb
  ofl/comforter/OFL.txt
  ofl/comforter/upstream.yaml
Labels: --- to_sandbox, II New Font

#3785 Hepta Slab: Version 1.101 added
  ofl/heptaslab/HeptaSlab[wght].ttf
  ofl/heptaslab/METADATA.pb
  ofl/heptaslab/upstream.yaml
Labels: - Ready for Review, II Font Upgrade

#3782 Signika: Version 2.001 added
  ofl/signika/METADATA.pb
  ofl/signika/OFL.txt
  ofl/signika/Signika[wght].ttf
  ofl/signika/upstream.yaml
Labels: --- to_sandbox, II Font Upgrade

#3859 M PLUS Code Latin: Version 1.001; ttfautohint (v1.8.3) added; M PLUS 1 Code: Version 1.001 added
  ofl/mplus1code/DESCRIPTION.en_us.html
  ofl/mplus1code/METADATA.pb
  ofl/mplus1code/Mplus1Code[wght].ttf
  ofl/mplus1code/OFL.txt
  ofl/mplus1code/upstream.yaml
  ofl/mpluscodelatin/DESCRIPTION.en_us.html
  ofl/mpluscodelatin/METADATA.pb
  ofl/mpluscodelatin/MplusCodeLatin[wdth,wght].ttf
  ofl/mpluscodelatin/OFL.txt
  ofl/mpluscodelatin/upstream.yaml
Labels: I CJK, --- to_sandbox, II New Font

#3815 Kosugi: Version 4.001 added
  apache/kosugi/DESCRIPTION.en_us.html
  apache/kosugi/Kosugi-Regular.ttf
  apache/kosugi/LICENSE.txt
  apache/kosugi/METADATA.pb
  apache/kosugi/upstream.yaml
Labels: I CJK, - Ready for Review

#3816 Kosugi Maru: Version 4.001 added
  apache/kosugimaru/DESCRIPTION.en_us.html
  apache/kosugimaru/KosugiMaru-Regular.ttf
  apache/kosugimaru/LICENSE.txt
  apache/kosugimaru/METADATA.pb
  apache/kosugimaru/upstream.yaml
Labels: I CJK, - Ready for Review
