Repository google/fonts, pull requests merged in 2021-02, with the labels that each got.

#2986 Oi: Version 2.000 added
  ofl/oi/DESCRIPTION.en_us.html
  ofl/oi/METADATA.pb
  ofl/oi/OFL.txt
  ofl/oi/Oi-Regular.ttf
  ofl/oi/upstream.yaml
Labels: -- Ready to push, II New Font

#2982 Fix link to the Rounded M+ project homepage
  ofl/mplus1p/DESCRIPTION.en_us.html
  ofl/roundedmplus1c/DESCRIPTION.en_us.html
Labels: -- Ready to push, II Description/Metadata

#2914 Libre Barcode 128 Text: Version 1.005; ttfautohint (v1.8.3) added
  ofl/librebarcode128text/DESCRIPTION.en_us.html
  ofl/librebarcode128text/LibreBarcode128Text-Regular.ttf
  ofl/librebarcode128text/METADATA.pb
  ofl/librebarcode128text/OFL.txt
  ofl/librebarcode128text/upstream.yaml
Labels: - Ready for Review, II Font Upgrade

#2913 Libre Barcode 128: Version 1.005; ttfautohint (v1.8.3) added
  ofl/librebarcode128/DESCRIPTION.en_us.html
  ofl/librebarcode128/LibreBarcode128-Regular.ttf
  ofl/librebarcode128/METADATA.pb
  ofl/librebarcode128/OFL.txt
  ofl/librebarcode128/upstream.yaml
Labels: - Ready for Review, II Font Upgrade

#2912 Libre Barcode 39 Extended Text: Version 1.005; ttfautohint (v1.8.3) added
  ofl/librebarcode39extendedtext/DESCRIPTION.en_us.html
  ofl/librebarcode39extendedtext/LibreBarcode39ExtendedText-Regular.ttf
  ofl/librebarcode39extendedtext/METADATA.pb
  ofl/librebarcode39extendedtext/OFL.txt
  ofl/librebarcode39extendedtext/upstream.yaml
Labels: - Ready for Review, II Font Upgrade

#2915 Libre Barcode EAN13 Text: Version 1.008; ttfautohint (v1.8.3) added
  ofl/librebarcodeean13text/DESCRIPTION.en_us.html
  ofl/librebarcodeean13text/LibreBarcodeEAN13Text-Regular.ttf
  ofl/librebarcodeean13text/METADATA.pb
Labels: -- Ready to push, II Font Upgrade

#2909 Libre Barcode 39: Version 1.005; ttfautohint (v1.8.3) added
  ofl/librebarcode39/DESCRIPTION.en_us.html
  ofl/librebarcode39/LibreBarcode39-Regular.ttf
  ofl/librebarcode39/METADATA.pb
  ofl/librebarcode39/OFL.txt
  ofl/librebarcode39/upstream.yaml
Labels: - Ready for Review, II Font Upgrade

#2911 Libre Barcode 39 Extended: Version 1.005; ttfautohint (v1.8.3) added
  ofl/librebarcode39extended/DESCRIPTION.en_us.html
  ofl/librebarcode39extended/LibreBarcode39Extended-Regular.ttf
  ofl/librebarcode39extended/METADATA.pb
  ofl/librebarcode39extended/OFL.txt
  ofl/librebarcode39extended/upstream.yaml
Labels: - Ready for Review, II Font Upgrade

#2910 Libre Barcode 39 Text: Version 1.005; ttfautohint (v1.8.3) added
  ofl/librebarcode39text/DESCRIPTION.en_us.html
  ofl/librebarcode39text/LibreBarcode39Text-Regular.ttf
  ofl/librebarcode39text/METADATA.pb
  ofl/librebarcode39text/OFL.txt
  ofl/librebarcode39text/upstream.yaml
Labels: - Ready for Review, II Font Upgrade

#2988 Shippori Mincho and B1: removed chinese subsets
  ofl/shipporimincho/METADATA.pb
  ofl/shipporiminchob1/METADATA.pb
Labels: - Ready for Review, II Description/Metadata

#2979 Archivo: Version 2.001 added
  ofl/archivo/Archivo-Bold.ttf
  ofl/archivo/Archivo-BoldItalic.ttf
  ofl/archivo/Archivo-Italic.ttf
  ofl/archivo/Archivo-Italic[wdth,wght].ttf
  ofl/archivo/Archivo-Medium.ttf
  ofl/archivo/Archivo-MediumItalic.ttf
  ofl/archivo/Archivo-Regular.ttf
  ofl/archivo/Archivo-SemiBold.ttf
  ofl/archivo/Archivo-SemiBoldItalic.ttf
  ofl/archivo/Archivo[wdth,wght].ttf
  ofl/archivo/DESCRIPTION.en_us.html
  ofl/archivo/METADATA.pb
  ofl/archivo/OFL.txt
  ofl/archivo/upstream.yaml
Labels: - Needs Dave's opinion, -- Regressions, II Font Upgrade

#2880 Tsukimi Rounded: Version 1.032; ttfautohint (v1.8.3) added
  ofl/tsukimirounded/DESCRIPTION.en_us.html
  ofl/tsukimirounded/METADATA.pb
  ofl/tsukimirounded/OFL.txt
  ofl/tsukimirounded/TsukimiRounded-Bold.ttf
  ofl/tsukimirounded/TsukimiRounded-Light.ttf
  ofl/tsukimirounded/TsukimiRounded-Medium.ttf
  ofl/tsukimirounded/TsukimiRounded-Regular.ttf
  ofl/tsukimirounded/TsukimiRounded-SemiBold.ttf
  ofl/tsukimirounded/upstream.yaml
Labels: - Needs Dave's opinion, II New Font

#2989 Update optical_size.textproto
  axisregistry/optical_size.textproto
Labels: -- Ready to push, II Axis Registry

#2991 Updated catalog info for Rasa (3x)
  catalog/designers/annagiedrys/bio.html
  catalog/designers/annagiedrys/info.pb
  catalog/designers/davidbrezina/bio.html
  catalog/designers/davidbrezina/david_brezinas.png
  catalog/designers/davidbrezina/info.pb
  catalog/designers/rosetta/info.pb
Labels: - Ready for Review, II Catalog

#2983 Cherry Bomb One: Version 4.100; ttfautohint (v1.8.3) added
  ofl/cherrybombone/CherryBombOne-Regular.ttf
Labels: -- Ready to push, II New Font

#3095 Brygada 1918: Version 3.005 added
  ofl/brygada1918/Brygada1918-Italic[wght].ttf
  ofl/brygada1918/Brygada1918[wght].ttf
  ofl/brygada1918/METADATA.pb
  ofl/brygada1918/upstream.yaml
Labels: -- Ready to push, II Font Upgrade

#3093 Fraunces and Space Grotesk designers bio added
  catalog/designers/binoydominic/binoy_dominic.png
  catalog/designers/binoydominic/bio.html
  catalog/designers/binoydominic/info.pb
  catalog/designers/flaviazimbardi/bio.html
  catalog/designers/flaviazimbardi/flavia_zimbardi.jpg
  catalog/designers/flaviazimbardi/info.pb
  catalog/designers/floriankarsten/bio.html
  catalog/designers/floriankarsten/florian_karsten.png
  catalog/designers/floriankarsten/info.pb
  catalog/designers/phaedracharles/bio.html
  catalog/designers/phaedracharles/info.pb
  catalog/designers/phaedracharles/phaedra_charles.jpg
  catalog/designers/santhoshthottingal/bio.html
  catalog/designers/santhoshthottingal/info.pb
  catalog/designers/santhoshthottingal/santhosh_thottingal.png
  catalog/designers/smc/bio.html
  catalog/designers/smc/info.pb
  catalog/designers/smc/smc.png
  catalog/designers/undercasetype/bio.html
  catalog/designers/undercasetype/info.pb
  catalog/designers/undercasetype/undercase_type.png
Labels: -- Ready to push

#3096 Benne: Version 1.001 added
  ofl/benne/Benne-Regular.ttf
  ofl/benne/upstream.yaml
Labels: - Ready for Review, II Font Upgrade

#3109 Added designers/bonnieshavertroup profile
  catalog/designers/bonnieshavertroup/bio.html
  catalog/designers/bonnieshavertroup/bonnieshavertroup.png
  catalog/designers/bonnieshavertroup/info.pb
Labels: --- to_sandbox, II Catalog

#3107 Kufam Metadata and designers info updated.
  catalog/designers/arturschmal/bio.html
  catalog/designers/originaltype/bio.html
  catalog/designers/originaltype/info.pb
  catalog/designers/originaltype/original_type.png
  ofl/kufam/METADATA.pb
Labels: --- to_sandbox, II Catalog, II Description/Metadata

#2802 Asap: Version 3.000 added
  ofl/asap/Asap-Bold.ttf
  ofl/asap/Asap-BoldItalic.ttf
  ofl/asap/Asap-Italic.ttf
  ofl/asap/Asap-Italic[wght].ttf
  ofl/asap/Asap-Medium.ttf
  ofl/asap/Asap-MediumItalic.ttf
  ofl/asap/Asap-Regular.ttf
  ofl/asap/Asap-SemiBold.ttf
  ofl/asap/Asap-SemiBoldItalic.ttf
  ofl/asap/Asap[wght].ttf
  ofl/asap/DESCRIPTION.en_us.html
  ofl/asap/METADATA.pb
  ofl/asap/OFL.txt
  ofl/asap/static/Asap-Bold.ttf
  ofl/asap/static/Asap-BoldItalic.ttf
  ofl/asap/static/Asap-Italic.ttf
  ofl/asap/static/Asap-Medium.ttf
  ofl/asap/static/Asap-MediumItalic.ttf
  ofl/asap/static/Asap-Regular.ttf
  ofl/asap/static/Asap-SemiBold.ttf
  ofl/asap/static/Asap-SemiBoldItalic.ttf
  ofl/asap/upstream.yaml
Labels: -- Ready to push, II Font Upgrade
