Repository google/fonts, pull requests merged in 2021-05, with the labels that each got.

#3364 Zen Tokyo Zoo: Version 1.002; ttfautohint (v1.8.3) added
  ofl/zentokyozoo/DESCRIPTION.en_us.html
  ofl/zentokyozoo/METADATA.pb
  ofl/zentokyozoo/OFL.txt
  ofl/zentokyozoo/ZenTokyoZoo-Regular.ttf
  ofl/zentokyozoo/upstream.yaml
Labels: --- to_sandbox, II New Font

#3379 Italianno: Version 1.100; ttfautohint (v1.8.3) added
  ofl/italianno/DESCRIPTION.en_us.html
  ofl/italianno/Italianno-Regular.ttf
  ofl/italianno/METADATA.pb
  ofl/italianno/OFL.txt
  ofl/italianno/upstream.yaml
Labels: --- to_sandbox, II New Font

#3384 Playball: Version 1.001 added
  ofl/playball/DESCRIPTION.en_us.html
  ofl/playball/METADATA.pb
  ofl/playball/OFL.txt
  ofl/playball/Playball-Regular.ttf
  ofl/playball/upstream.yaml
Labels: - Ready for Review, II Font Upgrade

#3362 Atkinson Hyperlegible: Version 1.006; ttfautohint (v1.8.3) added
  ofl/atkinsonhyperlegible/AtkinsonHyperlegible-Bold.ttf
  ofl/atkinsonhyperlegible/AtkinsonHyperlegible-BoldItalic.ttf
  ofl/atkinsonhyperlegible/AtkinsonHyperlegible-Italic.ttf
  ofl/atkinsonhyperlegible/AtkinsonHyperlegible-Regular.ttf
  ofl/atkinsonhyperlegible/DESCRIPTION.en_us.html
  ofl/atkinsonhyperlegible/METADATA.pb
  ofl/atkinsonhyperlegible/OFL.txt
  ofl/atkinsonhyperlegible/upstream.yaml
Labels: -- Ready to push, II New Font

#3386 Update Palette Mosaic description file
  ofl/palettemosaic/DESCRIPTION.en_us.html
Labels: - Ready for Review, II Description/Metadata/OFL

#3410 Quicksand: Version 3.006 added
  ofl/quicksand/METADATA.pb
  ofl/quicksand/Quicksand[wght].ttf
  ofl/quicksand/static/Quicksand-Bold.ttf
  ofl/quicksand/static/Quicksand-Light.ttf
  ofl/quicksand/static/Quicksand-Medium.ttf
  ofl/quicksand/static/Quicksand-Regular.ttf
  ofl/quicksand/upstream.yaml
Labels: --- to_sandbox, II Font Upgrade

#3423 tanukizamurai : bio added
  catalog/designers/tanukizamurai/bio.html
  catalog/designers/tanukizamurai/info.pb
  catalog/designers/tanukizamurai/tanukizamurai.png
Labels: - Ready for Review, II Catalog

#3420 Santiago Orozco: bio updated
  catalog/designers/santiagoorozco/bio.html
  catalog/designers/santiagoorozco/info.pb
  catalog/designers/santiagoorozco/santiago_orozco.png
  catalog/designers/santiagoorozco/santiagoorozco.png
Labels: - Ready for Review, II Catalog

#3421 SIL International: bio added
  catalog/designers/silinternational/bio.html
  catalog/designers/silinternational/info.pb
  catalog/designers/silinternational/silinternational.png
Labels: - Ready for Review, II Catalog

#3343 Fix incorrect file permissions
  ofl/baskervville/OFL.txt
  ofl/bethellen/OFL.txt
  ofl/dmmono/OFL.txt
  ofl/encodesans/OFL.txt
  ofl/encodesanssc/OFL.txt
  ofl/epilogue/OFL.txt
  ofl/farro/OFL.txt
  ofl/grandstander/OFL.txt
  ofl/ibmplexmono/OFL.txt
  ofl/ibmplexsans/OFL.txt
  ofl/ibmplexsanscondensed/OFL.txt
  ofl/ibmplexserif/OFL.txt
  ofl/librecaslondisplay/OFL.txt
  ofl/librecaslontext/OFL.txt
  ofl/livvic/OFL.txt
  ofl/oswald/OFL.txt
  ofl/petrona/OFL.txt
  ofl/podkova/OFL.txt
  ofl/publicsans/OFL.txt
  ofl/rokkitt/OFL.txt
  ofl/sourcecodepro/SourceCodePro-Black.ttf
  ofl/sourcecodepro/SourceCodePro-BlackItalic.ttf
  ofl/sourcecodepro/SourceCodePro-Bold.ttf
  ofl/sourcecodepro/SourceCodePro-BoldItalic.ttf
  ofl/sourcecodepro/SourceCodePro-ExtraLight.ttf
  ofl/sourcecodepro/SourceCodePro-ExtraLightItalic.ttf
  ofl/sourcecodepro/SourceCodePro-Italic.ttf
  ofl/sourcecodepro/SourceCodePro-Light.ttf
  ofl/sourcecodepro/SourceCodePro-LightItalic.ttf
  ofl/sourcecodepro/SourceCodePro-Medium.ttf
  ofl/sourcecodepro/SourceCodePro-MediumItalic.ttf
  ofl/sourcecodepro/SourceCodePro-Regular.ttf
  ofl/sourcecodepro/SourceCodePro-SemiBold.ttf
  ofl/sourcecodepro/SourceCodePro-SemiBoldItalic.ttf
  ofl/spartan/OFL.txt
  ofl/spectral/OFL.txt
  ofl/spectralsc/ofl.txt
  ofl/trispace/OFL.txt
  ofl/turretroad/OFL.txt
  ofl/turretroad/TurretRoad-Bold.ttf
  ofl/turretroad/TurretRoad-ExtraBold.ttf
  ofl/turretroad/TurretRoad-ExtraLight.ttf
  ofl/turretroad/TurretRoad-Light.ttf
  ofl/turretroad/TurretRoad-Medium.ttf
  ofl/turretroad/TurretRoad-Regular.ttf
Labels: - Needs Dave's opinion

#3417 Scheherazade new: version 3.100 added
  ofl/scheherazadenew/DESCRIPTION.en_us.html
  ofl/scheherazadenew/METADATA.pb
  ofl/scheherazadenew/OFL.txt
  ofl/scheherazadenew/ScheherazadeNew-Bold.ttf
  ofl/scheherazadenew/ScheherazadeNew-Regular.ttf
Labels: - Needs confirmation, II Font Upgrade

#3430 Andada Pro: Version 3.003 added
  ofl/andadapro/AndadaPro-Italic[wght].ttf
  ofl/andadapro/AndadaPro[wght].ttf
  ofl/andadapro/DESCRIPTION.en_us.html
  ofl/andadapro/METADATA.pb
  ofl/andadapro/OFL.txt
  ofl/andadapro/upstream.yaml
Labels: - Ready for Review, II New Font

#3424 Style Script: Version 1.010; ttfautohint (v1.8.3) added
  ofl/stylescript/DESCRIPTION.en_us.html
  ofl/stylescript/METADATA.pb
  ofl/stylescript/OFL.txt
  ofl/stylescript/StyleScript-Regular.ttf
  ofl/stylescript/upstream.yaml
Labels: - Ready for Review, II New Font

#3422 MonteCarlo: Version 1.010; ttfautohint (v1.8.3) added
  ofl/montecarlo/DESCRIPTION.en_us.html
  ofl/montecarlo/METADATA.pb
  ofl/montecarlo/MonteCarlo-Regular.ttf
  ofl/montecarlo/OFL.txt
  ofl/montecarlo/upstream.yaml
Labels: - Ready for Review, II New Font

#3443 Lovers Quarrel: Version 1.010; ttfautohint (v1.8.3) added
  ofl/loversquarrel/DESCRIPTION.en_us.html
  ofl/loversquarrel/LoversQuarrel-Regular.ttf
  ofl/loversquarrel/METADATA.pb
  ofl/loversquarrel/OFL.txt
  ofl/loversquarrel/upstream.yaml
Labels: - Ready for Review, II Font Upgrade

#3385 STIX Two Text: Version 2.13 b170 added
  ofl/stixtwotext/STIXTwoText-Italic[wght].ttf
  ofl/stixtwotext/STIXTwoText[wght].ttf
Labels: - Ready for Review, II New Font
