Repository google/fonts, pull requests merged in 2021-12, with the labels that each got.

#4108 Heebo : description updated
  ofl/heebo/DESCRIPTION.en_us.html
Labels: --- to sandbox, II Description/Metadata/OFL

#4124 Vollkorn: [HOTFIX] bumped up version number
  ofl/vollkorn/Vollkorn-Italic[wght].ttf
  ofl/vollkorn/Vollkorn[wght].ttf
Labels: - Ready for Review, II Font Upgrade, III Small Fix

#4111 Qwitcher Grypen: Version 1.100; ttfautohint (v1.8.3) added
  ofl/qwitchergrypen/DESCRIPTION.en_us.html
  ofl/qwitchergrypen/METADATA.pb
  ofl/qwitchergrypen/OFL.txt
  ofl/qwitchergrypen/QwitcherGrypen-Bold.ttf
  ofl/qwitchergrypen/QwitcherGrypen-Regular.ttf
  ofl/qwitchergrypen/upstream.yaml
Labels: - Ready for Review, II New Font

#4084 Twinkle Star: Version 2.010; ttfautohint (v1.8.3) added
  ofl/twinklestar/DESCRIPTION.en_us.html
  ofl/twinklestar/METADATA.pb
  ofl/twinklestar/OFL.txt
  ofl/twinklestar/TwinkleStar-Regular.ttf
  ofl/twinklestar/upstream.yaml
Labels: --- to sandbox, II New Font

#4088 Oooh Baby: Version 1.010; ttfautohint (v1.8.3) added
  ofl/ooohbaby/DESCRIPTION.en_us.html
  ofl/ooohbaby/METADATA.pb
  ofl/ooohbaby/OFL.txt
  ofl/ooohbaby/OoohBaby-Regular.ttf
  ofl/ooohbaby/upstream.yaml
Labels: --- to sandbox, II New Font

#4112 Moo Lah Lah: Version 1.010; ttfautohint (v1.8.3) added
  ofl/moolahlah/DESCRIPTION.en_us.html
  ofl/moolahlah/METADATA.pb
  ofl/moolahlah/MooLahLah-Regular.ttf
  ofl/moolahlah/OFL.txt
  ofl/moolahlah/upstream.yaml
Labels: --- to sandbox, II New Font

#4126 Baskervville: Version 1.001; ttfautohint (v1.8.3) added
  ofl/baskervville/Baskervville-Italic.ttf
  ofl/baskervville/Baskervville-Regular.ttf
  ofl/baskervville/upstream.yaml
Labels: --- to sandbox, II Font Upgrade

#4114 Inspiration: Version 2.010; ttfautohint (v1.8.3) added
  ofl/inspiration/DESCRIPTION.en_us.html
  ofl/inspiration/Inspiration-Regular.ttf
  ofl/inspiration/METADATA.pb
  ofl/inspiration/OFL.txt
  ofl/inspiration/upstream.yaml
Labels: --- to sandbox, II New Font

#4115 Kolker Brush: Version 1.010; ttfautohint (v1.8.3) added
  ofl/kolkerbrush/DESCRIPTION.en_us.html
  ofl/kolkerbrush/KolkerBrush-Regular.ttf
  ofl/kolkerbrush/METADATA.pb
  ofl/kolkerbrush/OFL.txt
  ofl/kolkerbrush/upstream.yaml
Labels: --- to sandbox, II New Font

#4095 splinesans: v1.000 added
  ofl/splinesans/DESCRIPTION.en_us.html
  ofl/splinesans/METADATA.pb
  ofl/splinesans/OFL.txt
  ofl/splinesans/SplineSans[wght].ttf
Labels: --- to sandbox, II New Font

#4145 Alice: Version 2.003; ttfautohint (v1.8.3) added
  ofl/alice/Alice-Regular.ttf
  ofl/alice/DESCRIPTION.en_us.html
  ofl/alice/METADATA.pb
  ofl/alice/OFL.txt
  ofl/alice/upstream.yaml
Labels: --- to sandbox, II Font Upgrade

#4136 Mea Culpa: Version 1.010; ttfautohint (v1.8.3) added
  ofl/meaculpa/DESCRIPTION.en_us.html
  ofl/meaculpa/METADATA.pb
  ofl/meaculpa/MeaCulpa-Regular.ttf
  ofl/meaculpa/OFL.txt
  ofl/meaculpa/upstream.yaml
Labels: - Ready for Review, II New Font

#4135 Love Light: Version 1.010; ttfautohint (v1.8.3) added
  ofl/lovelight/DESCRIPTION.en_us.html
  ofl/lovelight/LoveLight-Regular.ttf
  ofl/lovelight/METADATA.pb
  ofl/lovelight/OFL.txt
  ofl/lovelight/upstream.yaml
Labels: --- to sandbox, II New Font

#4121 M PLUS Code Latin: Version 1.005; ttfautohint (v1.8.3) added; M PLUS 1 Code: Version 1.005 added
  ofl/mplus1code/MPLUS1Code[wght].ttf
  ofl/mplus1code/upstream.yaml
  ofl/mpluscodelatin/MPLUSCodeLatin[wdth,wght].ttf
  ofl/mpluscodelatin/upstream.yaml
Labels: I CJK, --- to sandbox, III Small Fix

#4113 Ole: Version 1.010; ttfautohint (v1.8.3) added
  ofl/ole/DESCRIPTION.en_us.html
  ofl/ole/METADATA.pb
  ofl/ole/OFL.txt
  ofl/ole/Ole-Regular.ttf
  ofl/ole/upstream.yaml
Labels: --- to sandbox, II New Font

#4155 Font Bureau: designer added
  catalog/designers/fontbureau/bio.html
  catalog/designers/fontbureau/fontbureau.png
  catalog/designers/fontbureau/info.pb
Labels: - Ready for Review, II Designer profile

#4105 Bevan: Version 2.100; ttfautohint (v1.8.3) added
  ofl/bevan/Bevan-Italic.ttf
  ofl/bevan/Bevan-Regular.ttf
  ofl/bevan/DESCRIPTION.en_us.html
  ofl/bevan/METADATA.pb
  ofl/bevan/OFL.txt
  ofl/bevan/upstream.yaml
Labels: III Expand styles, - Needs Dave's opinion, II Font Upgrade

#4158 Baloo Bhaijaan 2: arabic subset added
  ofl/baloobhaijaan2/METADATA.pb
Labels: --- to sandbox, II Description/Metadata/OFL

#4159 Zen Maru Gothic: description updated
  ofl/zenmarugothic/DESCRIPTION.en_us.html
Labels: - Ready for Review, II Description/Metadata/OFL

#4146 League Gothic: Version 2.001 added
  ofl/leaguegothic/DESCRIPTION.en_us.html
  ofl/leaguegothic/LeagueGothic[slnt,wdth].ttf
  ofl/leaguegothic/LeagueGothic[wdth].ttf
  ofl/leaguegothic/METADATA.pb
  ofl/leaguegothic/OFL.txt
  ofl/leaguegothic/upstream.yaml
Labels: - Ready for Review, II New Font

#4140 oswald/DESC updated to correct Cyrillic info
  ofl/oswald/DESCRIPTION.en_us.html
Labels: --- to sandbox, II Description/Metadata/OFL

#4170 Fredoka: Version 2.000 added
  ofl/fredoka/DESCRIPTION.en_us.html
  ofl/fredoka/Fredoka[wdth,wght].ttf
  ofl/fredoka/METADATA.pb
  ofl/fredoka/OFL.txt
  ofl/fredoka/upstream.yaml
Labels: II New Font

#4175 Hubballi: Version 1.000; ttfautohint (v1.8.3) added
  ofl/hubballi/DESCRIPTION.en_us.html
  ofl/hubballi/Hubballi-Regular.ttf
  ofl/hubballi/METADATA.pb
  ofl/hubballi/OFL.txt
  ofl/hubballi/upstream.yaml
Labels: --- to sandbox, II New Font, > Commissioned

#4174 Math clarification done
  ofl/stixtwotext/DESCRIPTION.en_us.html
  ofl/stixtwotext/OFL.txt
Labels: --- to sandbox, II Description/Metadata/OFL
