Repository google/fonts, pull requests merged in 2021-11, with the labels that each got.

#3991 Nunito: Version 3.601 added
  ofl/nunito/METADATA.pb
  ofl/nunito/Nunito-Black.ttf
  ofl/nunito/Nunito-BlackItalic.ttf
  ofl/nunito/Nunito-Bold.ttf
  ofl/nunito/Nunito-BoldItalic.ttf
  ofl/nunito/Nunito-ExtraBold.ttf
  ofl/nunito/Nunito-ExtraBoldItalic.ttf
  ofl/nunito/Nunito-ExtraLight.ttf
  ofl/nunito/Nunito-ExtraLightItalic.ttf
  ofl/nunito/Nunito-Italic.ttf
  ofl/nunito/Nunito-Italic[wght].ttf
  ofl/nunito/Nunito-Light.ttf
  ofl/nunito/Nunito-LightItalic.ttf
  ofl/nunito/Nunito-Regular.ttf
  ofl/nunito/Nunito-SemiBold.ttf
  ofl/nunito/Nunito-SemiBoldItalic.ttf
  ofl/nunito/Nunito[wght].ttf
  ofl/nunito/upstream.yaml
Labels: III VF Replacement, - Ready for Review, II Font Upgrade, Commissioned

#3983 Baloo Paaji 2: Version 1.700 added
  ofl/baloopaaji2/BalooPaaji2-Bold.ttf
  ofl/baloopaaji2/BalooPaaji2-ExtraBold.ttf
  ofl/baloopaaji2/BalooPaaji2-Medium.ttf
  ofl/baloopaaji2/BalooPaaji2-Regular.ttf
  ofl/baloopaaji2/BalooPaaji2-SemiBold.ttf
  ofl/baloopaaji2/BalooPaaji2[wght].ttf
  ofl/baloopaaji2/DESCRIPTION.en_us.html
  ofl/baloopaaji2/METADATA.pb
  ofl/baloopaaji2/OFL.txt
  ofl/baloopaaji2/upstream.yaml
Labels: III VF Replacement, --- to_sandbox, II Font Upgrade

#4003 Luxurious Script: Version 1.010; ttfautohint (v1.8.3) added
  ofl/luxuriousscript/DESCRIPTION.en_us.html
  ofl/luxuriousscript/LuxuriousScript-Regular.ttf
  ofl/luxuriousscript/METADATA.pb
  ofl/luxuriousscript/OFL.txt
  ofl/luxuriousscript/upstream.yaml
Labels: - Ready for Review, II New Font

#4001 Fuzzy Bubbles: Version 1.010; ttfautohint (v1.8.3) added
  ofl/fuzzybubbles/DESCRIPTION.en_us.html
  ofl/fuzzybubbles/FuzzyBubbles-Bold.ttf
  ofl/fuzzybubbles/FuzzyBubbles-Regular.ttf
  ofl/fuzzybubbles/METADATA.pb
  ofl/fuzzybubbles/OFL.txt
  ofl/fuzzybubbles/upstream.yaml
Labels: - Ready for Review, II New Font

#4005 RedactedScript: Version 1.001; ttfautohint (v1.8.3) added
  ofl/redactedscript/DESCRIPTION.en_us.html
  ofl/redactedscript/METADATA.pb
  ofl/redactedscript/OFL.txt
  ofl/redactedscript/RedactedScript-Bold.ttf
  ofl/redactedscript/RedactedScript-Light.ttf
  ofl/redactedscript/RedactedScript-Regular.ttf
  ofl/redactedscript/upstream.yaml
Labels: --- to_sandbox, II New Font

#3982 Baloo Bhai 2: Version 1.700 added
  ofl/baloobhai2/BalooBhai2-Bold.ttf
  ofl/baloobhai2/BalooBhai2-ExtraBold.ttf
  ofl/baloobhai2/BalooBhai2-Medium.ttf
  ofl/baloobhai2/BalooBhai2-Regular.ttf
  ofl/baloobhai2/BalooBhai2-SemiBold.ttf
  ofl/baloobhai2/BalooBhai2[wght].ttf
  ofl/baloobhai2/DESCRIPTION.en_us.html
  ofl/baloobhai2/METADATA.pb
  ofl/baloobhai2/OFL.txt
  ofl/baloobhai2/upstream.yaml
Labels: III VF Replacement, --- to_sandbox, II Font Upgrade

#4010 sourcecodepro: v1.018 added
  ofl/sourcecodepro/METADATA.pb
  ofl/sourcecodepro/SourceCodePro-Black.ttf
  ofl/sourcecodepro/SourceCodePro-BlackItalic.ttf
  ofl/sourcecodepro/SourceCodePro-Bold.ttf
  ofl/sourcecodepro/SourceCodePro-BoldItalic.ttf
  ofl/sourcecodepro/SourceCodePro-ExtraLight.ttf
  ofl/sourcecodepro/SourceCodePro-ExtraLightItalic.ttf
  ofl/sourcecodepro/SourceCodePro-Italic.ttf
  ofl/sourcecodepro/SourceCodePro-Italic[wght].ttf
  ofl/sourcecodepro/SourceCodePro-Light.ttf
  ofl/sourcecodepro/SourceCodePro-LightItalic.ttf
  ofl/sourcecodepro/SourceCodePro-Medium.ttf
  ofl/sourcecodepro/SourceCodePro-MediumItalic.ttf
  ofl/sourcecodepro/SourceCodePro-Regular.ttf
  ofl/sourcecodepro/SourceCodePro-SemiBold.ttf
  ofl/sourcecodepro/SourceCodePro-SemiBoldItalic.ttf
  ofl/sourcecodepro/SourceCodePro[wght].ttf
Labels: III VF Replacement, - Ready for Review, II Font Upgrade

#4008 Dan Ross : designer added.
  catalog/designers/danross/bio.html
  catalog/designers/danross/dan_ross.png
  catalog/designers/danross/info.pb
Labels: - Ready for Review, II Catalog

#4031 Readex Pro: Version 1.203 added
  ofl/readexpro/ReadexPro[wght].ttf
Labels: - Ready for Review, II Font Upgrade, III Small Fix

#3992 Urbanist: Version 1.303 added
  ofl/urbanist/Urbanist-Italic[wght].ttf
  ofl/urbanist/Urbanist[wght].ttf
  ofl/urbanist/upstream.yaml
Labels: III Expand language support, II Font Upgrade

#4002 Gwendolyn: Version 1.010; ttfautohint (v1.8.3) added
  ofl/gwendolyn/DESCRIPTION.en_us.html
  ofl/gwendolyn/Gwendolyn-Bold.ttf
  ofl/gwendolyn/Gwendolyn-Regular.ttf
  ofl/gwendolyn/METADATA.pb
  ofl/gwendolyn/OFL.txt
  ofl/gwendolyn/upstream.yaml
Labels: --- to_sandbox, II New Font

#4000 Meow Script: Version 1.010; ttfautohint (v1.8.3) added
  ofl/meowscript/DESCRIPTION.en_us.html
  ofl/meowscript/METADATA.pb
  ofl/meowscript/MeowScript-Regular.ttf
  ofl/meowscript/OFL.txt
  ofl/meowscript/upstream.yaml
Labels: --- to_sandbox, II New Font

#3999 Smooch: Version 1.010; ttfautohint (v1.8.3) added
  ofl/smooch/DESCRIPTION.en_us.html
  ofl/smooch/METADATA.pb
  ofl/smooch/OFL.txt
  ofl/smooch/Smooch-Regular.ttf
  ofl/smooch/upstream.yaml
Labels: --- to_sandbox, II New Font

#4037 Artakana: bio updated
  catalog/designers/artakana/bio.html
Labels: --- to_sandbox, II Catalog

#4030 Taprom: Version 8.001; ttfautohint (v1.8.3) added
  ofl/taprom/Taprom-Regular.ttf
Labels: --- to_sandbox, II Font Upgrade, III Small Fix

#4029 Suwannaphum: Version 8.001; ttfautohint (v1.8.3) added
  ofl/suwannaphum/Suwannaphum-Black.ttf
  ofl/suwannaphum/Suwannaphum-Bold.ttf
  ofl/suwannaphum/Suwannaphum-Light.ttf
  ofl/suwannaphum/Suwannaphum-Regular.ttf
  ofl/suwannaphum/Suwannaphum-Thin.ttf
Labels: --- to_sandbox, II Font Upgrade, III Small Fix

#4009 Christian Naths : designer added
  catalog/designers/christiannaths/bio.html
  catalog/designers/christiannaths/christiannaths.png
  catalog/designers/christiannaths/info.pb
Labels: - Ready for Review, II Designer profile

#4028 Preahvihear: Version 8.001; ttfautohint (v1.8.3) added
  ofl/preahvihear/Preahvihear-Regular.ttf
Labels: --- to_sandbox, II Font Upgrade, III Small Fix

#4027 Odor Mean Chey: Version 8.001; ttfautohint (v1.8.3) added
  ofl/odormeanchey/OdorMeanChey-Regular.ttf
Labels: --- to_sandbox, II Font Upgrade, III Small Fix

#4026 Moulpali: Version 8.001; ttfautohint (v1.8.3) added
  ofl/moulpali/Moulpali-Regular.ttf
Labels: - Ready for Review, II Font Upgrade, III Small Fix

#4025 Moul: Version 8.001; ttfautohint (v1.8.3) added
  ofl/moul/Moul-Regular.ttf
Labels: - Ready for Review, II Font Upgrade, III Small Fix

#4004 Redacted: Version 1.001; ttfautohint (v1.8.3) added
  ofl/redacted/DESCRIPTION.en_us.html
  ofl/redacted/METADATA.pb
  ofl/redacted/OFL.txt
  ofl/redacted/Redacted-Regular.ttf
  ofl/redacted/upstream.yaml
Labels: --- to_sandbox, II New Font

#4049 Oi: Version 3.000 added
  ofl/oi/METADATA.pb
  ofl/oi/Oi-Regular.ttf
Labels: III Expand language support, --- to_sandbox, II Font Upgrade

#4024 Metal: Version 8.001; ttfautohint (v1.8.3) added
  ofl/metal/Metal-Regular.ttf
Labels: - Ready for Review, II Font Upgrade, III Small Fix

#4023 Koh Santepheap: Version 2.001; ttfautohint (v1.8.3) added
  ofl/kohsantepheap/KohSantepheap-Black.ttf
  ofl/kohsantepheap/KohSantepheap-Bold.ttf
  ofl/kohsantepheap/KohSantepheap-Light.ttf
  ofl/kohsantepheap/KohSantepheap-Regular.ttf
  ofl/kohsantepheap/KohSantepheap-Thin.ttf
Labels: --- to_sandbox, II Font Upgrade, III Small Fix

#4022 Hanuman: Version 8.001; ttfautohint (v1.8.3) added
  ofl/hanuman/Hanuman-Black.ttf
  ofl/hanuman/Hanuman-Bold.ttf
  ofl/hanuman/Hanuman-Light.ttf
  ofl/hanuman/Hanuman-Regular.ttf
  ofl/hanuman/Hanuman-Thin.ttf
Labels: --- to_sandbox, II Font Upgrade, III Small Fix

#4021 Freehand: Version 8.001; ttfautohint (v1.8.3) added
  ofl/freehand/Freehand-Regular.ttf
Labels: --- to_sandbox, II Font Upgrade, III Small Fix

#4020 Fasthand: Version 8.001; ttfautohint (v1.8.3) added
  ofl/fasthand/Fasthand-Regular.ttf
Labels: --- to_sandbox, II Font Upgrade, III Small Fix

#4019 Bokor: Version 8.001; ttfautohint (v1.8.3) added
  ofl/bokor/Bokor-Regular.ttf
Labels: --- to_sandbox, II Font Upgrade, III Small Fix

#4053 Update METADATA.pb for Nokora to fix license value
  ofl/nokora/METADATA.pb
Labels: II Description/Metadata/OFL

#4054 Eczar: Description and Metadata file updated
  ofl/eczar/DESCRIPTION.en_us.html
  ofl/eczar/METADATA.pb
Labels: --- to sandbox, II Description/Metadata/OFL

#4048 Vaibhav Singh profile added
  catalog/designers/vaibhavsingh/bio.html
  catalog/designers/vaibhavsingh/info.pb
  catalog/designers/vaibhavsingh/vaibhavsingh.png
Labels: --- to sandbox, II Designer profile

#4067 sourceserif4: v4.004 added.
  ofl/sourceserif4/DESCRIPTION.en_us.html
  ofl/sourceserif4/METADATA.pb
  ofl/sourceserif4/SourceSerif4-Italic[opsz,wght].ttf
  ofl/sourceserif4/SourceSerif4[opsz,wght].ttf
Labels: II New Font

#4064 Gutenberglabo : bio updated.
  catalog/designers/gutenberglabo/bio.html
Labels: - Ready for Review, II Designer profile

#4063 Erin MacLaughlin : bio updated : "USA" deleted.
  catalog/designers/erinmclaughlin/bio.html
Labels: - Ready for Review, II Designer profile

#4079 Yrsa: Version 2.004 added
  ofl/yrsa/OFL.txt
  ofl/yrsa/Yrsa-Italic[wght].ttf
  ofl/yrsa/Yrsa[wght].ttf
Labels: - Ready for Review, III Small Fix

#4078 Rasa: Version 2.004 added
  ofl/rasa/OFL.txt
  ofl/rasa/Rasa-Italic[wght].ttf
  ofl/rasa/Rasa[wght].ttf
Labels: - Ready for Review, III Small Fix

#4091 Superunion bio
  catalog/designers/superunion/bio.html
  catalog/designers/superunion/info.pb
  catalog/designers/superunion/superunion.png
Labels: - Ready for Review

#4090 Neonderthaw: Version 1.010; ttfautohint (v1.8.3) added
  ofl/neonderthaw/DESCRIPTION.en_us.html
  ofl/neonderthaw/METADATA.pb
  ofl/neonderthaw/Neonderthaw-Regular.ttf
  ofl/neonderthaw/OFL.txt
  ofl/neonderthaw/upstream.yaml
Labels: - Ready for Review, II New Font

#4089 Waterfall: Version 1.010; ttfautohint (v1.8.3) added
  ofl/waterfall/DESCRIPTION.en_us.html
  ofl/waterfall/METADATA.pb
  ofl/waterfall/OFL.txt
  ofl/waterfall/Waterfall-Regular.ttf
  ofl/waterfall/upstream.yaml
Labels: - Ready for Review, II New Font

#4085 Island Moments: Version 1.010 added
  ofl/islandmoments/DESCRIPTION.en_us.html
  ofl/islandmoments/IslandMoments-Regular.ttf
  ofl/islandmoments/METADATA.pb
  ofl/islandmoments/OFL.txt
  ofl/islandmoments/upstream.yaml
Labels: - Ready for Review, II New Font

#4097 artakana: name updated
  catalog/designers/artakana/info.pb
Labels: --- to sandbox, II Designer profile

#3981 Baloo 2: Version 1.700 added
  ofl/baloo2/Baloo2-Bold.ttf
  ofl/baloo2/Baloo2-ExtraBold.ttf
  ofl/baloo2/Baloo2-Medium.ttf
  ofl/baloo2/Baloo2-Regular.ttf
  ofl/baloo2/Baloo2-SemiBold.ttf
  ofl/baloo2/Baloo2[wght].ttf
  ofl/baloo2/DESCRIPTION.en_us.html
  ofl/baloo2/METADATA.pb
  ofl/baloo2/OFL.txt
  ofl/baloo2/upstream.yaml
Labels: III VF Replacement, - Ready for Review, II Font Upgrade

#4032 Expletus Sans: Version 7.500 added
  ofl/expletussans/DESCRIPTION.en_us.html
  ofl/expletussans/ExpletusSans-Bold.ttf
  ofl/expletussans/ExpletusSans-BoldItalic.ttf
  ofl/expletussans/ExpletusSans-Italic.ttf
  ofl/expletussans/ExpletusSans-Italic[wght].ttf
  ofl/expletussans/ExpletusSans-Medium.ttf
  ofl/expletussans/ExpletusSans-MediumItalic.ttf
  ofl/expletussans/ExpletusSans-Regular.ttf
  ofl/expletussans/ExpletusSans-SemiBold.ttf
  ofl/expletussans/ExpletusSans-SemiBoldItalic.ttf
  ofl/expletussans/ExpletusSans[wght].ttf
  ofl/expletussans/METADATA.pb
  ofl/expletussans/OFL.txt
  ofl/expletussans/upstream.yaml
Labels: III VF Replacement, - Ready for Review, II Font Upgrade

#4087 Vujahday Script: Version 1.010; ttfautohint (v1.8.3) added
  ofl/vujahdayscript/DESCRIPTION.en_us.html
  ofl/vujahdayscript/METADATA.pb
  ofl/vujahdayscript/OFL.txt
  ofl/vujahdayscript/VujahdayScript-Regular.ttf
  ofl/vujahdayscript/upstream.yaml
Labels: --- to sandbox, II New Font

#4086 Licorice: Version 1.010; ttfautohint (v1.8.3) added
  ofl/licorice/DESCRIPTION.en_us.html
  ofl/licorice/Licorice-Regular.ttf
  ofl/licorice/METADATA.pb
  ofl/licorice/OFL.txt
  ofl/licorice/upstream.yaml
Labels: --- to sandbox, II New Font

#4083 Imperial Script: Version 1.010; ttfautohint (v1.8.3) added
  ofl/imperialscript/DESCRIPTION.en_us.html
  ofl/imperialscript/ImperialScript-Regular.ttf
  ofl/imperialscript/METADATA.pb
  ofl/imperialscript/OFL.txt
  ofl/imperialscript/upstream.yaml
Labels: --- to sandbox, II New Font

#3980 Baloo Da 2: Version 1.700 added
  ofl/balooda2/BalooDa2-Bold.ttf
  ofl/balooda2/BalooDa2-ExtraBold.ttf
  ofl/balooda2/BalooDa2-Medium.ttf
  ofl/balooda2/BalooDa2-Regular.ttf
  ofl/balooda2/BalooDa2-SemiBold.ttf
  ofl/balooda2/BalooDa2[wght].ttf
  ofl/balooda2/DESCRIPTION.en_us.html
  ofl/balooda2/METADATA.pb
  ofl/balooda2/OFL.txt
  ofl/balooda2/upstream.yaml
Labels: III VF Replacement, - Ready for Review, II Font Upgrade

#3985 Baloo Chettan 2: Version 1.700 added
  ofl/baloochettan2/BalooChettan2-Bold.ttf
  ofl/baloochettan2/BalooChettan2-ExtraBold.ttf
  ofl/baloochettan2/BalooChettan2-Medium.ttf
  ofl/baloochettan2/BalooChettan2-Regular.ttf
  ofl/baloochettan2/BalooChettan2-SemiBold.ttf
  ofl/baloochettan2/BalooChettan2[wght].ttf
  ofl/baloochettan2/DESCRIPTION.en_us.html
  ofl/baloochettan2/METADATA.pb
  ofl/baloochettan2/OFL.txt
  ofl/baloochettan2/upstream.yaml
Labels: III VF Replacement, --- to sandbox, II Font Upgrade

#4072 Sheherazade New : description updated (link)
  ofl/scheherazadenew/DESCRIPTION.en_us.html
Labels: - Ready for Review, II Description/Metadata/OFL

#4081 Moon Dance: Version 1.010; ttfautohint (v1.8.3) added
  ofl/moondance/DESCRIPTION.en_us.html
  ofl/moondance/METADATA.pb
  ofl/moondance/MoonDance-Regular.ttf
  ofl/moondance/OFL.txt
  ofl/moondance/upstream.yaml
Labels: --- to sandbox, II New Font

#4080 The Nautigal: Version 1.100; ttfautohint (v1.8.3) added
  ofl/thenautigal/DESCRIPTION.en_us.html
  ofl/thenautigal/METADATA.pb
  ofl/thenautigal/OFL.txt
  ofl/thenautigal/TheNautigal-Bold.ttf
  ofl/thenautigal/TheNautigal-Regular.ttf
  ofl/thenautigal/upstream.yaml
Labels: --- to sandbox, II New Font

#4098 Merriweather description
  ofl/merriweather/DESCRIPTION.en_us.html
Labels: --- to sandbox, II Description/Metadata/OFL

#3986 Baloo Thambi 2: Version 1.700 added
  ofl/baloothambi2/BalooThambi2-Bold.ttf
  ofl/baloothambi2/BalooThambi2-ExtraBold.ttf
  ofl/baloothambi2/BalooThambi2-Medium.ttf
  ofl/baloothambi2/BalooThambi2-Regular.ttf
  ofl/baloothambi2/BalooThambi2-SemiBold.ttf
  ofl/baloothambi2/BalooThambi2[wght].ttf
  ofl/baloothambi2/DESCRIPTION.en_us.html
  ofl/baloothambi2/METADATA.pb
  ofl/baloothambi2/OFL.txt
  ofl/baloothambi2/upstream.yaml
Labels: III VF Replacement, - Ready for Review, II Font Upgrade

#4052 Lexend: designer added
  ofl/lexend/METADATA.pb
  ofl/lexenddeca/METADATA.pb
  ofl/lexendexa/METADATA.pb
  ofl/lexendgiga/METADATA.pb
  ofl/lexendmega/METADATA.pb
  ofl/lexendpeta/METADATA.pb
  ofl/lexendtera/METADATA.pb
  ofl/lexendzetta/METADATA.pb
Labels: - Ready for Review, II Description/Metadata/OFL

#4082 Luxurious Roman: Version 1.010; ttfautohint (v1.8.3) added
  ofl/luxuriousroman/DESCRIPTION.en_us.html
  ofl/luxuriousroman/LuxuriousRoman-Regular.ttf
  ofl/luxuriousroman/METADATA.pb
  ofl/luxuriousroman/OFL.txt
  ofl/luxuriousroman/upstream.yaml
Labels: - Ready for Review, II New Font

#4104 Correct EkType Github Repo URL
  ofl/baloo2/upstream.yaml
  ofl/baloobhai2/upstream.yaml
  ofl/baloobhaijaan2/upstream.yaml
  ofl/baloobhaina2/upstream.yaml
  ofl/baloochettan2/upstream.yaml
  ofl/balooda2/upstream.yaml
  ofl/baloopaaji2/upstream.yaml
  ofl/balootamma2/upstream.yaml
  ofl/balootammudu2/upstream.yaml
  ofl/baloothambi2/upstream.yaml
Labels: - Ready for Review, II Description/Metadata/OFL

#4107 Expletus Sans : Description updated
  ofl/expletussans/DESCRIPTION.en_us.html
Labels: II Description/Metadata/OFL
