Repository google/fonts, pull requests merged in 2021-01, with the labels that each got.

#2927 Alegreya: Version 2.009 added
  ofl/alegreya/Alegreya-Black.ttf
  ofl/alegreya/Alegreya-BlackItalic.ttf
  ofl/alegreya/Alegreya-Bold.ttf
  ofl/alegreya/Alegreya-BoldItalic.ttf
  ofl/alegreya/Alegreya-ExtraBold.ttf
  ofl/alegreya/Alegreya-ExtraBoldItalic.ttf
  ofl/alegreya/Alegreya-Italic.ttf
  ofl/alegreya/Alegreya-Italic[wght].ttf
  ofl/alegreya/Alegreya-Medium.ttf
  ofl/alegreya/Alegreya-MediumItalic.ttf
  ofl/alegreya/Alegreya-Regular.ttf
  ofl/alegreya/Alegreya[wght].ttf
  ofl/alegreya/METADATA.pb
  ofl/alegreya/upstream.yaml
Labels: - Ready for Review

#2750 Categorize Laila as sans-serif
  ofl/laila/METADATA.pb
Labels: -- Ready to push, II Description/Metadata

#2948 Fix designer attributes in ofl/lexend*/METADATA.pb
  ofl/lexenddeca/METADATA.pb
  ofl/lexendexa/METADATA.pb
  ofl/lexendgiga/METADATA.pb
  ofl/lexendmega/METADATA.pb
  ofl/lexendpeta/METADATA.pb
  ofl/lexendtera/METADATA.pb
  ofl/lexendzetta/METADATA.pb
Labels: -- Ready to push, II Description/Metadata

#2951 Anton: Version 2.116; ttfautohint (v1.8.3) added
  ofl/anton/Anton-Regular.ttf
  ofl/anton/DESCRIPTION.en_us.html
  ofl/anton/METADATA.pb
  ofl/anton/OFL.txt
  ofl/anton/upstream.yaml
Labels: - Needs confirmation, II Font Upgrade

#2917 Truculenta: Version 1.002 added
  ofl/truculenta/DESCRIPTION.en_us.html
  ofl/truculenta/METADATA.pb
  ofl/truculenta/OFL.txt
  ofl/truculenta/Truculenta[opsz,wdth,wght].ttf
  ofl/truculenta/upstream.yaml
Labels: -- Ready to push, II New Font

#2889 Sofia Sans: Version 4.100 added
  ofl/sofiasans/DESCRIPTION.en_us.html
  ofl/sofiasans/METADATA.pb
  ofl/sofiasans/OFL.txt
  ofl/sofiasans/SofiaSans-Italic[wdth,wght].ttf
  ofl/sofiasans/SofiaSans[wdth,wght].ttf
  ofl/sofiasans/upstream.yaml
Labels: -- Ready to push, II Font Upgrade

#2949 Kufam font designer's info added
  catalog/designers/arturschmal/artur_schmal.png
  catalog/designers/arturschmal/bio.html
  catalog/designers/arturschmal/info.pb
  catalog/designers/waelmorcos/bio.html
  catalog/designers/waelmorcos/info.pb
  catalog/designers/waelmorcos/wael_morcos.png
Labels: --- to_sandbox, II Catalog

#2955 Update info.pb
  catalog/designers/vaishnavimurthy/info.pb
Labels: - Ready for Review

#2957 Akaya Telivigala: Version 1.001; ttfautohint (v1.8.3) added
  ofl/akayatelivigala/AkayaTelivigala-Regular.ttf
  ofl/akayatelivigala/DESCRIPTION.en_us.html
  ofl/akayatelivigala/METADATA.pb
  ofl/akayatelivigala/OFL.txt
  ofl/akayatelivigala/upstream.yaml
Labels: - Ready for Review, II New Font

#2881 Cherry Bomb One: Version 4.000; ttfautohint (v1.8.3) added
  ofl/cherrybombone/CherryBombOne-Regular.ttf
  ofl/cherrybombone/DESCRIPTION.en_us.html
  ofl/cherrybombone/METADATA.pb
  ofl/cherrybombone/OFL.txt
  ofl/cherrybombone/upstream.yaml
Labels: - Ready for Review, II New Font

#2971 Akaya Telivigala: Version 1.001; ttfautohint (v1.8.3) added
  ofl/akayatelivigala/AkayaTelivigala-Regular.ttf
  ofl/akayatelivigala/upstream.yaml
Labels: - Ready for Review, II New Font

#2970 Akaya Kanadaka: Version 1.002; ttfautohint (v1.8.3) added
  ofl/akayakanadaka/AkayaKanadaka-Regular.ttf
  ofl/akayakanadaka/upstream.yaml
Labels: - Ready for Review, II New Font

#2978 Brygada 1918: Version 3.004 added
  ofl/brygada1918/Brygada1918[wght].ttf
  ofl/brygada1918/DESCRIPTION.en_us.html
  ofl/brygada1918/METADATA.pb
  ofl/brygada1918/OFL.txt
  ofl/brygada1918/upstream.yaml
Labels: -- Ready to push, II New Font

#2934 Kapakana: Version 1.000 added
  ofl/kapakana/DESCRIPTION.en_us.html
  ofl/kapakana/Kapakana[wght].ttf
  ofl/kapakana/METADATA.pb
  ofl/kapakana/OFL.txt
  ofl/kapakana/static/Kapakana-Light.ttf
  ofl/kapakana/static/Kapakana-Regular.ttf
  ofl/kapakana/upstream.yaml
Labels: -- Ready to push, II New Font

#2918 Aoboshi One: Version 1.000; ttfautohint (v1.8.3) added
  ofl/aoboshione/AoboshiOne-Regular.ttf
  ofl/aoboshione/DESCRIPTION.en_us.html
  ofl/aoboshione/METADATA.pb
  ofl/aoboshione/OFL.txt
  ofl/aoboshione/upstream.yaml
Labels: -- Missing script, -- Ready to push, II New Font
