Repository google/fonts, pull requests merged in 2021-07, with the labels that each got.

#3545 IBM Plex Sans Arabic: Version 1.1 added
  ofl/ibmplexsansarabic/DESCRIPTION.en_us.html
  ofl/ibmplexsansarabic/IBMPlexSansArabic-Bold.ttf
  ofl/ibmplexsansarabic/IBMPlexSansArabic-ExtraLight.ttf
  ofl/ibmplexsansarabic/IBMPlexSansArabic-Light.ttf
  ofl/ibmplexsansarabic/IBMPlexSansArabic-Medium.ttf
  ofl/ibmplexsansarabic/IBMPlexSansArabic-Regular.ttf
  ofl/ibmplexsansarabic/IBMPlexSansArabic-SemiBold.ttf
  ofl/ibmplexsansarabic/IBMPlexSansArabic-Thin.ttf
  ofl/ibmplexsansarabic/METADATA.pb
  ofl/ibmplexsansarabic/OFL.txt
  ofl/ibmplexsansarabic/upstream.yaml
Labels: - Ready for Review, II New Font

#3558 IBM Plex Sans Thai Looped: Version 1.1 added
  ofl/ibmplexsansthailooped/DESCRIPTION.en_us.html
  ofl/ibmplexsansthailooped/IBMPlexSansThaiLooped-Bold.ttf
  ofl/ibmplexsansthailooped/IBMPlexSansThaiLooped-ExtraLight.ttf
  ofl/ibmplexsansthailooped/IBMPlexSansThaiLooped-Light.ttf
  ofl/ibmplexsansthailooped/IBMPlexSansThaiLooped-Medium.ttf
  ofl/ibmplexsansthailooped/IBMPlexSansThaiLooped-Regular.ttf
  ofl/ibmplexsansthailooped/IBMPlexSansThaiLooped-SemiBold.ttf
  ofl/ibmplexsansthailooped/IBMPlexSansThaiLooped-Thin.ttf
  ofl/ibmplexsansthailooped/METADATA.pb
  ofl/ibmplexsansthailooped/OFL.txt
  ofl/ibmplexsansthailooped/upstream.yaml
Labels: - Ready for Review, II New Font

#3557 IBM Plex Sans Thai: Version 1.1 added
  ofl/ibmplexsansthai/DESCRIPTION.en_us.html
  ofl/ibmplexsansthai/IBMPlexSansThai-Bold.ttf
  ofl/ibmplexsansthai/IBMPlexSansThai-ExtraLight.ttf
  ofl/ibmplexsansthai/IBMPlexSansThai-Light.ttf
  ofl/ibmplexsansthai/IBMPlexSansThai-Medium.ttf
  ofl/ibmplexsansthai/IBMPlexSansThai-Regular.ttf
  ofl/ibmplexsansthai/IBMPlexSansThai-SemiBold.ttf
  ofl/ibmplexsansthai/IBMPlexSansThai-Thin.ttf
  ofl/ibmplexsansthai/METADATA.pb
  ofl/ibmplexsansthai/OFL.txt
  ofl/ibmplexsansthai/upstream.yaml
Labels: - Ready for Review, II New Font

#3556 IBM Plex Sans KR: Version 1.001 added
  ofl/ibmplexsanskr/DESCRIPTION.en_us.html
  ofl/ibmplexsanskr/IBMPlexSansKR-Bold.ttf
  ofl/ibmplexsanskr/IBMPlexSansKR-ExtraLight.ttf
  ofl/ibmplexsanskr/IBMPlexSansKR-Light.ttf
  ofl/ibmplexsanskr/IBMPlexSansKR-Medium.ttf
  ofl/ibmplexsanskr/IBMPlexSansKR-Regular.ttf
  ofl/ibmplexsanskr/IBMPlexSansKR-SemiBold.ttf
  ofl/ibmplexsanskr/IBMPlexSansKR-Thin.ttf
  ofl/ibmplexsanskr/METADATA.pb
  ofl/ibmplexsanskr/OFL.txt
  ofl/ibmplexsanskr/upstream.yaml
Labels: - Ready for Review, II New Font

#3555 IBM Plex Sans Devanagari: Version 1.1 added
  ofl/ibmplexsansdevanagari/DESCRIPTION.en_us.html
  ofl/ibmplexsansdevanagari/IBMPlexSansDevanagari-Bold.ttf
  ofl/ibmplexsansdevanagari/IBMPlexSansDevanagari-ExtraLight.ttf
  ofl/ibmplexsansdevanagari/IBMPlexSansDevanagari-Light.ttf
  ofl/ibmplexsansdevanagari/IBMPlexSansDevanagari-Medium.ttf
  ofl/ibmplexsansdevanagari/IBMPlexSansDevanagari-Regular.ttf
  ofl/ibmplexsansdevanagari/IBMPlexSansDevanagari-SemiBold.ttf
  ofl/ibmplexsansdevanagari/IBMPlexSansDevanagari-Thin.ttf
  ofl/ibmplexsansdevanagari/METADATA.pb
  ofl/ibmplexsansdevanagari/OFL.txt
  ofl/ibmplexsansdevanagari/upstream.yaml
Labels: - Ready for Review, II New Font

#3554 IBM Plex Sans Hebrew: Version 1.2 added
  ofl/ibmplexsanshebrew/DESCRIPTION.en_us.html
  ofl/ibmplexsanshebrew/IBMPlexSansHebrew-Bold.ttf
  ofl/ibmplexsanshebrew/IBMPlexSansHebrew-ExtraLight.ttf
  ofl/ibmplexsanshebrew/IBMPlexSansHebrew-Light.ttf
  ofl/ibmplexsanshebrew/IBMPlexSansHebrew-Medium.ttf
  ofl/ibmplexsanshebrew/IBMPlexSansHebrew-Regular.ttf
  ofl/ibmplexsanshebrew/IBMPlexSansHebrew-SemiBold.ttf
  ofl/ibmplexsanshebrew/IBMPlexSansHebrew-Thin.ttf
  ofl/ibmplexsanshebrew/METADATA.pb
  ofl/ibmplexsanshebrew/OFL.txt
  ofl/ibmplexsanshebrew/upstream.yaml
Labels: - Ready for Review, II New Font

#3517 Lexend Exa: Version 1.100 added; Lexend: Version 1.100 added; Lexend Giga: Version 1.100 added; Lexend Peta: Version 1.100 added; Lexend Mega: Version 1.100 added; Lexend Deca: Version 1.100 added; Lexend Zetta: Version 1.100 added; Lexend Tera: Version 1.100 added
  ofl/lexend/DESCRIPTION.en_us.html
  ofl/lexend/Lexend-Bold.ttf
  ofl/lexend/Lexend-ExtraBold.ttf
  ofl/lexend/Lexend-Light.ttf
  ofl/lexend/Lexend-Medium.ttf
  ofl/lexend/Lexend-Regular.ttf
  ofl/lexend/Lexend-SemiBold.ttf
  ofl/lexend/Lexend-Thin.ttf
  ofl/lexend/Lexend[wght].ttf
  ofl/lexend/METADATA.pb
  ofl/lexend/OFL.txt
  ofl/lexend/upstream.yaml
  ofl/lexenddeca/DESCRIPTION.en_us.html
  ofl/lexenddeca/LexendDeca-Regular.ttf
  ofl/lexenddeca/LexendDeca[wght].ttf
  ofl/lexenddeca/METADATA.pb
  ofl/lexenddeca/upstream.yaml
  ofl/lexendexa/DESCRIPTION.en_us.html
  ofl/lexendexa/LexendExa-Regular.ttf
  ofl/lexendexa/LexendExa[wght].ttf
  ofl/lexendexa/METADATA.pb
  ofl/lexendexa/upstream.yaml
  ofl/lexendgiga/DESCRIPTION.en_us.html
  ofl/lexendgiga/LexendGiga-Regular.ttf
  ofl/lexendgiga/LexendGiga[wght].ttf
  ofl/lexendgiga/METADATA.pb
  ofl/lexendgiga/upstream.yaml
  ofl/lexendmega/DESCRIPTION.en_us.html
  ofl/lexendmega/LexendMega-Regular.ttf
  ofl/lexendmega/LexendMega[wght].ttf
  ofl/lexendmega/METADATA.pb
  ofl/lexendmega/upstream.yaml
  ofl/lexendpeta/DESCRIPTION.en_us.html
  ofl/lexendpeta/LexendPeta-Regular.ttf
  ofl/lexendpeta/LexendPeta[wght].ttf
  ofl/lexendpeta/METADATA.pb
  ofl/lexendpeta/upstream.yaml
  ofl/lexendtera/DESCRIPTION.en_us.html
  ofl/lexendtera/LexendTera-Regular.ttf
  ofl/lexendtera/LexendTera[wght].ttf
  ofl/lexendtera/METADATA.pb
  ofl/lexendtera/upstream.yaml
  ofl/lexendzetta/DESCRIPTION.en_us.html
  ofl/lexendzetta/LexendZetta-Regular.ttf
  ofl/lexendzetta/LexendZetta[wght].ttf
  ofl/lexendzetta/METADATA.pb
  ofl/lexendzetta/upstream.yaml
Labels: --- to_sandbox, II Font Upgrade, III VF Replacement

#3456 Be Vietnam Pro: Version 1.000 added
  ofl/bevietnampro/BeVietnamPro-Black.ttf
  ofl/bevietnampro/BeVietnamPro-BlackItalic.ttf
  ofl/bevietnampro/BeVietnamPro-Bold.ttf
  ofl/bevietnampro/BeVietnamPro-BoldItalic.ttf
  ofl/bevietnampro/BeVietnamPro-ExtraBold.ttf
  ofl/bevietnampro/BeVietnamPro-ExtraBoldItalic.ttf
  ofl/bevietnampro/BeVietnamPro-ExtraLight.ttf
  ofl/bevietnampro/BeVietnamPro-ExtraLightItalic.ttf
  ofl/bevietnampro/BeVietnamPro-Italic.ttf
  ofl/bevietnampro/BeVietnamPro-Light.ttf
  ofl/bevietnampro/BeVietnamPro-LightItalic.ttf
  ofl/bevietnampro/BeVietnamPro-Medium.ttf
  ofl/bevietnampro/BeVietnamPro-MediumItalic.ttf
  ofl/bevietnampro/BeVietnamPro-Regular.ttf
  ofl/bevietnampro/BeVietnamPro-SemiBold.ttf
  ofl/bevietnampro/BeVietnamPro-SemiBoldItalic.ttf
  ofl/bevietnampro/BeVietnamPro-Thin.ttf
  ofl/bevietnampro/BeVietnamPro-ThinItalic.ttf
  ofl/bevietnampro/DESCRIPTION.en_us.html
  ofl/bevietnampro/METADATA.pb
  ofl/bevietnampro/OFL.txt
  ofl/bevietnampro/upstream.yaml
Labels: -- Needs Upstream Resolution, II New Font

#2942 Besley: version 2.000 added
  ofl/besley/Besley-Italic[wght].ttf
  ofl/besley/Besley[wght].ttf
  ofl/besley/DESCRIPTION.en_us.html
  ofl/besley/METADATA.pb
  ofl/besley/OFL.txt
  ofl/besley/upstream.yaml
Labels: - Ready for Review, II New Font

#3575 RUSerius: Version 1.010; ttfautohint (v1.8.3) added
  ofl/ruserius/DESCRIPTION.en_us.html
  ofl/ruserius/METADATA.pb
  ofl/ruserius/OFL.txt
  ofl/ruserius/RUSerius-Regular.ttf
  ofl/ruserius/upstream.yaml
Labels: - Ready for Review, II New Font

#3574 Allison: Version 1.010; ttfautohint (v1.8.3) added
  ofl/allison/Allison-Regular.ttf
  ofl/allison/DESCRIPTION.en_us.html
  ofl/allison/METADATA.pb
  ofl/allison/OFL.txt
  ofl/allison/upstream.yaml
Labels: - Ready for Review, II New Font

#3431 [gftools-packager] Urbanist: Version 1.250 added
  ofl/urbanist/DESCRIPTION.en_us.html
  ofl/urbanist/METADATA.pb
  ofl/urbanist/OFL.txt
  ofl/urbanist/Urbanist-Italic[wght].ttf
  ofl/urbanist/Urbanist[wght].ttf
  ofl/urbanist/upstream.yaml
Labels: - In Progress, II New Font

#2870 Rock 3D: Version 1.000 added
  ofl/rock3d/DESCRIPTION.en_us.html
  ofl/rock3d/METADATA.pb
  ofl/rock3d/OFL.txt
  ofl/rock3d/Rock3D-Regular.ttf
  ofl/rock3d/upstream.yaml
Labels: -- Ready to merge, II New Font

#2871 Shizuru Font: Version 1.000 added
  ofl/shizuru/DESCRIPTION.en_us.html
  ofl/shizuru/METADATA.pb
  ofl/shizuru/OFL.txt
  ofl/shizuru/Shizuru-Regular.ttf
  ofl/shizuru/upstream.yaml
Labels: -- Ready to merge, II New Font

#3440 IBM Plex Sans Condensed: Version 1.3 added
  ofl/ibmplexsanscondensed/DESCRIPTION.en_us.html
  ofl/ibmplexsanscondensed/IBMPlexSansCondensed-Bold.ttf
  ofl/ibmplexsanscondensed/IBMPlexSansCondensed-BoldItalic.ttf
  ofl/ibmplexsanscondensed/IBMPlexSansCondensed-ExtraLight.ttf
  ofl/ibmplexsanscondensed/IBMPlexSansCondensed-ExtraLightItalic.ttf
  ofl/ibmplexsanscondensed/IBMPlexSansCondensed-Italic.ttf
  ofl/ibmplexsanscondensed/IBMPlexSansCondensed-Light.ttf
  ofl/ibmplexsanscondensed/IBMPlexSansCondensed-LightItalic.ttf
  ofl/ibmplexsanscondensed/IBMPlexSansCondensed-Medium.ttf
  ofl/ibmplexsanscondensed/IBMPlexSansCondensed-MediumItalic.ttf
  ofl/ibmplexsanscondensed/IBMPlexSansCondensed-Regular.ttf
  ofl/ibmplexsanscondensed/IBMPlexSansCondensed-SemiBold.ttf
  ofl/ibmplexsanscondensed/IBMPlexSansCondensed-SemiBoldItalic.ttf
  ofl/ibmplexsanscondensed/IBMPlexSansCondensed-Thin.ttf
  ofl/ibmplexsanscondensed/IBMPlexSansCondensed-ThinItalic.ttf
  ofl/ibmplexsanscondensed/METADATA.pb
  ofl/ibmplexsanscondensed/OFL.txt
  ofl/ibmplexsanscondensed/upstream.yaml
Labels: - Ready for Review, II Font Upgrade

#3478 Rampart One: Version 1.100 added
  ofl/rampartone/DESCRIPTION.en_us.html
  ofl/rampartone/METADATA.pb
  ofl/rampartone/OFL.txt
  ofl/rampartone/RampartOne-Regular.ttf
  ofl/rampartone/upstream.yaml
Labels: - Ready for Review, I CJK, II Font Upgrade

#3582 Scheherazade New : version 3.200 added
  ofl/scheherazadenew/DESCRIPTION.en_us.html
  ofl/scheherazadenew/ScheherazadeNew-Bold.ttf
  ofl/scheherazadenew/ScheherazadeNew-Regular.ttf
Labels: - Ready for Review, II New Font

#3598 Ruda: multiple designers fixed
  ofl/ruda/METADATA.pb
Labels: -- Ready to merge, II Description/Metadata/OFL

#3597 Assistant: multiple designers fixed
  ofl/assistant/METADATA.pb
Labels: -- Ready to merge, II Description/Metadata/OFL

#3596 Heebo: multiple designers fixed
  ofl/heebo/METADATA.pb
Labels: -- Ready to merge, II Description/Metadata/OFL

#3594 Markazi Text: OFL added, multiple designers fixed
  ofl/markazitext/METADATA.pb
  ofl/markazitext/OFL.txt
Labels: -- Ready to merge, II Description/Metadata/OFL

#3595 David Libre: Multiple designers fixed
  ofl/davidlibre/DESCRIPTION.en_us.html
  ofl/davidlibre/DavidLibre-Bold.ttf
  ofl/davidlibre/DavidLibre-Medium.ttf
  ofl/davidlibre/DavidLibre-Regular.ttf
  ofl/davidlibre/METADATA.pb
  ofl/davidlibre/OFL.txt
Labels: -- Ready to merge, II Description/Metadata/OFL

#3593 Fira Code: multiple designers fixed
  ofl/firacode/METADATA.pb
Labels: -- Ready to merge, II Description/Metadata/OFL

#3592 Public Sans: multiple designers fixed
  ofl/publicsans/METADATA.pb
Labels: -- Ready to merge, II Description/Metadata/OFL

#3621 Lexend Families : updated repo URL in upstream.yaml and Description
  ofl/lexend/DESCRIPTION.en_us.html
  ofl/lexend/upstream.yaml
  ofl/lexenddeca/DESCRIPTION.en_us.html
  ofl/lexenddeca/upstream.yaml
  ofl/lexendexa/DESCRIPTION.en_us.html
  ofl/lexendexa/upstream.yaml
  ofl/lexendgiga/DESCRIPTION.en_us.html
  ofl/lexendgiga/upstream.yaml
  ofl/lexendmega/DESCRIPTION.en_us.html
  ofl/lexendmega/upstream.yaml
  ofl/lexendpeta/DESCRIPTION.en_us.html
  ofl/lexendpeta/upstream.yaml
  ofl/lexendtera/DESCRIPTION.en_us.html
  ofl/lexendtera/upstream.yaml
  ofl/lexendzetta/DESCRIPTION.en_us.html
  ofl/lexendzetta/upstream.yaml
Labels: II Description/Metadata/OFL, II Internal

#3622 Lexend: branch name updated in upstream.yaml
  ofl/lexend/upstream.yaml
  ofl/lexenddeca/upstream.yaml
  ofl/lexendexa/upstream.yaml
  ofl/lexendgiga/upstream.yaml
  ofl/lexendmega/upstream.yaml
  ofl/lexendpeta/upstream.yaml
  ofl/lexendtera/upstream.yaml
  ofl/lexendzetta/upstream.yaml
Labels: II Internal

#3623 Lexend Tera: Version 1.007 added; Lexend Zetta: Version 1.007 added; Lexend Peta: Version 1.007 added; Lexend: Version 1.007 added; Lexend Deca: Version 1.007 added; Lexend Giga: Version 1.007 added; Lexend Exa: Version 1.007 added; Lexend Mega: Version 1.007 added
  ofl/lexend/Lexend[wght].ttf
  ofl/lexend/METADATA.pb
  ofl/lexend/OFL.txt
  ofl/lexenddeca/LexendDeca[wght].ttf
  ofl/lexenddeca/METADATA.pb
  ofl/lexenddeca/OFL.txt
  ofl/lexendexa/LexendExa[wght].ttf
  ofl/lexendexa/METADATA.pb
  ofl/lexendexa/OFL.txt
  ofl/lexendgiga/LexendGiga[wght].ttf
  ofl/lexendgiga/METADATA.pb
  ofl/lexendgiga/OFL.txt
  ofl/lexendmega/LexendMega[wght].ttf
  ofl/lexendmega/METADATA.pb
  ofl/lexendmega/OFL.txt
  ofl/lexendpeta/LexendPeta[wght].ttf
  ofl/lexendpeta/METADATA.pb
  ofl/lexendpeta/OFL.txt
  ofl/lexendtera/LexendTera[wght].ttf
  ofl/lexendtera/METADATA.pb
  ofl/lexendtera/OFL.txt
  ofl/lexendzetta/LexendZetta[wght].ttf
  ofl/lexendzetta/METADATA.pb
  ofl/lexendzetta/OFL.txt
Labels: - Ready for Review, II Small Fix
