Repository google/fonts, pull requests merged in 2021-08, with the labels that each got.

#3616 hypertype : bio added
  catalog/designers/hypertype/bio.html
  catalog/designers/hypertype/hypertype.png
  catalog/designers/hypertype/info.pb
Labels: - Ready for Review, II Catalog

#3614 artakana : bio added (desinger name fixed)
  catalog/designers/artakana/artakana.png
  catalog/designers/artakana/bio.html
  catalog/designers/artakana/info.pb
  ofl/delagothicone/METADATA.pb
Labels: - Ready for Review, II Catalog

#3617 yangheeryu : bio added
  catalog/designers/yangheeryu/bio.html
  catalog/designers/yangheeryu/info.pb
  catalog/designers/yangheeryu/yangheeryu.png
Labels: - Ready for Review, II Catalog

#3634 Epilogue v2.112 (stat fix)
  ofl/epilogue/Epilogue-Italic[wght].ttf
  ofl/epilogue/Epilogue[wght].ttf
  ofl/epilogue/OFL.txt
  ofl/epilogue/static/Epilogue-Black.ttf
  ofl/epilogue/static/Epilogue-BlackItalic.ttf
  ofl/epilogue/static/Epilogue-Bold.ttf
  ofl/epilogue/static/Epilogue-BoldItalic.ttf
  ofl/epilogue/static/Epilogue-ExtraBold.ttf
  ofl/epilogue/static/Epilogue-ExtraBoldItalic.ttf
  ofl/epilogue/static/Epilogue-ExtraLight.ttf
  ofl/epilogue/static/Epilogue-ExtraLightItalic.ttf
  ofl/epilogue/static/Epilogue-Italic.ttf
  ofl/epilogue/static/Epilogue-Light.ttf
  ofl/epilogue/static/Epilogue-LightItalic.ttf
  ofl/epilogue/static/Epilogue-Medium.ttf
  ofl/epilogue/static/Epilogue-MediumItalic.ttf
  ofl/epilogue/static/Epilogue-Regular.ttf
  ofl/epilogue/static/Epilogue-SemiBold.ttf
  ofl/epilogue/static/Epilogue-SemiBoldItalic.ttf
  ofl/epilogue/static/Epilogue-Thin.ttf
  ofl/epilogue/static/Epilogue-ThinItalic.ttf
Labels: - Ready for Review, I VF, II Font Upgrade

#3670 Orbitron v2.001 (stat fix)
  ofl/orbitron/OFL.txt
  ofl/orbitron/Orbitron[wght].ttf
  ofl/orbitron/static/Orbitron-Black.ttf
  ofl/orbitron/static/Orbitron-Bold.ttf
  ofl/orbitron/static/Orbitron-ExtraBold.ttf
  ofl/orbitron/static/Orbitron-Medium.ttf
  ofl/orbitron/static/Orbitron-Regular.ttf
  ofl/orbitron/static/Orbitron-SemiBold.ttf
Labels: - Ready for Review, I VF, II Font Upgrade

#3665 Yanone Kaffeesatz v2.002 (stat fix)
  ofl/yanonekaffeesatz/OFL.txt
  ofl/yanonekaffeesatz/YanoneKaffeesatz[wght].ttf
  ofl/yanonekaffeesatz/static/YanoneKaffeesatz-Bold.ttf
  ofl/yanonekaffeesatz/static/YanoneKaffeesatz-ExtraLight.ttf
  ofl/yanonekaffeesatz/static/YanoneKaffeesatz-Light.ttf
  ofl/yanonekaffeesatz/static/YanoneKaffeesatz-Medium.ttf
  ofl/yanonekaffeesatz/static/YanoneKaffeesatz-Regular.ttf
  ofl/yanonekaffeesatz/static/YanoneKaffeesatz-SemiBold.ttf
Labels: - Ready for Review, I VF, II Font Upgrade

#3643 Manuale v1.002 (stat fix)
  ofl/manuale/Manuale-Italic[wght].ttf
  ofl/manuale/Manuale[wght].ttf
  ofl/manuale/OFL.txt
  ofl/manuale/static/Manuale-Bold.ttf
  ofl/manuale/static/Manuale-BoldItalic.ttf
  ofl/manuale/static/Manuale-ExtraBold.ttf
  ofl/manuale/static/Manuale-ExtraBoldItalic.ttf
  ofl/manuale/static/Manuale-Italic.ttf
  ofl/manuale/static/Manuale-Light.ttf
  ofl/manuale/static/Manuale-LightItalic.ttf
  ofl/manuale/static/Manuale-Medium.ttf
  ofl/manuale/static/Manuale-MediumItalic.ttf
  ofl/manuale/static/Manuale-Regular.ttf
  ofl/manuale/static/Manuale-Semibold.ttf
  ofl/manuale/static/Manuale-SemiboldItalic.ttf
  ofl/manuale/static/OFL.txt
Labels: - Ready for Review, I VF, II Font Upgrade

#3637 Grenze Gotisch v1.002 (stat fix)
  ofl/grenzegotisch/GrenzeGotisch[wght].ttf
  ofl/grenzegotisch/static/GrenzeGotisch-Black.ttf
  ofl/grenzegotisch/static/GrenzeGotisch-Bold.ttf
  ofl/grenzegotisch/static/GrenzeGotisch-ExtraBold.ttf
  ofl/grenzegotisch/static/GrenzeGotisch-ExtraLight.ttf
  ofl/grenzegotisch/static/GrenzeGotisch-Light.ttf
  ofl/grenzegotisch/static/GrenzeGotisch-Medium.ttf
  ofl/grenzegotisch/static/GrenzeGotisch-Regular.ttf
  ofl/grenzegotisch/static/GrenzeGotisch-SemiBold.ttf
  ofl/grenzegotisch/static/GrenzeGotisch-Thin.ttf
Labels: - Ready for Review, I VF, II Font Upgrade

#3560 Add a code of conduct
  CODE_OF_CONDUCT.md
  README.md
Labels: - Needs Dave's opinion

#3673 El Messiri: Version 2.020 added
  ofl/elmessiri/DESCRIPTION.en_us.html
  ofl/elmessiri/ElMessiri[wght].ttf
  ofl/elmessiri/METADATA.pb
  ofl/elmessiri/OFL.txt
  ofl/elmessiri/static/ElMessiri-Bold.ttf
  ofl/elmessiri/static/ElMessiri-Medium.ttf
  ofl/elmessiri/static/ElMessiri-Regular.ttf
  ofl/elmessiri/static/ElMessiri-SemiBold.ttf
  ofl/elmessiri/static/METADATA.pb
  ofl/elmessiri/upstream.yaml
Labels: --- to_sandbox, II Font Upgrade

#3672 Caramel: Version 1.010 added
  ofl/caramel/Caramel-Regular.ttf
  ofl/caramel/DESCRIPTION.en_us.html
  ofl/caramel/METADATA.pb
  ofl/caramel/OFL.txt
  ofl/caramel/upstream.yaml
Labels: -- Ready to merge, II New Font

#3676 Birthstone: Version 1.010; ttfautohint (v1.8.3) added
  ofl/birthstone/Birthstone-Regular.ttf
  ofl/birthstone/DESCRIPTION.en_us.html
  ofl/birthstone/METADATA.pb
  ofl/birthstone/OFL.txt
  ofl/birthstone/upstream.yaml
Labels: - Ready for Review, II New Font

#3675 Bonheur Royale: Version 1.010; ttfautohint (v1.8.3) added
  ofl/bonheurroyale/BonheurRoyale-Regular.ttf
  ofl/bonheurroyale/DESCRIPTION.en_us.html
  ofl/bonheurroyale/METADATA.pb
  ofl/bonheurroyale/OFL.txt
  ofl/bonheurroyale/upstream.yaml
Labels: - Ready for Review, II New Font

#3662 Podkova v2.103 (stat fix)
  ofl/podkova/OFL.txt
  ofl/podkova/Podkova[wght].ttf
  ofl/podkova/static/Podkova-Bold.ttf
  ofl/podkova/static/Podkova-ExtraBold.ttf
  ofl/podkova/static/Podkova-Medium.ttf
  ofl/podkova/static/Podkova-Regular.ttf
  ofl/podkova/static/Podkova-SemiBold.ttf
Labels: I VF, - Ready for Review, II Font Upgrade

#3663 Rokkitt v3.103 (stat fix)
  ofl/rokkitt/OFL.txt
  ofl/rokkitt/Rokkitt[wght].ttf
  ofl/rokkitt/static/METADATA.pb
  ofl/rokkitt/static/Rokkitt-Black.ttf
  ofl/rokkitt/static/Rokkitt-Bold.ttf
  ofl/rokkitt/static/Rokkitt-ExtraBold.ttf
  ofl/rokkitt/static/Rokkitt-ExtraLight.ttf
  ofl/rokkitt/static/Rokkitt-Light.ttf
  ofl/rokkitt/static/Rokkitt-Medium.ttf
  ofl/rokkitt/static/Rokkitt-Regular.ttf
  ofl/rokkitt/static/Rokkitt-SemiBold.ttf
  ofl/rokkitt/static/Rokkitt-Thin.ttf
Labels: I VF, - Ready for Review, II Font Upgrade

#3655 Roboto Slab v2.001 (stat fix)
  apache/robotoslab/RobotoSlab[wght].ttf
  apache/robotoslab/static/RobotoSlab-Black.ttf
  apache/robotoslab/static/RobotoSlab-Bold.ttf
  apache/robotoslab/static/RobotoSlab-ExtraBold.ttf
  apache/robotoslab/static/RobotoSlab-ExtraLight.ttf
  apache/robotoslab/static/RobotoSlab-Light.ttf
  apache/robotoslab/static/RobotoSlab-Medium.ttf
  apache/robotoslab/static/RobotoSlab-Regular.ttf
  apache/robotoslab/static/RobotoSlab-SemiBold.ttf
  apache/robotoslab/static/RobotoSlab-Thin.ttf
Labels: I VF, - Ready for Review, II Font Upgrade

#3652 Ruda v2.001 (stat fix)
  ofl/ruda/OFL.txt
  ofl/ruda/Ruda[wght].ttf
  ofl/ruda/static/Ruda-Black.ttf
  ofl/ruda/static/Ruda-Bold.ttf
  ofl/ruda/static/Ruda-ExtraBold.ttf
  ofl/ruda/static/Ruda-Medium.ttf
  ofl/ruda/static/Ruda-Regular.ttf
  ofl/ruda/static/Ruda-SemiBold.ttf
Labels: I VF, - Ready for Review, II Font Upgrade

#3644 Markazi Text v1.001 (stat fix)
  ofl/markazitext/DESCRIPTION.en_us.html
  ofl/markazitext/METADATA.pb
  ofl/markazitext/MarkaziText[wght].ttf
  ofl/markazitext/OFL.txt
  ofl/markazitext/static/MarkaziText-Bold.ttf
  ofl/markazitext/static/MarkaziText-Medium.ttf
  ofl/markazitext/static/MarkaziText-Regular.ttf
  ofl/markazitext/static/MarkaziText-SemiBold.ttf
Labels: I VF, - Ready for Review, -- Needs Metadata/Description changes, II Font Upgrade

#3694 Scheherazade New : Added arabic subset to metadata.pb
  ofl/scheherazadenew/METADATA.pb
Labels: -- Ready to merge, II Description/Metadata/OFL

#3693 Andada Pro: Version 3.003 added
  ofl/andadapro/AndadaPro-Italic[wght].ttf
  ofl/andadapro/AndadaPro[wght].ttf
Labels: --- to_sandbox, II Small Fix

#3684 RU Serius: Version 1.011; ttfautohint (v1.8.3) added
  ofl/ruserius/METADATA.pb
  ofl/ruserius/OFL.txt
  ofl/ruserius/RUSerius-Regular.ttf
Labels: - Ready for Review, II New Font

#3686 Explora: Version 1.010 added
  ofl/explora/DESCRIPTION.en_us.html
  ofl/explora/Explora-Regular.ttf
  ofl/explora/METADATA.pb
  ofl/explora/OFL.txt
  ofl/explora/upstream.yaml
Labels: --- to_sandbox, II New Font

#3678 Ephesis: Version 1.010; ttfautohint (v1.8.3) added
  ofl/ephesis/DESCRIPTION.en_us.html
  ofl/ephesis/Ephesis-Regular.ttf
  ofl/ephesis/METADATA.pb
  ofl/ephesis/OFL.txt
  ofl/ephesis/upstream.yaml
Labels: - Ready for Review, II New Font

#3640 Lemonada v4.005 (stat fix)
  ofl/lemonada/Lemonada[wght].ttf
  ofl/lemonada/OFL.txt
  ofl/lemonada/static/Lemonada-Bold.ttf
  ofl/lemonada/static/Lemonada-Light.ttf
  ofl/lemonada/static/Lemonada-Medium.ttf
  ofl/lemonada/static/Lemonada-Regular.ttf
  ofl/lemonada/static/Lemonada-SemiBold.ttf
  ofl/lemonada/static/METADATA.pb
Labels: I VF, --- to_sandbox, II Font Upgrade

#3731 Lemonada: removed static directory
  ofl/lemonada/static/Lemonada-Bold.ttf
  ofl/lemonada/static/Lemonada-Light.ttf
  ofl/lemonada/static/Lemonada-Medium.ttf
  ofl/lemonada/static/Lemonada-Regular.ttf
  ofl/lemonada/static/Lemonada-SemiBold.ttf
Labels: II No push needed

#3733 Archivo: description corrected
  ofl/archivo/DESCRIPTION.en_us.html
Labels: --- to_sandbox, II Description/Metadata/OFL

#3703 Red Hat Mono: Version 1.021 added
  ofl/redhatmono/OFL.txt
  ofl/redhatmono/RedHatMono-Italic[wght].ttf
  ofl/redhatmono/RedHatMono[wght].ttf
Labels: - In Progress, II Small Fix

#3735 Cherish: Version 1.005 added
  ofl/cherish/Cherish-Regular.ttf
  ofl/cherish/DESCRIPTION.en_us.html
  ofl/cherish/METADATA.pb
  ofl/cherish/OFL.txt
  ofl/cherish/upstream.yaml
Labels: - Ready for Review, II New Font

#3702 Red Hat Display: Version 1.021 added
  ofl/redhatdisplay/OFL.txt
  ofl/redhatdisplay/RedHatDisplay-Italic[wght].ttf
  ofl/redhatdisplay/RedHatDisplay[wght].ttf
Labels: - In Progress, II Small Fix

#3701 Red Hat Text: Version 1.021 added
  ofl/redhattext/OFL.txt
  ofl/redhattext/RedHatText-Italic[wght].ttf
  ofl/redhattext/RedHatText[wght].ttf
Labels: - Ready for Review, II Small Fix

#3745 Manuale METADATA correction
  ofl/manuale/METADATA.pb
Labels: - Ready for Review, II Description/Metadata/OFL, II Small Fix

#3746 Saira: Version 1.101 added
  ofl/saira/Saira-Italic[wdth,wght].ttf
  ofl/saira/Saira[wdth,wght].ttf
  ofl/saira/upstream.yaml
Labels: - Ready for Review, II Font Upgrade

#3776 Are You Serious: Version 1.100 added
  ofl/areyouserious/AreYouSerious-Regular.ttf
  ofl/areyouserious/DESCRIPTION.en_us.html
  ofl/areyouserious/METADATA.pb
  ofl/areyouserious/OFL.txt
  ofl/areyouserious/upstream.yaml
Labels: - Ready for Review, II New Font

#3770 Gideon Roman: Version 2.010 added
  ofl/gideonroman/DESCRIPTION.en_us.html
  ofl/gideonroman/GideonRoman-Regular.ttf
  ofl/gideonroman/METADATA.pb
  ofl/gideonroman/OFL.txt
  ofl/gideonroman/upstream.yaml
Labels: - Ready for Review, II New Font

#3769 Ruge Boogie: Version 1.010; ttfautohint (v1.8.3) added
  ofl/rugeboogie/DESCRIPTION.en_us.html
  ofl/rugeboogie/METADATA.pb
  ofl/rugeboogie/OFL.txt
  ofl/rugeboogie/RugeBoogie-Regular.ttf
  ofl/rugeboogie/upstream.yaml
Labels: - Ready for Review, II Font Upgrade

#3768 Estonia: Version 1.010; ttfautohint (v1.8.3) added
  ofl/estonia/DESCRIPTION.en_us.html
  ofl/estonia/Estonia-Regular.ttf
  ofl/estonia/METADATA.pb
  ofl/estonia/OFL.txt
  ofl/estonia/upstream.yaml
Labels: - Ready for Review, II New Font

#3767 Corinthia: Version 1.010; ttfautohint (v1.8.3) added
  ofl/corinthia/Corinthia-Bold.ttf
  ofl/corinthia/Corinthia-Regular.ttf
  ofl/corinthia/DESCRIPTION.en_us.html
  ofl/corinthia/METADATA.pb
  ofl/corinthia/OFL.txt
  ofl/corinthia/upstream.yaml
Labels: - Ready for Review, II New Font

#3766 Carattere: Version 1.010; ttfautohint (v1.8.3) added
  ofl/carattere/Carattere-Regular.ttf
  ofl/carattere/DESCRIPTION.en_us.html
  ofl/carattere/METADATA.pb
  ofl/carattere/OFL.txt
  ofl/carattere/upstream.yaml
Labels: - Ready for Review, II New Font

#3763 MuseoModerno: Version 1.002 added
  ofl/museomoderno/METADATA.pb
  ofl/museomoderno/MuseoModerno[wght].ttf
  ofl/museomoderno/upstream.yaml
Labels: I VF, - Ready for Review, II Font Upgrade
