Repository google/fonts, pull requests merged in 2021-04, with the labels that each got.

#2287 Unchen: Description's URL updated
  ofl/uchen/DESCRIPTION.en_us.html
Labels: -- Ready to push, II Description/Metadata/OFL

#3273 Yrsa: Version 2.000 added
  ofl/yrsa/DESCRIPTION.en_us.html
  ofl/yrsa/METADATA.pb
  ofl/yrsa/OFL.txt
  ofl/yrsa/Yrsa-Bold.ttf
  ofl/yrsa/Yrsa-Italic[wght].ttf
  ofl/yrsa/Yrsa-Light.ttf
  ofl/yrsa/Yrsa-Medium.ttf
  ofl/yrsa/Yrsa-Regular.ttf
  ofl/yrsa/Yrsa-SemiBold.ttf
  ofl/yrsa/Yrsa[wght].ttf
  ofl/yrsa/upstream.yaml
Labels: -- Ready to push, II Font Upgrade

#3272 Rasa: Version 2.000 added
  ofl/rasa/DESCRIPTION.en_us.html
  ofl/rasa/METADATA.pb
  ofl/rasa/OFL.txt
  ofl/rasa/Rasa-Bold.ttf
  ofl/rasa/Rasa-Italic[wght].ttf
  ofl/rasa/Rasa-Light.ttf
  ofl/rasa/Rasa-Medium.ttf
  ofl/rasa/Rasa-Regular.ttf
  ofl/rasa/Rasa-SemiBold.ttf
  ofl/rasa/Rasa[wght].ttf
  ofl/rasa/upstream.yaml
Labels: --- to_sandbox, II Font Upgrade

#3274 Catalog Danh Hong
  catalog/designers/danhhong/bio.html
  catalog/designers/danhhong/info.pb
Labels: - Ready for Review, II Catalog

#3266 Thomas Jockin : bio added
  catalog/designers/thomasjockin/bio.html
  catalog/designers/thomasjockin/info.pb
  catalog/designers/thomasjockin/thomas_jockin.png
Labels: --- to_sandbox, II Catalog

#3258 catalog/designers/rossmills
  catalog/designers/rossmills/bio.html
  catalog/designers/rossmills/info.pb
  catalog/designers/rossmills/ross_mills.png
Labels: - Needs confirmation, - Ready for Review, II Catalog

#2872 Palette Mosaic Font One: Version 1.000 added
  ofl/palettemosaicfontone/DESCRIPTION.en_us.html
  ofl/palettemosaicfontone/METADATA.pb
  ofl/palettemosaicfontone/OFL.txt
  ofl/palettemosaicfontone/PaletteMosaicFontOne-Regular.ttf
  ofl/palettemosaicfontone/upstream.yaml
Labels: - Needs Dave's opinion, II New Font

#3282 Natanael Gama: removed google+ link
  catalog/designers/natanaelgama/info.pb
Labels: -- Ready to push, II Catalog

#3289 Rodrigo Fuenzalida : Bio added
  catalog/designers/rodrigofuenzalida/bio.html
  catalog/designers/rodrigofuenzalida/info.pb
  catalog/designers/rodrigofuenzalida/rodrigofuenzalida.png
Labels: -- Ready to push, II Catalog

#3279 Recursive: Version 1.078 added
  ofl/recursive/DESCRIPTION.en_us.html
  ofl/recursive/METADATA.pb
  ofl/recursive/OFL.txt
  ofl/recursive/Recursive[CASL,CRSV,MONO,slnt,wght].ttf
  ofl/recursive/upstream.yaml
Labels: - In Progress, - Needs confirmation, II Font Upgrade

#2868 Otomanopee One: Version 3.003; ttfautohint (v1.8.3) added
  ofl/otomanopeeone/DESCRIPTION.en_us.html
  ofl/otomanopeeone/METADATA.pb
  ofl/otomanopeeone/OFL.txt
  ofl/otomanopeeone/OtomanopeeOne-Regular.ttf
  ofl/otomanopeeone/upstream.yaml
Labels: - Ready for Review, II New Font

#2801 Bitter: Version 2.002 added
  ofl/bitter/Bitter-Italic[wght].ttf
  ofl/bitter/Bitter[wght].ttf
  ofl/bitter/static/Bitter-Black.ttf
  ofl/bitter/static/Bitter-BlackItalic.ttf
  ofl/bitter/static/Bitter-Bold.ttf
  ofl/bitter/static/Bitter-BoldItalic.ttf
  ofl/bitter/static/Bitter-ExtraBold.ttf
  ofl/bitter/static/Bitter-ExtraBoldItalic.ttf
  ofl/bitter/static/Bitter-ExtraLight.ttf
  ofl/bitter/static/Bitter-ExtraLightItalic.ttf
  ofl/bitter/static/Bitter-Italic.ttf
  ofl/bitter/static/Bitter-Light.ttf
  ofl/bitter/static/Bitter-LightItalic.ttf
  ofl/bitter/static/Bitter-Medium.ttf
  ofl/bitter/static/Bitter-MediumItalic.ttf
  ofl/bitter/static/Bitter-Regular.ttf
  ofl/bitter/static/Bitter-SemiBold.ttf
  ofl/bitter/static/Bitter-SemiBoldItalic.ttf
  ofl/bitter/static/Bitter-Thin.ttf
  ofl/bitter/static/Bitter-ThinItalic.ttf
  ofl/bitter/upstream.yaml
Labels: - Ready for Review, II Font Upgrade

#3303 Natanael Gama : bio updated
  catalog/designers/natanaelgama/bio.html
Labels: -- Ready to push, II Catalog

#3275 Bona Nova: Version 4.001; ttfautohint (v1.8.3) added
  ofl/bonanova/BonaNova-Bold.ttf
  ofl/bonanova/BonaNova-Italic.ttf
  ofl/bonanova/BonaNova-Regular.ttf
  ofl/bonanova/DESCRIPTION.en_us.html
  ofl/bonanova/METADATA.pb
  ofl/bonanova/OFL.txt
  ofl/bonanova/upstream.yaml
Labels: -- Ready to push, II New Font

#3311 Chathura: removed ITC from designer
  ofl/chathura/METADATA.pb
Labels: --- to_sandbox, II Description/Metadata/OFL

#3304 STIX Two Math: Version 2.12 b168 added
  ofl/stixtwomath/DESCRIPTION.en_us.html
  ofl/stixtwomath/METADATA.pb
  ofl/stixtwomath/OFL.txt
  ofl/stixtwomath/STIXTwoMath-Regular.ttf
  ofl/stixtwomath/upstream.yaml
Labels: -- Ready to push, II New Font

#3256 STIX Two Text: Version 2.12 b168 added
  ofl/stixtwotext/DESCRIPTION.en_us.html
  ofl/stixtwotext/METADATA.pb
  ofl/stixtwotext/OFL.txt
  ofl/stixtwotext/STIXTwoText-Italic[wght].ttf
  ofl/stixtwotext/STIXTwoText[wght].ttf
  ofl/stixtwotext/upstream.yaml
Labels: --- to_sandbox, II New Font

#2924 [gftools-packager] Qahiri: Version 1.01 added
  ofl/qahiri/DESCRIPTION.en_us.html
  ofl/qahiri/METADATA.pb
  ofl/qahiri/OFL.txt
  ofl/qahiri/Qahiri-Regular.ttf
  ofl/qahiri/upstream.yaml
Labels: - Ready for Review, II New Font

#3326 Rasa: Version 2.001 added
  ofl/rasa/Rasa-Italic[wght].ttf
  ofl/rasa/Rasa[wght].ttf
Labels: --- to_sandbox, II Fix

#3327 Yrsa: Version 2.001 added
  ofl/yrsa/Yrsa-Italic[wght].ttf
  ofl/yrsa/Yrsa[wght].ttf
Labels: --- to_sandbox, II Fix

#3328 Qwigley: Version 1.010; ttfautohint (v1.8.3) added
  ofl/qwigley/DESCRIPTION.en_us.html
  ofl/qwigley/METADATA.pb
  ofl/qwigley/OFL.txt
  ofl/qwigley/Qwigley-Regular.ttf
  ofl/qwigley/upstream.yaml
Labels: - Ready for Review, II Font Upgrade

#3329 Bilbo: Version 1.100 added
  ofl/bilbo/Bilbo-Regular.ttf
  ofl/bilbo/DESCRIPTION.en_us.html
  ofl/bilbo/METADATA.pb
  ofl/bilbo/OFL.txt
  ofl/bilbo/upstream.yaml
Labels: - Ready for Review, II Font Upgrade

#3314 Festive: Version 1.101; ttfautohint (v1.8.3) added
  ofl/festive/DESCRIPTION.en_us.html
  ofl/festive/Festive-Regular.ttf
  ofl/festive/METADATA.pb
  ofl/festive/OFL.txt
  ofl/festive/upstream.yaml
Labels: - Ready for Review, II New Font

#3341 Catalog update: Cyreal
  catalog/designers/cyreal/info.pb
Labels: - Ready for Review, II Catalog

#3344 Rubik: Version 2.102 added
  ofl/rubik/OFL.txt
  ofl/rubik/Rubik-Italic[wght].ttf
  ofl/rubik/Rubik[wght].ttf
  ofl/rubik/static/Rubik-Black.ttf
  ofl/rubik/static/Rubik-BlackItalic.ttf
  ofl/rubik/static/Rubik-Bold.ttf
  ofl/rubik/static/Rubik-BoldItalic.ttf
  ofl/rubik/static/Rubik-Italic.ttf
  ofl/rubik/static/Rubik-Light.ttf
  ofl/rubik/static/Rubik-LightItalic.ttf
  ofl/rubik/static/Rubik-Medium.ttf
  ofl/rubik/static/Rubik-MediumItalic.ttf
  ofl/rubik/static/Rubik-Regular.ttf
  ofl/rubik/upstream.yaml
Labels: - Ready for Review, II Fix

#3345 Lexend Zetta: Version 1.005; ttfautohint (v1.8.3) added; Lexend Peta: Version 1.005; ttfautohint (v1.8.3) added; Lexend Exa: Version 1.005; ttfautohint (v1.8.3) added; Lexend Giga: Version 1.005; ttfautohint (v1.8.3) added; Lexend Mega: Version 1.005; ttfautohint (v1.8.3) added; Lexend Deca: Version 1.005; ttfautohint (v1.8.3) added; Lexend Tera: Version 1.005; ttfautohint (v1.8.3) added
  ofl/lexenddeca/LexendDeca-Regular.ttf
  ofl/lexenddeca/OFL.txt
  ofl/lexenddeca/upstream.yaml
  ofl/lexendexa/LexendExa-Regular.ttf
  ofl/lexendexa/OFL.txt
  ofl/lexendexa/upstream.yaml
  ofl/lexendgiga/LexendGiga-Regular.ttf
  ofl/lexendgiga/OFL.txt
  ofl/lexendgiga/upstream.yaml
  ofl/lexendmega/LexendMega-Regular.ttf
  ofl/lexendmega/OFL.txt
  ofl/lexendmega/upstream.yaml
  ofl/lexendpeta/LexendPeta-Regular.ttf
  ofl/lexendpeta/OFL.txt
  ofl/lexendpeta/upstream.yaml
  ofl/lexendtera/LexendTera-Regular.ttf
  ofl/lexendtera/OFL.txt
  ofl/lexendtera/upstream.yaml
  ofl/lexendzetta/LexendZetta-Regular.ttf
  ofl/lexendzetta/OFL.txt
  ofl/lexendzetta/upstream.yaml
Labels: - Ready for Review, II Font Upgrade

#3351 Catalog: Anna Giedrys
  catalog/designers/annagiedrys/bio.html
Labels: --- to_sandbox, II Catalog

#3259 catalog/designers/robleuschke
  catalog/designers/robleuschke/bio.html
  catalog/designers/robleuschke/info.pb
  catalog/designers/robleuschke/rob_leuschke.png
Labels: -- Ready to push, II Catalog

#3350 Tourney: Version 1.015 added
  ofl/tourney/DESCRIPTION.en_us.html
  ofl/tourney/METADATA.pb
  ofl/tourney/OFL.txt
  ofl/tourney/Tourney-Italic[wdth,wght].ttf
  ofl/tourney/Tourney[wdth,wght].ttf
  ofl/tourney/upstream.yaml
Labels: -- Ready to push, II New Font

#3359 Kousuke Nagai: bio added
  catalog/designers/kousukenagai/KousukeNagai.png
  catalog/designers/kousukenagai/bio.html
  catalog/designers/kousukenagai/info.pb
Labels: - Ready for Review, II Catalog

#3355 Akaya Telivigala: Version 1.002; ttfautohint (v1.8.3) added
  ofl/akayatelivigala/AkayaTelivigala-Regular.ttf
Labels: --- to_sandbox, II Small Fix

#3354 Fuggles: Version 1.100; ttfautohint (v1.8.3) added
  ofl/fuggles/DESCRIPTION.en_us.html
  ofl/fuggles/Fuggles-Regular.ttf
  ofl/fuggles/METADATA.pb
  ofl/fuggles/OFL.txt
  ofl/fuggles/upstream.yaml
Labels: --- to_sandbox, II New Font
