Repository google/fonts, pull requests merged in 2022-09, with the labels that each got.

#5167 Reem Kufi Ink: Version 1.004 added
  ofl/reemkufiink/METADATA.pb
  ofl/reemkufiink/ReemKufiInk-Regular.ttf
  ofl/reemkufiink/upstream.yaml
Labels: I New Font

#5164 Reem Kufi Fun: Version 1.004 added
  ofl/reemkufifun/METADATA.pb
  ofl/reemkufifun/ReemKufiFun[wght].ttf
  ofl/reemkufifun/upstream.yaml
Labels: - Ready for Review, I New Font

#5170 Reem Kufi Ink: Version 1.004 added
  ofl/reemkufiink/ReemKufiInk-Regular.ttf
Labels: --- to sandbox, I New Font

#5168 Reinstate more articles
  ofl/notosansadlam/article/ARTICLE.en_us.html
  ofl/notosansgurmukhi/article/ARTICLE.en_us.html
Labels: -- Needs confirmation, I Description/Metadata/OFL

#5176 Reinstate article for Adlam Unjoined
  ofl/notosansadlamunjoined/article/ARTICLE.en_us.html
Labels: z_Noto, - Ready for Review, I Description/Metadata/OFL

#5160 Nabla: Version 1.002 added
  ofl/nabla/METADATA.pb
  ofl/nabla/Nabla[EDPT,EHLT].ttf
  ofl/nabla/OFL.txt
  ofl/nabla/upstream.yaml
Labels: - Ready for Review, I New Font

#5122 Noto Sans Cham: Version 2.002 added
  ofl/notosanscham/METADATA.pb
  ofl/notosanscham/NotoSansCham[wght].ttf
  ofl/notosanscham/OFL.txt
  ofl/notosanscham/upstream.yaml
Labels: z_Noto, - Ready for Review, I Font Upgrade

#5209 Noto Sans Meetei Mayek: Version 2.002 added
  ofl/notosansmeeteimayek/METADATA.pb
  ofl/notosansmeeteimayek/NotoSansMeeteiMayek[wght].ttf
  ofl/notosansmeeteimayek/OFL.txt
  ofl/notosansmeeteimayek/upstream.yaml
Labels: z_Noto, - Ready for Review, I Font Upgrade

#5203 Noto Serif Grantha: Version 2.004; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notoserifgrantha/METADATA.pb
  ofl/notoserifgrantha/NotoSerifGrantha-Regular.ttf
  ofl/notoserifgrantha/OFL.txt
  ofl/notoserifgrantha/upstream.yaml
Labels: z_Noto, - Ready for Review, I Font Upgrade

#5204 Noto Sans Javanese: Version 2.004 added
  ofl/notosansjavanese/METADATA.pb
  ofl/notosansjavanese/NotoSansJavanese-Bold.ttf
  ofl/notosansjavanese/NotoSansJavanese-Regular.ttf
  ofl/notosansjavanese/NotoSansJavanese[wght].ttf
  ofl/notosansjavanese/OFL.txt
  ofl/notosansjavanese/upstream.yaml
Labels: z_Noto, - Ready for Review, I Font Upgrade

#5216 Baloo Bhaijaan 2: Version 1.701 added
  ofl/baloobhaijaan2/BalooBhaijaan2[wght].ttf
  ofl/baloobhaijaan2/METADATA.pb
  ofl/baloobhaijaan2/upstream.yaml
Labels: -- Bad rendering, - Ready for Review, I Font Bug, II Arabic / Semitic

#5237 Noto Sans Symbols: Version 2.002 added
  ofl/notosanssymbols/METADATA.pb
  ofl/notosanssymbols/NotoSansSymbols[wght].ttf
  ofl/notosanssymbols/OFL.txt
  ofl/notosanssymbols/upstream.yaml
Labels: - Ready for Review, I Font Upgrade

#5123 Noto Sans Cherokee: Version 2.001 added
  ofl/notosanscherokee/METADATA.pb
  ofl/notosanscherokee/NotoSansCherokee[wght].ttf
  ofl/notosanscherokee/OFL.txt
  ofl/notosanscherokee/upstream.yaml
Labels: I Font Upgrade

#5126 Noto Sans Coptic: Version 2.002; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosanscoptic/METADATA.pb
  ofl/notosanscoptic/NotoSansCoptic-Regular.ttf
  ofl/notosanscoptic/OFL.txt
  ofl/notosanscoptic/upstream.yaml
Labels: - Ready for Review, I Font Upgrade

#5138 Noto Sans Grantha: Version 2.003; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosansgrantha/METADATA.pb
  ofl/notosansgrantha/NotoSansGrantha-Regular.ttf
  ofl/notosansgrantha/OFL.txt
  ofl/notosansgrantha/upstream.yaml
Labels: --- to sandbox, I Font Upgrade

#5143 Noto Sans Mende Kikakui: Version 2.003; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosansmendekikakui/METADATA.pb
  ofl/notosansmendekikakui/NotoSansMendeKikakui-Regular.ttf
  ofl/notosansmendekikakui/OFL.txt
  ofl/notosansmendekikakui/upstream.yaml
Labels: - Ready for Review, I New Font

#5151 Noto Sans Canadian Aboriginal: Version 2.002 added
  ofl/notosanscanadianaboriginal/METADATA.pb
  ofl/notosanscanadianaboriginal/NotoSansCanadianAboriginal[wght].ttf
  ofl/notosanscanadianaboriginal/OFL.txt
  ofl/notosanscanadianaboriginal/upstream.yaml
Labels: --- to sandbox, I Font Upgrade

#5234 Gulzar: primary script added
  ofl/gulzar/METADATA.pb
Labels: --- to sandbox, I Description/Metadata/OFL

#5196 Noto Sans Warang Citi: Version 3.002; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosanswarangciti/METADATA.pb
  ofl/notosanswarangciti/NotoSansWarangCiti-Regular.ttf
  ofl/notosanswarangciti/OFL.txt
  ofl/notosanswarangciti/upstream.yaml
Labels: --- to sandbox, I Font Upgrade

#5198 Noto Sans Wancho: Version 2.001; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosanswancho/METADATA.pb
  ofl/notosanswancho/NotoSansWancho-Regular.ttf
  ofl/notosanswancho/OFL.txt
  ofl/notosanswancho/upstream.yaml
Labels: --- to sandbox, I Font Upgrade

#5249 Noto Serif Oriya documentation
  ofl/notoseriforiya/DESCRIPTION.en_us.html
  ofl/notoseriforiya/article/ARTICLE.en_us.html
Labels: - Ready for Review, I Description/Metadata/OFL

#5226 IBM Plex Sans JP: Version 1.001 added
  ofl/ibmplexsansjp/DESCRIPTION.en_us.html
  ofl/ibmplexsansjp/IBMPlexSansJP-Bold.ttf
  ofl/ibmplexsansjp/IBMPlexSansJP-ExtraLight.ttf
  ofl/ibmplexsansjp/IBMPlexSansJP-Light.ttf
  ofl/ibmplexsansjp/IBMPlexSansJP-Medium.ttf
  ofl/ibmplexsansjp/IBMPlexSansJP-Regular.ttf
  ofl/ibmplexsansjp/IBMPlexSansJP-SemiBold.ttf
  ofl/ibmplexsansjp/IBMPlexSansJP-Thin.ttf
  ofl/ibmplexsansjp/METADATA.pb
  ofl/ibmplexsansjp/OFL.txt
  ofl/ibmplexsansjp/upstream.yaml
Labels: II CJK, --- to sandbox, I New Font

#5251 Noto Sans Mongolian: Version 2.003; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosansmongolian/METADATA.pb
  ofl/notosansmongolian/NotoSansMongolian-Regular.ttf
  ofl/notosansmongolian/OFL.txt
  ofl/notosansmongolian/upstream.yaml
Labels: --- to sandbox, I Font Upgrade

#5250 Noto Sans Tagalog: Version 2.001; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosanstagalog/METADATA.pb
  ofl/notosanstagalog/NotoSansTagalog-Regular.ttf
  ofl/notosanstagalog/OFL.txt
  ofl/notosanstagalog/upstream.yaml
Labels: --- to sandbox, I Font Upgrade

#5139 Noto Sans Hanunoo: Version 2.003; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosanshanunoo/METADATA.pb
  ofl/notosanshanunoo/NotoSansHanunoo-Regular.ttf
  ofl/notosanshanunoo/OFL.txt
  ofl/notosanshanunoo/upstream.yaml
Labels: --- to sandbox, I Font Upgrade

#5113 Noto Sans Bassa Vah: Version 2.002 added
  ofl/notosansbassavah/METADATA.pb
  ofl/notosansbassavah/NotoSansBassaVah-Regular.ttf
  ofl/notosansbassavah/NotoSansBassaVah[wght].ttf
  ofl/notosansbassavah/OFL.txt
  ofl/notosansbassavah/upstream.yaml
Labels: -- Needs confirmation, I Font Upgrade

#5114 Noto Sans Hanifi Rohingya: Version 2.101 added
  ofl/notosanshanifirohingya/METADATA.pb
  ofl/notosanshanifirohingya/NotoSansHanifiRohingya[wght].ttf
  ofl/notosanshanifirohingya/OFL.txt
  ofl/notosanshanifirohingya/upstream.yaml
Labels: -- Needs confirmation, I Font Upgrade

#5116 Noto Sans Buginese: Version 2.002; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosansbuginese/METADATA.pb
  ofl/notosansbuginese/NotoSansBuginese-Regular.ttf
  ofl/notosansbuginese/OFL.txt
  ofl/notosansbuginese/upstream.yaml
Labels: - Ready for Review, I Font Upgrade

#5140 Noto Sans Kayah Li: Version 2.002 added
  ofl/notosanskayahli/METADATA.pb
  ofl/notosanskayahli/NotoSansKayahLi[wght].ttf
  ofl/notosanskayahli/OFL.txt
  ofl/notosanskayahli/upstream.yaml
Labels: - Ready for Review, I Font Upgrade

#5148 Noto Sans Pahawh Hmong: Version 2.001; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosanspahawhhmong/METADATA.pb
  ofl/notosanspahawhhmong/NotoSansPahawhHmong-Regular.ttf
  ofl/notosanspahawhhmong/OFL.txt
  ofl/notosanspahawhhmong/upstream.yaml
Labels: - Ready for Review, I Font Upgrade

#5142 Noto Sans Medefaidrin: Version 1.002 added
  ofl/notosansmedefaidrin/METADATA.pb
  ofl/notosansmedefaidrin/NotoSansMedefaidrin[wght].ttf
  ofl/notosansmedefaidrin/OFL.txt
  ofl/notosansmedefaidrin/upstream.yaml
Labels: - Ready for Review, I Font Upgrade

#5158 Noto Sans Mro: Version 2.001; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosansmro/METADATA.pb
  ofl/notosansmro/NotoSansMro-Regular.ttf
  ofl/notosansmro/OFL.txt
  ofl/notosansmro/article/ARTICLE.en_us.html
  ofl/notosansmro/upstream.yaml
Labels: - Ready for Review, I Font Upgrade

#5159 Noto Sans Multani: Version 2.001; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosansmultani/METADATA.pb
  ofl/notosansmultani/NotoSansMultani-Regular.ttf
  ofl/notosansmultani/OFL.txt
  ofl/notosansmultani/article/ARTICLE.en_us.html
  ofl/notosansmultani/upstream.yaml
Labels: - Ready for Review, I Font Upgrade

#5332 Noto Sans Limbu: Version 2.004; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosanslimbu/METADATA.pb
  ofl/notosanslimbu/NotoSansLimbu-Regular.ttf
  ofl/notosanslimbu/article/ARTICLE.en_us.html
  ofl/notosanslimbu/upstream.yaml
Labels: --- to sandbox, I Small Fix

#5334 Finlandica: Version 1.064 added
  ofl/finlandica/Finlandica-Italic[wght].ttf
  ofl/finlandica/Finlandica[wght].ttf
  ofl/finlandica/METADATA.pb
Labels: - Ready for Review, I Small Fix

#5242 Noto Sans Tai Tham: Version 2.002 added
  ofl/notosanstaitham/METADATA.pb
  ofl/notosanstaitham/NotoSansTaiTham[wght].ttf
  ofl/notosanstaitham/OFL.txt
  ofl/notosanstaitham/upstream.yaml
Labels: - Ready for Review, I Font Upgrade

#5252 Noto Sans Modi: Version 2.002; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosansmodi/METADATA.pb
  ofl/notosansmodi/NotoSansModi-Regular.ttf
  ofl/notosansmodi/OFL.txt
  ofl/notosansmodi/upstream.yaml
Labels: --- to sandbox, I Font Upgrade

#5239 Noto Sans Tai Le: Version 2.002; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosanstaile/METADATA.pb
  ofl/notosanstaile/NotoSansTaiLe-Regular.ttf
  ofl/notosanstaile/OFL.txt
  ofl/notosanstaile/upstream.yaml
Labels: --- to sandbox, I Font Upgrade

#5333 Update axis registry: YEAR, ELSH, ELGR
  axisregistry/Lib/axisregistry/data/element_grid.textproto
  axisregistry/Lib/axisregistry/data/element_shape.textproto
  axisregistry/Lib/axisregistry/data/year.textproto
Labels: - Ready for Review, I Axis Registry

#5353 Solway: metadata and description updated
  ofl/solway/DESCRIPTION.en_us.html
  ofl/solway/METADATA.pb
Labels: - Ready for Review, I Description/Metadata/OFL

#5354 Catalog: Inhouse Type added
  catalog/designers/inhousetype/bio.html
  catalog/designers/inhousetype/info.pb
  catalog/designers/inhousetype/inhousetype.jpg
Labels: --- to sandbox, I Designer profile

#5118 Noto Sans Chakma: Version 2.003; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosanschakma/METADATA.pb
  ofl/notosanschakma/NotoSansChakma-Regular.ttf
  ofl/notosanschakma/OFL.txt
  ofl/notosanschakma/upstream.yaml
Labels: -- Needs confirmation, I Font Upgrade
