Repository google/fonts, pull requests merged in 2022-10, with the labels that each got.

#5197 Noto Sans Yi: Version 2.001; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosansyi/METADATA.pb
  ofl/notosansyi/NotoSansYi-Regular.ttf
  ofl/notosansyi/OFL.txt
  ofl/notosansyi/upstream.yaml
Labels: --- to sandbox, I Font Upgrade

#5228 Noto Sans Takri: Version 2.003; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosanstakri/METADATA.pb
  ofl/notosanstakri/NotoSansTakri-Regular.ttf
  ofl/notosanstakri/OFL.txt
  ofl/notosanstakri/upstream.yaml
Labels: - Ready for Review, I Font Upgrade

#5225 Noto Sans Siddham: Version 2.004; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosanssiddham/METADATA.pb
  ofl/notosanssiddham/NotoSansSiddham-Regular.ttf
  ofl/notosanssiddham/OFL.txt
  ofl/notosanssiddham/upstream.yaml
Labels: --- to sandbox, I Font Upgrade

#5372 Noto Sans Modi: Version 2.003; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosansmodi/METADATA.pb
  ofl/notosansmodi/NotoSansModi-Regular.ttf
  ofl/notosansmodi/upstream.yaml
Labels: --- to sandbox, I Font Upgrade

#5371 Noto Sans Multani: Version 2.002; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosansmultani/METADATA.pb
  ofl/notosansmultani/NotoSansMultani-Regular.ttf
  ofl/notosansmultani/article/ARTICLE.en_us.html
  ofl/notosansmultani/upstream.yaml
Labels: --- to sandbox, I Font Upgrade

#5328 Cairo: Version 3.120 added
  ofl/cairo/Cairo[slnt,wght].ttf
  ofl/cairo/Cairo[wght].ttf
  ofl/cairo/METADATA.pb
  ofl/cairo/OFL.txt
  ofl/cairo/upstream.yaml
Labels: III Expand styles, --- to sandbox, I Font Upgrade, II Arabic / Semitic

#5327 Cairo Play: Version 3.120 added
  ofl/cairoplay/CairoPlay[slnt,wght].ttf
  ofl/cairoplay/METADATA.pb
Labels: - Ready for Review, I Small Fix, II Arabic / Semitic, II Color font

#5222 Noto Sans New Tai Lue: Version 2.003 added
  ofl/notosansnewtailue/METADATA.pb
  ofl/notosansnewtailue/NotoSansNewTaiLue-Regular.ttf
  ofl/notosansnewtailue/NotoSansNewTaiLue[wght].ttf
  ofl/notosansnewtailue/OFL.txt
  ofl/notosansnewtailue/upstream.yaml
Labels: --- to sandbox, I Font Upgrade

#5190 Noto Sans Tagbanwa: Version 2.001; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosanstagbanwa/METADATA.pb
  ofl/notosanstagbanwa/NotoSansTagbanwa-Regular.ttf
  ofl/notosanstagbanwa/OFL.txt
  ofl/notosanstagbanwa/upstream.yaml
Labels: --- to sandbox, I Font Upgrade

#5115 Noto Sans Bamum: Version 2.001 added
  ofl/notosansbamum/METADATA.pb
  ofl/notosansbamum/NotoSansBamum[wght].ttf
  ofl/notosansbamum/OFL.txt
  ofl/notosansbamum/upstream.yaml
Labels: -- Needs manager's opinion, I Font Upgrade, -- Needs lang sample

#5331 Readex Pro: Version 1.204 added
  ofl/readexpro/DESCRIPTION.en_us.html
  ofl/readexpro/METADATA.pb
  ofl/readexpro/ReadexPro[HEXP,wght].ttf
  ofl/readexpro/ReadexPro[wght].ttf
  ofl/readexpro/upstream.yaml
Labels: -- Requires Axis Registration, I Font Upgrade, III Custom axes

#5350 Climate Crisis: Version 1.003 added
  ofl/climatecrisis/ClimateCrisis[YEAR].ttf
  ofl/climatecrisis/DESCRIPTION.en_us.html
  ofl/climatecrisis/METADATA.pb
  ofl/climatecrisis/OFL.txt
  ofl/climatecrisis/upstream.yaml
Labels: -- Requires Axis Registration, I New Font, III Custom axes

#5355 Cantora One: version 1.002 added HOTFIX
  ofl/cantoraone/CantoraOne-Regular.ttf
  ofl/cantoraone/DESCRIPTION.en_us.html
  ofl/cantoraone/METADATA.pb
Labels: - Ready for Review, I Small Fix

#5292 Average: Version 1.003; ttfautohint (v1.8.4.7-5d5b) added
  ofl/average/Average-Regular.ttf
  ofl/average/DESCRIPTION.en_us.html
  ofl/average/METADATA.pb
  ofl/average/OFL.txt
  ofl/average/upstream.yaml
Labels: III Expand glyphset, --- to sandbox, I Font Upgrade

#5207 Noto Sans Masaram Gondi: Version 1.004; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosansmasaramgondi/METADATA.pb
  ofl/notosansmasaramgondi/NotoSansMasaramGondi-Regular.ttf
  ofl/notosansmasaramgondi/OFL.txt
  ofl/notosansmasaramgondi/upstream.yaml
Labels: - Ready for Review, I Font Upgrade

#5383 Added primary script to Readex and Cairo
  ofl/cairo/METADATA.pb
  ofl/readexpro/METADATA.pb
Labels: I Description/Metadata/OFL

#5374 Marhey: Version 1.000 added
  ofl/marhey/DESCRIPTION.en_us.html
  ofl/marhey/METADATA.pb
  ofl/marhey/Marhey[wght].ttf
  ofl/marhey/OFL.txt
  ofl/marhey/upstream.yaml
Labels: --- to sandbox, I New Font, II Arabic / Semitic

#5366 Nur & Bustan catalog profiles (upcoming Marhey font)
  catalog/designers/bustanularifin/bio.html
  catalog/designers/bustanularifin/bustanularifin.png
  catalog/designers/bustanularifin/info.pb
  catalog/designers/nursyamsi/bio.html
  catalog/designers/nursyamsi/info.pb
  catalog/designers/nursyamsi/nursyamsi.png
Labels: - Ready for Review, I Designer profile

#5181 Noto Sans Ol Chiki: Version 2.003 added
  ofl/notosansolchiki/METADATA.pb
  ofl/notosansolchiki/NotoSansOlChiki[wght].ttf
  ofl/notosansolchiki/OFL.txt
  ofl/notosansolchiki/upstream.yaml
Labels: - Ready for Review, I Font Upgrade

#5402 Designer added: Mariya Lish
  catalog/designers/mariyalish/bio.html
  catalog/designers/mariyalish/info.pb
  catalog/designers/mariyalish/mariyalish.png
Labels: - Ready for Review, I Designer profile

#5235 Noto Sans Syloti Nagri: Version 2.003; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosanssylotinagri/METADATA.pb
  ofl/notosanssylotinagri/NotoSansSylotiNagri-Regular.ttf
  ofl/notosanssylotinagri/OFL.txt
  ofl/notosanssylotinagri/upstream.yaml
Labels: - Ready for Review, I Font Upgrade

#5152 Noto Serif Khojki: Version 2.002 added
  ofl/notoserifkhojki/DESCRIPTION.en_us.html
  ofl/notoserifkhojki/METADATA.pb
  ofl/notoserifkhojki/NotoSerifKhojki[wght].ttf
  ofl/notoserifkhojki/OFL.txt
  ofl/notoserifkhojki/article/ARTICLE.en_us.html
  ofl/notoserifkhojki/upstream.yaml
Labels: --- to sandbox, I New Font, II Indic / Brahmic / Thai / Tai

#5376 Handjet: Version 2.003 added
  ofl/handjet/Handjet[EGRD,ESHP,wght].ttf
  ofl/handjet/Handjet[ELGR,ELSH,wght].ttf
  ofl/handjet/METADATA.pb
  ofl/handjet/OFL.txt
  ofl/handjet/upstream.yaml
Labels: - Ready for Review, -- Requires Axis Registration, I New Font, III Custom axes

#5182 Noto Sans Osage: Version 2.002; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosansosage/METADATA.pb
  ofl/notosansosage/NotoSansOsage-Regular.ttf
  ofl/notosansosage/OFL.txt
  ofl/notosansosage/upstream.yaml
Labels: --- to sandbox, I Font Upgrade

#5183 Noto Sans Osmanya: Version 2.001; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosansosmanya/METADATA.pb
  ofl/notosansosmanya/NotoSansOsmanya-Regular.ttf
  ofl/notosansosmanya/OFL.txt
  ofl/notosansosmanya/upstream.yaml
Labels: --- to sandbox, I Font Upgrade

#5184 Noto Sans Rejang: Version 2.001; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosansrejang/METADATA.pb
  ofl/notosansrejang/NotoSansRejang-Regular.ttf
  ofl/notosansrejang/OFL.txt
  ofl/notosansrejang/upstream.yaml
Labels: --- to sandbox, I Font Upgrade

#5384 Reem Kufi Fun: Version 1.005 added
  ofl/reemkufifun/METADATA.pb
  ofl/reemkufifun/ReemKufiFun[wght].ttf
  ofl/reemkufifun/upstream.yaml
Labels: - Ready for Review, III Improve rendering, I Font Bug, II Arabic / Semitic, II Color font

#5407 Handjet: override ELSH default
  ofl/handjet/METADATA.pb
Labels: I Description/Metadata/OFL, I Small Fix

#5373 Mansalva: Version 2.112; ttfautohint (v1.8.4.7-5d5b) added
  ofl/mansalva/DESCRIPTION.en_us.html
  ofl/mansalva/METADATA.pb
  ofl/mansalva/Mansalva-Regular.ttf
  ofl/mansalva/upstream.yaml
Labels: III Expand glyphset, --- to sandbox, I Font Upgrade

#5185 Noto Sans Pau Cin Hau: Version 2.002; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosanspaucinhau/METADATA.pb
  ofl/notosanspaucinhau/NotoSansPauCinHau-Regular.ttf
  ofl/notosanspaucinhau/OFL.txt
  ofl/notosanspaucinhau/upstream.yaml
Labels: --- to sandbox, I Font Upgrade

#5408 Designer added: Sophia Tai
  catalog/designers/sophiatai/bio.html
  catalog/designers/sophiatai/info.pb
  catalog/designers/sophiatai/sophiatai.png
Labels: --- to sandbox, I Designer profile

#5412 Reinstate Bamum "sample text"
  ofl/notosansbamum/METADATA.pb
Labels: --- to sandbox, I Description/Metadata/OFL

#5405 Removed some de-listed families
  TRIVIA.md
  ofl/andikanewbasic/AndikaNewBasic-Bold.ttf
  ofl/andikanewbasic/AndikaNewBasic-BoldItalic.ttf
  ofl/andikanewbasic/AndikaNewBasic-Italic.ttf
  ofl/andikanewbasic/AndikaNewBasic-Regular.ttf
  ofl/andikanewbasic/DESCRIPTION.en_us.html
  ofl/andikanewbasic/METADATA.pb
  ofl/andikanewbasic/OFL.txt
  ofl/andikanewbasic/upstream.yaml
  ofl/bevietnam/BeVietnam-Bold.ttf
  ofl/bevietnam/BeVietnam-BoldItalic.ttf
  ofl/bevietnam/BeVietnam-ExtraBold.ttf
  ofl/bevietnam/BeVietnam-ExtraBoldItalic.ttf
  ofl/bevietnam/BeVietnam-Italic.ttf
  ofl/bevietnam/BeVietnam-Light.ttf
  ofl/bevietnam/BeVietnam-LightItalic.ttf
  ofl/bevietnam/BeVietnam-Medium.ttf
  ofl/bevietnam/BeVietnam-MediumItalic.ttf
  ofl/bevietnam/BeVietnam-Regular.ttf
  ofl/bevietnam/BeVietnam-SemiBold.ttf
  ofl/bevietnam/BeVietnam-SemiBoldItalic.ttf
  ofl/bevietnam/BeVietnam-Thin.ttf
  ofl/bevietnam/BeVietnam-ThinItalic.ttf
  ofl/bevietnam/DESCRIPTION.en_us.html
  ofl/bevietnam/METADATA.pb
  ofl/bevietnam/OFL.txt
  ofl/gentiumbasic/DESCRIPTION.en_us.html
  ofl/gentiumbasic/FONTLOG.txt
  ofl/gentiumbasic/GenBasB.ttf
  ofl/gentiumbasic/GenBasBI.ttf
  ofl/gentiumbasic/GenBasI.ttf
  ofl/gentiumbasic/GenBasR.ttf
  ofl/gentiumbasic/METADATA.pb
  ofl/gentiumbasic/OFL.txt
  ofl/kdamthmor/DESCRIPTION.en_us.html
  ofl/kdamthmor/KdamThmor-Regular.ttf
  ofl/kdamthmor/METADATA.pb
  ofl/kdamthmor/OFL.txt
  ofl/scheherazade/DESCRIPTION.en_us.html
  ofl/scheherazade/METADATA.pb
  ofl/scheherazade/OFL.txt
  ofl/scheherazade/Scheherazade-Bold.ttf
  ofl/scheherazade/Scheherazade-Regular.ttf
  ofl/spartan/DESCRIPTION.en_us.html
  ofl/spartan/METADATA.pb
  ofl/spartan/OFL.txt
  ofl/spartan/Spartan[wght].ttf
Labels: - Ready for Review

#5427 GFK Q3 content bug fixes
  cc-by-sa/knowledge/glossary/terms/alphabet/term.textproto
  cc-by-sa/knowledge/glossary/terms/cjk/content.md
  cc-by-sa/knowledge/glossary/terms/cjk/term.textproto
  cc-by-sa/knowledge/glossary/terms/color_fonts/content.md
  cc-by-sa/knowledge/glossary/terms/designspace/content.md
  cc-by-sa/knowledge/glossary/terms/designspace/term.textproto
  cc-by-sa/knowledge/glossary/terms/emoji/content.md
  cc-by-sa/knowledge/glossary/terms/emoji/term.textproto
  cc-by-sa/knowledge/glossary/terms/letters/content.md
  cc-by-sa/knowledge/glossary/terms/letters/term.textproto
  cc-by-sa/knowledge/glossary/terms/parametric_axis/content.md
  cc-by-sa/knowledge/glossary/terms/rag/content.md
  cc-by-sa/knowledge/glossary/terms/rag/term.textproto
  cc-by-sa/knowledge/glossary/terms/reflow/content.md
  cc-by-sa/knowledge/glossary/terms/reflow/term.textproto
  cc-by-sa/knowledge/glossary/terms/tofu/content.md
  cc-by-sa/knowledge/glossary/terms/tofu/term.textproto
  cc-by-sa/knowledge/modules/hangeul/lessons/an_alphabet_for_reading_and_writing/content.md
  cc-by-sa/knowledge/modules/hangeul/lessons/an_introduction_to_hangeul/content.md
  cc-by-sa/knowledge/modules/hangeul/lessons/an_introduction_to_hangeul/images/thumbnail.svg
  cc-by-sa/knowledge/modules/hangeul/lessons/an_introduction_to_hangeul/lesson.textproto
  cc-by-sa/knowledge/modules/hangeul/lessons/designing_for_learnability/content.md
  cc-by-sa/knowledge/modules/hangeul/lessons/introduction_to_hangeul/content.md
  cc-by-sa/knowledge/modules/hangeul/lessons/introduction_to_hangeul/images/thumbnail.svg
  cc-by-sa/knowledge/modules/hangeul/lessons/introduction_to_hangeul/lesson.textproto
  cc-by-sa/knowledge/modules/hangeul/lessons/making_the_details_matter/content.md
  cc-by-sa/knowledge/modules/history_of_type/lessons/the_invention_of_type/content.md
  cc-by-sa/knowledge/modules/history_of_type/lessons/the_tight_not_touching_style/content.md
  cc-by-sa/knowledge/modules/history_of_type/lessons/transitional_faces/content.md
  cc-by-sa/knowledge/modules/history_of_type/lessons/what_have_the_romans_ever_done_for_us/content.md
  cc-by-sa/knowledge/modules/using_type/lessons/switching_from_static_to_variable_fonts/lesson.textproto
  cc-by-sa/knowledge/modules/using_variable_fonts_on_the_web/lessons/factors_that_influence_the_efficiency_of_variable_web_fonts/content.md
  cc-by-sa/knowledge/modules/using_variable_fonts_on_the_web/lessons/factors_that_influence_the_efficiency_of_variable_web_fonts/images/thumbnail.svg
  cc-by-sa/knowledge/modules/using_variable_fonts_on_the_web/lessons/interactive_animations_with_variable_fonts/content.md
  cc-by-sa/knowledge/modules/using_variable_fonts_on_the_web/lessons/interactive_animations_with_variable_fonts/images/4_1.gif
  cc-by-sa/knowledge/modules/using_variable_fonts_on_the_web/lessons/interactive_animations_with_variable_fonts/images/4_2.gif
  cc-by-sa/knowledge/modules/using_variable_fonts_on_the_web/lessons/interactive_animations_with_variable_fonts/images/4_3.gif
  cc-by-sa/knowledge/modules/using_variable_fonts_on_the_web/lessons/interactive_animations_with_variable_fonts/images/4_4a.gif
  cc-by-sa/knowledge/modules/using_variable_fonts_on_the_web/lessons/interactive_animations_with_variable_fonts/images/4_4b.gif
  cc-by-sa/knowledge/modules/using_variable_fonts_on_the_web/lessons/interactive_animations_with_variable_fonts/images/4_5.gif
  cc-by-sa/knowledge/modules/using_variable_fonts_on_the_web/lessons/interactive_animations_with_variable_fonts/images/4_6.gif
  cc-by-sa/knowledge/modules/using_variable_fonts_on_the_web/lessons/interactive_animations_with_variable_fonts/images/thumbnail.svg
  cc-by-sa/knowledge/modules/using_variable_fonts_on_the_web/lessons/optimizing_typographic_space_with_variable_fonts/content.md
  cc-by-sa/knowledge/modules/using_variable_fonts_on_the_web/lessons/optimizing_typographic_space_with_variable_fonts/images/3_1.gif
  cc-by-sa/knowledge/modules/using_variable_fonts_on_the_web/lessons/optimizing_typographic_space_with_variable_fonts/images/3_5.svg
  cc-by-sa/knowledge/modules/using_variable_fonts_on_the_web/lessons/optimizing_typographic_space_with_variable_fonts/images/3_6.svg
  cc-by-sa/knowledge/modules/using_variable_fonts_on_the_web/lessons/optimizing_typographic_space_with_variable_fonts/images/3_7.svg
  cc-by-sa/knowledge/modules/using_variable_fonts_on_the_web/lessons/optimizing_typographic_space_with_variable_fonts/images/3_8.gif
  cc-by-sa/knowledge/modules/using_variable_fonts_on_the_web/lessons/optimizing_typographic_space_with_variable_fonts/images/thumbnail.svg
  cc-by-sa/knowledge/modules/using_variable_fonts_on_the_web/lessons/variable_fonts_are_here/content.md
  cc-by-sa/knowledge/modules/using_variable_fonts_on_the_web/lessons/variable_fonts_are_here/images/thumbnail.svg
  cc-by-sa/knowledge/modules/using_variable_fonts_on_the_web/lessons/variable_fonts_are_here/lesson.textproto
  cc-by-sa/knowledge/modules/using_variable_fonts_on_the_web/lessons/web_font_comparisons_variable_vs_static/content.md
  cc-by-sa/knowledge/modules/using_variable_fonts_on_the_web/lessons/web_font_comparisons_variable_vs_static/images/thumbnail.svg
  cc-by-sa/knowledge/topics/type_history/topic.textproto
Labels: I Knowledge

#5410 primary script on selected families
  ofl/abyssinicasil/METADATA.pb
  ofl/alkalami/METADATA.pb
  ofl/baloo2/METADATA.pb
  ofl/baloobhai2/METADATA.pb
  ofl/baloobhaijaan2/METADATA.pb
  ofl/baloobhaina2/METADATA.pb
  ofl/baloochettan2/METADATA.pb
  ofl/balooda2/METADATA.pb
  ofl/baloopaaji2/METADATA.pb
  ofl/balootamma2/METADATA.pb
  ofl/balootammudu2/METADATA.pb
  ofl/baloothambi2/METADATA.pb
  ofl/bizudgothic/METADATA.pb
  ofl/bizudmincho/METADATA.pb
  ofl/bizudpgothic/METADATA.pb
  ofl/bizudpmincho/METADATA.pb
  ofl/harmattan/METADATA.pb
  ofl/ibmplexsansarabic/METADATA.pb
  ofl/ibmplexsansdevanagari/METADATA.pb
  ofl/ibmplexsanshebrew/METADATA.pb
  ofl/ibmplexsansjp/METADATA.pb
  ofl/ibmplexsanskr/METADATA.pb
  ofl/ibmplexsansthai/METADATA.pb
  ofl/ibmplexsansthailooped/METADATA.pb
  ofl/lateef/METADATA.pb
  ofl/nuosusil/METADATA.pb
  ofl/padauk/METADATA.pb
  ofl/scheherazadenew/METADATA.pb
  ofl/tirobangla/METADATA.pb
  ofl/tirodevanagarihindi/METADATA.pb
  ofl/tirodevanagarimarathi/METADATA.pb
  ofl/tirodevanagarisanskrit/METADATA.pb
  ofl/tirogurmukhi/METADATA.pb
  ofl/tirokannada/METADATA.pb
  ofl/tirotamil/METADATA.pb
  ofl/tirotelugu/METADATA.pb
  ofl/zenantique/METADATA.pb
  ofl/zenantiquesoft/METADATA.pb
  ofl/zenkakugothicantique/METADATA.pb
  ofl/zenkakugothicnew/METADATA.pb
  ofl/zenkurenaido/METADATA.pb
  ofl/zenmarugothic/METADATA.pb
  ofl/zenoldmincho/METADATA.pb
Labels: -- Needs confirmation, I Description/Metadata/OFL

#5439 IBM Plex JP: trying another lang ID
  ofl/ibmplexsansjp/METADATA.pb
Labels: I Description/Metadata/OFL

#5440 IBM Plex Sans KR: correct primary script
  ofl/ibmplexsanskr/METADATA.pb
Labels: I Description/Metadata/OFL

#5441 BIZ + ZEN fonts: corrected primary script
  ofl/bizudgothic/METADATA.pb
  ofl/bizudmincho/METADATA.pb
  ofl/bizudpgothic/METADATA.pb
  ofl/bizudpmincho/METADATA.pb
  ofl/zenantique/METADATA.pb
  ofl/zenantiquesoft/METADATA.pb
  ofl/zenkakugothicantique/METADATA.pb
  ofl/zenkakugothicnew/METADATA.pb
  ofl/zenkurenaido/METADATA.pb
  ofl/zenmarugothic/METADATA.pb
  ofl/zenoldmincho/METADATA.pb
Labels: I Description/Metadata/OFL

#5442 Testing Hani, Hira and Kana primary scripts
  ofl/tsukimirounded/METADATA.pb
  ofl/yujihentaiganaakari/METADATA.pb
  ofl/zcoolkuaile/METADATA.pb
Labels: I Description/Metadata/OFL

#5444 Primary script to ZCOOL fonts (simplified chinese)
  ofl/zcoolkuaile/METADATA.pb
  ofl/zcoolqingkehuangyou/METADATA.pb
  ofl/zcoolxiaowei/METADATA.pb
Labels: - Ready for Review, I Description/Metadata/OFL

#5437 Caroline Short: designer added
  catalog/designers/carolinashort/bio.html
  catalog/designers/carolinashort/carolinashort.png
  catalog/designers/carolinashort/info.pb
Labels: - Ready for Review, I Designer profile

#5187 Noto Sans Saurashtra: Version 2.001; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosanssaurashtra/METADATA.pb
  ofl/notosanssaurashtra/NotoSansSaurashtra-Regular.ttf
  ofl/notosanssaurashtra/OFL.txt
  ofl/notosanssaurashtra/upstream.yaml
Labels: - Ready for Review, I Font Upgrade

#5186 Noto Sans Sora Sompeng: Version 2.101 added
  ofl/notosanssorasompeng/METADATA.pb
  ofl/notosanssorasompeng/NotoSansSoraSompeng[wght].ttf
  ofl/notosanssorasompeng/OFL.txt
  ofl/notosanssorasompeng/upstream.yaml
Labels: - Ready for Review, I Font Upgrade

#5448 Added XROT and YROT (Tilt)
  axisregistry/Lib/axisregistry/data/x_rotation.textproto
  axisregistry/Lib/axisregistry/data/y_rotation.textproto
Labels: - Ready for Review, I Axis Registry

#5476 Add Khojki subset
  ofl/notoserifkhojki/METADATA.pb
Labels: --- to sandbox, I Description/Metadata/OFL, I Small Fix

#5472 Noto Sans Bamum: Version 2.002 added
  ofl/notosansbamum/METADATA.pb
  ofl/notosansbamum/NotoSansBamum[wght].ttf
  ofl/notosansbamum/upstream.yaml
Labels: - Ready for Review, I Font Upgrade

#5461 Fragment Mono : 1.010 added
  ofl/fragmentmono/DESCRIPTION.en_us.html
  ofl/fragmentmono/FragmentMono-Italic.ttf
  ofl/fragmentmono/FragmentMono-Regular.ttf
  ofl/fragmentmono/METADATA.pb
  ofl/fragmentmono/OFL.txt
Labels: - Ready for Review, I New Font

#5465 adding .ttx, .pyc back
  .gitignore
Labels: I Tools / workflow / repo

#5219 Noto Sans Sundanese: Version 2.003 added
  ofl/notosanssundanese/METADATA.pb
  ofl/notosanssundanese/NotoSansSundanese[wght].ttf
  ofl/notosanssundanese/OFL.txt
  ofl/notosanssundanese/upstream.yaml
Labels: --- to sandbox, I Font Upgrade

#5206 Noto Sans Lepcha: Version 2.006; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosanslepcha/METADATA.pb
  ofl/notosanslepcha/NotoSansLepcha-Regular.ttf
  ofl/notosanslepcha/OFL.txt
  ofl/notosanslepcha/upstream.yaml
Labels: --- to sandbox, I Font Upgrade

#5241 Noto Sans Tai Viet: Version 2.003; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosanstaiviet/METADATA.pb
  ofl/notosanstaiviet/NotoSansTaiViet-Regular.ttf
  ofl/notosanstaiviet/OFL.txt
  ofl/notosanstaiviet/upstream.yaml
Labels: -- Needs confirmation, I Font Upgrade

#5199 Noto Sans Zanabazar Square: Version 2.005; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosanszanabazarsquare/METADATA.pb
  ofl/notosanszanabazarsquare/NotoSansZanabazarSquare-Regular.ttf
  ofl/notosanszanabazarsquare/OFL.txt
  ofl/notosanszanabazarsquare/upstream.yaml
Labels: - Ready for Review, I Font Upgrade

#5165 Noto Sans Newa: Version 2.007; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosansnewa/METADATA.pb
  ofl/notosansnewa/NotoSansNewa-Regular.ttf
  ofl/notosansnewa/OFL.txt
  ofl/notosansnewa/upstream.yaml
Labels: --- to sandbox, I Font Upgrade

#5153 Noto Sans Khojki: Version 2.003; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosanskhojki/METADATA.pb
  ofl/notosanskhojki/NotoSansKhojki-Regular.ttf
  ofl/notosanskhojki/OFL.txt
  ofl/notosanskhojki/upstream.yaml
Labels: --- to sandbox, I Font Upgrade

#5478 More SIL primary script
  ofl/davidlibre/METADATA.pb
  ofl/mingzat/METADATA.pb
  ofl/taiheritagepro/METADATA.pb
Labels: - Ready for Review, I Description/Metadata/OFL

#5482 Edu fonts: updated description
  ofl/edunswactfoundation/DESCRIPTION.en_us.html
  ofl/eduqldbeginner/DESCRIPTION.en_us.html
  ofl/edusabeginner/DESCRIPTION.en_us.html
  ofl/edutasbeginner/DESCRIPTION.en_us.html
  ofl/eduvicwantbeginner/DESCRIPTION.en_us.html
Labels: - Ready for Review, I Description/Metadata/OFL
