Repository google/fonts, pull requests merged in 2022-12, with the labels that each got.

#5194 Noto Serif Toto: Version 2.001 added
  ofl/notoseriftoto/DESCRIPTION.en_us.html
  ofl/notoseriftoto/METADATA.pb
  ofl/notoseriftoto/NotoSerifToto[wght].ttf
  ofl/notoseriftoto/OFL.txt
  ofl/notoseriftoto/article/ARTICLE.en_us.html
  ofl/notoseriftoto/upstream.yaml
Labels: - Ready for Review, I New Font

#5220 Noto Sans Tangsa: Version 1.504 added
  ofl/notosanstangsa/DESCRIPTION.en_us.html
  ofl/notosanstangsa/METADATA.pb
  ofl/notosanstangsa/NotoSansTangsa[wght].ttf
  ofl/notosanstangsa/OFL.txt
  ofl/notosanstangsa/article/ARTICLE.en_us.html
  ofl/notosanstangsa/upstream.yaml
Labels: - Ready for Review, I New Font

#5654 Sofia Sans Condensed: Version 4.100 added
  ofl/sofiasanscondensed/METADATA.pb
Labels: I Description/Metadata/OFL

#5655 Sofia Sans Extra Condensed: Version 4.100 added
  ofl/sofiasansextracondensed/METADATA.pb
Labels: I Description/Metadata/OFL

#5522 Advent Pro: Version 3.000 added
  ofl/adventpro/AdventPro-Bold.ttf
  ofl/adventpro/AdventPro-ExtraLight.ttf
  ofl/adventpro/AdventPro-Italic[wdth,wght].ttf
  ofl/adventpro/AdventPro-Light.ttf
  ofl/adventpro/AdventPro-Medium.ttf
  ofl/adventpro/AdventPro-Regular.ttf
  ofl/adventpro/AdventPro-SemiBold.ttf
  ofl/adventpro/AdventPro-Thin.ttf
  ofl/adventpro/AdventPro[wdth,wght].ttf
  ofl/adventpro/DESCRIPTION.en_us.html
  ofl/adventpro/METADATA.pb
  ofl/adventpro/OFL.txt
  ofl/adventpro/upstream.yaml
Labels: III Expand glyphset, III VF Replacement, --- to sandbox, I Font Upgrade

#5660 DM Serif Display: Description and metadata updated
  ofl/dmserifdisplay/DESCRIPTION.en_us.html
  ofl/dmserifdisplay/METADATA.pb
Labels: - Ready for Review, I Description/Metadata/OFL

#5661 Dm Serif Text: description and metadata updated
  ofl/dmseriftext/DESCRIPTION.en_us.html
  ofl/dmseriftext/METADATA.pb
Labels: - Ready for Review, I Description/Metadata/OFL

#5663 Hanken Grotesk designer added to Metadata
  ofl/hankengrotesk/METADATA.pb
Labels: --- to sandbox, I Description/Metadata/OFL

#5664 Open Sans Condensed: removed directory
  apache/opensanscondensed/DESCRIPTION.en_us.html
  apache/opensanscondensed/LICENSE.txt
  apache/opensanscondensed/METADATA.pb
  apache/opensanscondensed/OpenSansCondensed-Bold.ttf
  apache/opensanscondensed/OpenSansCondensed-Light.ttf
  apache/opensanscondensed/OpenSansCondensed-LightItalic.ttf
Labels: I Tools / workflow / repo

#5570 Add minisite_url metadata for Arapey, Fraunces, Gulzar, Recursive, Space Grotesk
  ofl/fraunces/METADATA.pb
  ofl/gulzar/METADATA.pb
  ofl/recursive/METADATA.pb
  ofl/spacegrotesk/METADATA.pb
Labels: - Ready for Review, I Description/Metadata/OFL

#5650 Tilt Neon: Version 1.000 added
  ofl/tiltneon/DESCRIPTION.en_us.html
  ofl/tiltneon/METADATA.pb
  ofl/tiltneon/OFL.txt
  ofl/tiltneon/TiltNeon[XROT,YROT].ttf
  ofl/tiltneon/upstream.yaml
Labels: --- to sandbox, I New Font, III Custom axes

#5651 Tilt Prism: Version 1.000 added
  ofl/tiltprism/DESCRIPTION.en_us.html
  ofl/tiltprism/METADATA.pb
  ofl/tiltprism/OFL.txt
  ofl/tiltprism/TiltPrism[XROT,YROT].ttf
  ofl/tiltprism/upstream.yaml
Labels: --- to sandbox, I New Font, III Custom axes

#5652 Tilt Warp: Version 1.000 added
  ofl/tiltwarp/DESCRIPTION.en_us.html
  ofl/tiltwarp/METADATA.pb
  ofl/tiltwarp/OFL.txt
  ofl/tiltwarp/TiltWarp[XROT,YROT].ttf
  ofl/tiltwarp/upstream.yaml
Labels: - Ready for Review, I New Font, III Custom axes

#5674 Make small markdown fixes to recent GFK content
  cc-by-sa/knowledge/modules/choosing_type/lessons/pairing_typefaces_based_on_their_construction_using_the_font_matrix/content.md
  cc-by-sa/knowledge/modules/using_type/lessons/from_type_to_logotype/content.md
Labels: I Small Fix, I Knowledge

#5665 GFK Q4 fast-follows
  cc-by-sa/knowledge/contributors.textproto
  cc-by-sa/knowledge/glossary/terms/cyrillic/content.md
  cc-by-sa/knowledge/glossary/terms/cyrillic/images/thumbnail.svg
  cc-by-sa/knowledge/modules/history_of_type/lessons/modern_type/content.md
  cc-by-sa/knowledge/modules/readability_and_accessibility/lessons/how_type_influences_readability/content.md
  cc-by-sa/knowledge/modules/readability_and_accessibility/lessons/how_type_influences_readability/lesson.textproto
  cc-by-sa/knowledge/modules/readability_and_accessibility/lessons/introducing_accessibility_in_typography/lesson.textproto
  cc-by-sa/knowledge/modules/readability_and_accessibility/module.textproto
  cc-by-sa/knowledge/modules/using_variable_fonts_on_the_web/lessons/interactive_animations_with_variable_fonts/content.md
Labels: I Small Fix, I Knowledge

#5672 amiri: 1.000 added
  ofl/amiri/Amiri-Bold.ttf
  ofl/amiri/Amiri-BoldItalic.ttf
  ofl/amiri/Amiri-Italic.ttf
  ofl/amiri/Amiri-Regular.ttf
  ofl/amiri/DESCRIPTION.en_us.html
  ofl/amiri/METADATA.pb
  ofl/amiri/OFL.txt
Labels: I Font Upgrade

#5667 Kumbh Sans: Version 1.004 added
  ofl/kumbhsans/KumbhSans[YOPQ,wght].ttf
  ofl/kumbhsans/KumbhSans[wght].ttf
  ofl/kumbhsans/METADATA.pb
  ofl/kumbhsans/OFL.txt
  ofl/kumbhsans/upstream.yaml
Labels: III Expand styles, - Ready for Review, I Font Upgrade, III Custom axes

#5669 Adding Hanken Grotesk designers
  catalog/designers/alfredomarcopradil/alfredomarcopradil.png
  catalog/designers/alfredomarcopradil/bio.html
  catalog/designers/alfredomarcopradil/info.pb
  catalog/designers/hankendesignco/bio.html
  catalog/designers/hankendesignco/hankendesignco.png
  catalog/designers/hankendesignco/info.pb
Labels: --- to sandbox, I Designer profile

#5676 Padyakke Expanded One: Version 1.500; ttfautohint (v1.8.4.7-5d5b) added
  ofl/padyakkeexpandedone/DESCRIPTION.en_us.html
  ofl/padyakkeexpandedone/METADATA.pb
  ofl/padyakkeexpandedone/OFL.txt
  ofl/padyakkeexpandedone/PadyakkeExpandedOne-Regular.ttf
  ofl/padyakkeexpandedone/upstream.yaml
Labels: --- to sandbox, I New Font, II Indic / Brahmic / Thai / Tai

#5666 Inter Tight: Version 3.003 added
  ofl/intertight/InterTight-Italic[wght].ttf
  ofl/intertight/InterTight[wght].ttf
  ofl/intertight/METADATA.pb
  ofl/intertight/upstream.yaml
Labels: - Ready for Review, I Small Fix, III Improve rendering / layout

#5516 Fix BioRhyme naming.
  ofl/biorhyme/METADATA.pb
  ofl/biorhymeexpanded/METADATA.pb
Labels: I Description/Metadata/OFL

#5686 Alex Brush: Version 1.110; ttfautohint (v1.8.4.7-5d5b) added
  ofl/alexbrush/AlexBrush-Regular.ttf
  ofl/alexbrush/METADATA.pb
  ofl/alexbrush/upstream.yaml
Labels: - Ready for Review, I Font Upgrade, III Improve rendering / layout

#5710 Apply requested article edits.
  ofl/anekbangla/article/ARTICLE.en_us.html
  ofl/anekdevanagari/article/ARTICLE.en_us.html
  ofl/anekgujarati/article/ARTICLE.en_us.html
  ofl/anekgurmukhi/article/ARTICLE.en_us.html
  ofl/anekkannada/article/ARTICLE.en_us.html
  ofl/aneklatin/article/ARTICLE.en_us.html
  ofl/anekmalayalam/article/ARTICLE.en_us.html
  ofl/anekodia/article/ARTICLE.en_us.html
  ofl/anektamil/article/ARTICLE.en_us.html
  ofl/anektelugu/article/ARTICLE.en_us.html
  ofl/atkinsonhyperlegible/article/ARTICLE.en_us.html
  ofl/bizudgothic/article/ARTICLE.en_us.html
  ofl/bizudmincho/article/ARTICLE.en_us.html
  ofl/bizudpgothic/article/ARTICLE.en_us.html
  ofl/bizudpmincho/article/ARTICLE.en_us.html
  ofl/brygada1918/article/ARTICLE.en_us.html
  ofl/brygada1918/article/hero.png
  ofl/edunswactfoundation/article/ARTICLE.en_us.html
  ofl/eduqldbeginner/article/ARTICLE.en_us.html
  ofl/edusabeginner/article/ARTICLE.en_us.html
  ofl/edutasbeginner/article/ARTICLE.en_us.html
  ofl/eduvicwantbeginner/article/ARTICLE.en_us.html
  ofl/expletussans/article/ARTICLE.en_us.html
  ofl/flowblock/article/ARTICLE.en_us.html
  ofl/flowcircular/article/ARTICLE.en_us.html
  ofl/flowrounded/article/ARTICLE.en_us.html
  ofl/fraunces/article/ARTICLE.en_us.html
  ofl/lexend/article/ARTICLE.en_us.html
  ofl/questrial/article/ARTICLE.en_us.html
  ofl/radiocanada/article/ARTICLE.en_us.html
  ofl/redacted/article/ARTICLE.en_us.html
  ofl/redactedscript/article/ARTICLE.en_us.html
  ofl/robotoflex/article/ARTICLE.en_us.html
  ofl/robotoserif/article/ARTICLE.en_us.html
  ofl/spacemono/article/ARTICLE.en_us.html
  ofl/spectral/article/ARTICLE.en_us.html
  ofl/tirobangla/article/ARTICLE.en_us.html
  ofl/tirodevanagarihindi/article/ARTICLE.en_us.html
  ofl/tirodevanagarimarathi/article/ARTICLE.en_us.html
  ofl/tirodevanagarisanskrit/article/ARTICLE.en_us.html
  ofl/tirogurmukhi/article/ARTICLE.en_us.html
  ofl/tirokannada/article/ARTICLE.en_us.html
  ofl/tirotamil/article/ARTICLE.en_us.html
  ofl/tirotelugu/article/ARTICLE.en_us.html
  ofl/urbanist/article/ARTICLE.en_us.html
  ofl/zenantique/article/ARTICLE.en_us.html
  ofl/zenantiquesoft/article/ARTICLE.en_us.html
  ofl/zendots/article/ARTICLE.en_us.html
  ofl/zenkakugothicantique/article/ARTICLE.en_us.html
  ofl/zenkakugothicnew/article/ARTICLE.en_us.html
  ofl/zenkurenaido/article/ARTICLE.en_us.html
  ofl/zenloop/article/ARTICLE.en_us.html
  ofl/zenmarugothic/article/ARTICLE.en_us.html
  ofl/zenoldmincho/article/ARTICLE.en_us.html
  ofl/zentokyozoo/article/ARTICLE.en_us.html
Labels: --- to sandbox

#5715 Hanken Metadata designers rearranged
  ofl/hankengrotesk/METADATA.pb
Labels: --- to sandbox, I Description/Metadata/OFL

#5718 Baskervville: Version 1.002; ttfautohint (v1.8.4.7-5d5b) added
  ofl/baskervville/Baskervville-Italic.ttf
  ofl/baskervville/Baskervville-Regular.ttf
  ofl/baskervville/METADATA.pb
  ofl/baskervville/upstream.yaml
Labels: - Ready for Review, I Small Fix, III Improve rendering / layout

#5716 Allura: Version 1.110 added
  ofl/allura/Allura-Regular.ttf
  ofl/allura/METADATA.pb
  ofl/allura/upstream.yaml
Labels: - Ready for Review, I Small Fix, III Improve rendering / layout

#5297 Solitreo: Version 1.000; ttfautohint (v1.8.4.7-5d5b) added
  ofl/solitreo/DESCRIPTION.en_us.html
  ofl/solitreo/METADATA.pb
  ofl/solitreo/OFL.txt
  ofl/solitreo/Solitreo-Regular.ttf
  ofl/solitreo/upstream.yaml
Labels: - Ready for Review, I New Font
