Repository google/fonts, pull requests merged in 2022-06, with the labels that each got.

#4723 Akshar: Version 1.100 added
  ofl/akshar/Akshar[wght].ttf
  ofl/akshar/DESCRIPTION.en_us.html
  ofl/akshar/METADATA.pb
  ofl/akshar/upstream.yaml
Labels: --- to sandbox, I Font Upgrade, III Improve rendering, II Indic / Brahmic / Tai

#4721 Mingzat: Version 1.100 added
  ofl/mingzat/DESCRIPTION.en_us.html
  ofl/mingzat/METADATA.pb
  ofl/mingzat/Mingzat-Regular.ttf
  ofl/mingzat/OFL.txt
  ofl/mingzat/upstream.yaml
Labels: --- to sandbox, I New Font, II Indic / Brahmic / Thai

#4733 Finlandica: Version 1.063 added
  ofl/finlandica/Finlandica-Italic[wght].ttf
  ofl/finlandica/Finlandica[wght].ttf
  ofl/finlandica/METADATA.pb
Labels: --- to sandbox, I New Font

#4737 Designer added: Helsinki Type Studio
  catalog/designers/helsinkitypestudio/bio.html
  catalog/designers/helsinkitypestudio/helsinkitypestudio.png
  catalog/designers/helsinkitypestudio/info.pb
Labels: --- to sandbox, I Designer profile

#4738 Familjen Grotesk: Version 2.001 added
  ofl/familjengrotesk/FamiljenGrotesk-Italic[wght].ttf
  ofl/familjengrotesk/FamiljenGrotesk[wght].ttf
  ofl/familjengrotesk/METADATA.pb
  ofl/familjengrotesk/upstream.yaml
Labels: --- to sandbox, III Small Fix

#4741 Designer added: Jaakko Suomalainen
  catalog/jaakkosuomalainen/bio.html
  catalog/jaakkosuomalainen/info.pb
  catalog/jaakkosuomalainen/jaakkosuomalainen.png
Labels: --- to sandbox, I Designer profile

#4740 Designer added: Juho Hiilivirta
  catalog/designers/juhohiilivirta/bio.html
  catalog/designers/juhohiilivirta/info.pb
  catalog/designers/juhohiilivirta/juhohiilivirta.png
Labels: --- to sandbox, I Designer profile

#4739 Designer added: Niklas Ekholm
  catalog/designers/niklasekholm/bio.html
  catalog/designers/niklasekholm/info.pb
  catalog/designers/niklasekholm/niklasekholm.png
Labels: --- to sandbox, I Designer profile

#4720 Gantari: Version 1.000 added
  ofl/gantari/DESCRIPTION.en_us.html
  ofl/gantari/Gantari-Italic[wght].ttf
  ofl/gantari/Gantari[wght].ttf
  ofl/gantari/METADATA.pb
  ofl/gantari/OFL.txt
  ofl/gantari/upstream.yaml
Labels: --- to sandbox, I New Font

#4735 Designer added: lafontype
  catalog/designers/lafontype/bio.html
  catalog/designers/lafontype/info.pb
  catalog/designers/lafontype/lafontype.png
Labels: --- to sandbox, I Designer profile

#4722 normalized all chinese METADATA.pb
  ofl/notosanshk/METADATA.pb
  ofl/notosanssc/METADATA.pb
  ofl/notosanstc/METADATA.pb
  ofl/notoserifsc/METADATA.pb
  ofl/notoseriftc/METADATA.pb
Labels: - Ready for Review, I Description/Metadata/OFL

#4751 Noto Serif CJK subsets aligned to Noto Sans CJK
  ofl/notoserifhk/METADATA.pb
  ofl/notoserifjp/METADATA.pb
  ofl/notoserifkr/METADATA.pb
  ofl/notoserifsc/METADATA.pb
  ofl/notoseriftc/METADATA.pb
Labels: - Ready for Review, I Description/Metadata/OFL

#4752 Jaakko Suomalainen : moved to proper dir
  catalog/designers/jaakkosuomalainen/bio.html
  catalog/designers/jaakkosuomalainen/info.pb
  catalog/designers/jaakkosuomalainen/jaakkosuomalainen.png
Labels: --- to sandbox, I Designer profile

#4762 Edu QLD Beginners: Version 1.001 added
  ofl/eduqldbeginners/DESCRIPTION.en_us.html
  ofl/eduqldbeginners/EduQLDBeginners[wght].ttf
  ofl/eduqldbeginners/METADATA.pb
  ofl/eduqldbeginners/OFL.txt
  ofl/eduqldbeginners/upstream.yaml
Labels: --- to sandbox, I New Font

#4763 Edu SA Beginner: Version 1.001 added
  ofl/edusabeginner/DESCRIPTION.en_us.html
  ofl/edusabeginner/EduSABeginner[wght].ttf
  ofl/edusabeginner/METADATA.pb
  ofl/edusabeginner/OFL.txt
  ofl/edusabeginner/upstream.yaml
Labels: --- to sandbox, I New Font

#4766 Edu VIC WA NT Beginner: Version 1.001 added
  ofl/eduvicwantbeginner/DESCRIPTION.en_us.html
  ofl/eduvicwantbeginner/EduVICWANTBeginner[wght].ttf
  ofl/eduvicwantbeginner/METADATA.pb
  ofl/eduvicwantbeginner/OFL.txt
  ofl/eduvicwantbeginner/upstream.yaml
Labels: --- to sandbox, I New Font

#4765 Edu TAS Beginner: Version 1.001 added
  ofl/edutasbeginner/DESCRIPTION.en_us.html
  ofl/edutasbeginner/EduTASBeginner[wght].ttf
  ofl/edutasbeginner/METADATA.pb
  ofl/edutasbeginner/OFL.txt
  ofl/edutasbeginner/upstream.yaml
Labels: --- to sandbox, I New Font

#4756 Albert Sans: Version 1.025 added
  ofl/albertsans/AlbertSans-Italic[wght].ttf
  ofl/albertsans/AlbertSans[wght].ttf
  ofl/albertsans/DESCRIPTION.en_us.html
  ofl/albertsans/METADATA.pb
  ofl/albertsans/OFL.txt
  ofl/albertsans/upstream.yaml
Labels: --- to sandbox, I New Font

#4798 Rubik Maze: Version 2.200 added
  ofl/rubikmaze/DESCRIPTION.en_us.html
  ofl/rubikmaze/METADATA.pb
  ofl/rubikmaze/OFL.txt
  ofl/rubikmaze/RubikMaze-Regular.ttf
  ofl/rubikmaze/upstream.yaml
Labels: - Ready for Review, I New Font

#4796 Rubik Iso: Version 2.200 added
  ofl/rubikiso/DESCRIPTION.en_us.html
  ofl/rubikiso/METADATA.pb
  ofl/rubikiso/OFL.txt
  ofl/rubikiso/RubikIso-Regular.ttf
  ofl/rubikiso/upstream.yaml
Labels: - Ready for Review, I New Font

#4795 Rubik Distressed: Version 2.200 added
  ofl/rubikdistressed/DESCRIPTION.en_us.html
  ofl/rubikdistressed/METADATA.pb
  ofl/rubikdistressed/OFL.txt
  ofl/rubikdistressed/RubikDistressed-Regular.ttf
  ofl/rubikdistressed/upstream.yaml
Labels: --- to sandbox, I New Font

#4794 Rubik Dirt: Version 2.200 added
  ofl/rubikdirt/DESCRIPTION.en_us.html
  ofl/rubikdirt/METADATA.pb
  ofl/rubikdirt/OFL.txt
  ofl/rubikdirt/RubikDirt-Regular.ttf
  ofl/rubikdirt/upstream.yaml
Labels: --- to sandbox, I New Font

#4793 Rubik Burned: Version 2.200 added
  ofl/rubikburned/DESCRIPTION.en_us.html
  ofl/rubikburned/METADATA.pb
  ofl/rubikburned/OFL.txt
  ofl/rubikburned/RubikBurned-Regular.ttf
  ofl/rubikburned/upstream.yaml
Labels: --- to sandbox, I New Font

#4797 Rubik Marker Hatch: Version 2.200 added
  ofl/rubikmarkerhatch/DESCRIPTION.en_us.html
  ofl/rubikmarkerhatch/METADATA.pb
  ofl/rubikmarkerhatch/OFL.txt
  ofl/rubikmarkerhatch/RubikMarkerHatch-Regular.ttf
  ofl/rubikmarkerhatch/upstream.yaml
Labels: --- to sandbox, I New Font

#4767 Exo 2: Version 2.001 added
  ofl/exo2/METADATA.pb
  ofl/exo2/upstream.yaml
Labels: --- to sandbox, I Font Upgrade

#4770 Belleza: Version 1.003; ttfautohint (v1.8.4.7-5d5b) added
  ofl/belleza/Belleza-Regular.ttf
  ofl/belleza/DESCRIPTION.en_us.html
  ofl/belleza/METADATA.pb
  ofl/belleza/OFL.txt
  ofl/belleza/upstream.yaml
Labels: III Expand glyphset, --- to sandbox, I Font Upgrade

#4769 Alkalami: Version 2.000 added
  ofl/alkalami/Alkalami-Regular.ttf
  ofl/alkalami/DESCRIPTION.en_us.html
  ofl/alkalami/METADATA.pb
  ofl/alkalami/OFL.txt
  ofl/alkalami/upstream.yaml
Labels: - Ready for Review, I New Font, II Arabic

#4787 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: I Tools / workflow / repo

#4635 Updating copy to reflect Figma’s support of VFs
  cc-by-sa/knowledge/modules/using_type/lessons/designing_with_variable_fonts_in_desktop_apps/content.md
Labels: -- Needs Dave's opinion, - Ready for Review, I Knowledge

#4759 Alumni Sans Pinstripe: Version 1.010; ttfautohint (v1.8.4.7-5d5b) added
  ofl/alumnisanspinstripe/AlumniSansPinstripe-Italic.ttf
  ofl/alumnisanspinstripe/AlumniSansPinstripe-Regular.ttf
  ofl/alumnisanspinstripe/DESCRIPTION.en_us.html
  ofl/alumnisanspinstripe/METADATA.pb
  ofl/alumnisanspinstripe/OFL.txt
  ofl/alumnisanspinstripe/upstream.yaml
Labels: -- Needs confirmation, I New Font

#4668 Restore missing marks on Thai samples
  lang/Lib/gflanguages/data/languages/th_Thai.textproto
Labels: - Ready for Review, I API / Website / Platform

#4823 Edu VIC WA NT Beginner: Version 1.002 added; Edu QLD Beginners: Version 1.002 added; Edu NSW ACT Foundation: Version 1.002 added; Edu SA Beginner: Version 1.002 added; Edu TAS Beginner: Version 1.002 added
  ofl/edunswactfoundation/EduNSWACTFoundation[wght].ttf
  ofl/edunswactfoundation/METADATA.pb
  ofl/edunswactfoundation/upstream.yaml
  ofl/eduqldbeginners/DESCRIPTION.en_us.html
  ofl/eduqldbeginners/EduQLDBeginners[wght].ttf
  ofl/eduqldbeginners/METADATA.pb
  ofl/eduqldbeginners/OFL.txt
  ofl/eduqldbeginners/upstream.yaml
  ofl/edusabeginner/EduSABeginner[wght].ttf
  ofl/edusabeginner/METADATA.pb
  ofl/edusabeginner/upstream.yaml
  ofl/edutasbeginner/EduTASBeginner[wght].ttf
  ofl/edutasbeginner/METADATA.pb
  ofl/edutasbeginner/upstream.yaml
  ofl/eduvicwantbeginner/EduVICWANTBeginner[wght].ttf
  ofl/eduvicwantbeginner/METADATA.pb
  ofl/eduvicwantbeginner/upstream.yaml
Labels: III Small Fix

#4831 Edu VIC WA NT Beginner: Version 1.003 added; Edu QLD Beginner: Version 1.003 added; Edu NSW ACT Foundation: Version 1.003 added; Edu TAS Beginner: Version 1.003 added; Edu SA Beginner: Version 1.003 added
  ofl/edunswactfoundation/EduNSWACTFoundation[wght].ttf
  ofl/edunswactfoundation/METADATA.pb
  ofl/eduqldbeginner/EduQLDBeginner[wght].ttf
  ofl/eduqldbeginner/METADATA.pb
  ofl/eduqldbeginner/upstream.yaml
  ofl/edusabeginner/EduSABeginner[wght].ttf
  ofl/edusabeginner/METADATA.pb
  ofl/edutasbeginner/EduTASBeginner[wght].ttf
  ofl/edutasbeginner/METADATA.pb
  ofl/eduvicwantbeginner/EduVICWANTBeginner[wght].ttf
  ofl/eduvicwantbeginner/METADATA.pb
Labels: - Ready for Review, III Small Fix

#4670 DynaPuff: Version 2.000 added
  ofl/dynapuff/DESCRIPTION.en_us.html
  ofl/dynapuff/DynaPuff[wdth,wght].ttf
  ofl/dynapuff/METADATA.pb
  ofl/dynapuff/OFL.txt
  ofl/dynapuff/upstream.yaml
Labels: --- to sandbox, I New Font

#4842 Borna Izadpanah: bio updated (Gulzar)
  catalog/designers/bornaizadpanah/bio.html
  catalog/designers/bornaizadpanah/borna_izadpanah.png
  catalog/designers/bornaizadpanah/bornaizadpanah.png
  catalog/designers/bornaizadpanah/info.pb
Labels: --- to sandbox, I Designer profile, III Small Fix

#4837 Noto Serif Dogra: Version 1.005 added
  ofl/notoserifdogra/METADATA.pb
  ofl/notoserifdogra/NotoSerifDogra-Regular.ttf
  ofl/notoserifdogra/OFL.txt
  ofl/notoserifdogra/article/ARTICLE.en_us.html
  ofl/notoserifdogra/upstream.yaml
Labels: z_Noto, - Ready for Review, I Font Upgrade, II Indic / Brahmic / Thai

#4838 Noto Sans Buhid: Version 2.001 added
  ofl/notosansbuhid/METADATA.pb
  ofl/notosansbuhid/NotoSansBuhid-Regular.ttf
  ofl/notosansbuhid/OFL.txt
  ofl/notosansbuhid/article/ARTICLE.en_us.html
  ofl/notosansbuhid/upstream.yaml
Labels: z_Noto, --- to sandbox, I Font Upgrade, II Indic / Brahmic / Thai

#4822 Noto Serif Ahom: Version 2.005 added
  ofl/notoserifahom/METADATA.pb
  ofl/notoserifahom/NotoSerifAhom-Regular.ttf
  ofl/notoserifahom/OFL.txt
  ofl/notoserifahom/article/ARTICLE.en_us.html
  ofl/notoserifahom/upstream.yaml
Labels: z_Noto, --- to sandbox, I Font Upgrade, II Indic / Brahmic / Thai / Tai

#4839 Noto Sans Avestan: Version 2.002 added
  ofl/notosansavestan/METADATA.pb
  ofl/notosansavestan/NotoSansAvestan-Regular.ttf
  ofl/notosansavestan/OFL.txt
  ofl/notosansavestan/article/ARTICLE.en_us.html
  ofl/notosansavestan/upstream.yaml
Labels: z_Noto, --- to sandbox, I Font Upgrade, II Arabic
