Repository google/fonts, pull requests merged in 2022-05, with the labels that each got.

#4578 GFK vf and param edits
  cc-by-sa/knowledge/glossary/terms/optical_size_axis/content.md
  cc-by-sa/knowledge/glossary/terms/parametric_axis/content.md
  cc-by-sa/knowledge/modules/using_type/lessons/introducing_parametric_axes/images/introducing_parametric_axes_2.svg
  cc-by-sa/knowledge/modules/using_type/lessons/introducing_parametric_axes/images/thumbnail.svg
  cc-by-sa/knowledge/modules/using_type/lessons/introducing_parametric_axes/lesson.textproto
  cc-by-sa/knowledge/modules/using_type/lessons/styling_type_on_the_web_with_variable_fonts/lesson.textproto
Labels: --- to sandbox

#4587 Radio Canada: Version 2.101 added
  ofl/radiocanada/METADATA.pb
  ofl/radiocanada/RadioCanada-Italic[wdth,wght].ttf
  ofl/radiocanada/RadioCanada[wdth,wght].ttf
Labels: - Ready for Review, III Small Fix, III Improve rendering

#4592 Radio Canada: Version 2.102 added
  ofl/radiocanada/METADATA.pb
  ofl/radiocanada/RadioCanada-Italic[wdth,wght].ttf
  ofl/radiocanada/RadioCanada[wdth,wght].ttf
Labels: - Ready for Review, III Small Fix

#4622 GFK broken URL fixes
  cc-by-sa/knowledge/glossary/terms/grade/content.md
  cc-by-sa/knowledge/glossary/terms/grade_axis/content.md
  cc-by-sa/knowledge/glossary/terms/hierarchy/content.md
  cc-by-sa/knowledge/glossary/terms/ordinals/content.md
  cc-by-sa/knowledge/glossary/terms/overshoot/content.md
  cc-by-sa/knowledge/glossary/terms/superscript_subscript/content.md
  cc-by-sa/knowledge/glossary/terms/x_height/content.md
  cc-by-sa/knowledge/glossary/terms/yopq_axis/content.md
  cc-by-sa/knowledge/modules/using_type/lessons/breaking_the_rules/content.md
Labels: --- to sandbox

#4637 Kdam Thmor Pro: Version 1.003; ttfautohint (v1.8.4.7-5d5b) added
  ofl/kdamthmorpro/DESCRIPTION.en_us.html
  ofl/kdamthmorpro/KdamThmorPro-Regular.ttf
  ofl/kdamthmorpro/METADATA.pb
  ofl/kdamthmorpro/OFL.txt
  ofl/kdamthmorpro/upstream.yaml
Labels: - Ready for Review, I New Font

#4615 Aref Ruqaa Ink: Version 1.005 added
  ofl/arefruqaaink/ArefRuqaaInk-Bold.ttf
  ofl/arefruqaaink/ArefRuqaaInk-Regular.ttf
  ofl/arefruqaaink/METADATA.pb
  ofl/arefruqaaink/upstream.yaml
Labels: - Ready for Review, I New Font, II Arabic, II Color font

#4632 4628 review removed links
  cc-by-sa/knowledge/glossary/terms/contrast/content.md
  cc-by-sa/knowledge/glossary/terms/grade_axis/content.md
Labels: - Ready for Review, I Knowledge

#4643 Designer added: Paolo Biagini
  catalog/designers/paolobiagini/bio.html
  catalog/designers/paolobiagini/info.pb
  catalog/designers/paolobiagini/paolobiagini.png
Labels: --- to sandbox, I Designer profile

#4645 Designer added: Luke Prowse
  catalog/designers/lukeprowse/bio.html
  catalog/designers/lukeprowse/info.pb
Labels: - Ready for Review, I Designer profile

#4650 CJK metadata fixes
  ofl/notosanshk/METADATA.pb
  ofl/notosansjp/METADATA.pb
  ofl/notosanskr/METADATA.pb
Labels: II CJK, - Ready for Review, III Small Fix

#4649 Kantumruy Pro: Version 1.001 added
  ofl/kantumruypro/DESCRIPTION.en_us.html
  ofl/kantumruypro/KantumruyPro-Italic[wght].ttf
  ofl/kantumruypro/KantumruyPro[wght].ttf
  ofl/kantumruypro/METADATA.pb
  ofl/kantumruypro/OFL.txt
  ofl/kantumruypro/upstream.yaml
Labels: --- to sandbox, I New Font

#4651 Tai Heritage Pro: Version 2.600 added
  ofl/taiheritagepro/DESCRIPTION.en_us.html
  ofl/taiheritagepro/METADATA.pb
  ofl/taiheritagepro/OFL.txt
  ofl/taiheritagepro/TaiHeritagePro-Bold.ttf
  ofl/taiheritagepro/TaiHeritagePro-Regular.ttf
  ofl/taiheritagepro/upstream.yaml
Labels: - Ready for Review, I New Font

#4667 Blaka Ink: Version 1.001; ttfautohint (v1.8.4.7-5d5b) added
  ofl/blaka/DESCRIPTION.en_us.html
  ofl/blakahollow/DESCRIPTION.en_us.html
  ofl/blakaink/BlakaInk-Regular.ttf
  ofl/blakaink/DESCRIPTION.en_us.html
  ofl/blakaink/METADATA.pb
  ofl/blakaink/OFL.txt
  ofl/blakaink/upstream.yaml
Labels: --- to sandbox, I New Font, II Arabic, II Color font

#4666 Finlandica: Version 1.062 added
  ofl/finlandica/DESCRIPTION.en_us.html
  ofl/finlandica/Finlandica-Italic[wght].ttf
  ofl/finlandica/Finlandica[wght].ttf
  ofl/finlandica/METADATA.pb
  ofl/finlandica/OFL.txt
  ofl/finlandica/upstream.yaml
Labels: --- to sandbox, I New Font

#4658 Andika: Version 6.101 added
  ofl/andika/DESCRIPTION.en_us.html
  ofl/andika/METADATA.pb
Labels: - Ready for Review, I Description/Metadata/OFL

#4656 Public Sans: Version 2.001 added
  ofl/publicsans/DESCRIPTION.en_us.html
  ofl/publicsans/METADATA.pb
  ofl/publicsans/OFL.txt
  ofl/publicsans/PublicSans-Italic[wght].ttf
  ofl/publicsans/PublicSans[wght].ttf
  ofl/publicsans/upstream.yaml
Labels: III VF Replacement, --- to sandbox, I Font Upgrade

#4659 Charis SIL: Version 6.101 added
  ofl/charissil/CharisSIL-Bold.ttf
  ofl/charissil/CharisSIL-BoldItalic.ttf
  ofl/charissil/CharisSIL-Italic.ttf
  ofl/charissil/CharisSIL-Regular.ttf
  ofl/charissil/DESCRIPTION.en_us.html
  ofl/charissil/METADATA.pb
  ofl/charissil/OFL.txt
  ofl/charissil/upstream.yaml
Labels: --- to sandbox, I New Font

#4662 Gentium Plus: Version 6.101 added
  ofl/gentiumplus/DESCRIPTION.en_us.html
  ofl/gentiumplus/GentiumPlus-Bold.ttf
  ofl/gentiumplus/GentiumPlus-BoldItalic.ttf
  ofl/gentiumplus/GentiumPlus-Italic.ttf
  ofl/gentiumplus/GentiumPlus-Regular.ttf
  ofl/gentiumplus/METADATA.pb
  ofl/gentiumplus/OFL.txt
  ofl/gentiumplus/upstream.yaml
Labels: --- to sandbox, I New Font

#4663 Gentium Plus Book: Version 6.101 added
  ofl/gentiumplusbook/DESCRIPTION.en_us.html
  ofl/gentiumplusbook/GentiumBookPlus-Bold.ttf
  ofl/gentiumplusbook/GentiumBookPlus-BoldItalic.ttf
  ofl/gentiumplusbook/GentiumBookPlus-Italic.ttf
  ofl/gentiumplusbook/GentiumBookPlus-Regular.ttf
  ofl/gentiumplusbook/METADATA.pb
  ofl/gentiumplusbook/OFL.txt
  ofl/gentiumplusbook/upstream.yaml
Labels: --- to sandbox, I New Font

#4624 Update GFK Glossary entries
  cc-by-sa/knowledge/glossary/terms/casual_axis/content.md
  cc-by-sa/knowledge/glossary/terms/cursive_axis/content.md
  cc-by-sa/knowledge/glossary/terms/fill_axis/content.md
  cc-by-sa/knowledge/glossary/terms/grade_axis/content.md
  cc-by-sa/knowledge/glossary/terms/italic_axis/content.md
  cc-by-sa/knowledge/glossary/terms/monospace_axis/content.md
  cc-by-sa/knowledge/glossary/terms/optical_size_axis/content.md
  cc-by-sa/knowledge/glossary/terms/parametric_axis/content.md
  cc-by-sa/knowledge/glossary/terms/slant_axis/content.md
  cc-by-sa/knowledge/glossary/terms/softness_axis/content.md
  cc-by-sa/knowledge/glossary/terms/weight_axis/content.md
  cc-by-sa/knowledge/glossary/terms/width_axis/content.md
  cc-by-sa/knowledge/glossary/terms/wonky_axis/content.md
  cc-by-sa/knowledge/glossary/terms/xopq_axis/content.md
  cc-by-sa/knowledge/glossary/terms/xtra_axis/content.md
  cc-by-sa/knowledge/glossary/terms/yopq_axis/content.md
  cc-by-sa/knowledge/glossary/terms/ytas_axis/content.md
  cc-by-sa/knowledge/glossary/terms/ytde_axis/content.md
  cc-by-sa/knowledge/glossary/terms/ytfi_axis/content.md
  cc-by-sa/knowledge/glossary/terms/ytlc_axis/content.md
  cc-by-sa/knowledge/glossary/terms/ytuc_axis/content.md
Labels: - Ready for Review, I Knowledge

#4607 GFK Glossary: Title Case axis name in optical_size_axis
  cc-by-sa/knowledge/glossary/terms/optical_size_axis/content.md
  cc-by-sa/knowledge/glossary/terms/optical_size_axis/term.textproto
Labels: - Ready for Review, I Knowledge

#4674 Gulzar: Version 1.000;[57fe3b0]; ttfautohint (v1.8.4) added
  ofl/gulzar/DESCRIPTION.en_us.html
  ofl/gulzar/Gulzar-Regular.ttf
  ofl/gulzar/METADATA.pb
  ofl/gulzar/OFL.txt
  ofl/gulzar/upstream.yaml
Labels: - Ready for Review, I New Font, II Commissioned

#4689 Design profile: Alice Savoie
  catalog/designers/alicesavoie/alicesavoie.png
  catalog/designers/alicesavoie/bio.html
  catalog/designers/alicesavoie/info.pb
Labels: - Ready for Review, I Designer profile

#4690 Add designer profile for Simon Cozens
  catalog/designers/simoncozens/bio.html
  catalog/designers/simoncozens/info.pb
  catalog/designers/simoncozens/simoncozens.png
Labels: --- to sandbox, I Designer profile

#4694 Cormorant: Version 4.000 added
  ofl/cormorant/Cormorant-Bold.ttf
  ofl/cormorant/Cormorant-BoldItalic.ttf
  ofl/cormorant/Cormorant-Italic.ttf
  ofl/cormorant/Cormorant-Italic[wght].ttf
  ofl/cormorant/Cormorant-Light.ttf
  ofl/cormorant/Cormorant-LightItalic.ttf
  ofl/cormorant/Cormorant-Medium.ttf
  ofl/cormorant/Cormorant-MediumItalic.ttf
  ofl/cormorant/Cormorant-Regular.ttf
  ofl/cormorant/Cormorant-SemiBold.ttf
  ofl/cormorant/Cormorant-SemiBoldItalic.ttf
  ofl/cormorant/Cormorant[wght].ttf
  ofl/cormorant/METADATA.pb
  ofl/cormorant/OFL.txt
  ofl/cormorant/upstream.yaml
Labels: III VF Replacement, - Ready for Review, I Font Upgrade

#4701 Splash: Version 1.010; ttfautohint (v1.8.4.7-5d5b) added
  ofl/splash/DESCRIPTION.en_us.html
  ofl/splash/METADATA.pb
  ofl/splash/OFL.txt
  ofl/splash/Splash-Regular.ttf
  ofl/splash/upstream.yaml
Labels: - Ready for Review, I New Font

#4716 Gluten: Version 1.300 added
  ofl/gluten/Gluten[slnt,wght].ttf
  ofl/gluten/Gluten[wght].ttf
  ofl/gluten/METADATA.pb
  ofl/gluten/upstream.yaml
Labels: - Ready for Review, I Font Upgrade, III Custom axes

#4686 Arima: Version 1.100 added
  ofl/arima/Arima[wght].ttf
  ofl/arima/DESCRIPTION.en_us.html
  ofl/arima/METADATA.pb
  ofl/arima/OFL.txt
  ofl/arima/upstream.yaml
Labels: --- to sandbox, I New Font, II Indic / Brahmic / Tai

#4726 Removed old glyphsets mentions
  ofl/splinesansmono/DESCRIPTION.en_us.html
Labels: --- to sandbox, I Description/Metadata/OFL

#4719 Add related content urls (SuperHi)
  cc-by-sa/knowledge/glossary/terms/axis_in_variable_fonts/term.textproto
  cc-by-sa/knowledge/glossary/terms/cyrillic/term.textproto
  cc-by-sa/knowledge/glossary/terms/font/term.textproto
  cc-by-sa/knowledge/glossary/terms/greek_script/term.textproto
  cc-by-sa/knowledge/glossary/terms/ligature/term.textproto
  cc-by-sa/knowledge/glossary/terms/line_height_leading/term.textproto
  cc-by-sa/knowledge/glossary/terms/open_type/term.textproto
  cc-by-sa/knowledge/glossary/terms/script_writing_system/term.textproto
  cc-by-sa/knowledge/glossary/terms/text_copy/term.textproto
  cc-by-sa/knowledge/glossary/terms/typeface/term.textproto
  cc-by-sa/knowledge/glossary/terms/variable_fonts/term.textproto
  cc-by-sa/knowledge/glossary/terms/web_font/term.textproto
  cc-by-sa/knowledge/modules/choosing_type/lessons/a_checklist_for_choosing_type/lesson.textproto
  cc-by-sa/knowledge/modules/choosing_type/lessons/pairing_typefaces/lesson.textproto
  cc-by-sa/knowledge/modules/choosing_type/lessons/pairing_typefaces_by_the_same_type_designer_or_type_foundry/lesson.textproto
  cc-by-sa/knowledge/modules/choosing_type/lessons/pairing_typefaces_within_a_family_superfamily/lesson.textproto
  cc-by-sa/knowledge/modules/introducing_type/lessons/introducing_alternate_glyphs/lesson.textproto
  cc-by-sa/knowledge/modules/introducing_type/lessons/why_care_about_typography/lesson.textproto
  cc-by-sa/knowledge/modules/using_type/lessons/choosing_a_suitable_line_height/lesson.textproto
  cc-by-sa/knowledge/modules/using_type/lessons/language_support_in_fonts/lesson.textproto
  cc-by-sa/knowledge/modules/using_type/lessons/styling_type_on_the_web_with_variable_fonts/lesson.textproto
  cc-by-sa/knowledge/modules/using_type/lessons/the_foundations_of_web_typography/lesson.textproto
  cc-by-sa/knowledge/modules/using_type/lessons/using_web_fonts_from_a_font_delivery_service/lesson.textproto
Labels: - Ready for Review, I Knowledge
