Repository google/fonts, pull requests merged in 2022-08, with the labels that each got.

#5007 Noto Serif Armenian: Version 2.007 added
  ofl/notoserifarmenian/METADATA.pb
  ofl/notoserifarmenian/NotoSerifArmenian[wdth,wght].ttf
  ofl/notoserifarmenian/upstream.yaml
Labels: - Ready for Review, I Font Upgrade

#4988 Recursive: Version 1.085 added
  ofl/recursive/METADATA.pb
  ofl/recursive/Recursive[CASL,CRSV,MONO,slnt,wght].ttf
  ofl/recursive/upstream.yaml
Labels: III Expand glyphset, - Ready for Review, I Font Upgrade

#4955 Noto Sans Mono: Version 2.010 added
  ofl/notosansmono/METADATA.pb
  ofl/notosansmono/NotoSansMono[wdth,wght].ttf
  ofl/notosansmono/OFL.txt
  ofl/notosansmono/upstream.yaml
Labels: - Ready for Review, I Font Upgrade

#5006 Noto Sans Armenian: Version 2.007 added
  ofl/notosansarmenian/METADATA.pb
  ofl/notosansarmenian/NotoSansArmenian[wdth,wght].ttf
  ofl/notosansarmenian/upstream.yaml
Labels: -- Needs confirmation, I Font Upgrade

#5025 Noto Naskh Arabic UI: v2.015 added
  ofl/notonaskharabicui/NotoNaskhArabicUI[wght].ttf
Labels: - Ready for Review

#5026 Fruktur: Version 1.008; ttfautohint (v1.8.4.7-5d5b) added
  ofl/fruktur/DESCRIPTION.en_us.html
  ofl/fruktur/Fruktur-Italic.ttf
  ofl/fruktur/Fruktur-Regular.ttf
  ofl/fruktur/METADATA.pb
  ofl/fruktur/OFL.txt
  ofl/fruktur/upstream.yaml
Labels: III Expand glyphset, III Expand styles, - Ready for Review, I Font Upgrade

#4786 Cairo Play: Version 3.119 added
  ofl/cairoplay/CairoPlay[slnt,wght].ttf
  ofl/cairoplay/DESCRIPTION.en_us.html
  ofl/cairoplay/METADATA.pb
  ofl/cairoplay/OFL.txt
  ofl/cairoplay/upstream.yaml
Labels: -- Needs Upstream Resolution, I New Font, II Color font

#5040 Update Gulzar documentation
  ofl/gulzar/DESCRIPTION.en_us.html
  ofl/gulzar/METADATA.pb
Labels: - Ready for Review

#5031 Add content links to font descriptions
  ofl/atkinsonhyperlegible/DESCRIPTION.en_us.html
  ofl/bizudgothic/DESCRIPTION.en_us.html
  ofl/bizudmincho/DESCRIPTION.en_us.html
  ofl/bizudpgothic/DESCRIPTION.en_us.html
  ofl/bizudpmincho/DESCRIPTION.en_us.html
  ofl/brygada1918/DESCRIPTION.en_us.html
  ofl/expletussans/DESCRIPTION.en_us.html
  ofl/flowblock/DESCRIPTION.en_us.html
  ofl/flowcircular/DESCRIPTION.en_us.html
  ofl/flowrounded/DESCRIPTION.en_us.html
  ofl/fraunces/DESCRIPTION.en_us.html
  ofl/lexend/DESCRIPTION.en_us.html
  ofl/radiocanada/DESCRIPTION.en_us.html
  ofl/redacted/DESCRIPTION.en_us.html
  ofl/redactedscript/DESCRIPTION.en_us.html
  ofl/robotoflex/DESCRIPTION.en_us.html
  ofl/robotoserif/DESCRIPTION.en_us.html
  ofl/spacemono/DESCRIPTION.en_us.html
  ofl/spectral/DESCRIPTION.en_us.html
  ofl/tirobangla/DESCRIPTION.en_us.html
  ofl/tirodevanagarihindi/DESCRIPTION.en_us.html
  ofl/tirodevanagarimarathi/DESCRIPTION.en_us.html
  ofl/tirodevanagarisanskrit/DESCRIPTION.en_us.html
  ofl/tirogurmukhi/DESCRIPTION.en_us.html
  ofl/tirokannada/DESCRIPTION.en_us.html
  ofl/tirotamil/DESCRIPTION.en_us.html
  ofl/tirotelugu/DESCRIPTION.en_us.html
  ofl/urbanist/DESCRIPTION.en_us.html
  ofl/zenantique/DESCRIPTION.en_us.html
  ofl/zenantiquesoft/DESCRIPTION.en_us.html
  ofl/zenkakugothicantique/DESCRIPTION.en_us.html
  ofl/zenkakugothicnew/DESCRIPTION.en_us.html
  ofl/zenkurenaido/DESCRIPTION.en_us.html
  ofl/zenmarugothic/DESCRIPTION.en_us.html
  ofl/zenoldmincho/DESCRIPTION.en_us.html
  to_sandbox.txt
Labels: I Description/Metadata/OFL

#5048 Amiri Quran: Version 0.117 added
  ofl/amiriquran/AmiriQuran-Regular.ttf
  ofl/amiriquran/DESCRIPTION.en_us.html
  ofl/amiriquran/METADATA.pb
  ofl/amiriquran/OFL.txt
  ofl/amiriquran/upstream.yaml
Labels: - Ready for Review, I New Font

#4938 Noto Sans Myanmar: Version 2.107 added
  ofl/notosansmyanmar/METADATA.pb
  ofl/notosansmyanmar/NotoSansMyanmar-Black.ttf
  ofl/notosansmyanmar/NotoSansMyanmar-Bold.ttf
  ofl/notosansmyanmar/NotoSansMyanmar-ExtraBold.ttf
  ofl/notosansmyanmar/NotoSansMyanmar-ExtraLight.ttf
  ofl/notosansmyanmar/NotoSansMyanmar-Light.ttf
  ofl/notosansmyanmar/NotoSansMyanmar-Medium.ttf
  ofl/notosansmyanmar/NotoSansMyanmar-Regular.ttf
  ofl/notosansmyanmar/NotoSansMyanmar-SemiBold.ttf
  ofl/notosansmyanmar/NotoSansMyanmar-Thin.ttf
  ofl/notosansmyanmar/NotoSansMyanmar[wdth,wght].ttf
  ofl/notosansmyanmar/OFL.txt
  ofl/notosansmyanmar/upstream.yaml
Labels: - Ready for Review, I Font Upgrade

#5049 Revert "replace all "." with "۔"(Arabic full stop) for '_Arab' language sample texts (#4549)"
  lang/Lib/gflanguages/data/languages/ar_Arab.textproto
  lang/Lib/gflanguages/data/languages/arb_Arab.textproto
  lang/Lib/gflanguages/data/languages/arz_Arab.textproto
  lang/Lib/gflanguages/data/languages/azb_Arab.textproto
  lang/Lib/gflanguages/data/languages/fa_Arab.textproto
  lang/Lib/gflanguages/data/languages/gbz_Arab.textproto
  lang/Lib/gflanguages/data/languages/kk_Arab.textproto
  lang/Lib/gflanguages/data/languages/ks_Arab.textproto
  lang/Lib/gflanguages/data/languages/ky_Arab.textproto
  lang/Lib/gflanguages/data/languages/min_Arab.textproto
  lang/Lib/gflanguages/data/languages/mis_Arab.textproto
  lang/Lib/gflanguages/data/languages/ms_Arab.textproto
  lang/Lib/gflanguages/data/languages/ota_Arab.textproto
  lang/Lib/gflanguages/data/languages/sd_Arab.textproto
  lang/Lib/gflanguages/data/languages/tg_Arab.textproto
  lang/Lib/gflanguages/data/languages/tt_Arab.textproto
  lang/Lib/gflanguages/data/languages/ug_Arab.textproto
  lang/Lib/gflanguages/data/languages/zlm_Arab.textproto
Labels: - Ready for Review, I Description/Metadata/OFL

#5042 removed extra "exist"
  TRIVIA.md
Labels: - Ready for Review, III Small Fix

#5059 Reem Kufi Ink: Version 1.002 added
  ofl/reemkufiink/METADATA.pb
  ofl/reemkufiink/OFL.txt
  ofl/reemkufiink/ReemKufiInk-Bold.ttf
  ofl/reemkufiink/ReemKufiInk-Regular.ttf
  ofl/reemkufiink/upstream.yaml
Labels: - Ready for Review, I New Font

#5080 Reem Kufi Fun: Version 1.003 added
  ofl/reemkufifun/METADATA.pb
  ofl/reemkufifun/OFL.txt
  ofl/reemkufifun/ReemKufiFun[wght].ttf
  ofl/reemkufifun/upstream.yaml
Labels: - Ready for Review, I New Font

#5064 Update README.md
  README.md
Labels: - Ready for Review

#5088 Lang update from subtree
  lang/Lib/gflanguages/data/languages/hak_Hant.textproto
  lang/Lib/gflanguages/data/languages/lzh_Hant.textproto
  lang/Lib/gflanguages/data/languages/yue_Hant.textproto
  lang/Lib/gflanguages/data/languages/za_Hant.textproto
Labels: - Ready for Review, I API / Website / Platform

#5072 Sync axisregistry subtree and resolve conflicts
  axisregistry/.github/workflows/publish-release.yml
  axisregistry/.github/workflows/tox.yml
  axisregistry/Lib/axisregistry/__init__.py
  axisregistry/Lib/axisregistry/data/element_grid.textproto
  axisregistry/setup.py
  axisregistry/test_requirements.txt
  axisregistry/tests/data/MavenPro-Regular.ttf
  axisregistry/tests/data/OpenSans-Italic[wdth,wght].ttf
  axisregistry/tests/data/OpenSans-Italic[wdth,wght]_STAT.ttx
  axisregistry/tests/data/OpenSansCondensed-Italic[wght].ttf
  axisregistry/tests/data/OpenSansCondensed-Italic[wght]_STAT.ttx
  axisregistry/tests/data/OpenSansCondensed[wght].ttf
  axisregistry/tests/data/OpenSansCondensed[wght]_STAT.ttx
  axisregistry/tests/data/OpenSans[wdth,wght].ttf
  axisregistry/tests/data/OpenSans[wdth,wght]_STAT.ttx
  axisregistry/tests/data/RobotoFlex[GRAD,XOPQ,XTRA,YOPQ,YTAS,YTDE,YTFI,YTLC,YTUC,opsz,slnt,wdth,wght].ttf
  axisregistry/tests/data/RobotoFlex[GRAD,XOPQ,XTRA,YOPQ,YTAS,YTDE,YTFI,YTLC,YTUC,opsz,slnt,wdth,wght]_STAT.ttx
  axisregistry/tests/data/Wonky[wdth,wght].ttf
  axisregistry/tests/data/Wonky[wdth,wght]_STAT.ttx
  axisregistry/tests/gen_test_data.py
  axisregistry/tests/test_names.py
  axisregistry/tox.ini
Labels: - Ready for Review, I Axis Registry

#4859 Noto Nastaliq Urdu: Version 3.004 added
  ofl/notonastaliqurdu/METADATA.pb
  ofl/notonastaliqurdu/NotoNastaliqUrdu-Bold.ttf
  ofl/notonastaliqurdu/NotoNastaliqUrdu-Regular.ttf
  ofl/notonastaliqurdu/NotoNastaliqUrdu[wght].ttf
  ofl/notonastaliqurdu/OFL.txt
  ofl/notonastaliqurdu/upstream.yaml
Labels: - Ready for Review, I Font Upgrade, II Arabic / Semitic

#4934 Noto Sans Adlam: Version 3.001 added
  ofl/notosansadlam/METADATA.pb
  ofl/notosansadlam/NotoSansAdlam[wght].ttf
  ofl/notosansadlam/OFL.txt
  ofl/notosansadlam/article/ARTICLE.en_us.html
  ofl/notosansadlam/upstream.yaml
Labels: -- Needs confirmation, I Font Upgrade

#4933 Noto Sans Adlam Unjoined: Version 3.001 added
  ofl/notosansadlamunjoined/METADATA.pb
  ofl/notosansadlamunjoined/NotoSansAdlamUnjoined[wght].ttf
  ofl/notosansadlamunjoined/OFL.txt
  ofl/notosansadlamunjoined/article/ARTICLE.en_us.html
  ofl/notosansadlamunjoined/upstream.yaml
Labels: -- Needs confirmation, I Font Upgrade

#5100 Noto Sans Oriya: Version 2.003 added
  ofl/notosansoriya/METADATA.pb
  ofl/notosansoriya/NotoSansOriya[wdth,wght].ttf
  ofl/notosansoriya/upstream.yaml
Labels: z_Noto, - Ready for Review, I Font Upgrade, II Indic / Brahmic / Thai / Tai

#4906 Noto Sans Gurmukhi: Version 2.003 added
  ofl/notosansgurmukhi/METADATA.pb
  ofl/notosansgurmukhi/NotoSansGurmukhi[wdth,wght].ttf
  ofl/notosansgurmukhi/OFL.txt
  ofl/notosansgurmukhi/article/ARTICLE.en_us.html
  ofl/notosansgurmukhi/upstream.yaml
Labels: I Font Upgrade

#5105 Update lang vi_Latn.textproto
  lang/Lib/gflanguages/data/languages/vi_Latn.textproto
Labels: - Ready for Review, I Lang

#5095 Add subset for math to Nabla and Kumbh Sans
  ofl/kumbhsans/METADATA.pb
  ofl/nabla/METADATA.pb
Labels: - Ready for Review, I API / Website / Platform

#5111 Noto Sans Thai Looped: Version 1.001; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosansthailooped/METADATA.pb
  ofl/notosansthailooped/NotoSansThaiLooped-Black.ttf
  ofl/notosansthailooped/NotoSansThaiLooped-Bold.ttf
  ofl/notosansthailooped/NotoSansThaiLooped-ExtraBold.ttf
  ofl/notosansthailooped/NotoSansThaiLooped-ExtraLight.ttf
  ofl/notosansthailooped/NotoSansThaiLooped-Light.ttf
  ofl/notosansthailooped/NotoSansThaiLooped-Medium.ttf
  ofl/notosansthailooped/NotoSansThaiLooped-Regular.ttf
  ofl/notosansthailooped/NotoSansThaiLooped-SemiBold.ttf
  ofl/notosansthailooped/NotoSansThaiLooped-Thin.ttf
  ofl/notosansthailooped/OFL.txt
  ofl/notosansthailooped/upstream.yaml
Labels: z_Noto, - Ready for Review, I Font Upgrade, II Indic / Brahmic / Thai / Tai

#5112 Noto Sans Batak: Version 2.002; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosansbatak/METADATA.pb
  ofl/notosansbatak/NotoSansBatak-Regular.ttf
  ofl/notosansbatak/OFL.txt
  ofl/notosansbatak/upstream.yaml
Labels: z_Noto, - Ready for Review, I Font Upgrade

#5132 Designer: arthurreindersfolmer added
  catalog/designers/arthurreindersfolmer/arthurreindersfolmer.png
  catalog/designers/arthurreindersfolmer/bio.html
  catalog/designers/arthurreindersfolmer/info.pb
Labels: - Ready for Review, I Designer profile

#5134 nabla: update description
  ofl/nabla/DESCRIPTION.en_us.html
Labels: - Ready for Review, I Description/Metadata/OFL

#5149 add missing fallback_only to axes metadata
  axisregistry/Lib/axisregistry/data/edge_highlight.textproto
  axisregistry/Lib/axisregistry/data/element_grid.textproto
  axisregistry/Lib/axisregistry/data/extrusion_depth.textproto
  to_sandbox.txt
Labels: --- to sandbox, I Axis Registry
