Repository google/fonts, pull requests merged in 2022-04, with the labels that each got.

#4466 Curly quotes fix
  cc-by-sa/knowledge/glossary/terms/axis_in_variable_fonts/content.md
  cc-by-sa/knowledge/glossary/terms/em/content.md
  cc-by-sa/knowledge/glossary/terms/italic_axis/content.md
  cc-by-sa/knowledge/glossary/terms/optical_size_axis/content.md
  cc-by-sa/knowledge/glossary/terms/placeholder_text/content.md
  cc-by-sa/knowledge/glossary/terms/weight_axis/content.md
  cc-by-sa/knowledge/glossary/terms/width_axis/content.md
  cc-by-sa/knowledge/modules/choosing_type/lessons/emotive_considerations_for_choosing_typefaces/content.md
  cc-by-sa/knowledge/modules/choosing_type/lessons/pairing_typefaces/content.md
Labels: --- to sandbox, I Knowledge

#4448 Neelakash Kshetrimayum designer added
  catalog/designers/neelakashkshetrimayum/bio.html
  catalog/designers/neelakashkshetrimayum/info.pb
  catalog/designers/neelakashkshetrimayum/neelakashkshetrimayum.png
Labels: - Ready for Review, I Designer profile

#4426 Fernando Mello designer added
  catalog/designers/fernandomello/bio.html
  catalog/designers/fernandomello/fernandomello.png
  catalog/designers/fernandomello/info.pb
Labels: - Ready for Review, I Designer profile

#4483 Correcting Hebrew illo to right-to-left
  cc-by-sa/knowledge/modules/using_type/lessons/language_support_in_fonts/images/language_support_in_fonts_3.svg
Labels: --- to sandbox

#4489 Alumni Sans Collegiate One: Version 1.010 added
  ofl/alumnisanscollegiateone/AlumniSansCollegiateOne-Regular.ttf
  ofl/alumnisanscollegiateone/DESCRIPTION.en_us.html
  ofl/alumnisanscollegiateone/METADATA.pb
  ofl/alumnisanscollegiateone/OFL.txt
  ofl/alumnisanscollegiateone/upstream.yaml
Labels: - Ready for Review, I New Font

#4477 Arizonia: Version 1.010; ttfautohint (v1.8.4.7-5d5b) added
  ofl/arizonia/Arizonia-Regular.ttf
  ofl/arizonia/DESCRIPTION.en_us.html
  ofl/arizonia/METADATA.pb
  ofl/arizonia/OFL.txt
  ofl/arizonia/upstream.yaml
Labels: - Ready for Review, I Font Upgrade

#4500 Removed "/" at the end of the line.
  catalog/designers/alexandresaumierdemers/bio.html
  catalog/designers/coppersandbrasses/bio.html
Labels: --- to sandbox, I Designer profile

#4492 knowledge/glossary/terms/regular_upright/content
  cc-by-sa/knowledge/glossary/terms/regular_upright/content.md
Labels: --- to sandbox, I Knowledge

#4498 Libre Bodoni: Version 2.003 added
  ofl/librebodoni/DESCRIPTION.en_us.html
  ofl/librebodoni/LibreBodoni-Italic[wght].ttf
  ofl/librebodoni/LibreBodoni[wght].ttf
  ofl/librebodoni/METADATA.pb
  ofl/librebodoni/OFL.txt
  ofl/librebodoni/upstream.yaml
Labels: --- to sandbox, I New Font

#4387 Tall Chai catalogue info
  catalog/designers/tallchai/bio.html
  catalog/designers/tallchai/info.pb
  catalog/designers/tallchai/logo.png
Labels: --- to sandbox, I Designer profile

#4474 Vazirmatn: Version 32.102 added
  ofl/vazirmatn/DESCRIPTION.en_us.html
  ofl/vazirmatn/METADATA.pb
  ofl/vazirmatn/Vazirmatn[wght].ttf
Labels: --- to sandbox, III Small Fix, II Arabic

#4450 Tiro Bangla: Version 1.52 added
  ofl/tirobangla/DESCRIPTION.en_us.html
  ofl/tirobangla/METADATA.pb
  ofl/tirobangla/OFL.txt
  ofl/tirobangla/TiroBangla-Italic.ttf
  ofl/tirobangla/TiroBangla-Regular.ttf
  ofl/tirobangla/upstream.yaml
Labels: --- to sandbox, I New Font, II Indic

#4456 Tiro Tamil: Version 1.52 added
  ofl/tirotamil/DESCRIPTION.en_us.html
  ofl/tirotamil/METADATA.pb
  ofl/tirotamil/OFL.txt
  ofl/tirotamil/TiroTamil-Italic.ttf
  ofl/tirotamil/TiroTamil-Regular.ttf
  ofl/tirotamil/upstream.yaml
Labels: --- to sandbox, I New Font, II Indic

#4457 Tiro Telugu: Version 1.52 added
  ofl/tirotelugu/DESCRIPTION.en_us.html
  ofl/tirotelugu/METADATA.pb
  ofl/tirotelugu/OFL.txt
  ofl/tirotelugu/TiroTelugu-Italic.ttf
  ofl/tirotelugu/TiroTelugu-Regular.ttf
  ofl/tirotelugu/upstream.yaml
Labels: - Ready for Review, I New Font, II Indic

#4455 Tiro Kannada: Version 1.52 added
  ofl/tirokannada/DESCRIPTION.en_us.html
  ofl/tirokannada/METADATA.pb
  ofl/tirokannada/OFL.txt
  ofl/tirokannada/TiroKannada-Italic.ttf
  ofl/tirokannada/TiroKannada-Regular.ttf
  ofl/tirokannada/upstream.yaml
Labels: --- to sandbox, I New Font, II Indic

#4454 Tiro Gurmukhi: Version 1.52 added
  ofl/tirogurmukhi/DESCRIPTION.en_us.html
  ofl/tirogurmukhi/METADATA.pb
  ofl/tirogurmukhi/OFL.txt
  ofl/tirogurmukhi/TiroGurmukhi-Italic.ttf
  ofl/tirogurmukhi/TiroGurmukhi-Regular.ttf
  ofl/tirogurmukhi/upstream.yaml
Labels: --- to sandbox, I New Font, II Indic

#4453 Tiro Devanagari Sanskrit: Version 1.52 added
  ofl/tirodevanagarisanskrit/DESCRIPTION.en_us.html
  ofl/tirodevanagarisanskrit/METADATA.pb
  ofl/tirodevanagarisanskrit/OFL.txt
  ofl/tirodevanagarisanskrit/TiroDevaSanskrit-Italic.ttf
  ofl/tirodevanagarisanskrit/TiroDevaSanskrit-Regular.ttf
  ofl/tirodevanagarisanskrit/upstream.yaml
Labels: --- to sandbox, I New Font, II Indic

#4452 Tiro Devanagari Marathi: Version 1.52 added
  ofl/tirodevanagarimarathi/DESCRIPTION.en_us.html
  ofl/tirodevanagarimarathi/METADATA.pb
  ofl/tirodevanagarimarathi/OFL.txt
  ofl/tirodevanagarimarathi/TiroDevaMarathi-Italic.ttf
  ofl/tirodevanagarimarathi/TiroDevaMarathi-Regular.ttf
  ofl/tirodevanagarimarathi/upstream.yaml
Labels: --- to sandbox, I New Font, II Indic

#4451 Tiro Devanagari Hindi: Version 1.52 added
  ofl/tirodevanagarihindi/DESCRIPTION.en_us.html
  ofl/tirodevanagarihindi/METADATA.pb
  ofl/tirodevanagarihindi/OFL.txt
  ofl/tirodevanagarihindi/TiroDevaHindi-Italic.ttf
  ofl/tirodevanagarihindi/TiroDevaHindi-Regular.ttf
  ofl/tirodevanagarihindi/upstream.yaml
Labels: - Ready for Review, I New Font, II Indic

#4533 Removing extra “the” in `contrast` glossary term
  cc-by-sa/knowledge/glossary/terms/contrast/content.md
Labels: --- to sandbox, I Knowledge

#4497 Spline Sans Mono: Version 1.001 added
  ofl/splinesansmono/METADATA.pb
  ofl/splinesansmono/OFL.txt
  ofl/splinesansmono/SplineSansMono[wght].ttf
  ofl/splinesansmono/upstream.yaml
Labels: --- to sandbox, I New Font

#4502 Spline Sans: Version 1.001 added
  ofl/splinesans/METADATA.pb
  ofl/splinesans/OFL.txt
  ofl/splinesans/SplineSans[wght].ttf
  ofl/splinesans/upstream.yaml
Labels: --- to sandbox, III Small Fix

#4535 Andika: Version 6.101 added
  ofl/andika/Andika-Bold.ttf
  ofl/andika/Andika-BoldItalic.ttf
  ofl/andika/Andika-Italic.ttf
  ofl/andika/Andika-Regular.ttf
  ofl/andika/DESCRIPTION.en_us.html
  ofl/andika/METADATA.pb
  ofl/andika/OFL.txt
  ofl/andika/upstream.yaml
Labels: III Expand glyphset, --- to sandbox, I Font Upgrade

#4552 introducing_variable_fonts/content Add mixing axes
  cc-by-sa/knowledge/modules/introducing_type/lessons/introducing_variable_fonts/content.md
Labels: --- to sandbox

#4558 Radio Canada: Version 2.100 added
  ofl/radiocanada/METADATA.pb
  ofl/radiocanada/RadioCanada-Italic[wdth,wght].ttf
  ofl/radiocanada/upstream.yaml
Labels: III Expand styles, --- to sandbox, I Font Upgrade

#4556 Blaka Hollow: Version 1.001; ttfautohint (v1.8.4.7-5d5b) added
  ofl/blakahollow/BlakaHollow-Regular.ttf
  ofl/blakahollow/DESCRIPTION.en_us.html
  ofl/blakahollow/METADATA.pb
  ofl/blakahollow/OFL.txt
  ofl/blakahollow/upstream.yaml
Labels: --- to sandbox, I New Font, II Arabic

#4557 Update Roboto Flex description and add/fix profiles
  catalog/designers/davidberlow/bio.html
  catalog/designers/davidberlow/davidberlow.jpg
  catalog/designers/davidberlow/info.pb
  catalog/designers/fontbureau/bio.html
  catalog/designers/ilyaruderman/bio.html
  catalog/designers/ilyaruderman/ilyaruderman.jpg
  catalog/designers/ilyaruderman/info.pb
  catalog/designers/irenevlachou/bio.html
  catalog/designers/irenevlachou/info.pb
  catalog/designers/irenevlachou/irenevlachou.jpg
  catalog/designers/mikhailstrukov/bio.html
  catalog/designers/mikhailstrukov/info.pb
  catalog/designers/mikhailstrukov/mikhailstrukov.jpg
  catalog/designers/santiagoorozco/bio.html
  catalog/designers/yuryostromentsky/bio.html
  catalog/designers/yuryostromentsky/info.pb
  catalog/designers/yuryostromentsky/yuryostromentsky.jpg
  ofl/robotoflex/DESCRIPTION.en_us.html
  ofl/robotoflex/METADATA.pb
Labels: - Ready for Review, I Designer profile, I Description/Metadata/OFL

#4563 Joan: Version 1.000; ttfautohint (v1.8.3) added
  ofl/joan/DESCRIPTION.en_us.html
  ofl/joan/Joan-Regular.ttf
  ofl/joan/METADATA.pb
  ofl/joan/OFL.txt
  ofl/joan/upstream.yaml
Labels: - Ready for Review, I New Font

#4565 Nuosu SIL: Version 2.200 added
  ofl/nuosusil/DESCRIPTION.en_us.html
  ofl/nuosusil/METADATA.pb
  ofl/nuosusil/NuosuSIL-Regular.ttf
  ofl/nuosusil/OFL.txt
  ofl/nuosusil/upstream.yaml
Labels: II CJK, - Ready for Review, I New Font

#4544 Updated contributing.md with correct links
  CONTRIBUTING.md
Labels: I Tools / workflow / repo, -- Needs Dave's opinion, - Ready for Review

#4496 Paprika: Version 1.010; ttfautohint (v1.8.3) added
  ofl/paprika/DESCRIPTION.en_us.html
  ofl/paprika/METADATA.pb
  ofl/paprika/OFL.txt
  ofl/paprika/Paprika-Regular.ttf
  ofl/paprika/upstream.yaml
Labels: III Expand glyphset, --- to sandbox, I Font Upgrade

#4564 Tiro devanagari file names HOTFIX
  ofl/tirodevanagarihindi/METADATA.pb
  ofl/tirodevanagarihindi/TiroDevanagariHindi-Italic.ttf
  ofl/tirodevanagarihindi/TiroDevanagariHindi-Regular.ttf
  ofl/tirodevanagarimarathi/METADATA.pb
  ofl/tirodevanagarimarathi/TiroDevanagariMarathi-Italic.ttf
  ofl/tirodevanagarimarathi/TiroDevanagariMarathi-Regular.ttf
  ofl/tirodevanagarisanskrit/METADATA.pb
  ofl/tirodevanagarisanskrit/TiroDevanagariSanskrit-Italic.ttf
  ofl/tirodevanagarisanskrit/TiroDevanagariSanskrit-Regular.ttf
Labels: - Ready for Review, I Description/Metadata/OFL, III Small Fix
