Repository google/fonts, pull requests merged in 2022-03, with the labels that each got.

#4338 Familjen Grotesk: Version 2.000 added
  ofl/familjengrotesk/DESCRIPTION.en_us.html
  ofl/familjengrotesk/FamiljenGrotesk-Italic[wght].ttf
  ofl/familjengrotesk/FamiljenGrotesk[wght].ttf
  ofl/familjengrotesk/METADATA.pb
  ofl/familjengrotesk/OFL.txt
  ofl/familjengrotesk/upstream.yaml
Labels: --- to sandbox, I New Font

#4291 Noto Sans: 2.007 added
  ofl/notosans/DESCRIPTION.en_us.html
  ofl/notosans/METADATA.pb
  ofl/notosans/NotoSans-Black.ttf
  ofl/notosans/NotoSans-BlackItalic.ttf
  ofl/notosans/NotoSans-Bold.ttf
  ofl/notosans/NotoSans-BoldItalic.ttf
  ofl/notosans/NotoSans-ExtraBold.ttf
  ofl/notosans/NotoSans-ExtraBoldItalic.ttf
  ofl/notosans/NotoSans-ExtraLight.ttf
  ofl/notosans/NotoSans-ExtraLightItalic.ttf
  ofl/notosans/NotoSans-Italic.ttf
  ofl/notosans/NotoSans-Light.ttf
  ofl/notosans/NotoSans-LightItalic.ttf
  ofl/notosans/NotoSans-Medium.ttf
  ofl/notosans/NotoSans-MediumItalic.ttf
  ofl/notosans/NotoSans-Regular.ttf
  ofl/notosans/NotoSans-SemiBold.ttf
  ofl/notosans/NotoSans-SemiBoldItalic.ttf
  ofl/notosans/NotoSans-Thin.ttf
  ofl/notosans/NotoSans-ThinItalic.ttf
  ofl/notosans/OFL.txt
Labels: --- to sandbox, I Font Upgrade

#4343 Syne: Version 2.200 added
  ofl/syne/DESCRIPTION.en_us.html
  ofl/syne/METADATA.pb
  ofl/syne/OFL.txt
  ofl/syne/Syne[wght].ttf
  ofl/syne/upstream.yaml
Labels: III Expand glyphset, --- to sandbox, I Font Upgrade

#4344 Jaikishan Patel designer added
  catalog/designers/jaikishanpatel/bio.html
  catalog/designers/jaikishanpatel/info.pb
  catalog/designers/jaikishanpatel/jaikishanpatel.png
Labels: --- to sandbox, I Designer profile

#4345 Fredoka: Version 2.001 added
  ofl/fredoka/Fredoka[wdth,wght].ttf
  ofl/fredoka/METADATA.pb
Labels: - Ready for Review, III Small Fix

#4329 Knowledge: add Roboto Serif in examples
  knowledge/glossary/terms/superfamily/content.md
Labels: - Ready for Review, I Knowledge

#4346 robotoserif: v1.007 added
  ofl/robotoserif/RobotoSerif-Italic[GRAD,opsz,wdth,wght].ttf
  ofl/robotoserif/RobotoSerif[GRAD,opsz,wdth,wght].ttf
Labels: - Ready for Review

#4333 Sofia Sans: Version 4.100 added
  ofl/sofiasans/DESCRIPTION.en_us.html
  ofl/sofiasans/METADATA.pb
  ofl/sofiasans/SofiaSans-Italic[wdth,wght].ttf
  ofl/sofiasans/SofiaSans[wdth,wght].ttf
  ofl/sofiasans/upstream.yaml
Labels: - In Progress, I New Font

#4356 knowledge/glossary/terms/axis_in_variable_fonts/content small correction
  knowledge/glossary/terms/axis_in_variable_fonts/content.md
Labels: --- to sandbox, I Knowledge

#4368 Added Tokotype
  catalog/designers/tokotype/Tokotype-Marks.png
  catalog/designers/tokotype/bio.html
  catalog/designers/tokotype/info.pb
Labels: - Ready for Review, I Designer profile

#4365 Send Flowers: Version 1.010; ttfautohint (v1.8.4.7-5d5b) added
  ofl/sendflowers/DESCRIPTION.en_us.html
  ofl/sendflowers/METADATA.pb
  ofl/sendflowers/OFL.txt
  ofl/sendflowers/SendFlowers-Regular.ttf
  ofl/sendflowers/upstream.yaml
Labels: - Ready for Review, I New Font

#4364 Lavishly Yours: Version 1.010; ttfautohint (v1.8.3) added
  ofl/lavishlyyours/DESCRIPTION.en_us.html
  ofl/lavishlyyours/LavishlyYours-Regular.ttf
  ofl/lavishlyyours/METADATA.pb
  ofl/lavishlyyours/OFL.txt
  ofl/lavishlyyours/upstream.yaml
Labels: - Ready for Review, I New Font

#4375 Designer added: Eduardo Tunni
  catalog/designers/eduardotunni/bio.html
  catalog/designers/eduardotunni/eduardotunni.png
  catalog/designers/eduardotunni/info.pb
Labels: --- to sandbox, I Designer profile

#4351 Added Saber’s catalogue info (upcoming Vazirmatn font)
  catalog/designers/saberrastikerdar/bio.html
  catalog/designers/saberrastikerdar/info.pb
Labels: --- to sandbox, I Designer profile

#4378 Designer added : George Triantafyllakos
  catalog/designers/georgetriantafyllakos/bio.html
  catalog/designers/georgetriantafyllakos/georgetriantafyllakos.png
  catalog/designers/georgetriantafyllakos/info.pb
Labels: --- to sandbox, I Designer profile

#4379 Toshi Omagari: designer added
  catalog/designers/toshiomagari/bio.html
  catalog/designers/toshiomagari/info.pb
  catalog/designers/toshiomagari/toshiomagari.png
Labels: --- to sandbox, I Designer profile

#4352 Vazirmatn: Version 32.0.0 added
  ofl/vazirmatn/DESCRIPTION.en_us.html
  ofl/vazirmatn/METADATA.pb
  ofl/vazirmatn/OFL.txt
  ofl/vazirmatn/Vazirmatn[wght].ttf
  ofl/vazirmatn/upstream.yaml
Labels: - Ready for Review, I New Font

#4383 Radio Canada: Version 2.100 added
  ofl/radiocanada/DESCRIPTION.en_us.html
  ofl/radiocanada/METADATA.pb
  ofl/radiocanada/OFL.txt
  ofl/radiocanada/RadioCanada[wdth,wght].ttf
  ofl/radiocanada/upstream.yaml
Labels: --- to sandbox, I New Font

#4385 add fallback_only to .textproto
  axisregistry/flair.textproto
  axisregistry/volume.textproto
  axisregistry/x_opaque.textproto
  axisregistry/x_transparent.textproto
  axisregistry/x_transparent_figures.textproto
  axisregistry/y_opaque.textproto
  axisregistry/y_transparent_ascender.textproto
  axisregistry/y_transparent_descender.textproto
  axisregistry/y_transparent_figures.textproto
  axisregistry/y_transparent_lowercase.textproto
  axisregistry/y_transparent_uppercase.textproto
  to_sandbox.txt
Labels: I Axis Registry

#4386 Update heebo credit
  ofl/heebo/METADATA.pb
  to_sandbox.txt
Labels: --- to sandbox, I Description/Metadata/OFL

#4394 Heebo: credit updated
  ofl/heebo/METADATA.pb
Labels: --- to sandbox, I Description/Metadata/OFL

#4396 Alexandre Saumier Demers: designer added
  catalog/designers/alexandresaumierdemers/alexandresaumierdemers.png
  catalog/designers/alexandresaumierdemers/bio.html
  catalog/designers/alexandresaumierdemers/info.pb
Labels: --- to sandbox, I Designer profile

#4392 Cooper and Brasses: designer added
  catalog/designers/coppersandbrasses/bio.html
  catalog/designers/coppersandbrasses/coppersandbrasses.png
  catalog/designers/coppersandbrasses/info.pb
Labels: --- to sandbox, I Designer profile

#4388 Akshar: Version 1.000 added
  ofl/akshar/Akshar[wght].ttf
  ofl/akshar/DESCRIPTION.en_us.html
  ofl/akshar/METADATA.pb
  ofl/akshar/OFL.txt
  ofl/akshar/upstream.yaml
Labels: - Ready for Review, I New Font

#4397 Morisawa Inc.: designer added
  catalog/designers/morisawainc./bio.html
  catalog/designers/morisawainc./info.pb
  catalog/designers/morisawainc./morisawainc.png
Labels: --- to sandbox, I Designer profile

#4410 Updated gfk launch content for q1
  knowledge/glossary/terms/drop_cap/content.md
  knowledge/glossary/terms/em/content.md
  knowledge/glossary/terms/em/images/Em_1.svg
  knowledge/glossary/terms/em/images/em_2.svg
  knowledge/glossary/terms/em/images/thumbnail.svg
  knowledge/glossary/terms/em/term.textproto
  knowledge/glossary/terms/optical_sizes/images/thumbnail.svg
  knowledge/modules/choosing_type/lessons/choosing_typefaces_that_have_optical_sizes/images/2.5.2.svg
  knowledge/modules/choosing_type/lessons/choosing_typefaces_that_have_optical_sizes/images/thumbnail.svg
  knowledge/modules/choosing_type/lessons/emotive_considerations_for_choosing_typefaces/images/2.1.2.svg
  knowledge/modules/choosing_type/lessons/exploring_typefaces_with_multiple_weights_or_grades/images/2.3.4.svg
  knowledge/modules/choosing_type/lessons/exploring_width_in_type/lesson.textproto
  knowledge/modules/choosing_type/lessons/exploring_x_height_the_em_square/images/2.9.1.svg
  knowledge/modules/introducing_type/lessons/introducing_alternate_glyphs/content.md
  knowledge/modules/introducing_type/lessons/introducing_variable_fonts/images/1.8.7.svg
  knowledge/modules/introducing_type/lessons/introducing_weights_styles/lesson.textproto
  knowledge/modules/introducing_type/lessons/open_type_features_in_practice/lesson.textproto
  knowledge/modules/introducing_type/lessons/why_care_about_typography/lesson.textproto
  knowledge/modules/using_type/lessons/styling_type_on_the_web_with_variable_fonts/content.md
Labels: --- to sandbox, I Knowledge

#4395 Knowledge 3benefit vf
  knowledge/glossary/terms/variable_fonts/content.md
Labels: - Ready for Review, I Knowledge

#4399 My Soul: Version 1.010; ttfautohint (v1.8.4.7-5d5b) added
  ofl/mysoul/DESCRIPTION.en_us.html
  ofl/mysoul/METADATA.pb
  ofl/mysoul/MySoul-Regular.ttf
  ofl/mysoul/OFL.txt
  ofl/mysoul/upstream.yaml
Labels: --- to sandbox, I New Font

#4408 Plus Jakarta Sans: Version 2.006 added
  ofl/plusjakartasans/DESCRIPTION.en_us.html
  ofl/plusjakartasans/METADATA.pb
  ofl/plusjakartasans/OFL.txt
  ofl/plusjakartasans/PlusJakartaSans-Italic[wght].ttf
  ofl/plusjakartasans/PlusJakartaSans[wght].ttf
  ofl/plusjakartasans/upstream.yaml
Labels: --- to sandbox, I New Font

#4409 Sofia Sans: Version 4.102 added
  ofl/sofiasans/METADATA.pb
  ofl/sofiasans/SofiaSans-Italic[wdth,wght].ttf
  ofl/sofiasans/SofiaSans[wdth,wght].ttf
Labels: --- blocked

#4406 Catalogue tokotype
  catalog/designers/tokotype/bio.html
Labels: --- to sandbox, I Designer profile

#4415 Updock: Version 1.010; ttfautohint (v1.8.4.7-5d5b) added
  ofl/updock/DESCRIPTION.en_us.html
  ofl/updock/METADATA.pb
  ofl/updock/OFL.txt
  ofl/updock/Updock-Regular.ttf
  ofl/updock/upstream.yaml
Labels: - Ready for Review, I New Font

#4414 Whisper: Version 1.010; ttfautohint (v1.8.4.7-5d5b) added
  ofl/whisper/DESCRIPTION.en_us.html
  ofl/whisper/METADATA.pb
  ofl/whisper/OFL.txt
  ofl/whisper/Whisper-Regular.ttf
  ofl/whisper/upstream.yaml
Labels: - Ready for Review, I New Font

#4412 Ms Madi: Version 1.010; ttfautohint (v1.8.3) added
  ofl/msmadi/DESCRIPTION.en_us.html
  ofl/msmadi/METADATA.pb
  ofl/msmadi/MsMadi-Regular.ttf
  ofl/msmadi/OFL.txt
  ofl/msmadi/upstream.yaml
Labels: - Ready for Review, I New Font

#4413 Square Peg: Version 1.010; ttfautohint (v1.8.4.7-5d5b) added
  ofl/squarepeg/DESCRIPTION.en_us.html
  ofl/squarepeg/METADATA.pb
  ofl/squarepeg/OFL.txt
  ofl/squarepeg/SquarePeg-Regular.ttf
  ofl/squarepeg/upstream.yaml
Labels: --- to sandbox, I New Font

#4419 Fix axis def markdown tables
  knowledge/glossary/terms/casual_axis/content.md
  knowledge/glossary/terms/cursive_axis/content.md
  knowledge/glossary/terms/fill_axis/content.md
  knowledge/glossary/terms/grade_axis/content.md
  knowledge/glossary/terms/italic_axis/content.md
  knowledge/glossary/terms/monospace_axis/content.md
  knowledge/glossary/terms/optical_size_axis/content.md
  knowledge/glossary/terms/slant_axis/content.md
  knowledge/glossary/terms/softness_axis/content.md
  knowledge/glossary/terms/weight_axis/content.md
  knowledge/glossary/terms/width_axis/content.md
  knowledge/glossary/terms/wonky_axis/content.md
Labels: --- to sandbox, I Knowledge

#4425 Axis def tweaks
  knowledge/glossary/terms/axis_in_variable_fonts/content.md
  knowledge/modules/choosing_type/lessons/a_checklist_for_choosing_type/content.md
  knowledge/modules/introducing_type/lessons/an_overview_of_latin_type_anatomy/content.md
  knowledge/modules/using_type/lessons/language_support_in_fonts/content.md
  knowledge/modules/using_type/lessons/the_foundations_of_web_typography/content.md
Labels: --- to sandbox, I Knowledge

#4442 Typeface credits etc
  cc-by-sa/knowledge/glossary/terms/casual_axis/content.md
  cc-by-sa/knowledge/glossary/terms/cursive_axis/content.md
  cc-by-sa/knowledge/glossary/terms/grade/content.md
  cc-by-sa/knowledge/glossary/terms/grade_axis/content.md
  cc-by-sa/knowledge/glossary/terms/greek_script/content.md
  cc-by-sa/knowledge/glossary/terms/hierarchy/content.md
  cc-by-sa/knowledge/glossary/terms/italic_axis/content.md
  cc-by-sa/knowledge/glossary/terms/monospace_axis/content.md
  cc-by-sa/knowledge/glossary/terms/optical_size_axis/content.md
  cc-by-sa/knowledge/glossary/terms/overshoot/content.md
  cc-by-sa/knowledge/glossary/terms/script_writing_system/content.md
  cc-by-sa/knowledge/glossary/terms/slant_axis/content.md
  cc-by-sa/knowledge/glossary/terms/softness_axis/content.md
  cc-by-sa/knowledge/glossary/terms/superscript_subscript/content.md
  cc-by-sa/knowledge/glossary/terms/weight_axis/content.md
  cc-by-sa/knowledge/glossary/terms/wonky_axis/content.md
  cc-by-sa/knowledge/modules/choosing_type/lessons/a_checklist_for_choosing_type/content.md
  cc-by-sa/knowledge/modules/choosing_type/lessons/a_checklist_for_choosing_type/images/a_checklist_for_choosing_type_2.svg
  cc-by-sa/knowledge/modules/introducing_type/lessons/an_overview_of_latin_type_anatomy/content.md
  cc-by-sa/knowledge/modules/using_type/lessons/language_support_in_fonts/content.md
Labels: --- to sandbox

#4428 Spline Sans Mono: Version 1.000 added
  ofl/splinesansmono/DESCRIPTION.en_us.html
  ofl/splinesansmono/METADATA.pb
  ofl/splinesansmono/OFL.txt
  ofl/splinesansmono/SplineSansMono[wght].ttf
Labels: - Ready for Review, I New Font
