Repository google/fonts, pull requests merged in 2022-02, with the labels that each got.

#3211 Update width.textproto to include the range implemented in Roboto Flex
  axisregistry/width.textproto
Labels: - In Progress, II Axis Registry

#4265 ABeeZee: Version 1.003; ttfautohint (v1.8.3) added
  ofl/abeezee/ABeeZee-Italic.ttf
  ofl/abeezee/ABeeZee-Regular.ttf
  ofl/abeezee/DESCRIPTION.en_us.html
  ofl/abeezee/METADATA.pb
  ofl/abeezee/OFL.txt
  ofl/abeezee/upstream.yaml
Labels: --- to sandbox, II Font Upgrade

#4283 Anek Tamil: Version 1.003 added
  ofl/anektamil/AnekTamil[wdth,wght].ttf
  ofl/anektamil/DESCRIPTION.en_us.html
  ofl/anektamil/METADATA.pb
  ofl/anektamil/OFL.txt
  ofl/anektamil/upstream.yaml
Labels: --- to sandbox, II New Font

#4282 Anek Odia: Version 1.003 added
  ofl/anekodia/AnekOdia[wdth,wght].ttf
  ofl/anekodia/DESCRIPTION.en_us.html
  ofl/anekodia/METADATA.pb
  ofl/anekodia/OFL.txt
  ofl/anekodia/upstream.yaml
Labels: --- to sandbox, II New Font

#4276 Anek Devanagari: Version 1.003 added
  ofl/anekdevanagari/AnekDevanagari[wdth,wght].ttf
  ofl/anekdevanagari/DESCRIPTION.en_us.html
  ofl/anekdevanagari/METADATA.pb
  ofl/anekdevanagari/OFL.txt
  ofl/anekdevanagari/upstream.yaml
Labels: --- to sandbox, II New Font

#4275 Anek Bangla: Version 1.003 added
  ofl/anekbangla/AnekBangla[wdth,wght].ttf
  ofl/anekbangla/DESCRIPTION.en_us.html
  ofl/anekbangla/METADATA.pb
  ofl/anekbangla/OFL.txt
  ofl/anekbangla/upstream.yaml
Labels: --- to sandbox, II New Font

#4290 update axis textproto
  axisregistry/README.md
  axisregistry/casual.textproto
  axisregistry/cursive.textproto
  axisregistry/fill.textproto
  axisregistry/grade.textproto
  axisregistry/italic.textproto
  axisregistry/monospace.textproto
  axisregistry/optical_size.textproto
  axisregistry/slant.textproto
  axisregistry/softness.textproto
  axisregistry/weight.textproto
  axisregistry/width.textproto
  axisregistry/wonky.textproto
  to_sandbox.txt
Labels: II Axis Registry

#4296 Spartan : metadata and description updated (author name)
  ofl/spartan/DESCRIPTION.en_us.html
  ofl/spartan/METADATA.pb
Labels: - Ready for Review

#4295 Spline Sans : Metadata and description updated (author name)
  ofl/splinesans/DESCRIPTION.en_us.html
  ofl/splinesans/METADATA.pb
Labels: - Ready for Review, II Description/Metadata/OFL

#4247 Noto sans et serif display: reverse primary categories in metadata.pb
  ofl/notosansdisplay/METADATA.pb
  ofl/notoserifdisplay/METADATA.pb
Labels: - Ready for Review, II Description/Metadata/OFL, III Small Fix

#4307 Anek Odia: Version 1.003 added
  ofl/anekodia/AnekOdia[wdth,wght].ttf
  ofl/anekodia/METADATA.pb
  ofl/anekodia/upstream.yaml
Labels: --- to sandbox, II New Font

#4306 Anek Gujarati: Version 1.003 added
  ofl/anekgujarati/AnekGujarati[wdth,wght].ttf
  ofl/anekgujarati/METADATA.pb
  ofl/anekgujarati/upstream.yaml
Labels: --- to sandbox, II New Font

#4304 Anek Bangla: Version 1.003 added
  ofl/anekbangla/AnekBangla[wdth,wght].ttf
  ofl/anekbangla/METADATA.pb
  ofl/anekbangla/upstream.yaml
Labels: --- to sandbox, II New Font

#4278 Anek Gurmukhi: Version 1.003 added
  ofl/anekgurmukhi/AnekGurmukhi[wdth,wght].ttf
  ofl/anekgurmukhi/DESCRIPTION.en_us.html
  ofl/anekgurmukhi/METADATA.pb
  ofl/anekgurmukhi/OFL.txt
  ofl/anekgurmukhi/upstream.yaml
Labels: --- to sandbox, II New Font

#4280 Anek Latin: Version 1.003 added
  ofl/aneklatin/AnekLatin[wdth,wght].ttf
  ofl/aneklatin/DESCRIPTION.en_us.html
  ofl/aneklatin/METADATA.pb
  ofl/aneklatin/OFL.txt
  ofl/aneklatin/upstream.yaml
Labels: --- to sandbox, II New Font

#4313 Rubik Beastly: Version 2.200 added
  ofl/rubikbeastly/DESCRIPTION.en_us.html
  ofl/rubikbeastly/METADATA.pb
  ofl/rubikbeastly/RubikBeastly-Regular.ttf
  ofl/rubikbeastly/upstream.yaml
Labels: --- to sandbox, II Font Upgrade

#4321 Eczar: Version 2.000 added
  ofl/eczar/DESCRIPTION.en_us.html
  ofl/eczar/Eczar-Bold.ttf
  ofl/eczar/Eczar-ExtraBold.ttf
  ofl/eczar/Eczar-Medium.ttf
  ofl/eczar/Eczar-Regular.ttf
  ofl/eczar/Eczar-SemiBold.ttf
  ofl/eczar/Eczar[wght].ttf
  ofl/eczar/METADATA.pb
  ofl/eczar/OFL.txt
  ofl/eczar/upstream.yaml
Labels: III Expand glyphset, --- to sandbox, II Font Upgrade

#4303 Add Roboto Serif
  ofl/robotoserif/DESCRIPTION.en_us.html
  ofl/robotoserif/METADATA.pb
  ofl/robotoserif/OFL.txt
  ofl/robotoserif/RobotoSerif-Italic[GRAD,opsz,wdth,wght].ttf
  ofl/robotoserif/RobotoSerif[GRAD,opsz,wdth,wght].ttf
Labels: --- to sandbox, II New Font

#4314 Rubik Bubbles: Version 2.200 added
  ofl/rubikbubbles/DESCRIPTION.en_us.html
  ofl/rubikbubbles/METADATA.pb
  ofl/rubikbubbles/OFL.txt
  ofl/rubikbubbles/RubikBubbles-Regular.ttf
  ofl/rubikbubbles/upstream.yaml
Labels: - Ready for Review, II New Font

#4316 Rubik Microbe: Version 2.200 added
  ofl/rubikmicrobe/DESCRIPTION.en_us.html
  ofl/rubikmicrobe/METADATA.pb
  ofl/rubikmicrobe/OFL.txt
  ofl/rubikmicrobe/RubikMicrobe-Regular.ttf
  ofl/rubikmicrobe/upstream.yaml
Labels: --- to sandbox, II New Font

#4317 Rubik Puddles: Version 2.200 added
  ofl/rubikpuddles/DESCRIPTION.en_us.html
  ofl/rubikpuddles/METADATA.pb
  ofl/rubikpuddles/OFL.txt
  ofl/rubikpuddles/RubikPuddles-Regular.ttf
  ofl/rubikpuddles/upstream.yaml
Labels: - Ready for Review, II New Font

#4318 Rubik Glitch: Version 2.200 added
  ofl/rubikglitch/DESCRIPTION.en_us.html
  ofl/rubikglitch/METADATA.pb
  ofl/rubikglitch/OFL.txt
  ofl/rubikglitch/RubikGlitch-Regular.ttf
  ofl/rubikglitch/upstream.yaml
Labels: --- to sandbox, II New Font

#4319 Rubik Moonrocks: Version 2.200 added
  ofl/rubikmoonrocks/DESCRIPTION.en_us.html
  ofl/rubikmoonrocks/METADATA.pb
  ofl/rubikmoonrocks/OFL.txt
  ofl/rubikmoonrocks/RubikMoonrocks-Regular.ttf
  ofl/rubikmoonrocks/upstream.yaml
Labels: --- to sandbox, II New Font

#4320 Rubik Wet Paint: Version 2.200 added
  ofl/rubikwetpaint/DESCRIPTION.en_us.html
  ofl/rubikwetpaint/METADATA.pb
  ofl/rubikwetpaint/OFL.txt
  ofl/rubikwetpaint/RubikWetPaint-Regular.ttf
  ofl/rubikwetpaint/upstream.yaml
Labels: --- to sandbox, II New Font

#4322 Grape Nuts: Version 1.010; ttfautohint (v1.8.3) added
  ofl/grapenuts/DESCRIPTION.en_us.html
  ofl/grapenuts/GrapeNuts-Regular.ttf
  ofl/grapenuts/METADATA.pb
  ofl/grapenuts/OFL.txt
  ofl/grapenuts/upstream.yaml
Labels: --- to sandbox, II New Font

#4323 Beau Rivage: Version 1.010; ttfautohint (v1.8.3) added
  ofl/beaurivage/BeauRivage-Regular.ttf
  ofl/beaurivage/DESCRIPTION.en_us.html
  ofl/beaurivage/METADATA.pb
  ofl/beaurivage/OFL.txt
  ofl/beaurivage/upstream.yaml
Labels: --- to sandbox, II New Font

#4206 Clarify Open Sans licensing status as OFL
  apache/opensans/DESCRIPTION.en_us.html
  apache/opensans/LICENSE.txt
  ofl/opensans/DESCRIPTION.en_us.html
  ofl/opensans/METADATA.pb
  ofl/opensans/OFL.txt
  ofl/opensans/OpenSans-Italic[wdth,wght].ttf
  ofl/opensans/OpenSans[wdth,wght].ttf
  ofl/opensans/upstream.yaml
Labels: - Ready for Review, I Description/Metadata/OFL

#4324 Babylonica: Version 1.010; ttfautohint (v1.8.3) added
  ofl/babylonica/Babylonica-Regular.ttf
  ofl/babylonica/DESCRIPTION.en_us.html
  ofl/babylonica/METADATA.pb
  ofl/babylonica/OFL.txt
  ofl/babylonica/upstream.yaml
Labels: --- to sandbox, I New Font

#4332 Kufam's description updated
  ofl/kufam/DESCRIPTION.en_us.html
Labels: - Ready for Review, I Description/Metadata/OFL

#4331 Alumni Sans Inline One: Version 1.100; ttfautohint (v1.8.3) added
  ofl/alumnisansinlineone/AlumniSansInlineOne-Italic.ttf
  ofl/alumnisansinlineone/AlumniSansInlineOne-Regular.ttf
  ofl/alumnisansinlineone/DESCRIPTION.en_us.html
  ofl/alumnisansinlineone/METADATA.pb
  ofl/alumnisansinlineone/OFL.txt
  ofl/alumnisansinlineone/upstream.yaml
Labels: --- to sandbox, I New Font
