Repository google/fonts, pull requests merged in 2023-02, with the labels that each got.

#5849 Update solway/METADATA.pb designer
  ofl/solway/METADATA.pb
Labels: I Designer profile, I Description/Metadata/OFL

#5852 Frank Ruhl Libre: Version 6.001;gftools[0.9.23] added
  ofl/frankruhllibre/FrankRuhlLibre[wght].ttf
  ofl/frankruhllibre/METADATA.pb
Labels: - Ready for Review, I Font Upgrade, I Small Fix

#5807 Unica One: Version 2.000; ttfautohint (v1.8.4.7-5d5b) added
  ofl/unicaone/DESCRIPTION.en_us.html
  ofl/unicaone/METADATA.pb
  ofl/unicaone/OFL.txt
  ofl/unicaone/UnicaOne-Regular.ttf
  ofl/unicaone/upstream.yaml
Labels: III Expand glyphset, - Ready for Review, I Font Upgrade

#5853 subtree pull axisregistry
  axisregistry/.github/ISSUE_TEMPLATE/1_add-axis.md
  axisregistry/Lib/axisregistry/__init__.py
  axisregistry/Lib/axisregistry/data/flair.textproto
  axisregistry/Lib/axisregistry/data/flare.svg
  axisregistry/Lib/axisregistry/data/flare.textproto
  axisregistry/Lib/axisregistry/data/morph.textproto
  axisregistry/Lib/axisregistry/data/optical_size.textproto
  axisregistry/Lib/axisregistry/data/volume.textproto
  axisregistry/Lib/axisregistry/data/width.textproto
  axisregistry/Lib/axisregistry/data/wonky.textproto
  axisregistry/Lib/axisregistry/data/x_rotation.textproto
  axisregistry/Lib/axisregistry/data/y_rotation.textproto
  axisregistry/README.md
  axisregistry/setup.py
Labels: I Axis Registry

#5855 Konkhmer Sleokchher: Version 1.000; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.23] added
  catalog/designers/suonmaysophanith/bio.html
  catalog/designers/suonmaysophanith/info.pb
  catalog/designers/suonmaysophanith/suonmaysophanith.png
  ofl/konkhmersleokchher/DESCRIPTION.en_us.html
  ofl/konkhmersleokchher/KonkhmerSleokchher-Regular.ttf
  ofl/konkhmersleokchher/METADATA.pb
  ofl/konkhmersleokchher/OFL.txt
  ofl/konkhmersleokchher/upstream.yaml
Labels: -- Needs manager's opinion, I Designer profile, I New Font

#5851 Metrophobic: Version 3.200; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.23] added
  ofl/metrophobic/DESCRIPTION.en_us.html
  ofl/metrophobic/METADATA.pb
  ofl/metrophobic/Metrophobic-Regular.ttf
  ofl/metrophobic/OFL.txt
  ofl/metrophobic/upstream.yaml
Labels: III Expand glyphset, -- Needs manager's opinion, - Ready for Review, I Font Upgrade

#5813 Voltaire: Version 1.008; ttfautohint (v1.8.4.7-5d5b) added
  ofl/voltaire/DESCRIPTION.en_us.html
  ofl/voltaire/METADATA.pb
  ofl/voltaire/Voltaire-Regular.ttf
Labels: III Expand glyphset, - Upstream is working on it, -- Needs manager's opinion, I Font Upgrade

#5859 Paytone One: Version 1.002; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.23] added
  ofl/paytoneone/DESCRIPTION.en_us.html
  ofl/paytoneone/METADATA.pb
  ofl/paytoneone/PaytoneOne-Regular.ttf
  ofl/paytoneone/upstream.yaml
Labels: III Expand glyphset, --- to sandbox, I Font Upgrade

#5860 Offside: Version 1.002; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.23] added
  ofl/offside/DESCRIPTION.en_us.html
  ofl/offside/METADATA.pb
  ofl/offside/OFL.txt
  ofl/offside/Offside-Regular.ttf
  ofl/offside/upstream.yaml
Labels: III Expand glyphset, - Ready for Review, I Font Upgrade

#5865 Wix Madefor Display: Version 1.200 added
  ofl/wixmadefordisplay/DESCRIPTION.en_us.html
  ofl/wixmadefordisplay/METADATA.pb
  ofl/wixmadefordisplay/OFL.txt
  ofl/wixmadefordisplay/WixMadeforDisplay[wght].ttf
  ofl/wixmadefordisplay/upstream.yaml
Labels: --- to sandbox, I New Font

#5560 Alkatra: Version 1.100 added
  ofl/alkatra/Alkatra[wght].ttf
  ofl/alkatra/DESCRIPTION.en_us.html
  ofl/alkatra/METADATA.pb
  ofl/alkatra/OFL.txt
  ofl/alkatra/upstream.yaml
Labels: - Ready for Review, I New Font, II Indic / Brahmic / Thai / Tai

#5871 Warnes: Version 1.002; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.23] added
  ofl/warnes/DESCRIPTION.en_us.html
  ofl/warnes/METADATA.pb
  ofl/warnes/OFL.txt
  ofl/warnes/Warnes-Regular.ttf
  ofl/warnes/upstream.yaml
Labels: III Expand glyphset, - Ready for Review, I Font Upgrade

#5872 Faster One: Version 1.003; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.23] added
  ofl/fasterone/DESCRIPTION.en_us.html
  ofl/fasterone/FasterOne-Regular.ttf
  ofl/fasterone/METADATA.pb
  ofl/fasterone/OFL.txt
  ofl/fasterone/upstream.yaml
Labels: III Expand glyphset, --- to sandbox, I Font Upgrade

#5738 Noto Sans Avestan: Version 2.003; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosansavestan/METADATA.pb
  ofl/notosansavestan/NotoSansAvestan-Regular.ttf
  ofl/notosansavestan/upstream.yaml
Labels: - Ready for Review, I Font Upgrade

#5873 Libre Bodoni: Version 2.005;gftools[0.9.23] added
  ofl/librebodoni/LibreBodoni-Italic[wght].ttf
  ofl/librebodoni/LibreBodoni[wght].ttf
  ofl/librebodoni/METADATA.pb
Labels: - Ready for Review, I Font Upgrade, I Small Fix

#5780 Pathway Extreme: Version 1.000 added
  ofl/pathwayextreme/DESCRIPTION.en_us.html
  ofl/pathwayextreme/METADATA.pb
  ofl/pathwayextreme/OFL.txt
  ofl/pathwayextreme/PathwayExtreme-Italic[opsz,wdth,wght].ttf
  ofl/pathwayextreme/PathwayExtreme[opsz,wdth,wght].ttf
  ofl/pathwayextreme/upstream.yaml
Labels: - Ready for Review, I New Font

#5878 wixmadefortext: v1.200 added
  ofl/wixmadefortext/METADATA.pb
  ofl/wixmadefortext/WixMadeforText-Bold.ttf
  ofl/wixmadefortext/WixMadeforText-BoldItalic.ttf
  ofl/wixmadefortext/WixMadeforText-ExtraBold.ttf
  ofl/wixmadefortext/WixMadeforText-ExtraBoldItalic.ttf
  ofl/wixmadefortext/WixMadeforText-Italic.ttf
  ofl/wixmadefortext/WixMadeforText-Italic[wght].ttf
  ofl/wixmadefortext/WixMadeforText-Medium.ttf
  ofl/wixmadefortext/WixMadeforText-MediumItalic.ttf
  ofl/wixmadefortext/WixMadeforText-Regular.ttf
  ofl/wixmadefortext/WixMadeforText-SemiBold.ttf
  ofl/wixmadefortext/WixMadeforText-SemiBoldItalic.ttf
Labels: - Ready for Review, I New Font

#5874 Pontano Sans: Version 2.000;gftools[0.9.23] added
  ofl/pontanosans/DESCRIPTION.en_us.html
  ofl/pontanosans/METADATA.pb
  ofl/pontanosans/OFL.txt
  ofl/pontanosans/PontanoSans-Regular.ttf
  ofl/pontanosans/PontanoSans[wght].ttf
  ofl/pontanosans/upstream.yaml
Labels: III VF Replacement, -- Needs manager's opinion, I Font Upgrade

#5896 Delicious Handrawn: Version 1.001; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.23] added
  ofl/delicioushandrawn/DeliciousHandrawn-Regular.ttf
  ofl/delicioushandrawn/METADATA.pb
Labels: - Ready for Review, I New Font, I Small Fix

#5891 Orienta: Version 1.002; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.23] added
  ofl/orienta/DESCRIPTION.en_us.html
  ofl/orienta/METADATA.pb
  ofl/orienta/OFL.txt
  ofl/orienta/Orienta-Regular.ttf
  ofl/orienta/upstream.yaml
Labels: III Expand glyphset, - Ready for Review, I Font Upgrade

#5890 Imprima: Version 1.002; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.23] added
  ofl/imprima/DESCRIPTION.en_us.html
  ofl/imprima/Imprima-Regular.ttf
  ofl/imprima/METADATA.pb
  ofl/imprima/OFL.txt
  ofl/imprima/upstream.yaml
Labels: III Expand glyphset, - Ready for Review, I Font Upgrade

#5895 Akatab: Version 3.000 added (SIL)
  ofl/akatab/Akatab-Black.ttf
  ofl/akatab/Akatab-Bold.ttf
  ofl/akatab/Akatab-ExtraBold.ttf
  ofl/akatab/Akatab-Medium.ttf
  ofl/akatab/Akatab-Regular.ttf
  ofl/akatab/Akatab-SemiBold.ttf
  ofl/akatab/DESCRIPTION.en_us.html
  ofl/akatab/METADATA.pb
  ofl/akatab/OFL.txt
  ofl/akatab/upstream.yaml
Labels: - Ready for Review, I New Font, II African

#5903 Diplomata: Version 1.002; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.23] added
  ofl/diplomata/DESCRIPTION.en_us.html
  ofl/diplomata/Diplomata-Regular.ttf
  ofl/diplomata/METADATA.pb
  ofl/diplomata/OFL.txt
  ofl/diplomata/upstream.yaml
Labels: III Expand glyphset, - Ready for Review, I Font Upgrade

#5904 DiplomataSC: Version 1.002; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.23] added
  ofl/diplomatasc/DESCRIPTION.en_us.html
  ofl/diplomatasc/DiplomataSC-Regular.ttf
  ofl/diplomatasc/METADATA.pb
  ofl/diplomatasc/OFL.txt
  ofl/diplomatasc/upstream.yaml
Labels: III Expand glyphset, - Ready for Review, I Font Upgrade

#5906 Kite One: Version 1.002; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.23] added
  ofl/kiteone/DESCRIPTION.en_us.html
  ofl/kiteone/KiteOne-Regular.ttf
  ofl/kiteone/METADATA.pb
  ofl/kiteone/OFL.txt
  ofl/kiteone/upstream.yaml
Labels: III Expand glyphset, - Ready for Review, I Font Upgrade

#5908 Unlock: Version 1.003; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.23] added
  ofl/unlock/DESCRIPTION.en_us.html
  ofl/unlock/METADATA.pb
  ofl/unlock/OFL.txt
  ofl/unlock/Unlock-Regular.ttf
  ofl/unlock/upstream.yaml
Labels: III Expand glyphset, - Ready for Review, I Font Upgrade

#5907 Strait: Version 1.002; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.23] added
  ofl/strait/DESCRIPTION.en_us.html
  ofl/strait/METADATA.pb
  ofl/strait/OFL.txt
  ofl/strait/Strait-Regular.ttf
  ofl/strait/upstream.yaml
Labels: III Expand glyphset, - Ready for Review, I Font Upgrade

#5923 Zen Maru Gothic: Version 1.002 added
  ofl/zenmarugothic/DESCRIPTION.en_us.html
  ofl/zenmarugothic/ZenMaruGothic-Regular.ttf
  ofl/zenmarugothic/upstream.yaml
Labels: II CJK, - Ready for Review, I Small Fix

#5925 subtree pull googlefonts/lang
  lang/Lib/gflanguages/__init__.py
  lang/Lib/gflanguages/data/languages/th_Thai.textproto
  lang/Lib/gflanguages/languages_public.proto
  lang/Lib/gflanguages/languages_public_pb2.py
  lang/README.md
  lang/dev-requirements.txt
  lang/requirements.txt
  lang/setup.py
  lang/tests/test_data_languages.py
  lang/tox.ini
Labels: I Lang

#5919 Francois One: Version 3.000; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.23] added
  ofl/francoisone/DESCRIPTION.en_us.html
  ofl/francoisone/FrancoisOne-Regular.ttf
  ofl/francoisone/METADATA.pb
  ofl/francoisone/OFL.txt
  ofl/francoisone/upstream.yaml
Labels: III Expand glyphset, -- Needs manager's opinion, I Font Upgrade

#5914 Arima: Version 1.101;gftools[0.9.23] added
  ofl/arima/Arima[wght].ttf
  ofl/arima/DESCRIPTION.en_us.html
  ofl/arima/METADATA.pb
  ofl/arima/upstream.yaml
Labels: -- Needs manager's opinion, I Small Fix, III Improve rendering / layout

#5927 Anuphan: Version 3.001;gftools[0.9.23] added
  ofl/anuphan/Anuphan[wght].ttf
  ofl/anuphan/DESCRIPTION.en_us.html
  ofl/anuphan/METADATA.pb
  ofl/anuphan/OFL.txt
  ofl/anuphan/upstream.yaml
Labels: - Ready for Review, II Indic / Brahmic / Thai / Tai

#5942 Fredoka: added missing designer
  ofl/fredoka/DESCRIPTION.en_us.html
  ofl/fredoka/METADATA.pb
Labels: - Ready for Review, I Description/Metadata/OFL

#5943 Metrophobic description
  ofl/metrophobic/DESCRIPTION.en_us.html
Labels: - Ready for Review, I Description/Metadata/OFL
