Repository google/fonts, pull requests merged in 2023-12, with the labels that each got.

#6784 Noto Sans Sundanese: Version 2.005 added
  ofl/notosanssundanese/METADATA.pb
  ofl/notosanssundanese/NotoSansSundanese[wght].ttf
  ofl/notosanssundanese/upstream.yaml
Labels: I Font Upgrade

#6764 Noto Sans Glagolitic: Version 2.004; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosansglagolitic/METADATA.pb
  ofl/notosansglagolitic/NotoSansGlagolitic-Regular.ttf
  ofl/notosansglagolitic/upstream.yaml
Labels: I Font Upgrade

#7036 Ysabeau Office: Version 2.002; featfreeze: tnum,lnum,ss02 added
  ofl/ysabeauoffice/DESCRIPTION.en_us.html
  ofl/ysabeauoffice/METADATA.pb
  ofl/ysabeauoffice/YsabeauOffice-Italic[wght].ttf
  ofl/ysabeauoffice/YsabeauOffice[wght].ttf
Labels: I Font Upgrade, III Improve rendering / layout

#7037 Ysabeau SC: Version 2.002; featfreeze: smcp added
  ofl/ysabeausc/DESCRIPTION.en_us.html
  ofl/ysabeausc/METADATA.pb
  ofl/ysabeausc/YsabeauSC[wght].ttf
Labels: I Font Upgrade, III Improve rendering / layout

#7028 Kumbh Sans: Version 1.005 added
  ofl/kumbhsans/KumbhSans[YOPQ,wght].ttf
  ofl/kumbhsans/METADATA.pb
Labels: I Small Fix, III Improve rendering / layout

#7070 Update knowledge/glossary/terms/licensing/content.md OFL links
  cc-by-sa/knowledge/glossary/terms/licensing/content.md
Labels: I Knowledge

#7069 Designer added: Oded Ezer (Heebo)
  catalog/designers/odedezer/bio.html
  catalog/designers/odedezer/info.pb
  catalog/designers/odedezer/odedezer.png
Labels: I Designer profile

#7049 Noto Sans PhagsPa: Version 2.004; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosansphagspa/METADATA.pb
  ofl/notosansphagspa/NotoSansPhagsPa-Regular.ttf
  ofl/notosansphagspa/OFL.txt
  ofl/notosansphagspa/upstream.yaml
Labels: I Font Upgrade

#7068 AdventPro : changed designer in metadata.pb
  ofl/adventpro/METADATA.pb
Labels: I Description/Metadata/OFL

#7067 Add designer: VivaRado
  catalog/designers/vivarado/info.pb
  catalog/designers/vivarado/vivarado.png
Labels: I Designer profile

#7044 Asset: Version 1.003; ttfautohint (v1.8.4.7-5d5b) added
  ofl/asset/Asset-Regular.ttf
  ofl/asset/DESCRIPTION.en_us.html
  ofl/asset/METADATA.pb
  ofl/asset/OFL.txt
  ofl/asset/upstream.yaml
Labels: III Improve rendering / layout, I Font Bug

#7071 Update knowledge/glossary/terms/licensing/content.md to fix URL
  cc-by-sa/knowledge/glossary/terms/licensing/content.md
Labels: I Knowledge

#7074 Add minisite URL
  ofl/alegreya/METADATA.pb
  ofl/alegreyasans/METADATA.pb
  ofl/andadapro/METADATA.pb
  ofl/besley/METADATA.pb
  ofl/bonanova/METADATA.pb
  ofl/brygada1918/METADATA.pb
  ofl/cambo/METADATA.pb
  ofl/climatecrisis/METADATA.pb
  ofl/ebgaramond/METADATA.pb
  ofl/figtree/METADATA.pb
  ofl/grandstander/METADATA.pb
  ofl/inter/METADATA.pb
  ofl/jetbrainsmono/METADATA.pb
  ofl/jost/METADATA.pb
  ofl/lexend/METADATA.pb
  ofl/overpass/METADATA.pb
  ofl/piazzolla/METADATA.pb
  ofl/publicsans/METADATA.pb
  ofl/robotoserif/METADATA.pb
  ofl/spacemono/METADATA.pb
  ofl/unbounded/METADATA.pb
  ofl/vollkorn/METADATA.pb
Labels: I Description/Metadata/OFL

#7079 Fix typos in minisite_url metadata fields
  ofl/bonanova/METADATA.pb
  ofl/jetbrainsmono/METADATA.pb
  ofl/unbounded/METADATA.pb
Labels: I Description/Metadata/OFL

#7080 Delist : added Phag+Pa URL
  to_delist.txt
Labels: I Tools / workflow / repo

#7093 Playwrite FR Trad: Version 1.000 added
  ofl/playwritefrtrad/DESCRIPTION.en_us.html
  ofl/playwritefrtrad/METADATA.pb
  ofl/playwritefrtrad/OFL.txt
  ofl/playwritefrtrad/PlaywriteFRTrad[wght].ttf
  ofl/playwritefrtrad/article/ARTICLE.en_us.html
  ofl/playwritefrtrad/upstream.yaml
Labels: I New Font

#7094 Playwrite CO: Version 1.000 added
  ofl/playwriteco/DESCRIPTION.en_us.html
  ofl/playwriteco/METADATA.pb
  ofl/playwriteco/OFL.txt
  ofl/playwriteco/PlaywriteCO[wght].ttf
  ofl/playwriteco/article/ARTICLE.en_us.html
  ofl/playwriteco/upstream.yaml
Labels: I New Font

#7092 Updated to-lists Dec 11
  to_delist.txt
  to_production.txt
  to_sandbox.txt
Labels: I Tools / workflow / repo

#7088 Update ofl/robotoflex/article/ARTICLE.en_us.html with YouTube embed
  ofl/robotoflex/article/ARTICLE.en_us.html
Labels: I Description/Metadata/OFL
