Repository google/fonts, pull requests merged in 2023-04, with the labels that each got.

#6145 Binoy Dominic img updated
  catalog/designers/binoydominic/binoy_dominic.png
  catalog/designers/binoydominic/binoydominic.png
  catalog/designers/binoydominic/info.pb
Labels: I Designer profile

#6147 Agdasima: Version 2.002 added
  ofl/agdasima/Agdasima-Bold.ttf
  ofl/agdasima/Agdasima-Regular.ttf
  ofl/agdasima/DESCRIPTION.en_us.html
  ofl/agdasima/METADATA.pb
  ofl/agdasima/OFL.txt
  ofl/agdasima/upstream.yaml
Labels: - Ready for Review, I New Font

#6039 Noto Sans Nag Mundari: Version 1.000 added
  ofl/notosansnagmundari/DESCRIPTION.en_us.html
  ofl/notosansnagmundari/METADATA.pb
  ofl/notosansnagmundari/NotoSansNagMundari[wght].ttf
  ofl/notosansnagmundari/OFL.txt
  ofl/notosansnagmundari/article/ARTICLE.en_us.html
  ofl/notosansnagmundari/upstream.yaml
Labels: I New Font, -- Needs lang/glyphset update

#6171 Julee: designer's name updated
  ofl/julee/METADATA.pb
Labels: --- to sandbox, I Description/Metadata/OFL

#6168 Update METADATA.pb for Konkhmer Sleokcher
  ofl/konkhmersleokchher/METADATA.pb
Labels: --- to sandbox, I Description/Metadata/OFL

#6172 Add Kana script and languages to DarumaDropOne
  ofl/darumadropone/METADATA.pb
Labels: I Description/Metadata/OFL

#6167 Fix Noto URL in issue template
  .github/ISSUE_TEMPLATE/3_font-bug.md
Labels: I Tools / workflow / repo

#6157 Noto Sans Gujarati: Version 2.104 added
  ofl/notosansgujarati/METADATA.pb
  ofl/notosansgujarati/NotoSansGujarati[wdth,wght].ttf
  ofl/notosansgujarati/upstream.yaml
Labels: - Ready for Review, I Font Upgrade

#6144 Chilanka: Version 1.600 added
  ofl/chilanka/Chilanka-Regular.ttf
  ofl/chilanka/METADATA.pb
  ofl/chilanka/OFL.txt
  ofl/chilanka/upstream.yaml
Labels: - Ready for Review, I Small Fix, II Indic / Brahmic / Thai / Tai

#6102 Frode Helland - Geologica designer
  catalog/designers/frodehelland/frodehelland.png
  catalog/designers/frodehelland/info.pb
Labels: - Ready for Review, I Designer profile

#6104 Sindre Bremnes - Geologica designer
  catalog/designers/sindrebremnes/info.pb
  catalog/designers/sindrebremnes/sindrebremnes.png
Labels: - Ready for Review, I Designer profile

#6131 Noto Serif Devanagari: Version 2.004 added
  ofl/notoserifdevanagari/METADATA.pb
  ofl/notoserifdevanagari/NotoSerifDevanagari[wdth,wght].ttf
  ofl/notoserifdevanagari/upstream.yaml
Labels: - Ready for Review, I Font Upgrade

#6130 Noto Sans Devanagari: Version 2.004 added
  ofl/notosansdevanagari/METADATA.pb
  ofl/notosansdevanagari/NotoSansDevanagari[wdth,wght].ttf
  ofl/notosansdevanagari/upstream.yaml
Labels: - Ready for Review, I Font Upgrade

#5703 Noto Sans Nushu: Version 1.003; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosansnushu/METADATA.pb
  ofl/notosansnushu/NotoSansNushu-Regular.ttf
  ofl/notosansnushu/OFL.txt
  ofl/notosansnushu/article/ARTICLE.en_us.html
  ofl/notosansnushu/upstream.yaml
Labels: - Ready for Review, I Font Upgrade

#6178 Frank Ruhl Libre: Version 6.002;gftools[0.9.28] added
  ofl/frankruhllibre/FrankRuhlLibre[wght].ttf
  ofl/frankruhllibre/METADATA.pb
Labels: - Ready for Review, I Small Fix

#6148 Unbounded: Version 1.701;gftools[0.9.28.dev5+ged2979d] added
  ofl/unbounded/METADATA.pb
  ofl/unbounded/Unbounded[wght].ttf
  ofl/unbounded/upstream.yaml
Labels: - Ready for Review, I Small Fix

#6122 Noto Serif Gujarati: Version 2.103 added
  ofl/notoserifgujarati/METADATA.pb
  ofl/notoserifgujarati/NotoSerifGujarati[wght].ttf
  ofl/notoserifgujarati/upstream.yaml
Labels: - Ready for Review, I Font Upgrade

#6183 Lang pull subtree nandinagari
  lang/CHANGELOG.md
  lang/Lib/gflanguages/data/languages/sa_Nand.textproto
  lang/Lib/gflanguages/data/scripts/Nand.textproto
Labels: - Ready for Review, I Lang

#5700 Noto Sans Nandinagari: Version 1.001; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosansnandinagari/DESCRIPTION.en_us.html
  ofl/notosansnandinagari/METADATA.pb
  ofl/notosansnandinagari/NotoSansNandinagari-Regular.ttf
  ofl/notosansnandinagari/OFL.txt
  ofl/notosansnandinagari/article/ARTICLE.en_us.html
  ofl/notosansnandinagari/upstream.yaml
Labels: I New Font, -- Needs lang/glyphset update

#6181 Lugrasimo: Version 1.001 added
  ofl/lugrasimo/DESCRIPTION.en_us.html
  ofl/lugrasimo/Lugrasimo-Regular.ttf
  ofl/lugrasimo/METADATA.pb
  ofl/lugrasimo/OFL.txt
  ofl/lugrasimo/upstream.yaml
Labels: - Ready for Review, I New Font

#6026 Playfair: Version 2.000;gftools[0.9.27] added
  ofl/playfair/DESCRIPTION.en_us.html
  ofl/playfair/METADATA.pb
  ofl/playfair/OFL.txt
  ofl/playfair/Playfair-Italic[opsz,wdth,wght].ttf
  ofl/playfair/Playfair[opsz,wdth,wght].ttf
  ofl/playfair/upstream.yaml
Labels: - Ready for Review, I New Font

#5736 Noto Sans Kharoshthi: Version 2.004; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosanskharoshthi/METADATA.pb
  ofl/notosanskharoshthi/NotoSansKharoshthi-Regular.ttf
  ofl/notosanskharoshthi/OFL.txt
  ofl/notosanskharoshthi/upstream.yaml
Labels: - Ready for Review, I Font Upgrade

#5739 Noto Sans Syriac: Version 3.000 added
  ofl/notosanssyriac/DESCRIPTION.en_us.html
  ofl/notosanssyriac/METADATA.pb
  ofl/notosanssyriac/NotoSansSyriac-Black.ttf
  ofl/notosanssyriac/NotoSansSyriac-Regular.ttf
  ofl/notosanssyriac/NotoSansSyriac-Thin.ttf
  ofl/notosanssyriac/NotoSansSyriac[wght].ttf
  ofl/notosanssyriac/OFL.txt
  ofl/notosanssyriac/article/ARTICLE.en_us.html
  ofl/notosanssyriac/upstream.yaml
Labels: III VF Replacement, - Ready for Review, I Font Upgrade

#6160 Instrument Sans: Version 1.000;gftools[0.9.27] added
  ofl/instrumentsans/DESCRIPTION.en_us.html
  ofl/instrumentsans/InstrumentSans-Italic[wdth,wght].ttf
  ofl/instrumentsans/InstrumentSans[wdth,wght].ttf
  ofl/instrumentsans/METADATA.pb
  ofl/instrumentsans/OFL.txt
  ofl/instrumentsans/upstream.yaml
Labels: - Ready for Review, I New Font

#6184 Radio Canada: Version 2.104;gftools[0.9.28.dev5+ged2979d] added
  ofl/radiocanada/DESCRIPTION.en_us.html
  ofl/radiocanada/METADATA.pb
  ofl/radiocanada/RadioCanada-Italic[wdth,wght].ttf
  ofl/radiocanada/RadioCanada[wdth,wght].ttf
  ofl/radiocanada/article/ARTICLE.en_us.html
  ofl/radiocanada/article/hero.png
Labels: III Expand glyphset, - Ready for Review, I Font Upgrade

#6202 Noto Sans Symbols 2: Restore sample text
  ofl/notosanssymbols2/METADATA.pb
Labels: - Ready for Review, I Description/Metadata/OFL

#6200 Bebas Neue: category updated
  ofl/bebasneue/METADATA.pb
Labels: - Ready for Review, I Description/Metadata/OFL

#6192 Correcting typo in Nick‘s latest GFK article
  cc-by-sa/knowledge/modules/using_type/lessons/the_complications_of_typographic_size/content.md
Labels: --- to sandbox, I Knowledge

#6205 Tiro Tamil: description fix
  ofl/tirotamil/article/ARTICLE.en_us.html
Labels: --- to sandbox, I Description/Metadata/OFL

#6207 Wixmadefortext: Updated metadatas
  ofl/wixmadefortext/METADATA.pb
Labels: - Ready for Review, I Description/Metadata/OFL

#6206 Wix Made For Text: added description
  ofl/wixmadefortext/DESCRIPTION.en_us.html
Labels: - Ready for Review, I Description/Metadata/OFL

#5759 Noto Serif Balinese: Version 2.005; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notoserifbalinese/METADATA.pb
  ofl/notoserifbalinese/NotoSerifBalinese-Regular.ttf
Labels: --- to sandbox, I Font Upgrade

#6212 Subtree pull Axis Registry introducing `SHRP`
  axisregistry/Lib/axisregistry/__init__.py
  axisregistry/Lib/axisregistry/data/mutation.textproto
  axisregistry/Lib/axisregistry/data/sharpness.textproto
  axisregistry/tests/data/Playfair[opsz,wdth,wght].ttf
  axisregistry/tests/data/Wavefont[ROND,YALN,wght].ttf
  axisregistry/tests/data/Wavefont[ROND,YALN,wght]_STAT.ttx
  axisregistry/tests/test_names.py
Labels: - Ready for Review, I Axis Registry

#6225 Karla description updated
  ofl/karla/DESCRIPTION.en_us.html
Labels: --- to sandbox, I Description/Metadata/OFL

#6209 Monofett: Version 1.100; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.28] added
  ofl/monofett/DESCRIPTION.en_us.html
  ofl/monofett/METADATA.pb
  ofl/monofett/Monofett-Regular.ttf
  ofl/monofett/Monofett.ttf
  ofl/monofett/OFL.txt
  ofl/monofett/upstream.yaml
Labels: --- to sandbox, I Font Upgrade

#6224 Designer updated: Nermin Kahrimanovic
  catalog/designers/nerminkahrimanovic/nermin_kahrimanovic.png
Labels: --- to sandbox, I Designer profile

#6213 Vectro Type - Kablammo designer
  catalog/designers/vectrotype/bio.html
  catalog/designers/vectrotype/info.pb
  catalog/designers/vectrotype/vectrotypefoundry.png
Labels: --- to sandbox, I Designer profile

#6215 Lizy Gershenzon - Kablammo designer
  catalog/designers/lizygershenzon/bio.html
  catalog/designers/lizygershenzon/info.pb
  catalog/designers/lizygershenzon/lizygershenzon.png
Labels: --- to sandbox, I Designer profile

#6220 Daria Cohen - Kablammo designer
  catalog/designers/dariacohen/bio.html
  catalog/designers/dariacohen/dariacohen.png
  catalog/designers/dariacohen/info.pb
Labels: --- to sandbox, I Designer profile
