Repository google/fonts, pull requests merged in 2023-01, with the labels that each got.

#5772 Tiro Telugu: Version 1.53 added
  ofl/tirotelugu/DESCRIPTION.en_us.html
  ofl/tirotelugu/METADATA.pb
  ofl/tirotelugu/TiroTelugu-Italic.ttf
  ofl/tirotelugu/TiroTelugu-Regular.ttf
  ofl/tirotelugu/article/ARTICLE.en_us.html
  ofl/tirotelugu/article/hero.png
  ofl/tirotelugu/upstream.yaml
Labels: I Small Fix

#5779 Sofia Sans Condensed: Version 4.101 added
  ofl/sofiasanscondensed/DESCRIPTION.en_us.html
  ofl/sofiasanscondensed/METADATA.pb
  ofl/sofiasanscondensed/SofiaSansCondensed-Italic[wght].ttf
  ofl/sofiasanscondensed/SofiaSansCondensed[wght].ttf
Labels: - Ready for Review, I Small Fix

#5778 Sofia Sans Semi Condensed: Version 4.101 added
  ofl/sofiasanssemicondensed/DESCRIPTION.en_us.html
  ofl/sofiasanssemicondensed/METADATA.pb
  ofl/sofiasanssemicondensed/SofiaSansSemiCondensed-Italic[wght].ttf
  ofl/sofiasanssemicondensed/SofiaSansSemiCondensed[wght].ttf
Labels: - Ready for Review, I Small Fix

#5777 Sofia Sans Extra Condensed: Version 4.101 added
  ofl/sofiasansextracondensed/DESCRIPTION.en_us.html
  ofl/sofiasansextracondensed/METADATA.pb
  ofl/sofiasansextracondensed/SofiaSansExtraCondensed-Italic[wght].ttf
  ofl/sofiasansextracondensed/SofiaSansExtraCondensed[wght].ttf
Labels: - Ready for Review, I Small Fix

#5776 Sofia Sans: Version 4.101 added
  ofl/sofiasans/DESCRIPTION.en_us.html
  ofl/sofiasans/METADATA.pb
  ofl/sofiasans/SofiaSans-Italic[wght].ttf
  ofl/sofiasans/SofiaSans[wght].ttf
Labels: - Ready for Review, I Small Fix

#5763 Designer updated: Alexandra Korolkova
  catalog/designers/alexandrakorolkova/alexandra_korolkova.png
  catalog/designers/alexandrakorolkova/alexandrakorolkova.png
  catalog/designers/alexandrakorolkova/bio.html
  catalog/designers/alexandrakorolkova/info.pb
Labels: - Ready for Review, I Designer profile

#5752 Designer added: Agung Rohmat
  catalog/designers/agungrohmat/agungrohmat.png
  catalog/designers/agungrohmat/bio.html
  catalog/designers/agungrohmat/info.pb
Labels: - Ready for Review, I Designer profile

#5794 Martian Mono: Version 1.000 added
  ofl/martianmono/DESCRIPTION.en_us.html
  ofl/martianmono/METADATA.pb
  ofl/martianmono/MartianMono[wdth,wght].ttf
Labels: III Expand glyphset, --- to sandbox, I Font Upgrade

#5785 Shantell Sans: Version 1.008;[ac192a2d6] added
  ofl/shantellsans/DESCRIPTION.en_us.html
  ofl/shantellsans/METADATA.pb
  ofl/shantellsans/OFL.txt
  ofl/shantellsans/ShantellSans-Italic[BNCE,INFM,SPAC,wght].ttf
  ofl/shantellsans/ShantellSans[BNCE,INFM,SPAC,wght].ttf
  ofl/shantellsans/upstream.yaml
Labels: - Ready for Review, I New Font

#5788 Catalog updates for Shantell Sans
  catalog/designers/anyadanilova/anyadanilova.png
  catalog/designers/anyadanilova/bio.html
  catalog/designers/anyadanilova/info.pb
  catalog/designers/arrowtype/bio.html
  catalog/designers/shantellmartin/bio.html
  catalog/designers/shantellmartin/info.pb
  catalog/designers/shantellmartin/shantellmartin.png
Labels: - Ready for Review, I Designer profile

#5799 Labrada: Version 1.000 added
  ofl/labrada/DESCRIPTION.en_us.html
  ofl/labrada/Labrada-Italic[wght].ttf
  ofl/labrada/Labrada[wght].ttf
  ofl/labrada/METADATA.pb
  ofl/labrada/OFL.txt
  ofl/labrada/upstream.yaml
Labels: --- to sandbox, I New Font

#5806 Designer added: Vitaly Kuzmin
  catalog/designers/vitalykuzmin/bio.html
  catalog/designers/vitalykuzmin/info.pb
  catalog/designers/vitalykuzmin/vitalykuzmin.png
Labels: - Ready for Review, I Designer profile

#5753 Golos Text: Version 2.004 added
  ofl/golostext/DESCRIPTION.en_us.html
  ofl/golostext/GolosText[wght].ttf
  ofl/golostext/METADATA.pb
  ofl/golostext/OFL.txt
  ofl/golostext/upstream.yaml
Labels: - Ready for Review, I New Font

#5751 Designer added: Duarte Pinto
  catalog/designers/duartepinto/bio.html
  catalog/designers/duartepinto/duartepinto.png
  catalog/designers/duartepinto/info.pb
Labels: - Ready for Review, I Designer profile

#5750 Delicious Handrawn: Version 1.000; ttfautohint (v1.8.4.7-5d5b) added
  ofl/delicioushandrawn/DESCRIPTION.en_us.html
  ofl/delicioushandrawn/DeliciousHandrawn-Regular.ttf
  ofl/delicioushandrawn/METADATA.pb
  ofl/delicioushandrawn/OFL.txt
  ofl/delicioushandrawn/upstream.yaml
Labels: - Ready for Review, I New Font

#5743 Mynerve: Version 1.000; ttfautohint (v1.8.4.7-5d5b) added
  ofl/mynerve/DESCRIPTION.en_us.html
  ofl/mynerve/METADATA.pb
  ofl/mynerve/Mynerve-Regular.ttf
  ofl/mynerve/OFL.txt
  ofl/mynerve/upstream.yaml
Labels: --- to sandbox, I New Font

#5749 Gloock: Version 1.000; ttfautohint (v1.8.4.7-5d5b) added
  ofl/gloock/DESCRIPTION.en_us.html
  ofl/gloock/Gloock-Regular.ttf
  ofl/gloock/METADATA.pb
  ofl/gloock/OFL.txt
  ofl/gloock/upstream.yaml
Labels: --- to sandbox, I New Font

#5820 Gajraj One: Version 1.000 added
  ofl/gajrajone/DESCRIPTION.en_us.html
  ofl/gajrajone/GajrajOne-Regular.ttf
  ofl/gajrajone/METADATA.pb
  ofl/gajrajone/OFL.txt
  ofl/gajrajone/upstream.yaml
Labels: - Ready for Review, I New Font, II Indic / Brahmic / Thai / Tai

#5821 Catalog for Saraubh Sharma (Gajraj One)
  catalog/designers/saurabhsharma/bio.html
  catalog/designers/saurabhsharma/info.pb
  catalog/designers/saurabhsharma/saurabhsharma.png
Labels: - Ready for Review, I Designer profile

#5823 Varela Round: Version 3.010; ttfautohint (v1.8.4.7-5d5b) added
  ofl/varelaround/METADATA.pb
  ofl/varelaround/OFL.txt
  ofl/varelaround/VarelaRound-Regular.ttf
  ofl/varelaround/upstream.yaml
Labels: - Ready for Review, I Font Upgrade

#5815 Gilda Display: Version 1.002; ttfautohint (v1.8.4.7-5d5b) added
  ofl/gildadisplay/DESCRIPTION.en_us.html
  ofl/gildadisplay/GildaDisplay-Regular.ttf
  ofl/gildadisplay/METADATA.pb
  ofl/gildadisplay/OFL.txt
  ofl/gildadisplay/upstream.yaml
Labels: III Expand glyphset, - Ready for Review, I Font Upgrade

#5830 Added minisite_url for Shantell Sans
  ofl/shantellsans/METADATA.pb
Labels: - Ready for Review, I Designer profile, I Small Fix

#5800 Rokkitt: Version 3.103 added
  ofl/rokkitt/DESCRIPTION.en_us.html
  ofl/rokkitt/METADATA.pb
  ofl/rokkitt/Rokkitt-Italic[wght].ttf
  ofl/rokkitt/Rokkitt[wght].ttf
  ofl/rokkitt/upstream.yaml
Labels: III Expand styles, - Ready for Review, I Font Upgrade

#5833 Fauna One: Version 2.001; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.23] added
  ofl/faunaone/DESCRIPTION.en_us.html
  ofl/faunaone/FaunaOne-Regular.ttf
  ofl/faunaone/METADATA.pb
  ofl/faunaone/OFL.txt
  ofl/faunaone/upstream.yaml
Labels: III Expand glyphset, - Ready for Review, I Font Upgrade

#5848 Phudu: Version 1.005;gftools[0.9.23] added
  ofl/phudu/DESCRIPTION.en_us.html
  ofl/phudu/METADATA.pb
  ofl/phudu/OFL.txt
  ofl/phudu/Phudu[wght].ttf
  ofl/phudu/upstream.yaml
Labels: - Ready for Review, I New Font

#5843 Updated IBM Plex descriptions on request of Mike Abbink
  ofl/ibmplexmono/DESCRIPTION.en_us.html
  ofl/ibmplexsans/DESCRIPTION.en_us.html
  ofl/ibmplexsansarabic/DESCRIPTION.en_us.html
  ofl/ibmplexsanscondensed/DESCRIPTION.en_us.html
  ofl/ibmplexsansdevanagari/DESCRIPTION.en_us.html
  ofl/ibmplexsanshebrew/DESCRIPTION.en_us.html
  ofl/ibmplexsansjp/DESCRIPTION.en_us.html
  ofl/ibmplexsanskr/DESCRIPTION.en_us.html
  ofl/ibmplexsansthai/DESCRIPTION.en_us.html
  ofl/ibmplexsansthailooped/DESCRIPTION.en_us.html
  ofl/ibmplexserif/DESCRIPTION.en_us.html
Labels: - Ready for Review, I Description/Metadata/OFL

#5844 Designer bio for Duong Tran (Phudu)
  catalog/designers/duongtran/bio.html
  catalog/designers/duongtran/duongtran.png
  catalog/designers/duongtran/info.pb
Labels: - Ready for Review, I Designer profile
