Repository google/fonts, pull requests merged in 2023-08, with the labels that each got.

#6565 Mako: Version 1.100; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.33] added
  ofl/mako/DESCRIPTION.en_us.html
  ofl/mako/METADATA.pb
  ofl/mako/Mako-Regular.ttf
  ofl/mako/OFL.txt
  ofl/mako/upstream.yaml
Labels: III Expand glyphset, I Font Upgrade

#6635 Update minisite URL in METADATA.pb for Wavefont
  ofl/wavefont/METADATA.pb
Labels: I Description/Metadata/OFL

#6612 Use sd_Sind, not sa_Sind, for Khudawadi
  ofl/notosanskhudawadi/METADATA.pb
Labels: I Lang

#6594 Norican: Version 1.100; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.33] added
  ofl/norican/DESCRIPTION.en_us.html
  ofl/norican/METADATA.pb
  ofl/norican/Norican-Regular.ttf
  ofl/norican/OFL.txt
  ofl/norican/upstream.yaml
Labels: III Expand glyphset, I Font Upgrade

#6359 Inclusive Sans: Version 1.000; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.30] added
  ofl/inclusivesans/DESCRIPTION.en_us.html
  ofl/inclusivesans/InclusiveSans-Italic.ttf
  ofl/inclusivesans/InclusiveSans-Regular.ttf
  ofl/inclusivesans/METADATA.pb
  ofl/inclusivesans/OFL.txt
  ofl/inclusivesans/upstream.yaml
Labels: I New Font

#6645 updated to_*lists 29th Aug.
  to_delist.txt
  to_production.txt
  to_sandbox.txt
Labels: I Tools / workflow / repo

#6627 Lateef: Version 4.200 added
  ofl/lateef/Lateef-Bold.ttf
  ofl/lateef/Lateef-ExtraBold.ttf
  ofl/lateef/Lateef-ExtraLight.ttf
  ofl/lateef/Lateef-Light.ttf
  ofl/lateef/Lateef-Medium.ttf
  ofl/lateef/Lateef-Regular.ttf
  ofl/lateef/Lateef-SemiBold.ttf
  ofl/lateef/METADATA.pb
  ofl/lateef/OFL.txt
  ofl/lateef/upstream.yaml
Labels: III Expand glyphset, I Font Upgrade

#6585 Mooli: Version 1.000; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.33] added
  ofl/mooli/DESCRIPTION.en_us.html
  ofl/mooli/METADATA.pb
  ofl/mooli/Mooli-Regular.ttf
  ofl/mooli/OFL.txt
  ofl/mooli/upstream.yaml
Labels: I New Font

#6648 Lang v055
  lang/Lib/gflanguages/data/languages/sd_Khud.textproto
  lang/Lib/gflanguages/data/languages/sd_Sind.textproto
Labels: I Lang

#6650 updated lists 30th Aug
  to_delist.txt
  to_production.txt
  to_sandbox.txt
Labels: I Tools / workflow / repo
