Repository google/fonts, pull requests merged in 2023-11, with the labels that each got.

#6765 Noto Serif Georgian: Version 2.003 added
  ofl/notoserifgeorgian/METADATA.pb
  ofl/notoserifgeorgian/NotoSerifGeorgian[wdth,wght].ttf
  ofl/notoserifgeorgian/upstream.yaml
Labels: I Font Upgrade

#6763 Noto Serif Dogra: Version 1.007; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notoserifdogra/METADATA.pb
  ofl/notoserifdogra/NotoSerifDogra-Regular.ttf
  ofl/notoserifdogra/upstream.yaml
Labels: I Font Upgrade

#6932 Narnoor: Version 3.000 added
  ofl/narnoor/DESCRIPTION.en_us.html
  ofl/narnoor/METADATA.pb
  ofl/narnoor/Narnoor-Bold.ttf
  ofl/narnoor/Narnoor-ExtraBold.ttf
  ofl/narnoor/Narnoor-Medium.ttf
  ofl/narnoor/Narnoor-Regular.ttf
  ofl/narnoor/Narnoor-SemiBold.ttf
  ofl/narnoor/OFL.txt
  ofl/narnoor/upstream.yaml
Labels: I Font Upgrade, II Indic / Brahmic / Thai / Tai

#6936 updated lists November 3rd
  to_delist.txt
  to_production.txt
  to_sandbox.txt
Labels: I Tools / workflow / repo

#6937 Open Sans: Version 3.000 added
  ofl/opensans/METADATA.pb
  ofl/opensans/OpenSans-Italic[wdth,wght].ttf
  ofl/opensans/OpenSans[wdth,wght].ttf
  ofl/opensans/upstream.yaml
Labels: I Font Upgrade

#6771 Noto Sans Lydian: Version 2.002; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosanslydian/METADATA.pb
  ofl/notosanslydian/NotoSansLydian-Regular.ttf
  ofl/notosanslydian/upstream.yaml
Labels: I Font Upgrade

#6953 Subtree pull Axis Registry introducing `BLED`, `SCAN`, and `SHLN`
  axisregistry/Lib/axisregistry/__init__.py
  axisregistry/Lib/axisregistry/data/bleed.textproto
  axisregistry/Lib/axisregistry/data/scanlines.textproto
  axisregistry/Lib/axisregistry/data/shadow_length.textproto
  axisregistry/Lib/axisregistry/data/sharpness.textproto
Labels: I Axis Registry

#6929 Alike: Version 1.301; ttfautohint (v1.8.4.7-5d5b) added
  ofl/alike/Alike-Regular.ttf
  ofl/alike/DESCRIPTION.en_us.html
  ofl/alike/FONTLOG.txt
  ofl/alike/METADATA.pb
  ofl/alike/OFL.txt
  ofl/alike/upstream.yaml
Labels: I Font Upgrade

#6917 Workbench: Version 2.000;gftools[0.9.33] added
  ofl/workbench/DESCRIPTION.en_us.html
  ofl/workbench/METADATA.pb
  ofl/workbench/OFL.txt
  ofl/workbench/Workbench[BLED,SCAN].ttf
  ofl/workbench/upstream.yaml
Labels: I New Font

#6966 add font tagging data
  tags/all/families.csv
Labels: I Tools / workflow / repo

#6961 Honk: Version 1.000 added
  ofl/honk/DESCRIPTION.en_us.html
  ofl/honk/Honk[MORF,SHLN].ttf
  ofl/honk/METADATA.pb
  ofl/honk/OFL.txt
  ofl/honk/upstream.yaml
Labels: I New Font, II Color font

#6970 Lang v059
  lang/Lib/gflanguages/data/languages/sd_Khoj.textproto
Labels: I Lang

#6969 Open Sans: Version 3.003 added
  ofl/opensans/METADATA.pb
  ofl/opensans/OFL.txt
  ofl/opensans/OpenSans-Italic[wdth,wght].ttf
  ofl/opensans/OpenSans[wdth,wght].ttf
Labels: I Font Upgrade

#6971 Updated lists 16th of November
  to_production.txt
  to_sandbox.txt
Labels: I Tools / workflow / repo

#6990 PPS about draft
  ofl/playpensans/DESCRIPTION.en_us.html
  ofl/playpensans/article/ARTICLE.en_us.html
  ofl/playpensans/article/PlaypenSans-about1a.png
  ofl/playpensans/article/PlaypenSans-about2.png
  ofl/playpensans/article/PlaypenSans-about2a.png
  ofl/playpensans/article/PlaypenSans-about3a.png
  ofl/playpensans/article/e-birthday-cake.png
  ofl/playpensans/article/e-color-palette.png
  ofl/playpensans/article/e-index-pointing.png
  ofl/playpensans/article/e-shooting-star.png
Labels: I Tools / workflow / repo

#6985 Update Linefont About page text
  ofl/linefont/DESCRIPTION.en_us.html
Labels: I Description/Metadata/OFL

#6984 Update Wavefont About documentation
  ofl/wavefont/DESCRIPTION.en_us.html
Labels: I Description/Metadata/OFL

#6976 Vernon Adams: updated biography
  catalog/designers/vernonadams/bio.html
Labels: I Designer profile

#6992 Denis Masharov: updated (Ruslan)
  catalog/designers/denismasharov/bio.html
Labels: I Designer profile

#6996 PPS about test 2
  ofl/playpensans/article/ARTICLE.en_us.html
Labels: I Tools / workflow / repo

#6938 Noto Sans Mongolian: Version 3.000; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosansmongolian/METADATA.pb
  ofl/notosansmongolian/NotoSansMongolian-Regular.ttf
  ofl/notosansmongolian/upstream.yaml
Labels: I Font Upgrade

#6995 Hedvig: designer added (Hedvig letters)
  catalog/designers/hedvig/bio.html
  catalog/designers/hedvig/hedvig.png
  catalog/designers/hedvig/info.pb
Labels: I Designer profile

#6973 Sancreek: Version 1.100; ttfautohint (v1.8.4.7-5d5b) added
  ofl/sancreek/DESCRIPTION.en_us.html
  ofl/sancreek/METADATA.pb
  ofl/sancreek/OFL.txt
  ofl/sancreek/Sancreek-Regular.ttf
  ofl/sancreek/upstream.yaml
Labels: I Font Upgrade

#6994 Hedvig Letters (Sans+Serif): description+designer updated
  ofl/hedvigletterssans/DESCRIPTION.en_us.html
  ofl/hedvigletterssans/METADATA.pb
  ofl/hedviglettersserif/DESCRIPTION.en_us.html
  ofl/hedviglettersserif/METADATA.pb
Labels: I Description/Metadata/OFL

#6762 Noto Sans Coptic: Version 2.004; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosanscoptic/METADATA.pb
  ofl/notosanscoptic/NotoSansCoptic-Regular.ttf
  ofl/notosanscoptic/upstream.yaml
Labels: I Font Upgrade

#6998 Rubik Broken Fax: Version 2.201 added
  ofl/rubikbrokenfax/DESCRIPTION.en_us.html
  ofl/rubikbrokenfax/METADATA.pb
  ofl/rubikbrokenfax/OFL.txt
  ofl/rubikbrokenfax/RubikBrokenFax-Regular.ttf
  ofl/rubikbrokenfax/upstream.yaml
Labels: I New Font

#7001 Playpen Sans About: deleting the table
  ofl/playpensans/article/ARTICLE.en_us.html
Labels: I Tools / workflow / repo

#7000 Rubik Doodle Triangles: Version 2.201 added
  ofl/rubikdoodletriangles/DESCRIPTION.en_us.html
  ofl/rubikdoodletriangles/METADATA.pb
  ofl/rubikdoodletriangles/OFL.txt
  ofl/rubikdoodletriangles/RubikDoodleTriangles-Regular.ttf
  ofl/rubikdoodletriangles/upstream.yaml
Labels: I New Font

#6999 Rubik Doodle Shadow: Version 2.201 added
  ofl/rubikdoodleshadow/DESCRIPTION.en_us.html
  ofl/rubikdoodleshadow/METADATA.pb
  ofl/rubikdoodleshadow/OFL.txt
  ofl/rubikdoodleshadow/RubikDoodleShadow-Regular.ttf
  ofl/rubikdoodleshadow/upstream.yaml
Labels: I New Font

#7003 Rubik Lines: Version 2.201 added
  ofl/rubiklines/DESCRIPTION.en_us.html
  ofl/rubiklines/METADATA.pb
  ofl/rubiklines/OFL.txt
  ofl/rubiklines/RubikLines-Regular.ttf
  ofl/rubiklines/upstream.yaml
Labels: I New Font

#7004 Rubik Scribble: Version 2.103 added
  ofl/rubikscribble/DESCRIPTION.en_us.html
  ofl/rubikscribble/METADATA.pb
  ofl/rubikscribble/OFL.txt
  ofl/rubikscribble/RubikScribble-Regular.ttf
  ofl/rubikscribble/upstream.yaml
Labels: I New Font

#7005 Rubik Maps: Version 2.201 added
  ofl/rubikmaps/DESCRIPTION.en_us.html
  ofl/rubikmaps/METADATA.pb
  ofl/rubikmaps/OFL.txt
  ofl/rubikmaps/RubikMaps-Regular.ttf
  ofl/rubikmaps/upstream.yaml
Labels: I New Font

#7008 Kalnia: adding more images to the About section
  ofl/kalnia/article/ARTICLE.en_us.html
  ofl/kalnia/article/KalniaTypeface-01.png
  ofl/kalnia/article/KalniaTypeface-02.png
  ofl/kalnia/article/KalniaTypeface-03.png
  ofl/kalnia/article/KalniaTypeface-04.png
Labels: I Description/Metadata/OFL

#7010 Updated lists 24th of November
  to_production.txt
  to_sandbox.txt
Labels: I Tools / workflow / repo

#6857 Noto Naskh Arabic: Version 2.017 added
  ofl/notonaskharabic/METADATA.pb
  ofl/notonaskharabic/NotoNaskhArabic[wght].ttf
  ofl/notonaskharabic/upstream.yaml
Labels: I Font Upgrade

#6859 Noto Sans Arabic: Version 2.011 added
  ofl/notosansarabic/METADATA.pb
  ofl/notosansarabic/NotoSansArabic[wdth,wght].ttf
  ofl/notosansarabic/OFL.txt
  ofl/notosansarabic/upstream.yaml
Labels: I Font Upgrade, II Arabic / Hebrew / Semitic / RTL

#6993 Ruslan Display: HOTFIX version 1.001
  ofl/ruslandisplay/METADATA.pb
  ofl/ruslandisplay/OFL.txt
  ofl/ruslandisplay/RuslanDisplay-Regular.ttf
  ofl/ruslandisplay/RuslanDisplay.ttf
Labels: I Small Fix

#6948 Heebo: Version 3.100 added
  ofl/heebo/DESCRIPTION.en_us.html
  ofl/heebo/Heebo[wght].ttf
  ofl/heebo/METADATA.pb
  ofl/heebo/OFL.txt
  ofl/heebo/upstream.yaml
Labels: I Font Upgrade, II Arabic / Hebrew / Semitic / RTL

#7006 Playpen Sans: Version 1.002 added
  ofl/playpensans/METADATA.pb
  ofl/playpensans/PlaypenSans[wght].ttf
  ofl/playpensans/upstream.yaml
Labels: I Font Upgrade

#7027 PPS Article refactored
  ofl/playpensans/article/ARTICLE.en_us.html
  ofl/playpensans/article/PlaypenSans-about1a.png
  ofl/playpensans/article/PlaypenSans-about2.png
  ofl/playpensans/article/PlaypenSans-about3a.png
  ofl/playpensans/article/PlaypenSans-about4a.png
  ofl/playpensans/article/e-birthday-cake.png
  ofl/playpensans/article/e-color-palette.png
  ofl/playpensans/article/e-index-pointing.png
  ofl/playpensans/article/e-shooting-star.png
Labels: I Description/Metadata/OFL

#7031 Rubik Glitch Pop: Version 2.201 added
  ofl/rubikglitchpop/DESCRIPTION.en_us.html
  ofl/rubikglitchpop/METADATA.pb
  ofl/rubikglitchpop/OFL.txt
  ofl/rubikglitchpop/RubikGlitchPop-Regular.ttf
  ofl/rubikglitchpop/upstream.yaml
Labels: I New Font

#7032 Emoji subset added to PPS metadata
  ofl/playpensans/METADATA.pb
Labels: I Description/Metadata/OFL

#7034 Ysabeau: Version 2.002 added
  ofl/ysabeau/DESCRIPTION.en_us.html
  ofl/ysabeau/METADATA.pb
  ofl/ysabeau/Ysabeau-Italic[wght].ttf
  ofl/ysabeau/Ysabeau[wght].ttf
Labels: I Font Upgrade, III Improve rendering / layout

#7035 Ysabeau Infant: Version 2.002; featfreeze: ss01,ss02,lnum added
  ofl/ysabeauinfant/DESCRIPTION.en_us.html
  ofl/ysabeauinfant/METADATA.pb
  ofl/ysabeauinfant/YsabeauInfant-Italic[wght].ttf
  ofl/ysabeauinfant/YsabeauInfant[wght].ttf
Labels: I Font Upgrade, III Improve rendering / layout

#7041 Playpen Sans: Version 1.003 added
  ofl/playpensans/METADATA.pb
  ofl/playpensans/PlaypenSans[wght].ttf
  ofl/playpensans/article/ARTICLE.en_us.html
Labels: I New Font
