Repository google/fonts, pull requests merged in 2023-07, with the labels that each got.

#5259 Noto Sans Deseret: Version 2.001; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosansdeseret/METADATA.pb
  ofl/notosansdeseret/NotoSansDeseret-Regular.ttf
  ofl/notosansdeseret/OFL.txt
  ofl/notosansdeseret/upstream.yaml
Labels: I Font Upgrade

#5258 Noto Sans Brahmi: Version 2.003; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosansbrahmi/METADATA.pb
  ofl/notosansbrahmi/NotoSansBrahmi-Regular.ttf
  ofl/notosansbrahmi/OFL.txt
  ofl/notosansbrahmi/upstream.yaml
Labels: I Font Upgrade

#6229 REM: Version 1.004;gftools[0.9.28] added
  ofl/rem/DESCRIPTION.en_us.html
  ofl/rem/METADATA.pb
  ofl/rem/OFL.txt
  ofl/rem/REM-Italic[wght].ttf
  ofl/rem/REM[wght].ttf
  ofl/rem/upstream.yaml
Labels: I New Font

#6415 Sen: Version 2.000;gftools[0.9.30] added
  ofl/sen/DESCRIPTION.en_us.html
  ofl/sen/METADATA.pb
  ofl/sen/OFL.txt
  ofl/sen/Sen-Bold.ttf
  ofl/sen/Sen-ExtraBold.ttf
  ofl/sen/Sen-Regular.ttf
  ofl/sen/Sen[wght].ttf
  ofl/sen/upstream.yaml
Labels: III VF Replacement, I Font Upgrade

#5260 Noto Sans Cuneiform: Version 2.001; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosanscuneiform/METADATA.pb
  ofl/notosanscuneiform/NotoSansCuneiform-Regular.ttf
  ofl/notosanscuneiform/OFL.txt
  ofl/notosanscuneiform/upstream.yaml
Labels: I Font Upgrade

#5261 Noto Sans Egyptian Hieroglyphs: Version 2.001; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosansegyptianhieroglyphs/METADATA.pb
  ofl/notosansegyptianhieroglyphs/NotoSansEgyptianHieroglyphs-Regular.ttf
  ofl/notosansegyptianhieroglyphs/OFL.txt
  ofl/notosansegyptianhieroglyphs/upstream.yaml
Labels: I Font Upgrade

#5262 Noto Sans Linear B: Version 2.002; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosanslinearb/METADATA.pb
  ofl/notosanslinearb/NotoSansLinearB-Regular.ttf
  ofl/notosanslinearb/OFL.txt
  ofl/notosanslinearb/upstream.yaml
Labels: I Font Upgrade

#5263 Noto Sans Linear A: Version 2.001; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosanslineara/METADATA.pb
  ofl/notosanslineara/NotoSansLinearA-Regular.ttf
  ofl/notosanslineara/OFL.txt
  ofl/notosanslineara/upstream.yaml
Labels: I Font Upgrade

#5264 Noto Sans Lydian: Version 2.001; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosanslydian/METADATA.pb
  ofl/notosanslydian/NotoSansLydian-Regular.ttf
  ofl/notosanslydian/OFL.txt
  ofl/notosanslydian/upstream.yaml
Labels: I Font Upgrade

#6497 updated sandbox list
  to_sandbox.txt
Labels: I Tools / workflow / repo

#6503 Borel: Version 1.002; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.32] added
  ofl/borel/Borel-Regular.ttf
  ofl/borel/DESCRIPTION.en_us.html
  ofl/borel/METADATA.pb
  ofl/borel/OFL.txt
  ofl/borel/upstream.yaml
Labels: I New Font

#6504 Designer: Rosalie Wagner (Borel)
  catalog/designers/rosaliewagner/bio.html
  catalog/designers/rosaliewagner/info.pb
  catalog/designers/rosaliewagner/rosaliewagner.png
Labels: I Designer profile

#6501 Ruwudu: Version 3.000 added
  ofl/ruwudu/DESCRIPTION.en_us.html
  ofl/ruwudu/METADATA.pb
  ofl/ruwudu/OFL.txt
  ofl/ruwudu/Ruwudu-Bold.ttf
  ofl/ruwudu/Ruwudu-Medium.ttf
  ofl/ruwudu/Ruwudu-Regular.ttf
  ofl/ruwudu/Ruwudu-SemiBold.ttf
  ofl/ruwudu/upstream.yaml
Labels: I New Font, II Arabic / Hebrew / Semitic / RTL

#6508 Namdhinggo: Version 3.001 added
  ofl/namdhinggo/DESCRIPTION.en_us.html
  ofl/namdhinggo/METADATA.pb
  ofl/namdhinggo/Namdhinggo-Bold.ttf
  ofl/namdhinggo/Namdhinggo-ExtraBold.ttf
  ofl/namdhinggo/Namdhinggo-Medium.ttf
  ofl/namdhinggo/Namdhinggo-Regular.ttf
  ofl/namdhinggo/Namdhinggo-SemiBold.ttf
  ofl/namdhinggo/OFL.txt
  ofl/namdhinggo/upstream.yaml
Labels: I New Font, II Indic / Brahmic / Thai / Tai

#6509 Dai Banna SIL: Version 4.000 added
  ofl/daibannasil/DESCRIPTION.en_us.html
  ofl/daibannasil/DaiBannaSIL-Bold.ttf
  ofl/daibannasil/DaiBannaSIL-BoldItalic.ttf
  ofl/daibannasil/DaiBannaSIL-Italic.ttf
  ofl/daibannasil/DaiBannaSIL-Light.ttf
  ofl/daibannasil/DaiBannaSIL-LightItalic.ttf
  ofl/daibannasil/DaiBannaSIL-Medium.ttf
  ofl/daibannasil/DaiBannaSIL-MediumItalic.ttf
  ofl/daibannasil/DaiBannaSIL-Regular.ttf
  ofl/daibannasil/DaiBannaSIL-SemiBold.ttf
  ofl/daibannasil/DaiBannaSIL-SemiBoldItalic.ttf
  ofl/daibannasil/METADATA.pb
  ofl/daibannasil/OFL.txt
  ofl/daibannasil/upstream.yaml
Labels: I New Font, II Indic / Brahmic / Thai / Tai

#5265 Noto Sans Mahajani: Version 2.003; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosansmahajani/METADATA.pb
  ofl/notosansmahajani/NotoSansMahajani-Regular.ttf
  ofl/notosansmahajani/OFL.txt
  ofl/notosansmahajani/upstream.yaml
Labels: I Font Upgrade

#5266 Noto Sans Manichaean: Version 2.004; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosansmanichaean/METADATA.pb
  ofl/notosansmanichaean/NotoSansManichaean-Regular.ttf
  ofl/notosansmanichaean/OFL.txt
  ofl/notosansmanichaean/upstream.yaml
Labels: I Font Upgrade

#5267 Noto Sans Phoenician: Version 2.001; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosansphoenician/METADATA.pb
  ofl/notosansphoenician/NotoSansPhoenician-Regular.ttf
  ofl/notosansphoenician/OFL.txt
  ofl/notosansphoenician/upstream.yaml
Labels: I Font Upgrade

#5268 Noto Sans Ogham: Version 2.001; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosansogham/METADATA.pb
  ofl/notosansogham/NotoSansOgham-Regular.ttf
  ofl/notosansogham/OFL.txt
  ofl/notosansogham/upstream.yaml
Labels: I Font Upgrade

#6511 Adam Jagosz: designer added (Tektur)
  catalog/designers/adamjagosz/adamjagosz.png
  catalog/designers/adamjagosz/bio.html
  catalog/designers/adamjagosz/info.pb
Labels: I Designer profile

#6510 Lisu Bosa: Version 2.000 added
  ofl/lisubosa/DESCRIPTION.en_us.html
  ofl/lisubosa/LisuBosa-Black.ttf
  ofl/lisubosa/LisuBosa-BlackItalic.ttf
  ofl/lisubosa/LisuBosa-Bold.ttf
  ofl/lisubosa/LisuBosa-BoldItalic.ttf
  ofl/lisubosa/LisuBosa-ExtraBold.ttf
  ofl/lisubosa/LisuBosa-ExtraBoldItalic.ttf
  ofl/lisubosa/LisuBosa-ExtraLight.ttf
  ofl/lisubosa/LisuBosa-ExtraLightItalic.ttf
  ofl/lisubosa/LisuBosa-Italic.ttf
  ofl/lisubosa/LisuBosa-Light.ttf
  ofl/lisubosa/LisuBosa-LightItalic.ttf
  ofl/lisubosa/LisuBosa-Medium.ttf
  ofl/lisubosa/LisuBosa-MediumItalic.ttf
  ofl/lisubosa/LisuBosa-Regular.ttf
  ofl/lisubosa/LisuBosa-SemiBold.ttf
  ofl/lisubosa/LisuBosa-SemiBoldItalic.ttf
  ofl/lisubosa/METADATA.pb
  ofl/lisubosa/OFL.txt
  ofl/lisubosa/upstream.yaml
Labels: I New Font, II Indic / Brahmic / Thai / Tai, -- Needs lang/glyphset update

#6512 updated to_sandbox list
  to_sandbox.txt
Labels: I Tools / workflow / repo

#6513 Borel: Version 1.003; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.32] added
  ofl/borel/Borel-Regular.ttf
  ofl/borel/METADATA.pb
  ofl/borel/upstream.yaml
Labels: I Small Fix

#6538 Ruwudu: Version 3.000 added
  ofl/ruwudu/METADATA.pb
Labels: I Description/Metadata/OFL, II Arabic / Hebrew / Semitic / RTL

#6539 Handjet: updated description
  ofl/handjet/DESCRIPTION.en_us.html
Labels: I Description/Metadata/OFL

#6541 updated lists
  to_production.txt
  to_sandbox.txt
Labels: I API / Website / Platform

#5276 Noto Sans Anatolian Hieroglyphs: Version 2.001; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosansanatolianhieroglyphs/METADATA.pb
  ofl/notosansanatolianhieroglyphs/NotoSansAnatolianHieroglyphs-Regular.ttf
  ofl/notosansanatolianhieroglyphs/OFL.txt
  ofl/notosansanatolianhieroglyphs/upstream.yaml
Labels: I Font Upgrade

#5277 Noto Sans Carian: Version 2.001; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosanscarian/METADATA.pb
  ofl/notosanscarian/NotoSansCarian-Regular.ttf
  ofl/notosanscarian/OFL.txt
  ofl/notosanscarian/upstream.yaml
Labels: I Font Upgrade

#5270 Noto Sans Gothic: Version 2.001; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosansgothic/METADATA.pb
  ofl/notosansgothic/NotoSansGothic-Regular.ttf
  ofl/notosansgothic/OFL.txt
  ofl/notosansgothic/upstream.yaml
Labels: I Font Upgrade

#5271 Noto Sans Khudawadi: Version 2.003; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosanskhudawadi/METADATA.pb
  ofl/notosanskhudawadi/NotoSansKhudawadi-Regular.ttf
  ofl/notosanskhudawadi/OFL.txt
  ofl/notosanskhudawadi/upstream.yaml
Labels: I Font Upgrade

#5272 Noto Sans Tirhuta: Version 2.003; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosanstirhuta/METADATA.pb
  ofl/notosanstirhuta/NotoSansTirhuta-Regular.ttf
  ofl/notosanstirhuta/OFL.txt
  ofl/notosanstirhuta/upstream.yaml
Labels: I Font Upgrade

#6544 Updated lists
  to_production.txt
  to_sandbox.txt
Labels: I API / Website / Platform

#6527 Subtree pull Axis Registry introducing `ZROT`
  axisregistry/Lib/axisregistry/data/z_rotation.textproto
Labels: I Axis Registry

#6484 Roboto Flex: Version 3.200;gftools[0.9.32] added
  ofl/robotoflex/RobotoFlex[GRAD,XOPQ,XTRA,YOPQ,YTAS,YTDE,YTFI,YTLC,YTUC,opsz,slnt,wdth,wght].ttf
  ofl/robotoflex/upstream.yaml
Labels: I Font Upgrade

#5282 Noto Sans Mandaic: Version 2.002; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosansmandaic/METADATA.pb
  ofl/notosansmandaic/NotoSansMandaic-Regular.ttf
  ofl/notosansmandaic/OFL.txt
  ofl/notosansmandaic/upstream.yaml
Labels: I Font Upgrade

#5284 Noto Sans Imperial Aramaic: Version 2.001; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosansimperialaramaic/METADATA.pb
  ofl/notosansimperialaramaic/NotoSansImperialAramaic-Regular.ttf
  ofl/notosansimperialaramaic/OFL.txt
  ofl/notosansimperialaramaic/upstream.yaml
Labels: I Font Upgrade

#6548 Lang v053
  lang/Lib/gflanguages/data/languages/doi_Dogr.textproto
  lang/Lib/gflanguages/data/languages/hi_Mahj.textproto
  lang/Lib/gflanguages/data/languages/lep_Lepc.textproto
  lang/Lib/gflanguages/data/languages/sat_Olck.textproto
  lang/Lib/gflanguages/data/languages/sd_Khoj.textproto
  lang/Lib/gflanguages/data/languages/sd_Khud.textproto
  lang/Lib/gflanguages/data/languages/sd_Sind.textproto
Labels: I Lang

#6549 Ruwudu: Version 3.000 added
  ofl/ruwudu/METADATA.pb
Labels: I New Font, II Arabic / Hebrew / Semitic / RTL

#6551 to_lists updated
  to_delist.txt
  to_production.txt
  to_sandbox.txt
Labels: I API / Website / Platform

#6514 Oswald: Version 4.103;gftools[0.9.32] added
  ofl/oswald/DESCRIPTION.en_us.html
  ofl/oswald/METADATA.pb
  ofl/oswald/OFL.txt
  ofl/oswald/Oswald[wght].ttf
  ofl/oswald/upstream.yaml
Labels: III Expand glyphset, I Font Upgrade, III Improve rendering / layout

#6522 ADLaM Display: Version 2.000; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.28] added
  ofl/adlamdisplay/ADLaMDisplay-Regular.ttf
  ofl/adlamdisplay/DESCRIPTION.en_us.html
  ofl/adlamdisplay/METADATA.pb
  ofl/adlamdisplay/OFL.txt
  ofl/adlamdisplay/upstream.yaml
Labels: I New Font

#6560 Teko: Version 2.000;gftools[0.9.28.dev9+g7d2139d.d20230707] added
  .github/workflows/test.yaml
  ofl/teko/DESCRIPTION.en_us.html
  ofl/teko/METADATA.pb
  ofl/teko/OFL.txt
  ofl/teko/Teko-Bold.ttf
  ofl/teko/Teko-Light.ttf
  ofl/teko/Teko-Medium.ttf
  ofl/teko/Teko-Regular.ttf
  ofl/teko/Teko-SemiBold.ttf
  ofl/teko/Teko[wght].ttf
  ofl/teko/upstream.yaml
Labels: - In Progress

#6523 Bricolage Grotesque: Version 1.001;gftools[0.9.32] added
  ofl/bricolagegrotesque/BricolageGrotesque[opsz,wdth,wght].ttf
  ofl/bricolagegrotesque/DESCRIPTION.en_us.html
  ofl/bricolagegrotesque/METADATA.pb
Labels: I New Font

#5286 Noto Sans Inscriptional Pahlavi: Version 2.003; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosansinscriptionalpahlavi/METADATA.pb
  ofl/notosansinscriptionalpahlavi/NotoSansInscriptionalPahlavi-Regular.ttf
  ofl/notosansinscriptionalpahlavi/OFL.txt
  ofl/notosansinscriptionalpahlavi/upstream.yaml
Labels: I Font Upgrade

#5288 Noto Sans Mayan Numerals: Version 2.001; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosansmayannumerals/METADATA.pb
  ofl/notosansmayannumerals/NotoSansMayanNumerals-Regular.ttf
  ofl/notosansmayannumerals/OFL.txt
  ofl/notosansmayannumerals/upstream.yaml
Labels: I Font Upgrade

#5285 Noto Sans Indic Siyaq Numbers: Version 2.002; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosansindicsiyaqnumbers/METADATA.pb
  ofl/notosansindicsiyaqnumbers/NotoSansIndicSiyaqNumbers-Regular.ttf
  ofl/notosansindicsiyaqnumbers/OFL.txt
  ofl/notosansindicsiyaqnumbers/upstream.yaml
Labels: I Font Upgrade

#5287 Noto Sans Lycian: Version 2.001; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosanslycian/METADATA.pb
  ofl/notosanslycian/NotoSansLycian-Regular.ttf
  ofl/notosanslycian/OFL.txt
  ofl/notosanslycian/upstream.yaml
Labels: I Font Upgrade, -- Needs lang/glyphset update

#6562 update Gulzar article
  ofl/gulzar/article/ARTICLE.en_us.html
Labels: I Description/Metadata/OFL

#6554 Subtree pull Axis Registry updating `ZROT`
  axisregistry/Lib/axisregistry/data/z_rotation.textproto
Labels: I Axis Registry, I Small Fix

#6573 Lang v054
  lang/Lib/gflanguages/data/languages/ae_Avst.textproto
  lang/Lib/gflanguages/data/languages/bbc_Batk.textproto
  lang/Lib/gflanguages/data/languages/bho_Kthi.textproto
  lang/Lib/gflanguages/data/languages/bku_Buhd.textproto
  lang/Lib/gflanguages/data/languages/doi_Takr.textproto
  lang/Lib/gflanguages/data/languages/hnn_Hano.textproto
  lang/Lib/gflanguages/data/languages/sa_Avst.textproto
  lang/Lib/gflanguages/data/languages/sa_Batk.textproto
  lang/Lib/gflanguages/data/languages/sa_Buhd.textproto
  lang/Lib/gflanguages/data/languages/sa_Dogr.textproto
  lang/Lib/gflanguages/data/languages/sa_Hano.textproto
  lang/Lib/gflanguages/data/languages/sa_Khoj.textproto
  lang/Lib/gflanguages/data/languages/sa_Kthi.textproto
  lang/Lib/gflanguages/data/languages/sa_Lepc.textproto
  lang/Lib/gflanguages/data/languages/sa_Mahj.textproto
  lang/Lib/gflanguages/data/languages/sa_Olck.textproto
  lang/Lib/gflanguages/data/languages/sa_Saur.textproto
  lang/Lib/gflanguages/data/languages/sa_Takr.textproto
  lang/Lib/gflanguages/data/languages/saz_Saur.textproto
Labels: I Lang

#6426 Noto Serif Khojki: Version 2.004 added
  ofl/notoserifkhojki/METADATA.pb
  ofl/notoserifkhojki/NotoSerifKhojki[wght].ttf
  ofl/notoserifkhojki/upstream.yaml
Labels: I Font Upgrade

#6427 Noto Sans Khojki: Version 2.004; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosanskhojki/METADATA.pb
  ofl/notosanskhojki/NotoSansKhojki-Regular.ttf
  ofl/notosanskhojki/upstream.yaml
Labels: I Font Upgrade

#6572 Wavefont: Version 3.004;gftools[0.9.33] added
  ofl/wavefont/METADATA.pb
  ofl/wavefont/Wavefont[ROND,YELA,wght].ttf
  ofl/wavefont/upstream.yaml
Labels: I Small Fix

#6575 Remove Sanskrit sample from Hanunoo
  ofl/notosanshanunoo/METADATA.pb
Labels: I Description/Metadata/OFL

#6576 Remove Sanskrit sample text from Dogra
  ofl/notoserifdogra/METADATA.pb
Labels: I Description/Metadata/OFL

#6574 Removed fake sanskrit sample texts
  ofl/mingzat/METADATA.pb
  ofl/notosansavestan/METADATA.pb
  ofl/notosansbatak/METADATA.pb
  ofl/notosansbuhid/METADATA.pb
  ofl/notosanskaithi/METADATA.pb
  ofl/notosanslepcha/METADATA.pb
  ofl/notosansmahajani/METADATA.pb
  ofl/notosansolchiki/METADATA.pb
  ofl/notosanssaurashtra/METADATA.pb
Labels: I Description/Metadata/OFL

#6579 updated to_lists
  to_delist.txt
  to_production.txt
  to_sandbox.txt
Labels: I Tools / workflow / repo
