Repository google/fonts, pull requests merged in 2023-10, with the labels that each got.

#6827 Add primary_script to Murecho
  ofl/murecho/METADATA.pb
Labels: I Description/Metadata/OFL

#6829 Kay Pho Du: Version 3.000 added
  ofl/kayphodu/DESCRIPTION.en_us.html
  ofl/kayphodu/KayPhoDu-Bold.ttf
  ofl/kayphodu/KayPhoDu-Medium.ttf
  ofl/kayphodu/KayPhoDu-Regular.ttf
  ofl/kayphodu/KayPhoDu-SemiBold.ttf
  ofl/kayphodu/METADATA.pb
  ofl/kayphodu/OFL.txt
  ofl/kayphodu/upstream.yaml
Labels: I New Font, II Indic / Brahmic / Thai / Tai

#6821 Noto Sans Mono: Version 2.014 added
  ofl/notosansmono/METADATA.pb
  ofl/notosansmono/NotoSansMono[wdth,wght].ttf
  ofl/notosansmono/upstream.yaml
Labels: I Font Upgrade

#6820 Noto Serif: Version 2.013 added
  ofl/notoserif/METADATA.pb
  ofl/notoserif/NotoSerif-Italic[wdth,wght].ttf
  ofl/notoserif/NotoSerif[wdth,wght].ttf
  ofl/notoserif/upstream.yaml
Labels: I Font Upgrade

#6819 Noto Sans: Version 2.013 added
  ofl/notosans/METADATA.pb
  ofl/notosans/NotoSans-Italic[wdth,wght].ttf
  ofl/notosans/NotoSans[wdth,wght].ttf
  ofl/notosans/upstream.yaml
Labels: I Font Upgrade

#6814 Blaka: Version 1.003 added
  ofl/blaka/Blaka-Regular.ttf
  ofl/blaka/DESCRIPTION.en_us.html
  ofl/blaka/METADATA.pb
Labels: I Font Upgrade

#6815 Blaka Hollow: Version 1.003 added
  ofl/blakahollow/BlakaHollow-Regular.ttf
  ofl/blakahollow/DESCRIPTION.en_us.html
  ofl/blakahollow/METADATA.pb
Labels: I Font Upgrade

#6816 Blaka Ink: Version 1.003; ttfautohint (v1.8.4.7-5d5b) added
  ofl/blakaink/BlakaInk-Regular.ttf
  ofl/blakaink/METADATA.pb
Labels: I Font Upgrade, II Color font

#6824 Noto Nastaliq Urdu: Version 3.009 added
  ofl/notonastaliqurdu/METADATA.pb
  ofl/notonastaliqurdu/NotoNastaliqUrdu[wght].ttf
  ofl/notonastaliqurdu/upstream.yaml
Labels: I Font Upgrade

#6810 Noto Serif Khmer: Version 2.004 added
  ofl/notoserifkhmer/METADATA.pb
  ofl/notoserifkhmer/NotoSerifKhmer[wdth,wght].ttf
  ofl/notoserifkhmer/upstream.yaml
Labels: I Font Upgrade

#6809 Noto Sans Khmer: Version 2.004 added
  ofl/notosanskhmer/METADATA.pb
  ofl/notosanskhmer/NotoSansKhmer[wdth,wght].ttf
  ofl/notosanskhmer/upstream.yaml
Labels: I Font Upgrade

#6806 Noto Sans Telugu: Version 2.005 added
  ofl/notosanstelugu/METADATA.pb
  ofl/notosanstelugu/NotoSansTelugu[wdth,wght].ttf
  ofl/notosanstelugu/upstream.yaml
Labels: I Font Upgrade

#6795 Noto Sans Kannada: Version 2.005 added
  ofl/notosanskannada/METADATA.pb
  ofl/notosanskannada/NotoSansKannada[wdth,wght].ttf
  ofl/notosanskannada/upstream.yaml
Labels: I Font Upgrade

#6790 Noto Serif Kannada: Version 2.005 added
  ofl/notoserifkannada/METADATA.pb
  ofl/notoserifkannada/NotoSerifKannada[wght].ttf
  ofl/notoserifkannada/upstream.yaml
Labels: I Font Upgrade

#6788 Noto Serif Thai: Version 2.002 added
  ofl/notoserifthai/METADATA.pb
  ofl/notoserifthai/NotoSerifThai[wdth,wght].ttf
  ofl/notoserifthai/upstream.yaml
Labels: I Font Upgrade

#6826 Add primary_script to Yomogi
  ofl/yomogi/METADATA.pb
Labels: I Description/Metadata/OFL

#6830 agbalumo: Version 1.000; ttfautohint (v1.8.4) added
  ofl/agbalumo/Agbalumo-Regular.ttf
  ofl/agbalumo/DESCRIPTION.en_us.html
  ofl/agbalumo/METADATA.pb
  ofl/agbalumo/OFL.txt
  ofl/agbalumo/upstream.yaml
Labels: I New Font

#6843 Onest metadatas and article
  ofl/onest/METADATA.pb
Labels: I Description/Metadata/OFL

#6785 Noto Sans Takri: Version 2.005; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosanstakri/METADATA.pb
  ofl/notosanstakri/NotoSansTakri-Regular.ttf
  ofl/notosanstakri/upstream.yaml
Labels: I Font Upgrade

#6786 Noto Sans Tangsa: Version 1.506 added
  ofl/notosanstangsa/METADATA.pb
  ofl/notosanstangsa/NotoSansTangsa[wght].ttf
  ofl/notosanstangsa/upstream.yaml
Labels: I Font Upgrade

#6777 Noto Sans Manichaean: Version 2.005; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosansmanichaean/METADATA.pb
  ofl/notosansmanichaean/NotoSansManichaean-Regular.ttf
  ofl/notosansmanichaean/upstream.yaml
Labels: I Font Upgrade

#6776 Noto Sans Nandinagari: Version 1.002; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosansnandinagari/METADATA.pb
  ofl/notosansnandinagari/NotoSansNandinagari-Regular.ttf
  ofl/notosansnandinagari/upstream.yaml
Labels: I Font Upgrade

#6849 Gabarito: designer order updated
  ofl/gabarito/METADATA.pb
Labels: I Description/Metadata/OFL

#6799 Linefont: Version 3.002;gftools[0.9.33] added
  ofl/linefont/DESCRIPTION.en_us.html
  ofl/linefont/Linefont[wdth,wght].ttf
  ofl/linefont/METADATA.pb
  ofl/linefont/OFL.txt
  ofl/linefont/upstream.yaml
Labels: I New Font, II Icon / symbols / not text

#6850 Reddit Sans: Version 1.012 added
  ofl/redditsans/DESCRIPTION.en_us.html
  ofl/redditsans/METADATA.pb
  ofl/redditsans/OFL.txt
  ofl/redditsans/RedditSans-Bold.ttf
  ofl/redditsans/RedditSans-BoldItalic.ttf
  ofl/redditsans/RedditSans-ExtraBold.ttf
  ofl/redditsans/RedditSans-ExtraBoldItalic.ttf
  ofl/redditsans/RedditSans-Italic.ttf
  ofl/redditsans/RedditSans-Light.ttf
  ofl/redditsans/RedditSans-LightItalic.ttf
  ofl/redditsans/RedditSans-Regular.ttf
  ofl/redditsans/RedditSans-SemiBold.ttf
  ofl/redditsans/RedditSans-SemiBoldItalic.ttf
  ofl/redditsans/upstream.yaml
Labels: I New Font

#6852 Rethink Sans: Version 1.001 added
  ofl/rethinksans/METADATA.pb
  ofl/rethinksans/RethinkSans-Italic[wght].ttf
  ofl/rethinksans/RethinkSans[wght].ttf
  ofl/rethinksans/upstream.yaml
Labels: I Small Fix

#6853 Linefont: custom sample text
  ofl/linefont/METADATA.pb
Labels: I Description/Metadata/OFL

#6833 Roboto Slab: Version 2.002 added
  apache/robotoslab/METADATA.pb
  apache/robotoslab/RobotoSlab[wght].ttf
  apache/robotoslab/upstream.yaml
Labels: I Small Fix

#6855 updated lists 12th October
  to_production.txt
  to_sandbox.txt
Labels: I Tools / workflow / repo

#6858 Linefont: added missing property, removed useless ones
  ofl/linefont/METADATA.pb
Labels: I Description/Metadata/OFL, I Small Fix

#6861 Noto Sans Symbols 2: Version 2.008; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosanssymbols2/METADATA.pb
  ofl/notosanssymbols2/NotoSansSymbols2-Regular.ttf
  ofl/notosanssymbols2/upstream.yaml
Labels: I Font Upgrade

#6775 Noto Sans Meroitic: Version 2.002; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosansmeroitic/METADATA.pb
  ofl/notosansmeroitic/NotoSansMeroitic-Regular.ttf
  ofl/notosansmeroitic/upstream.yaml
Labels: I Font Upgrade

#6864 Linefont: removed latin subsets
  ofl/linefont/METADATA.pb
Labels: I Description/Metadata/OFL

#6792 Noto Sans Thaana: Version 3.000 added
  ofl/notosansthaana/METADATA.pb
  ofl/notosansthaana/NotoSansThaana[wght].ttf
  ofl/notosansthaana/upstream.yaml
Labels: I Font Upgrade

#6862 Onest article
  ofl/onest/article/ARTICLE.en_us.html
  ofl/onest/article/image1.jpg
  ofl/onest/article/image2.jpg
  ofl/onest/article/image3.jpg
  ofl/onest/article/image4.jpg
Labels: I Description/Metadata/OFL

#6846 Borel: Version 1.005; ttfautohint (v1.8.4.7-5d5b) added
  ofl/borel/Borel-Regular.ttf
  ofl/borel/DESCRIPTION.en_us.html
  ofl/borel/METADATA.pb
Labels: III Expand glyphset, I Font Upgrade

#6867 Noto Sans Thaana: Update description
  ofl/notosansthaana/DESCRIPTION.en_us.html
Labels: I Description/Metadata/OFL

#6756 Noto Serif Ahom: Version 2.007; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notoserifahom/METADATA.pb
  ofl/notoserifahom/NotoSerifAhom-Regular.ttf
  ofl/notoserifahom/upstream.yaml
Labels: I Font Upgrade

#6758 Noto Serif Armenian: Version 2.008 added
  ofl/notoserifarmenian/METADATA.pb
  ofl/notoserifarmenian/NotoSerifArmenian[wdth,wght].ttf
  ofl/notoserifarmenian/upstream.yaml
Labels: I Font Upgrade

#6759 Noto Sans Armenian: Version 2.008 added
  ofl/notosansarmenian/METADATA.pb
  ofl/notosansarmenian/NotoSansArmenian[wdth,wght].ttf
  ofl/notosansarmenian/upstream.yaml
Labels: I Font Upgrade

#6875 updated lists October 19th
  to_production.txt
  to_sandbox.txt
Labels: I Tools / workflow / repo

#6885 Update AR One Sans DESCRIPTION.en_us.html
  ofl/aronesans/DESCRIPTION.en_us.html
Labels: I Description/Metadata/OFL

#6879 Kalnia: Version 1.105 added
  ofl/kalnia/DESCRIPTION.en_us.html
  ofl/kalnia/Kalnia[wdth,wght].ttf
  ofl/kalnia/METADATA.pb
  ofl/kalnia/OFL.txt
  ofl/kalnia/article/ARTICLE.en_us.html
  ofl/kalnia/article/KalniaTypeface-01.png
  ofl/kalnia/article/KalniaTypeface-02.png
  ofl/kalnia/upstream.yaml
Labels: I New Font

#6774 Noto Serif Khojki: Version 2.005 added
  ofl/notoserifkhojki/METADATA.pb
  ofl/notoserifkhojki/NotoSerifKhojki[wght].ttf
  ofl/notoserifkhojki/upstream.yaml
Labels: I Font Upgrade

#6773 Noto Sans Khojki: Version 2.005; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosanskhojki/METADATA.pb
  ofl/notosanskhojki/NotoSansKhojki-Regular.ttf
  ofl/notosanskhojki/upstream.yaml
Labels: I Font Upgrade

#6880 Designer added: Frida Medrano (Kalnia)
  catalog/designers/fridamedrano/bio.html
  catalog/designers/fridamedrano/fridamedrano.png
  catalog/designers/fridamedrano/info.pb
Labels: I Designer profile

#6881 Afacad: Version 1.000 added
  ofl/afacad/Afacad-Italic[wght].ttf
  ofl/afacad/Afacad[wght].ttf
  ofl/afacad/DESCRIPTION.en_us.html
  ofl/afacad/METADATA.pb
  ofl/afacad/OFL.txt
  ofl/afacad/article/ARTICLE.en_us.html
  ofl/afacad/article/afacad_01_promo.png
  ofl/afacad/article/afacad_02_promo.png
  ofl/afacad/article/afacad_03_kapitael.png
  ofl/afacad/article/afacad_04_promo.png
  ofl/afacad/upstream.yaml
Labels: I New Font

#6883 Add designer: Dicotype
  catalog/designers/dicotype/bio.html
  catalog/designers/dicotype/dicotype.png
  catalog/designers/dicotype/info.pb
Labels: I Designer profile

#6897 Hedvig Letters Serif: Version 1.000 added
  ofl/hedviglettersserif/DESCRIPTION.en_us.html
  ofl/hedviglettersserif/HedvigLettersSerif[opsz].ttf
  ofl/hedviglettersserif/METADATA.pb
  ofl/hedviglettersserif/OFL.txt
  ofl/hedviglettersserif/upstream.yaml
Labels: I New Font

#6896 Hedvig Letters Sans: Version 1.000; ttfautohint (v1.8.4.7-5d5b) added
  ofl/hedvigletterssans/DESCRIPTION.en_us.html
  ofl/hedvigletterssans/HedvigLettersSans-Regular.ttf
  ofl/hedvigletterssans/METADATA.pb
  ofl/hedvigletterssans/OFL.txt
  ofl/hedvigletterssans/upstream.yaml
Labels: I New Font

#6902 Tor Weibull: designer added (Hedvig Letters)
  catalog/designers/torweibull/bio.html
  catalog/designers/torweibull/info.pb
  catalog/designers/torweibull/torweibull.png
Labels: I Designer profile

#6900 Kanon Foundry: designer added (Hedvig Letters)
  catalog/designers/kanonfoundry/bio.html
  catalog/designers/kanonfoundry/info.pb
  catalog/designers/kanonfoundry/kanonfoundry.png
Labels: I Designer profile

#6901 Alexander Örn: designer added (Hedvig Letters)
  catalog/designers/alexanderorn/alexanderorn.png
  catalog/designers/alexanderorn/bio.html
  catalog/designers/alexanderorn/info.pb
Labels: I Designer profile

#6882 Add designer: Kristian Möller
  catalog/designers/kristianmoller/bio.html
  catalog/designers/kristianmoller/info.pb
  catalog/designers/kristianmoller/kristianmoller.png
Labels: I Designer profile

#6760 Noto Sans Chorasmian: Version 1.003; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosanschorasmian/METADATA.pb
  ofl/notosanschorasmian/NotoSansChorasmian-Regular.ttf
  ofl/notosanschorasmian/upstream.yaml
Labels: I Font Upgrade

#6911 Add designer: Naipe Foundry
  catalog/designers/naipefoundry/bio.html
  catalog/designers/naipefoundry/info.pb
  catalog/designers/naipefoundry/naipefoundry.png
Labels: I Designer profile

#6910 Gabarito: metadatas updated
  ofl/gabarito/METADATA.pb
Labels: I Description/Metadata/OFL

#6778 Noto Sans Gujarati: Version 2.105 added
  ofl/notosansgujarati/METADATA.pb
  ofl/notosansgujarati/NotoSansGujarati[wdth,wght].ttf
  ofl/notosansgujarati/upstream.yaml
Labels: I Font Upgrade

#6779 Noto Serif Gujarati: Version 2.105 added
  ofl/notoserifgujarati/METADATA.pb
  ofl/notoserifgujarati/NotoSerifGujarati[wght].ttf
  ofl/notoserifgujarati/upstream.yaml
Labels: I Font Upgrade

#6761 Noto Sans Cham: Version 2.004 added
  ofl/notosanscham/METADATA.pb
  ofl/notosanscham/NotoSansCham[wght].ttf
  ofl/notosanscham/upstream.yaml
Labels: I Font Upgrade

#6914 fix: broken GitHub Labs link replaced
  README.md
Labels: I Tools / workflow / repo
