Repository google/fonts, pull requests merged in 2023-09, with the labels that each got.

#6654 Karla: Version 2.004;gftools[0.9.33] added
  ofl/karla/Karla-Italic[wght].ttf
  ofl/karla/Karla[wght].ttf
  ofl/karla/METADATA.pb
Labels: I Small Fix

#6561 Young Serif: Version 3.002; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.33.dev8+g029e19f] added
  ofl/youngserif/DESCRIPTION.en_us.html
  ofl/youngserif/METADATA.pb
  ofl/youngserif/OFL.txt
  ofl/youngserif/YoungSerif-Regular.ttf
  ofl/youngserif/upstream.yaml
Labels: I New Font

#6467 Noto Sans Tifinagh: Version 2.006; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosanstifinagh/METADATA.pb
  ofl/notosanstifinagh/NotoSansTifinagh-Regular.ttf
  ofl/notosanstifinagh/upstream.yaml
Labels: I Font Upgrade

#6466 Noto Sans Javanese: Version 2.005 added
  ofl/notosansjavanese/METADATA.pb
  ofl/notosansjavanese/NotoSansJavanese[wght].ttf
  ofl/notosansjavanese/upstream.yaml
Labels: I Font Upgrade

#6461 Noto Sans Symbols: Version 2.003 added
  ofl/notosanssymbols/METADATA.pb
  ofl/notosanssymbols/NotoSansSymbols[wght].ttf
  ofl/notosanssymbols/upstream.yaml
Labels: I Font Upgrade

#6458 Noto Sans Cham: Version 2.003 added
  ofl/notosanscham/METADATA.pb
  ofl/notosanscham/NotoSansCham[wght].ttf
  ofl/notosanscham/upstream.yaml
Labels: I Font Upgrade

#6432 Noto Sans Syloti Nagri: Version 2.004; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosanssylotinagri/METADATA.pb
  ofl/notosanssylotinagri/NotoSansSylotiNagri-Regular.ttf
  ofl/notosanssylotinagri/upstream.yaml
Labels: I Font Upgrade

#6431 Noto Sans Coptic: Version 2.003; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosanscoptic/METADATA.pb
  ofl/notosanscoptic/NotoSansCoptic-Regular.ttf
  ofl/notosanscoptic/upstream.yaml
Labels: I Font Upgrade

#6430 Noto Sans Hanifi Rohingya: Version 2.102 added
  ofl/notosanshanifirohingya/METADATA.pb
  ofl/notosanshanifirohingya/NotoSansHanifiRohingya[wght].ttf
  ofl/notosanshanifirohingya/upstream.yaml
Labels: I Font Upgrade

#6429 Noto Sans NKo: Version 2.004; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosansnko/METADATA.pb
  ofl/notosansnko/NotoSansNKo-Regular.ttf
  ofl/notosansnko/upstream.yaml
Labels: I Font Upgrade

#6460 Noto Sans Symbols 2: Version 2.007; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosanssymbols2/METADATA.pb
  ofl/notosanssymbols2/NotoSansSymbols2-Regular.ttf
  ofl/notosanssymbols2/upstream.yaml
Labels: I Font Upgrade

#6651 Rethink Sans: Version 1.000;gftools[0.9.33] added
  ofl/rethinksans/DESCRIPTION.en_us.html
  ofl/rethinksans/METADATA.pb
  ofl/rethinksans/OFL.txt
  ofl/rethinksans/RethinkSans-Italic[wght].ttf
  ofl/rethinksans/RethinkSans[wght].ttf
  ofl/rethinksans/upstream.yaml
Labels: I New Font

#6414 Noto Sans Lao Looped: Version 1.002 added
  ofl/notosanslaolooped/METADATA.pb
  ofl/notosanslaolooped/NotoSansLaoLooped[wdth,wght].ttf
  ofl/notosanslaolooped/upstream.yaml
Labels: I Font Upgrade

#6413 Noto Sans Zanabazar Square: Version 2.006; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosanszanabazarsquare/METADATA.pb
  ofl/notosanszanabazarsquare/NotoSansZanabazarSquare-Regular.ttf
  ofl/notosanszanabazarsquare/upstream.yaml
Labels: I Font Upgrade

#6412 Noto Sans Lao: Version 2.003 added
  ofl/notosanslao/METADATA.pb
  ofl/notosanslao/NotoSansLao[wdth,wght].ttf
  ofl/notosanslao/upstream.yaml
Labels: I Font Upgrade

#6411 Noto Serif Lao: Version 2.003 added
  ofl/notoseriflao/METADATA.pb
  ofl/notoseriflao/NotoSerifLao[wdth,wght].ttf
  ofl/notoseriflao/upstream.yaml
Labels: I Font Upgrade

#6399 Noto Sans Siddham: Version 2.005; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosanssiddham/METADATA.pb
  ofl/notosanssiddham/NotoSansSiddham-Regular.ttf
  ofl/notosanssiddham/upstream.yaml
Labels: I Font Upgrade

#6400 Noto Music: Version 2.003; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notomusic/METADATA.pb
  ofl/notomusic/NotoMusic-Regular.ttf
  ofl/notomusic/upstream.yaml
Labels: I Font Upgrade

#6659 Amiri Quran: colorv0 SVG table added
  ofl/amiriquran/AmiriQuran-Regular.ttf
  ofl/amiriqurancolored/AmiriQuranColored-Regular.ttf
  ofl/amiriqurancolored/DESCRIPTION.en_us.html
  ofl/amiriqurancolored/METADATA.pb
  ofl/amiriqurancolored/OFL.txt
Labels: I Small Fix, II Color font

#6661 Onest: Version 1.000;gftools[0.9.33] added
  ofl/onest/DESCRIPTION.en_us.html
  ofl/onest/METADATA.pb
  ofl/onest/OFL.txt
  ofl/onest/Onest[wght].ttf
  ofl/onest/upstream.yaml
Labels: I New Font

#6656 Niteesh Yadav designer of AR One Sans
  catalog/designers/niteeshyadav/bio.html
  catalog/designers/niteeshyadav/info.pb
  catalog/designers/niteeshyadav/niteeshyadav.png
Labels: I Designer profile

#6662 AR One Sans: Version 1.001;gftools[0.9.33] added
  ofl/aronesans/AROneSans[ARRR,wght].ttf
  ofl/aronesans/DESCRIPTION.en_us.html
  ofl/aronesans/METADATA.pb
  ofl/aronesans/OFL.txt
  ofl/aronesans/upstream.yaml
Labels: I New Font

#6403 Noto Sans Modi: Version 2.004; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosansmodi/METADATA.pb
  ofl/notosansmodi/NotoSansModi-Regular.ttf
  ofl/notosansmodi/upstream.yaml
Labels: I Font Upgrade

#6668 Designer added: Dmitri Voloshin
  catalog/designers/dmitrivoloshin/bio.html
  catalog/designers/dmitrivoloshin/dmitrivoloshin.png
  catalog/designers/dmitrivoloshin/info.pb
Labels: I Designer profile

#6408 Noto Sans Gunjala Gondi: Version 1.004 added
  ofl/notosansgunjalagondi/METADATA.pb
  ofl/notosansgunjalagondi/NotoSansGunjalaGondi[wght].ttf
  ofl/notosansgunjalagondi/upstream.yaml
Labels: I Font Upgrade

#6404 Noto Sans Tai Viet: Version 2.004; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosanstaiviet/METADATA.pb
  ofl/notosanstaiviet/NotoSansTaiViet-Regular.ttf
  ofl/notosanstaiviet/upstream.yaml
Labels: I Font Upgrade

#6410 Noto Sans Tangsa: Version 1.505 added
  ofl/notosanstangsa/METADATA.pb
  ofl/notosanstangsa/NotoSansTangsa[wght].ttf
  ofl/notosanstangsa/upstream.yaml
Labels: I Font Upgrade

#6672 Updated lists 7th Sept.
  to_delist.txt
  to_production.txt
  to_sandbox.txt
Labels: I Tools / workflow / repo

#5377 Noto Serif Dogra: Version 1.006; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notoserifdogra/METADATA.pb
  ofl/notoserifdogra/NotoSerifDogra-Regular.ttf
  ofl/notoserifdogra/upstream.yaml
Labels: I Font Upgrade

#5369 Noto Sans Bhaiksuki: Version 2.002; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosansbhaiksuki/METADATA.pb
  ofl/notosansbhaiksuki/NotoSansBhaiksuki-Regular.ttf
  ofl/notosansbhaiksuki/OFL.txt
  ofl/notosansbhaiksuki/upstream.yaml
Labels: I Font Upgrade

#5278 Noto Sans Cypriot: Version 2.001; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosanscypriot/METADATA.pb
  ofl/notosanscypriot/NotoSansCypriot-Regular.ttf
  ofl/notosanscypriot/OFL.txt
  ofl/notosanscypriot/upstream.yaml
Labels: I Font Upgrade

#6419 Noto Sans Rejang: Version 2.002; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosansrejang/METADATA.pb
  ofl/notosansrejang/NotoSansRejang-Regular.ttf
  ofl/notosansrejang/upstream.yaml
Labels: I Font Upgrade

#6679 Add Slab Serif as a stroke category for Montagu Slab
  ofl/montaguslab/METADATA.pb
Labels: I Description/Metadata/OFL

#6669 Designer added: Andrey Kudryavtsev
  catalog/designers/andreykudryavtsev/bio.html
  catalog/designers/andreykudryavtsev/info.pb
Labels: I Designer profile

#6678 Designer added: Veronika Burian
  catalog/designers/veronikaburian/bio.html
  catalog/designers/veronikaburian/info.pb
  catalog/designers/veronikaburian/veronikaburian.png
Labels: I Designer profile

#6676 Designer added: Laura Meseguer
  catalog/designers/laurameseguer/bio.html
  catalog/designers/laurameseguer/info.pb
  catalog/designers/laurameseguer/laurameseguer.png
Labels: I Designer profile

#6677 Designer added: José Scaglione
  catalog/designers/josescaglione/bio.html
  catalog/designers/josescaglione/info.pb
  catalog/designers/josescaglione/josescaglione.png
Labels: I Designer profile

#6673 Playpen Sans: Version 1.000 added
  ofl/playpensans/DESCRIPTION.en_us.html
  ofl/playpensans/METADATA.pb
  ofl/playpensans/OFL.txt
  ofl/playpensans/PlaypenSans[wght].ttf
  ofl/playpensans/upstream.yaml
Labels: I New Font

#6686 updated lists 8th Sept.
  to_production.txt
  to_sandbox.txt
Labels: I Tools / workflow / repo

#6696 Update lang to 0.5.6
  lang/Lib/gflanguages/data/languages/ban_Bali.textproto
  lang/Lib/gflanguages/data/languages/gon_Gonm.textproto
  lang/Lib/gflanguages/data/languages/hoc_Wara.textproto
  lang/Lib/gflanguages/data/languages/kaw_Kawi.textproto
  lang/Lib/gflanguages/data/languages/mro_Mroo.textproto
  lang/Lib/gflanguages/data/languages/oui_Ougr.textproto
  lang/Lib/gflanguages/data/languages/peo_Xpeo.textproto
  lang/Lib/gflanguages/data/languages/skr_Mult.textproto
  lang/Lib/gflanguages/data/scripts/Kawi.textproto
  lang/Lib/gflanguages/data/scripts/Ougr.textproto
Labels: I Lang

#6685 Kameron: Version 1.100 added
  ofl/kameron/DESCRIPTION.en_us.html
  ofl/kameron/Kameron-Bold.ttf
  ofl/kameron/Kameron-Regular.ttf
  ofl/kameron/Kameron[wght].ttf
  ofl/kameron/METADATA.pb
  ofl/kameron/OFL.txt
  ofl/kameron/upstream.yaml
Labels: III VF Replacement, I Font Upgrade

#6699 Gabarito: Version 1.000 added
  ofl/gabarito/DESCRIPTION.en_us.html
  ofl/gabarito/Gabarito[wght].ttf
  ofl/gabarito/METADATA.pb
  ofl/gabarito/OFL.txt
  ofl/gabarito/upstream.yaml
Labels: I New Font

#6698 Pixelify Sans: Version 1.000 added
  ofl/pixelifysans/DESCRIPTION.en_us.html
  ofl/pixelifysans/METADATA.pb
  ofl/pixelifysans/OFL.txt
  ofl/pixelifysans/PixelifySans[wght].ttf
  ofl/pixelifysans/upstream.yaml
Labels: I New Font

#6704 Noto Sans New Tai Lue: Version 2.004 added
  ofl/notosansnewtailue/METADATA.pb
  ofl/notosansnewtailue/NotoSansNewTaiLue[wght].ttf
  ofl/notosansnewtailue/upstream.yaml
Labels: I Small Fix

#6707 Designer added: Alvaro Franca
  catalog/designers/alvarofranca/alvarofranca.png
  catalog/designers/alvarofranca/bio.html
  catalog/designers/alvarofranca/info.pb
Labels: I Designer profile

#6708 Designer added: Felipe Casaprima
  catalog/designers/felipecasaprima/bio.html
  catalog/designers/felipecasaprima/felipecasaprima.png
  catalog/designers/felipecasaprima/info.pb
Labels: I Designer profile

#6709 Update knowledge/modules/choosing_type/module.textproto
  cc-by-sa/knowledge/modules/choosing_type/module.textproto
Labels: I Knowledge

#6712 Add designer: Leandro Assis
  catalog/designers/leandroassis/bio.html
  catalog/designers/leandroassis/info.pb
  catalog/designers/leandroassis/leandroassis.png
Labels: I Designer profile

#6713 Add designer: Stefie Justprince
  catalog/designers/stefiejustprince/bio.html
  catalog/designers/stefiejustprince/info.pb
  catalog/designers/stefiejustprince/stefiejustprince.png
Labels: I Designer profile

#6715 updated lists 15th September
  to_production.txt
  to_sandbox.txt
Labels: I Tools / workflow / repo

#6725 Update Gotu description to fix a broken repo link
  ofl/gotu/DESCRIPTION.en_us.html
Labels: I Description/Metadata/OFL

#6737 BioRhyme: Version 1.600;gftools[0.9.33] added
  ofl/biorhyme/BioRhyme-Bold.ttf
  ofl/biorhyme/BioRhyme-ExtraBold.ttf
  ofl/biorhyme/BioRhyme-ExtraLight.ttf
  ofl/biorhyme/BioRhyme-Light.ttf
  ofl/biorhyme/BioRhyme-Regular.ttf
  ofl/biorhyme/BioRhyme[wdth,wght].ttf
  ofl/biorhyme/DESCRIPTION.en_us.html
  ofl/biorhyme/METADATA.pb
  ofl/biorhyme/OFL.txt
  ofl/biorhyme/upstream.yaml
Labels: III VF Replacement, I Font Upgrade

#6738 Sometype Mono: Version 1.001 added
  ofl/sometypemono/DESCRIPTION.en_us.html
  ofl/sometypemono/METADATA.pb
  ofl/sometypemono/OFL.txt
  ofl/sometypemono/SometypeMono-Bold.ttf
  ofl/sometypemono/SometypeMono-BoldItalic.ttf
  ofl/sometypemono/SometypeMono-Italic.ttf
  ofl/sometypemono/SometypeMono-Italic[wght].ttf
  ofl/sometypemono/SometypeMono-Medium.ttf
  ofl/sometypemono/SometypeMono-MediumItalic.ttf
  ofl/sometypemono/SometypeMono-Regular.ttf
  ofl/sometypemono/SometypeMono[wght].ttf
  ofl/sometypemono/upstream.yaml
Labels: I New Font

#6714 Shanti: Version 1.100; ttfautohint (v1.8.4) added
  ofl/shanti/DESCRIPTION.en_us.html
  ofl/shanti/METADATA.pb
  ofl/shanti/OFL.txt
  ofl/shanti/Shanti-Regular.ttf
  ofl/shanti/upstream.yaml
Labels: I Font Upgrade

#6719 sourcesans 3.052 added
  ofl/sourcesans3/METADATA.pb
  ofl/sourcesans3/SourceSans3-Italic[wght].ttf
  ofl/sourcesans3/SourceSans3[wght].ttf
Labels: I Font Upgrade

#6742 Updated lists 21st September
  to_production.txt
  to_sandbox.txt
Labels: I Tools / workflow / repo

#6705 Wavefont: Version 3.005;gftools[0.9.33] added
  ofl/wavefont/METADATA.pb
  ofl/wavefont/Wavefont[ROND,YELA,wght].ttf
Labels: III Expand styles, I Font Upgrade

#6746 Playpen Sans: Version 1.001 added
  ofl/playpensans/DESCRIPTION.en_us.html
  ofl/playpensans/METADATA.pb
  ofl/playpensans/PlaypenSans[wght].ttf
Labels: I New Font

#6469 Noto Sans Kawi: Version 1.000 added
  ofl/notosanskawi/DESCRIPTION.en_us.html
  ofl/notosanskawi/METADATA.pb
  ofl/notosanskawi/NotoSansKawi[wght].ttf
  ofl/notosanskawi/OFL.txt
  ofl/notosanskawi/article/ARTICLE.en_us.html
  ofl/notosanskawi/upstream.yaml
Labels: I New Font

#5283 Noto Sans Elymaic: Version 1.001; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosanselymaic/METADATA.pb
  ofl/notosanselymaic/NotoSansElymaic-Regular.ttf
  ofl/notosanselymaic/OFL.txt
  ofl/notosanselymaic/upstream.yaml
Labels: I Font Upgrade

#5281 Noto Sans Caucasian Albanian: Version 2.005; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosanscaucasianalbanian/METADATA.pb
  ofl/notosanscaucasianalbanian/NotoSansCaucasianAlbanian-Regular.ttf
  ofl/notosanscaucasianalbanian/OFL.txt
  ofl/notosanscaucasianalbanian/upstream.yaml
Labels: I Font Upgrade

#5395 Noto Serif Old Uyghur: Version 1.002; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notoserifolduyghur/DESCRIPTION.en_us.html
  ofl/notoserifolduyghur/METADATA.pb
  ofl/notoserifolduyghur/NotoSerifOldUyghur-Regular.ttf
  ofl/notoserifolduyghur/OFL.txt
  ofl/notoserifolduyghur/article/ARTICLE.en_us.html
  ofl/notoserifolduyghur/upstream.yaml
Labels: I New Font

#6801 Remove ASAP VF Beta
  ofl/asapvfbeta/AsapVFBeta-Condensed.ttf
  ofl/asapvfbeta/AsapVFBeta-Italic.ttf
  ofl/asapvfbeta/AsapVFBeta.ttf
  ofl/asapvfbeta/DESCRIPTION.en_us.html
  ofl/asapvfbeta/EARLY_ACCESS.category
  ofl/asapvfbeta/OFL.txt
Labels: I Tools / workflow / repo

#6805 Fix URLs for description files with associated upstream yaml files only
  ofl/balsamiqsans/DESCRIPTION.en_us.html
  ofl/kumbhsans/DESCRIPTION.en_us.html
  ofl/redrose/DESCRIPTION.en_us.html
Labels: I Description/Metadata/OFL

#6808 Updated lists Sept. 28th
  to_production.txt
  to_sandbox.txt
Labels: I Tools / workflow / repo
