Repository google/fonts, pull requests merged in 2023-03, with the labels that each got.

#5944 Denk One: Version 1.004; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.23] added
  ofl/denkone/DESCRIPTION.en_us.html
  ofl/denkone/DenkOne-Regular.ttf
  ofl/denkone/METADATA.pb
  ofl/denkone/OFL.txt
  ofl/denkone/upstream.yaml
Labels: III Expand glyphset, --- to sandbox, I Font Upgrade

#5931 Mate SC: Version 1.003; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.24] added
  ofl/matesc/DESCRIPTION.en_us.html
  ofl/matesc/METADATA.pb
  ofl/matesc/MateSC-Regular.ttf
  ofl/matesc/OFL.txt
  ofl/matesc/upstream.yaml
Labels: III Expand glyphset, --- to sandbox, I Font Upgrade

#5930 Mate: Version 1.003; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.24] added
  ofl/mate/DESCRIPTION.en_us.html
  ofl/mate/METADATA.pb
  ofl/mate/Mate-Italic.ttf
  ofl/mate/Mate-Regular.ttf
  ofl/mate/OFL.txt
  ofl/mate/upstream.yaml
Labels: III Expand glyphset, --- to sandbox, I Font Upgrade

#5949 Lemon: Version 1.003; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.24] added
  ofl/lemon/DESCRIPTION.en_us.html
  ofl/lemon/Lemon-Regular.ttf
  ofl/lemon/METADATA.pb
  ofl/lemon/OFL.txt
  ofl/lemon/upstream.yaml
Labels: III Expand glyphset, - Ready for Review, I Font Upgrade

#5948 Joti One: Version 1.002; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.24] added
  ofl/jotione/DESCRIPTION.en_us.html
  ofl/jotione/JotiOne-Regular.ttf
  ofl/jotione/METADATA.pb
  ofl/jotione/OFL.txt
  ofl/jotione/upstream.yaml
Labels: III Expand glyphset, - Ready for Review, I Font Upgrade

#5956 Alkalami: Version 3.000 added
  ofl/alkalami/Alkalami-Regular.ttf
  ofl/alkalami/METADATA.pb
  ofl/alkalami/OFL.txt
  ofl/alkalami/upstream.yaml
Labels: III Expand glyphset, - Ready for Review, I Font Upgrade

#5962 Schibsted Grotesk: Version 1.100;gftools[0.9.25] added
  ofl/schibstedgrotesk/DESCRIPTION.en_us.html
  ofl/schibstedgrotesk/METADATA.pb
  ofl/schibstedgrotesk/OFL.txt
  ofl/schibstedgrotesk/SchibstedGrotesk-Italic[wght].ttf
  ofl/schibstedgrotesk/SchibstedGrotesk[wght].ttf
  ofl/schibstedgrotesk/upstream.yaml
Labels: - Ready for Review, I New Font

#5959 Julee: Version 1.002; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.23] added
  ofl/julee/DESCRIPTION.en_us.html
  ofl/julee/Julee-Regular.ttf
  ofl/julee/METADATA.pb
  ofl/julee/OFL.txt
  ofl/julee/upstream.yaml
Labels: III Expand glyphset, - Ready for Review, I Font Upgrade

#5971 Cairo: Version 3.130;gftools[0.9.24] added
  ofl/cairo/Cairo[slnt,wght].ttf
  ofl/cairo/METADATA.pb
Labels: - Ready for Review, I Font Bug

#5972 Cairo Play: Version 3.130;gftools[0.9.24] added
  ofl/cairoplay/CairoPlay[slnt,wght].ttf
  ofl/cairoplay/METADATA.pb
  ofl/cairoplay/upstream.yaml
Labels: - Ready for Review, I Font Bug

#5986 Akatab: added primary_script for Tifinagh
  ofl/akatab/METADATA.pb
Labels: --- to sandbox, I Description/Metadata/OFL

#5983 Christian Thalmann: designer added
  catalog/designers/christianthalmann/bio.html
  catalog/designers/christianthalmann/christianthalmann.png
  catalog/designers/christianthalmann/info.pb
Labels: - Ready for Review, I Designer profile

#5982 Designer added: Julián Tunni
  catalog/designers/juliantunni/bio.html
  catalog/designers/juliantunni/info.pb
  catalog/designers/juliantunni/juliantunni.png
Labels: --- to sandbox, I Designer profile

#5984 Designer added: Bakken & Bæck
  catalog/designers/bakkenandbaeck/bakkenandbaeck.png
  catalog/designers/bakkenandbaeck/bio.html
  catalog/designers/bakkenandbaeck/info.pb
Labels: - Ready for Review, I Designer profile

#5985 Designer added: Henrik Kongsvoll
  catalog/designers/henrikkongsvoll/bio.html
  catalog/designers/henrikkongsvoll/henrikkongsvoll.png
  catalog/designers/henrikkongsvoll/info.pb
Labels: - Ready for Review, I Designer profile

#5988 Narnoor metadata: primary_script
  ofl/narnoor/METADATA.pb
Labels: - Ready for Review, I Description/Metadata/OFL

#5989 Noto Serif Telugu: Version 2.004 added
  ofl/notoseriftelugu/METADATA.pb
  ofl/notoseriftelugu/NotoSerifTelugu[wght].ttf
  ofl/notoseriftelugu/upstream.yaml
Labels: z_Noto, - Ready for Review, I Font Upgrade, II Indic / Brahmic / Thai / Tai

#5990 Noto Sans Telugu: Version 2.004 added
  ofl/notosanstelugu/METADATA.pb
  ofl/notosanstelugu/NotoSansTelugu[wdth,wght].ttf
  ofl/notosanstelugu/upstream.yaml
Labels: z_Noto, - Ready for Review, I Font Upgrade, II Indic / Brahmic / Thai / Tai

#5976 Anybody: Version 1.113;gftools[0.9.25] added
  ofl/anybody/Anybody-Italic[wdth,wght].ttf
  ofl/anybody/Anybody[wdth,wght].ttf
  ofl/anybody/METADATA.pb
  ofl/anybody/upstream.yaml
Labels: - Ready for Review, I Small Fix, III Improve rendering / layout

#5929 Sigmar: Version 1.000; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.24] added
  ofl/sigmar/DESCRIPTION.en_us.html
  ofl/sigmar/METADATA.pb
  ofl/sigmar/OFL.txt
  ofl/sigmar/Sigmar-Regular.ttf
  ofl/sigmar/upstream.yaml
Labels: --- to sandbox, I New Font

#6009 Anybody: Version 1.114;gftools[0.9.25] added
  ofl/anybody/Anybody-Italic[wdth,wght].ttf
  ofl/anybody/Anybody[wdth,wght].ttf
  ofl/anybody/METADATA.pb
Labels: - Ready for Review, I Small Fix

#6007 Poltawski Nowy: Version 1.001;gftools[0.9.25] added
  ofl/poltawskinowy/DESCRIPTION.en_us.html
  ofl/poltawskinowy/METADATA.pb
  ofl/poltawskinowy/OFL.txt
  ofl/poltawskinowy/PoltawskiNowy-Italic[wght].ttf
  ofl/poltawskinowy/PoltawskiNowy[wght].ttf
  ofl/poltawskinowy/upstream.yaml
Labels: --- to sandbox, I New Font

#5995 Gabriela: Version 2.001;gftools[0.9.26] added
  ofl/gabriela/DESCRIPTION.en_us.html
  ofl/gabriela/Gabriela-Regular.ttf
  ofl/gabriela/METADATA.pb
  ofl/gabriela/OFL.txt
  ofl/gabriela/upstream.yaml
Labels: III Expand glyphset, --- to sandbox, I Font Upgrade

#6006 Pathway Gothic One: Version 1.003; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.26] added
  ofl/pathwaygothicone/DESCRIPTION.en_us.html
  ofl/pathwaygothicone/METADATA.pb
  ofl/pathwaygothicone/OFL.txt
  ofl/pathwaygothicone/PathwayGothicOne-Regular.ttf
  ofl/pathwaygothicone/upstream.yaml
Labels: III Expand glyphset, --- to sandbox, I Font Upgrade

#6003 Pathway Extreme: Version 1.001;gftools[0.9.26] added
  ofl/pathwayextreme/METADATA.pb
  ofl/pathwayextreme/PathwayExtreme-Italic[opsz,wdth,wght].ttf
  ofl/pathwayextreme/PathwayExtreme[opsz,wdth,wght].ttf
Labels: --- to sandbox, I New Font

#6005 Carlito: Version 1.104 added [HOTFIX]
  ofl/carlito/Carlito-Bold.ttf
  ofl/carlito/Carlito-BoldItalic.ttf
  ofl/carlito/Carlito-Italic.ttf
  ofl/carlito/Carlito-Regular.ttf
  ofl/carlito/DESCRIPTION.en_us.html
  ofl/carlito/METADATA.pb
  ofl/carlito/OFL.txt
  ofl/carlito/upstream.yaml
Labels: --- to sandbox, I New Font

#6031 Removed a useless line
  ofl/denkone/DESCRIPTION.en_us.html
  ofl/fjallaone/DESCRIPTION.en_us.html
  ofl/fruktur/DESCRIPTION.en_us.html
  ofl/limelight/DESCRIPTION.en_us.html
  ofl/merriweathersans/DESCRIPTION.en_us.html
Labels: --- to sandbox, I Description/Metadata/OFL

#6029 Designer updated: Rodrigo Fuenzalida
  catalog/designers/rodrigofuenzalida/bio.html
  catalog/designers/rodrigofuenzalida/rodrigofuenzalida.png
Labels: --- to sandbox, I Designer profile

#6030 Designer added: Jordan Egstad
  catalog/designers/jordanegstad/bio.html
  catalog/designers/jordanegstad/info.pb
  catalog/designers/jordanegstad/jordanegstad.png
Labels: --- to sandbox, I Designer profile

#6032 Limelight: Added designer (sorkin)
  ofl/limelight/METADATA.pb
Labels: --- to sandbox, I Description/Metadata/OFL

#6038 Julee metadatas
  ofl/julee/METADATA.pb
Labels: --- to sandbox, I Description/Metadata/OFL

#6047 Trocchi: Version 1.101; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.27] added
  ofl/trocchi/METADATA.pb
  ofl/trocchi/OFL.txt
  ofl/trocchi/Trocchi-Regular.ttf
  ofl/trocchi/upstream.yaml
Labels: - Ready for Review, I Font Upgrade

#6043 Designer info for Vina Sans
  catalog/designers/nguyentype/bio.html
  catalog/designers/nguyentype/info.pb
  catalog/designers/nguyentype/nguyentype.png
Labels: --- to sandbox, I Designer profile

#6053 Noto Sans Symbols 2: Version 2.006; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosanssymbols2/METADATA.pb
  ofl/notosanssymbols2/NotoSansSymbols2-Regular.ttf
  ofl/notosanssymbols2/upstream.yaml
Labels: III Expand glyphset, - Ready for Review, I Font Upgrade

#6035 Castoro: Version 2.04 added
  ofl/castoro/Castoro-Italic.ttf
  ofl/castoro/Castoro-Regular.ttf
  ofl/castoro/DESCRIPTION.en_us.html
  ofl/castoro/METADATA.pb
  ofl/castoro/upstream.yaml
Labels: --- to sandbox, I Font Upgrade

#5981 Instrument Serif: Version 1.000; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.23] added
  ofl/instrumentserif/DESCRIPTION.en_us.html
  ofl/instrumentserif/InstrumentSerif-Italic.ttf
  ofl/instrumentserif/InstrumentSerif-Regular.ttf
  ofl/instrumentserif/METADATA.pb
  ofl/instrumentserif/OFL.txt
  ofl/instrumentserif/upstream.yaml
Labels: --- to sandbox, I New Font

#6059 Lang subtree: nag mundari script
  lang/CHANGELOG.md
  lang/Lib/gflanguages/data/languages/unr_Nagm.textproto
  lang/Lib/gflanguages/data/scripts/Nagm.textproto
  lang/requirements.txt
Labels: --- to sandbox, I Lang

#6063 Designer added: Claus Eggers Sørensen
  catalog/designers/clauseggerssorensen/bio.html
  catalog/designers/clauseggerssorensen/clauseggerssorensen.png
  catalog/designers/clauseggerssorensen/info.pb
Labels: --- to sandbox, I Designer profile

#6068 Delicious Handrawn: Version 1.002; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.27] added
  ofl/delicioushandrawn/DeliciousHandrawn-Regular.ttf
  ofl/delicioushandrawn/METADATA.pb
Labels: - Ready for Review, I Small Fix

#5771 GFK 2023 improvements
  cc-by-sa/knowledge/glossary/terms/alphabet/content.md
  cc-by-sa/knowledge/glossary/terms/cjk/content.md
  cc-by-sa/knowledge/glossary/terms/cyrillic/content.md
  cc-by-sa/knowledge/glossary/terms/letters/content.md
  cc-by-sa/knowledge/glossary/terms/script/content.md
  cc-by-sa/knowledge/glossary/terms/script/images/thumbnail.svg
  cc-by-sa/knowledge/glossary/terms/script/term.textproto
  cc-by-sa/knowledge/glossary/terms/tofu/content.md
  cc-by-sa/knowledge/glossary/terms/writing_system/content.md
  cc-by-sa/knowledge/glossary/terms/writing_system/images/thumbnail.svg
  cc-by-sa/knowledge/glossary/terms/writing_system/term.textproto
  cc-by-sa/knowledge/modules/designing_hangeul/lessons/an_alphabet_for_reading_and_writing/content.md
  cc-by-sa/knowledge/modules/designing_hangeul/lessons/an_alphabet_for_reading_and_writing/lesson.textproto
  cc-by-sa/knowledge/modules/designing_hangeul/lessons/an_introduction_to_hangeul/content.md
  cc-by-sa/knowledge/modules/designing_hangeul/lessons/an_introduction_to_hangeul/lesson.textproto
  cc-by-sa/knowledge/modules/designing_hangeul/lessons/designing_for_learnability/lesson.textproto
  cc-by-sa/knowledge/modules/designing_hangeul/lessons/lessons_from_hangeul/lesson.textproto
  cc-by-sa/knowledge/modules/designing_hangeul/lessons/making_the_details_matter/lesson.textproto
  cc-by-sa/knowledge/modules/readability_and_accessibility/lessons/how_type_influences_readability/content.md
  cc-by-sa/knowledge/modules/readability_and_accessibility/lessons/introducing_accessibility_in_typography/content.md
  cc-by-sa/knowledge/modules/readability_and_accessibility/lessons/introducing_accessibility_in_typography/images/accessibility_extra.svg
  cc-by-sa/knowledge/modules/type_in_china_japan_and_korea/lessons/cjk_typesetting_rules/lesson.textproto
  cc-by-sa/knowledge/modules/type_in_china_japan_and_korea/lessons/japanese_typography_basics/content.md
  cc-by-sa/knowledge/modules/type_in_china_japan_and_korea/lessons/japanese_typography_basics/lesson.textproto
  cc-by-sa/knowledge/modules/type_in_china_japan_and_korea/lessons/the_evolution_of_hangeul_type_design/content.md
  cc-by-sa/knowledge/modules/type_in_china_japan_and_korea/lessons/the_evolution_of_hangeul_type_design/lesson.textproto
  cc-by-sa/knowledge/modules/type_in_china_japan_and_korea/lessons/type_classification_in_cjk_chinese/lesson.textproto
  cc-by-sa/knowledge/modules/type_in_china_japan_and_korea/lessons/type_classification_in_cjk_japanese/lesson.textproto
  cc-by-sa/knowledge/modules/type_in_china_japan_and_korea/lessons/type_classification_in_cjk_korean/lesson.textproto
  cc-by-sa/knowledge/modules/using_type/lessons/language_support_in_fonts/content.md
  cc-by-sa/knowledge/modules/using_type/lessons/language_support_in_fonts/lesson.textproto
Labels: --- to sandbox, I Knowledge

#6079 Braah One: Version 1.000 added
  ofl/braahone/BraahOne-Regular.ttf
  ofl/braahone/DESCRIPTION.en_us.html
  ofl/braahone/METADATA.pb
  ofl/braahone/OFL.txt
  ofl/braahone/upstream.yaml
Labels: - Ready for Review, I New Font, II Indic / Brahmic / Thai / Tai

#6080 Ashish Kumar designer info (Braah)
  catalog/designers/ashishkumar/ashishkumar.png
  catalog/designers/ashishkumar/bio.html
  catalog/designers/ashishkumar/info.pb
Labels: - Ready for Review, I Designer profile

#6109 Noto Sans Tamil: Version 2.004 added
  ofl/notosanstamil/METADATA.pb
  ofl/notosanstamil/NotoSansTamil[wdth,wght].ttf
  ofl/notosanstamil/upstream.yaml
Labels: --- to sandbox, I Font Upgrade

#6117 Noto Sans Gurmukhi: Version 2.004 added
  ofl/notosansgurmukhi/METADATA.pb
  ofl/notosansgurmukhi/NotoSansGurmukhi[wdth,wght].ttf
  ofl/notosansgurmukhi/upstream.yaml
Labels: --- to sandbox, I Font Upgrade

#6115 Noto Serif Sinhala: Version 2.007 added
  ofl/notoserifsinhala/METADATA.pb
  ofl/notoserifsinhala/NotoSerifSinhala[wdth,wght].ttf
  ofl/notoserifsinhala/upstream.yaml
Labels: --- to sandbox, I Font Upgrade

#6114 Noto Serif Kannada: Version 2.004 added
  ofl/notoserifkannada/METADATA.pb
  ofl/notoserifkannada/NotoSerifKannada[wght].ttf
  ofl/notoserifkannada/upstream.yaml
Labels: --- to sandbox, I Font Upgrade

#6113 Noto Sans Kannada: Version 2.004 added
  ofl/notosanskannada/METADATA.pb
  ofl/notosanskannada/NotoSansKannada[wdth,wght].ttf
  ofl/notosanskannada/upstream.yaml
Labels: --- to sandbox, I Font Upgrade

#6111 Noto Serif Malayalam: Version 2.104 added
  ofl/notoserifmalayalam/METADATA.pb
  ofl/notoserifmalayalam/NotoSerifMalayalam[wght].ttf
  ofl/notoserifmalayalam/upstream.yaml
Labels: --- to sandbox, I Font Upgrade

#6072 Bruno Ace: Version 1.100; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.27] added
  ofl/brunoace/BrunoAce-Regular.ttf
  ofl/brunoace/DESCRIPTION.en_us.html
  ofl/brunoace/METADATA.pb
  ofl/brunoace/OFL.txt
  ofl/brunoace/upstream.yaml
Labels: --- to sandbox, I New Font

#6073 Bruno Ace SC: Version 1.100; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.27] added
  ofl/brunoacesc/BrunoAceSC-Regular.ttf
  ofl/brunoacesc/DESCRIPTION.en_us.html
  ofl/brunoacesc/METADATA.pb
  ofl/brunoacesc/OFL.txt
  ofl/brunoacesc/upstream.yaml
Labels: --- to sandbox, I New Font

#6110 Noto Sans Oriya: Version 2.005 added
  ofl/notosansoriya/METADATA.pb
  ofl/notosansoriya/NotoSansOriya[wdth,wght].ttf
  ofl/notosansoriya/upstream.yaml
Labels: --- to sandbox, I Font Upgrade

#6081 Comme: Version 1.000;gftools[0.9.27] added
  ofl/comme/Comme[wght].ttf
  ofl/comme/DESCRIPTION.en_us.html
  ofl/comme/METADATA.pb
  ofl/comme/OFL.txt
  ofl/comme/upstream.yaml
Labels: --- to sandbox, I New Font
