Repository google/fonts, pull requests merged in 2023-06, with the labels that each got.

#5320 Noto Sans Nabataean: Version 2.001; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosansnabataean/METADATA.pb
  ofl/notosansnabataean/NotoSansNabataean-Regular.ttf
  ofl/notosansnabataean/OFL.txt
  ofl/notosansnabataean/upstream.yaml
Labels: - Ready for Review, I Font Upgrade

#5319 Noto Sans Samaritan: Version 2.001; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosanssamaritan/METADATA.pb
  ofl/notosanssamaritan/NotoSansSamaritan-Regular.ttf
  ofl/notosanssamaritan/OFL.txt
  ofl/notosanssamaritan/upstream.yaml
Labels: --- to sandbox, I Font Upgrade

#6332 Space Mono: Designer name in Metadata
  ofl/spacemono/METADATA.pb
Labels: --- to sandbox, I Description/Metadata/OFL

#6335 Secular One: Version 1.002; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.29] added
  ofl/secularone/DESCRIPTION.en_us.html
  ofl/secularone/METADATA.pb
  ofl/secularone/OFL.txt
  ofl/secularone/SecularOne-Regular.ttf
  ofl/secularone/upstream.yaml
Labels: --- to sandbox, I Small Fix

#6331 Designer added: Colophon Foundry
  catalog/designers/colophonfoundry/bio.html
  catalog/designers/colophonfoundry/colophonfoundry.png
  catalog/designers/colophonfoundry/info.pb
Labels: --- to sandbox, I Designer profile

#6338 Lang
  lang/CHANGELOG.md
  lang/Lib/gflanguages/data/languages/doi_Deva.textproto
  lang/Lib/gflanguages/data/languages/fy_Latn.textproto
  lang/Lib/gflanguages/data/languages/gld_Cyrl.textproto
  lang/Lib/gflanguages/data/languages/grc_Cprt.textproto
  lang/Lib/gflanguages/data/languages/mak_Maka.textproto
  lang/Lib/gflanguages/data/languages/sa_Deva.textproto
  lang/Lib/gflanguages/data/languages/st_Latn.textproto
  lang/Lib/gflanguages/data/languages/th_Thai.textproto
  lang/Lib/gflanguages/data/scripts/Maka.textproto
  lang/tests/test_data_languages.py
Labels: --- to sandbox, I Lang

#5789 Noto Sans: Version 2.010 added
  ofl/notosans/METADATA.pb
  ofl/notosans/NotoSans-Black.ttf
  ofl/notosans/NotoSans-BlackItalic.ttf
  ofl/notosans/NotoSans-Bold.ttf
  ofl/notosans/NotoSans-BoldItalic.ttf
  ofl/notosans/NotoSans-ExtraBold.ttf
  ofl/notosans/NotoSans-ExtraBoldItalic.ttf
  ofl/notosans/NotoSans-ExtraLight.ttf
  ofl/notosans/NotoSans-ExtraLightItalic.ttf
  ofl/notosans/NotoSans-Italic.ttf
  ofl/notosans/NotoSans-Italic[wdth,wght].ttf
  ofl/notosans/NotoSans-Light.ttf
  ofl/notosans/NotoSans-LightItalic.ttf
  ofl/notosans/NotoSans-Medium.ttf
  ofl/notosans/NotoSans-MediumItalic.ttf
  ofl/notosans/NotoSans-Regular.ttf
  ofl/notosans/NotoSans-SemiBold.ttf
  ofl/notosans/NotoSans-SemiBoldItalic.ttf
  ofl/notosans/NotoSans-Thin.ttf
  ofl/notosans/NotoSans-ThinItalic.ttf
  ofl/notosans/NotoSans[wdth,wght].ttf
  ofl/notosans/OFL.txt
  ofl/notosans/upstream.yaml
Labels: III VF Replacement, - Ready for Review, I Font Upgrade

#6328 Delisted Source Sans Pro and Source Serif Pro
  TRIVIA.md
  ofl/pecita/DESCRIPTION.en_us.html
  ofl/pecita/METADATA.pb
  ofl/pecita/OFL.txt
  ofl/pecita/Pecita.ttf
  ofl/ruserius/DESCRIPTION.en_us.html
  ofl/ruserius/METADATA.pb
  ofl/ruserius/OFL.txt
  ofl/ruserius/RUSerius-Regular.ttf
  ofl/ruserius/upstream.yaml
  ofl/sourcesanspro/DESCRIPTION.en_us.html
  ofl/sourcesanspro/METADATA.pb
  ofl/sourcesanspro/OFL.txt
  ofl/sourcesanspro/README
  ofl/sourcesanspro/SourceSansPro-Black.ttf
  ofl/sourcesanspro/SourceSansPro-BlackItalic.ttf
  ofl/sourcesanspro/SourceSansPro-Bold.ttf
  ofl/sourcesanspro/SourceSansPro-BoldItalic.ttf
  ofl/sourcesanspro/SourceSansPro-ExtraLight.ttf
  ofl/sourcesanspro/SourceSansPro-ExtraLightItalic.ttf
  ofl/sourcesanspro/SourceSansPro-Italic.ttf
  ofl/sourcesanspro/SourceSansPro-Light.ttf
  ofl/sourcesanspro/SourceSansPro-LightItalic.ttf
  ofl/sourcesanspro/SourceSansPro-Regular.ttf
  ofl/sourcesanspro/SourceSansPro-SemiBold.ttf
  ofl/sourcesanspro/SourceSansPro-SemiBoldItalic.ttf
  ofl/sourceserifpro/DESCRIPTION.en_us.html
  ofl/sourceserifpro/METADATA.pb
  ofl/sourceserifpro/OFL.txt
  ofl/sourceserifpro/README
  ofl/sourceserifpro/SourceSerifPro-Black.ttf
  ofl/sourceserifpro/SourceSerifPro-BlackItalic.ttf
  ofl/sourceserifpro/SourceSerifPro-Bold.ttf
  ofl/sourceserifpro/SourceSerifPro-BoldItalic.ttf
  ofl/sourceserifpro/SourceSerifPro-ExtraLight.ttf
  ofl/sourceserifpro/SourceSerifPro-ExtraLightItalic.ttf
  ofl/sourceserifpro/SourceSerifPro-Italic.ttf
  ofl/sourceserifpro/SourceSerifPro-Light.ttf
  ofl/sourceserifpro/SourceSerifPro-LightItalic.ttf
  ofl/sourceserifpro/SourceSerifPro-Regular.ttf
  ofl/sourceserifpro/SourceSerifPro-SemiBold.ttf
  ofl/sourceserifpro/SourceSerifPro-SemiBoldItalic.ttf
  to_delist.txt
Labels: I Tools / workflow / repo

#6345 Aleo: Version 2.001;gftools[0.9.29] added
  ofl/aleo/Aleo-Bold.ttf
  ofl/aleo/Aleo-BoldItalic.ttf
  ofl/aleo/Aleo-Italic.ttf
  ofl/aleo/Aleo-Italic[wght].ttf
  ofl/aleo/Aleo-Light.ttf
  ofl/aleo/Aleo-LightItalic.ttf
  ofl/aleo/Aleo-Regular.ttf
  ofl/aleo/Aleo[wght].ttf
  ofl/aleo/DESCRIPTION.en_us.html
  ofl/aleo/METADATA.pb
  ofl/aleo/OFL.txt
  ofl/aleo/upstream.yaml
Labels: III Expand glyphset, III Expand styles, III VF Replacement, --- to sandbox, I Font Upgrade

#6025 Noto Serif Ottoman Siyaq: Version 1.005; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notoserifottomansiyaq/DESCRIPTION.en_us.html
  ofl/notoserifottomansiyaq/METADATA.pb
  ofl/notoserifottomansiyaq/NotoSerifOttomanSiyaq-Regular.ttf
  ofl/notoserifottomansiyaq/OFL.txt
  ofl/notoserifottomansiyaq/article/ARTICLE.en_us.html
  ofl/notoserifottomansiyaq/upstream.yaml
Labels: --- to sandbox, I New Font

#5397 Noto Serif Makasar: Version 1.001; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notoserifmakasar/DESCRIPTION.en_us.html
  ofl/notoserifmakasar/METADATA.pb
  ofl/notoserifmakasar/NotoSerifMakasar-Regular.ttf
  ofl/notoserifmakasar/OFL.txt
  ofl/notoserifmakasar/article/ARTICLE.en_us.html
  ofl/notoserifmakasar/upstream.yaml
Labels: --- to sandbox, I New Font

#6352 pull Lang v089: Gunjala Gondi sample text
  lang/CHANGELOG.md
  lang/Lib/gflanguages/data/languages/sa_Gong.textproto
  lang/Lib/gflanguages/data/languages/wsg_Gong.textproto
Labels: --- to sandbox, I Lang

#6356 Akatab: added sample text to avoid tofu
  ofl/akatab/METADATA.pb
Labels: - Ready for Review, I Description/Metadata/OFL

#6361 Fix Gondi Metadata
  ofl/narnoor/METADATA.pb
  ofl/notosansgunjalagondi/METADATA.pb
Labels: I Description/Metadata/OFL

#6318 DM Sans: Version 4.003;gftools[0.9.29] added
  ofl/dmsans/DESCRIPTION.en_us.html
  ofl/dmsans/DMSans-Bold.ttf
  ofl/dmsans/DMSans-BoldItalic.ttf
  ofl/dmsans/DMSans-Italic.ttf
  ofl/dmsans/DMSans-Italic[opsz,wght].ttf
  ofl/dmsans/DMSans-Medium.ttf
  ofl/dmsans/DMSans-MediumItalic.ttf
  ofl/dmsans/DMSans-Regular.ttf
  ofl/dmsans/DMSans[opsz,wght].ttf
  ofl/dmsans/METADATA.pb
  ofl/dmsans/OFL.txt
  ofl/dmsans/upstream.yaml
Labels: III Expand glyphset, III VF Replacement, I Font Upgrade

#6373 DM Sans: Version 4.004;gftools[0.9.30] added
  ofl/dmsans/DMSans-Italic[opsz,wght].ttf
  ofl/dmsans/DMSans[opsz,wght].ttf
  ofl/dmsans/METADATA.pb
Labels: III Expand glyphset, III VF Replacement, I Font Upgrade

#6355 Frank Ruhl Libre: Version 6.002;gftools[0.9.28] added
  ofl/frankruhllibre/FrankRuhlLibre[wght].ttf
  ofl/frankruhllibre/METADATA.pb
Labels: I Small Fix

#6370 Catalog: Omaima Dajani (Rubik Arabic)
  catalog/designers/omaimadajani/bio.html
  catalog/designers/omaimadajani/info.pb
Labels: I Designer profile

#6347 Catalog: Daniel Grumer (Rubik Arabic)
  catalog/designers/danielgrumer/bio.html
  catalog/designers/danielgrumer/danielgrumer.png
  catalog/designers/danielgrumer/info.pb
Labels: I Designer profile

#6342 Ysabeau SC: Version 2.001;gftools[0.9.28.dev9+g7d2139d]; featfreeze: smcp added
  ofl/ysabeausc/DESCRIPTION.en_us.html
  ofl/ysabeausc/METADATA.pb
  ofl/ysabeausc/OFL.txt
  ofl/ysabeausc/YsabeauSC[wght].ttf
  ofl/ysabeausc/upstream.yaml
Labels: I New Font

#6341 Ysabeau Infant: Version 2.001;gftools[0.9.28.dev9+g7d2139d]; featfreeze: ss01,ss02,lnum added
  ofl/ysabeauinfant/DESCRIPTION.en_us.html
  ofl/ysabeauinfant/METADATA.pb
  ofl/ysabeauinfant/OFL.txt
  ofl/ysabeauinfant/YsabeauInfant-Italic[wght].ttf
  ofl/ysabeauinfant/YsabeauInfant[wght].ttf
  ofl/ysabeauinfant/upstream.yaml
Labels: - Ready for Review, I New Font

#6340 Ysabeau Office: Version 2.001;gftools[0.9.28.dev9+g7d2139d]; featfreeze: tnum,lnum,ss02 added
  ofl/ysabeauoffice/DESCRIPTION.en_us.html
  ofl/ysabeauoffice/METADATA.pb
  ofl/ysabeauoffice/OFL.txt
  ofl/ysabeauoffice/YsabeauOffice-Italic[wght].ttf
  ofl/ysabeauoffice/YsabeauOffice[wght].ttf
  ofl/ysabeauoffice/upstream.yaml
Labels: I New Font

#6249 Agdasima: Version 2.002 added
  ofl/agdasima/Agdasima-Bold.ttf
  ofl/agdasima/Agdasima-Regular.ttf
  ofl/agdasima/DESCRIPTION.en_us.html
  ofl/agdasima/METADATA.pb
Labels: I New Font

#6374 Playfair: Version 2.001;gftools[0.9.30] added
  ofl/playfair/DESCRIPTION.en_us.html
  ofl/playfair/METADATA.pb
  ofl/playfair/Playfair-Italic[opsz,wdth,wght].ttf
  ofl/playfair/Playfair[opsz,wdth,wght].ttf
Labels: - Ready for Review, I Small Fix

#6358 Subtree pull Axis Registry introducing `YELA`
  axisregistry/Lib/axisregistry/data/y_element_alignment.textproto
Labels: I Axis Registry

#5701 Noto Sans Gunjala Gondi: Version 1.003 added
  ofl/notosansgunjalagondi/DESCRIPTION.en_us.html
  ofl/notosansgunjalagondi/METADATA.pb
  ofl/notosansgunjalagondi/NotoSansGunjalaGondi-Regular.ttf
  ofl/notosansgunjalagondi/NotoSansGunjalaGondi[wght].ttf
  ofl/notosansgunjalagondi/OFL.txt
  ofl/notosansgunjalagondi/article/ARTICLE.en_us.html
  ofl/notosansgunjalagondi/upstream.yaml
Labels: III VF Replacement, I Font Upgrade

#5756 Noto Sans Duployan: Version 3.001 added
  ofl/notosansduployan/DESCRIPTION.en_us.html
  ofl/notosansduployan/METADATA.pb
  ofl/notosansduployan/NotoSansDuployan-Bold.ttf
  ofl/notosansduployan/NotoSansDuployan-Regular.ttf
  ofl/notosansduployan/OFL.txt
  ofl/notosansduployan/article/ARTICLE.en_us.html
  ofl/notosansduployan/upstream.yaml
Labels: I Font Upgrade

#5705 Noto Sans Tamil Supplement: Version 2.001; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosanstamilsupplement/METADATA.pb
  ofl/notosanstamilsupplement/NotoSansTamilSupplement-Regular.ttf
  ofl/notosanstamilsupplement/OFL.txt
  ofl/notosanstamilsupplement/article/ARTICLE.en_us.html
  ofl/notosanstamilsupplement/upstream.yaml
Labels: I Font Upgrade

#5318 Noto Sans Old Sogdian: Version 2.002; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosansoldsogdian/METADATA.pb
  ofl/notosansoldsogdian/NotoSansOldSogdian-Regular.ttf
  ofl/notosansoldsogdian/OFL.txt
  ofl/notosansoldsogdian/upstream.yaml
Labels: I Font Upgrade

#5316 Noto Sans Meroitic: Version 2.001; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosansmeroitic/METADATA.pb
  ofl/notosansmeroitic/NotoSansMeroitic-Regular.ttf
  ofl/notosansmeroitic/OFL.txt
  ofl/notosansmeroitic/upstream.yaml
Labels: I Font Upgrade

#6252 Bacasime Antique: Version 2.000 added
  ofl/bacasimeantique/BacasimeAntique-Regular.ttf
  ofl/bacasimeantique/DESCRIPTION.en_us.html
  ofl/bacasimeantique/METADATA.pb
  ofl/bacasimeantique/OFL.txt
  ofl/bacasimeantique/upstream.yaml
Labels: I New Font

#6158 Belanosima: Version 2.000 added
  ofl/belanosima/Belanosima-Bold.ttf
  ofl/belanosima/Belanosima-Regular.ttf
  ofl/belanosima/Belanosima-SemiBold.ttf
  ofl/belanosima/DESCRIPTION.en_us.html
  ofl/belanosima/METADATA.pb
  ofl/belanosima/OFL.txt
  ofl/belanosima/upstream.yaml
Labels: I New Font

#6381 Tektur: Version 1.004;gftools[0.9.30] added
  ofl/tektur/DESCRIPTION.en_us.html
  ofl/tektur/METADATA.pb
  ofl/tektur/OFL.txt
  ofl/tektur/Tektur[wdth,wght].ttf
  ofl/tektur/upstream.yaml
Labels: I New Font

#6185 Wavefont: Version 3.003 added
  ofl/wavefont/DESCRIPTION.en_us.html
  ofl/wavefont/METADATA.pb
  ofl/wavefont/OFL.txt
  ofl/wavefont/Wavefont[ROND,YELA,wght].ttf
  ofl/wavefont/upstream.yaml
Labels: - Ready for Review, I New Font, III Custom axes

#6251 Lugrasimo: Version 1.001 added
  ofl/lugrasimo/Lugrasimo-Regular.ttf
  ofl/lugrasimo/METADATA.pb
Labels: I New Font

#6250 Lumanosimo: Version 1.010 added
  ofl/lumanosimo/Lumanosimo-Regular.ttf
  ofl/lumanosimo/METADATA.pb
Labels: - Ready for Review, I New Font

#6383 Rubik: added arabic subet
  ofl/rubik/METADATA.pb
Labels: I Description/Metadata/OFL

#6385 updated lists
  to_production.txt
  to_sandbox.txt
Labels: I Tools / workflow / repo

#6384 Revert "Francois One: Version 3.000; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.23] added"
  ofl/francoisone/DESCRIPTION.en_us.html
  ofl/francoisone/FrancoisOne-Regular.ttf
  ofl/francoisone/METADATA.pb
  ofl/francoisone/OFL.txt
  ofl/francoisone/upstream.yaml
Labels: I Tools / workflow / repo

#6382 Dmitry Ivanov: designer added (wavefont)
  catalog/designers/dmitryivanov/bio.html
  catalog/designers/dmitryivanov/dmitryivanov.png
  catalog/designers/dmitryivanov/info.pb
Labels: - Ready for Review, I Designer profile

#6395 Tektur: Version 1.005;gftools[0.9.30] added
  ofl/tektur/METADATA.pb
  ofl/tektur/Tektur[wdth,wght].ttf
  ofl/tektur/upstream.yaml
Labels: I Small Fix

#5315 Noto Sans Old South Arabian: Version 2.001; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosansoldsoutharabian/METADATA.pb
  ofl/notosansoldsoutharabian/NotoSansOldSouthArabian-Regular.ttf
  ofl/notosansoldsoutharabian/OFL.txt
  ofl/notosansoldsoutharabian/upstream.yaml
Labels: - Ready for Review, I Font Upgrade

#5314 Noto Sans Old Permic: Version 2.001; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosansoldpermic/METADATA.pb
  ofl/notosansoldpermic/NotoSansOldPermic-Regular.ttf
  ofl/notosansoldpermic/OFL.txt
  ofl/notosansoldpermic/upstream.yaml
Labels: - Ready for Review, I Font Upgrade

#5313 Noto Sans Old Persian: Version 2.001; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosansoldpersian/METADATA.pb
  ofl/notosansoldpersian/NotoSansOldPersian-Regular.ttf
  ofl/notosansoldpersian/OFL.txt
  ofl/notosansoldpersian/upstream.yaml
Labels: - Ready for Review, I Font Upgrade

#6396 Victor Mono: Version 1.561;gftools[0.9.30] added
  ofl/victormono/DESCRIPTION.en_us.html
  ofl/victormono/METADATA.pb
  ofl/victormono/OFL.txt
  ofl/victormono/VictorMono-Italic[wght].ttf
  ofl/victormono/VictorMono[wght].ttf
  ofl/victormono/upstream.yaml
Labels: I New Font

#6378 Bricolage Grotesque: Version 1.000;gftools[0.9.30] added
  ofl/bricolagegrotesque/BricolageGrotesque[opsz,wdth,wght].ttf
  ofl/bricolagegrotesque/DESCRIPTION.en_us.html
  ofl/bricolagegrotesque/METADATA.pb
  ofl/bricolagegrotesque/OFL.txt
  ofl/bricolagegrotesque/upstream.yaml
Labels: -- Needs Meta/Desc/License changes, I New Font

#5312 Noto Sans Old North Arabian: Version 2.001; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosansoldnortharabian/METADATA.pb
  ofl/notosansoldnortharabian/NotoSansOldNorthArabian-Regular.ttf
  ofl/notosansoldnortharabian/OFL.txt
  ofl/notosansoldnortharabian/upstream.yaml
Labels: - Ready for Review, I Font Upgrade

#6416 Joan: Version 1.001; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.30] added
  ofl/joan/Joan-Regular.ttf
  ofl/joan/METADATA.pb
  ofl/joan/upstream.yaml
Labels: I Font Upgrade

#6417 Lang v050
  lang/CHANGELOG.md
  lang/Lib/gflanguages/data/languages/sq_Vith.textproto
  lang/Lib/gflanguages/data/scripts/Vith.textproto
Labels: I Lang

#6386 Designer added: Mathieu Triay
  catalog/designers/mathieutriay/bio.html
  catalog/designers/mathieutriay/info.pb
  catalog/designers/mathieutriay/mathieutriay.png
Labels: I Designer profile

#5767 Noto Serif Khitan Small Script: Version 1.000; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notoserifkhitansmallscript/DESCRIPTION.en_us.html
  ofl/notoserifkhitansmallscript/METADATA.pb
  ofl/notoserifkhitansmallscript/NotoSerifKhitanSmallScript-Regular.ttf
  ofl/notoserifkhitansmallscript/OFL.txt
  ofl/notoserifkhitansmallscript/article/ARTICLE.en_us.html
  ofl/notoserifkhitansmallscript/upstream.yaml
Labels: I New Font

#5702 Noto Sans Cypro Minoan: Version 1.503; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosanscyprominoan/DESCRIPTION.en_us.html
  ofl/notosanscyprominoan/METADATA.pb
  ofl/notosanscyprominoan/NotoSansCyproMinoan-Regular.ttf
  ofl/notosanscyprominoan/OFL.txt
  ofl/notosanscyprominoan/article/ARTICLE.en_us.html
  ofl/notosanscyprominoan/upstream.yaml
Labels: I New Font

#5740 Noto Sans Syriac Eastern: Version 3.001 added
  ofl/notosanssyriaceastern/DESCRIPTION.en_us.html
  ofl/notosanssyriaceastern/METADATA.pb
  ofl/notosanssyriaceastern/NotoSansSyriacEastern[wght].ttf
  ofl/notosanssyriaceastern/OFL.txt
  ofl/notosanssyriaceastern/article/ARTICLE.en_us.html
  ofl/notosanssyriaceastern/upstream.yaml
Labels: I New Font

#5311 Noto Sans Old Italic: Version 2.003; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosansolditalic/METADATA.pb
  ofl/notosansolditalic/NotoSansOldItalic-Regular.ttf
  ofl/notosansolditalic/OFL.txt
  ofl/notosansolditalic/upstream.yaml
Labels: I Font Upgrade

#5310 Noto Sans Marchen: Version 2.003; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosansmarchen/METADATA.pb
  ofl/notosansmarchen/NotoSansMarchen-Regular.ttf
  ofl/notosansmarchen/OFL.txt
  ofl/notosansmarchen/upstream.yaml
Labels: I Font Upgrade

#5317 Noto Sans Old Turkic: Version 2.002; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosansoldturkic/METADATA.pb
  ofl/notosansoldturkic/NotoSansOldTurkic-Regular.ttf
  ofl/notosansoldturkic/OFL.txt
  ofl/notosansoldturkic/upstream.yaml
Labels: I Font Upgrade

#5394 Noto Serif Vithkuqi: Version 1.005 added
  ofl/notoserifvithkuqi/DESCRIPTION.en_us.html
  ofl/notoserifvithkuqi/METADATA.pb
  ofl/notoserifvithkuqi/NotoSerifVithkuqi[wght].ttf
  ofl/notoserifvithkuqi/OFL.txt
  ofl/notoserifvithkuqi/article/ARTICLE.en_us.html
  ofl/notoserifvithkuqi/upstream.yaml
Labels: I New Font, -- Needs lang/glyphset update

#6420 updated lists
  to_production.txt
  to_sandbox.txt
Labels: I Tools / workflow / repo

#6421 Bangers: Version 2.100; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.31] added
  ofl/bangers/Bangers-Regular.ttf
  ofl/bangers/DESCRIPTION.en_us.html
  ofl/bangers/METADATA.pb
  ofl/bangers/OFL.txt
  ofl/bangers/upstream.yaml
Labels: III Expand glyphset, I Font Upgrade

#6457 Akatab: shortened sample text
  ofl/akatab/METADATA.pb
Labels: I Description/Metadata/OFL

#6459 Wavefont: changed sample text and corrected description
  ofl/wavefont/DESCRIPTION.en_us.html
  ofl/wavefont/METADATA.pb
Labels: I Description/Metadata/OFL

#5307 Noto Sans Old Hungarian: Version 2.004; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosansoldhungarian/METADATA.pb
  ofl/notosansoldhungarian/NotoSansOldHungarian-Regular.ttf
  ofl/notosansoldhungarian/OFL.txt
  ofl/notosansoldhungarian/upstream.yaml
Labels: I Font Upgrade

#5306 Noto Serif Yezidi: Version 1.001 added
  ofl/notoserifyezidi/METADATA.pb
  ofl/notoserifyezidi/NotoSerifYezidi[wght].ttf
  ofl/notoserifyezidi/OFL.txt
  ofl/notoserifyezidi/upstream.yaml
Labels: I Font Upgrade

#5305 Noto Sans Soyombo: Version 2.001; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosanssoyombo/METADATA.pb
  ofl/notosanssoyombo/NotoSansSoyombo-Regular.ttf
  ofl/notosanssoyombo/OFL.txt
  ofl/notosanssoyombo/upstream.yaml
Labels: I Font Upgrade

#5304 Noto Sans Runic: Version 2.002; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosansrunic/METADATA.pb
  ofl/notosansrunic/NotoSansRunic-Regular.ttf
  ofl/notosansrunic/OFL.txt
  ofl/notosansrunic/upstream.yaml
Labels: I Font Upgrade

#5303 Noto Sans Glagolitic: Version 2.002; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosansglagolitic/METADATA.pb
  ofl/notosansglagolitic/NotoSansGlagolitic-Regular.ttf
  ofl/notosansglagolitic/OFL.txt
  ofl/notosansglagolitic/upstream.yaml
Labels: I Font Upgrade

#5302 Noto Sans Kaithi: Version 2.004; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosanskaithi/METADATA.pb
  ofl/notosanskaithi/NotoSansKaithi-Regular.ttf
  ofl/notosanskaithi/OFL.txt
  ofl/notosanskaithi/upstream.yaml
Labels: I Font Upgrade

#6423 Nuosu SIL: Version 2.300 added
  ofl/nuosusil/METADATA.pb
  ofl/nuosusil/NuosuSIL-Regular.ttf
  ofl/nuosusil/OFL.txt
  ofl/nuosusil/article/ARTICLE.en_us.html
  ofl/nuosusil/article/hero.png
  ofl/nuosusil/upstream.yaml
Labels: II CJK, I Font Upgrade

#6473 updated to lists
  to_production.txt
  to_sandbox.txt
Labels: I Tools / workflow / repo

#6476 Update issue templates
  .github/ISSUE_TEMPLATE/1_add-font.md
  .github/ISSUE_TEMPLATE/3_font-bug.md
Labels: I Tools / workflow / repo

#6477 Added deleted lang path to to_delist list
  to_delist.txt
  to_production.txt
Labels: I Tools / workflow / repo

#6474 Signika: Version 2.003;gftools[0.9.32] added
  ofl/signika/DESCRIPTION.en_us.html
  ofl/signika/METADATA.pb
  ofl/signika/Signika[GRAD,wght].ttf
  ofl/signika/Signika[wght].ttf
  ofl/signika/upstream.yaml
Labels: III Expand styles, I Font Upgrade

#6482 Baskervville: Version 1.003; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.31] added
  ofl/baskervville/Baskervville-Italic.ttf
  ofl/baskervville/Baskervville-Regular.ttf
  ofl/baskervville/DESCRIPTION.en_us.html
  ofl/baskervville/METADATA.pb
Labels: I Small Fix
