Repository google/fonts, pull requests merged in 2023-05, with the labels that each got.

#6201 Harmattan: Version 4.000 added
  ofl/harmattan/DESCRIPTION.en_us.html
  ofl/harmattan/Harmattan-Bold.ttf
  ofl/harmattan/Harmattan-Medium.ttf
  ofl/harmattan/Harmattan-Regular.ttf
  ofl/harmattan/Harmattan-SemiBold.ttf
  ofl/harmattan/METADATA.pb
  ofl/harmattan/OFL.txt
  ofl/harmattan/upstream.yaml
Labels: III Expand glyphset, III Expand styles, I Font Upgrade, II Arabic / Hebrew / Semitic / RTL, -- Needs lang/glyphset update

#6199 Scheherazade New: Version 4.000 added
  ofl/scheherazadenew/DESCRIPTION.en_us.html
  ofl/scheherazadenew/METADATA.pb
  ofl/scheherazadenew/OFL.txt
  ofl/scheherazadenew/ScheherazadeNew-Bold.ttf
  ofl/scheherazadenew/ScheherazadeNew-Medium.ttf
  ofl/scheherazadenew/ScheherazadeNew-Regular.ttf
  ofl/scheherazadenew/ScheherazadeNew-SemiBold.ttf
  ofl/scheherazadenew/upstream.yaml
Labels: III Expand glyphset, III Expand styles, --- to sandbox, I Font Upgrade, II Arabic / Hebrew / Semitic / RTL, -- Needs lang/glyphset update

#6198 Lateef: Version 4.000 added
  ofl/lateef/Lateef-Bold.ttf
  ofl/lateef/Lateef-ExtraBold.ttf
  ofl/lateef/Lateef-ExtraLight.ttf
  ofl/lateef/Lateef-Light.ttf
  ofl/lateef/Lateef-Medium.ttf
  ofl/lateef/Lateef-Regular.ttf
  ofl/lateef/Lateef-SemiBold.ttf
  ofl/lateef/METADATA.pb
  ofl/lateef/OFL.txt
  ofl/lateef/upstream.yaml
Labels: III Expand glyphset, --- to sandbox, I Font Upgrade, II Arabic / Hebrew / Semitic / RTL, -- Needs lang/glyphset update

#6228 Instrument serif: description corrected
  ofl/instrumentserif/DESCRIPTION.en_us.html
Labels: - Ready for Review, I Description/Metadata/OFL

#6133 Noto Sans Mono: Version 2.011 added
  ofl/notosansmono/METADATA.pb
  ofl/notosansmono/NotoSansMono[wdth,wght].ttf
  ofl/notosansmono/upstream.yaml
Labels: - Ready for Review, I Font Upgrade

#5737 Noto Traditional Nushu: Version 2.003 added
  ofl/nototraditionalnushu/METADATA.pb
  ofl/nototraditionalnushu/NotoTraditionalNushu-Regular.ttf
  ofl/nototraditionalnushu/NotoTraditionalNushu[wght].ttf
  ofl/nototraditionalnushu/OFL.txt
  ofl/nototraditionalnushu/upstream.yaml
Labels: III VF Replacement, --- to sandbox, I Font Upgrade

#5445 Noto Sans Inscriptional Parthian: Version 2.003; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosansinscriptionalparthian/METADATA.pb
  ofl/notosansinscriptionalparthian/NotoSansInscriptionalParthian-Regular.ttf
  ofl/notosansinscriptionalparthian/OFL.txt
  ofl/notosansinscriptionalparthian/upstream.yaml
Labels: - Ready for Review, I Font Upgrade

#5392 Noto Sans Chorasmian: Version 1.002; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosanschorasmian/DESCRIPTION.en_us.html
  ofl/notosanschorasmian/METADATA.pb
  ofl/notosanschorasmian/NotoSansChorasmian-Regular.ttf
  ofl/notosanschorasmian/OFL.txt
  ofl/notosanschorasmian/article/ARTICLE.en_us.html
  ofl/notosanschorasmian/upstream.yaml
Labels: - Ready for Review, I New Font

#5387 Noto Sans Elbasan: Version 2.004; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosanselbasan/METADATA.pb
  ofl/notosanselbasan/NotoSansElbasan-Regular.ttf
  ofl/notosanselbasan/OFL.txt
  ofl/notosanselbasan/upstream.yaml
Labels: --- to sandbox, I Font Upgrade

#5368 Noto Sans Ugaritic: Version 2.001; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosansugaritic/METADATA.pb
  ofl/notosansugaritic/NotoSansUgaritic-Regular.ttf
  ofl/notosansugaritic/OFL.txt
  ofl/notosansugaritic/upstream.yaml
Labels: --- to sandbox, I Font Upgrade

#6256 Update bio of Suon May Sophanith
  catalog/designers/suonmaysophanith/bio.html
Labels: --- to sandbox, I Designer profile

#6280 Poltawski Nowy: added display name
  ofl/poltawskinowy/METADATA.pb
Labels: - Ready for Review, I Description/Metadata/OFL

#6230 Darker Grotesque: Version 1.000;gftools[0.9.28] added
  ofl/darkergrotesque/DESCRIPTION.en_us.html
  ofl/darkergrotesque/DESCRIPTION.vi_vn.html
  ofl/darkergrotesque/DarkerGrotesque-Black.ttf
  ofl/darkergrotesque/DarkerGrotesque-Bold.ttf
  ofl/darkergrotesque/DarkerGrotesque-ExtraBold.ttf
  ofl/darkergrotesque/DarkerGrotesque-Light.ttf
  ofl/darkergrotesque/DarkerGrotesque-Medium.ttf
  ofl/darkergrotesque/DarkerGrotesque-Regular.ttf
  ofl/darkergrotesque/DarkerGrotesque-SemiBold.ttf
  ofl/darkergrotesque/DarkerGrotesque[wght].ttf
  ofl/darkergrotesque/METADATA.pb
  ofl/darkergrotesque/OFL.txt
  ofl/darkergrotesque/upstream.yaml
Labels: III Expand glyphset, III VF Replacement, - Ready for Review, I Small Fix

#6254 Designer Added: ViệtAnh Nguyễn
  catalog/vietanhnguyen/bio.html
  catalog/vietanhnguyen/info.pb
  catalog/vietanhnguyen/vietanhnguyen.png
Labels: --- to sandbox, I Designer profile

#6296 Update asap family DESCRIPTION.en_us.html
  ofl/asap/DESCRIPTION.en_us.html
Labels: - Ready for Review

#6302 Braah One: Version 1.001; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.29] added
  ofl/braahone/BraahOne-Regular.ttf
  ofl/braahone/DESCRIPTION.en_us.html
  ofl/braahone/METADATA.pb
  ofl/braahone/upstream.yaml
Labels: - Ready for Review, I Small Fix, II Indic / Brahmic / Thai / Tai

#6290 Add Tilt Warp minisite URL
  ofl/tiltwarp/METADATA.pb
Labels: - Ready for Review, I Description/Metadata/OFL

#6292 Add Tilt Neon minisite URL
  ofl/tiltneon/METADATA.pb
Labels: - Ready for Review, I Description/Metadata/OFL

#6291 Add Tilt Prism minisite URL
  ofl/tiltprism/METADATA.pb
Labels: --- to sandbox, I Description/Metadata/OFL

#6306 Xanh Mono + BeVietnam: updated metadata+description
  ofl/bevietnampro/METADATA.pb
  ofl/xanhmono/DESCRIPTION.en_us.html
  ofl/xanhmono/DESCRIPTION.vi_vn.html
  ofl/xanhmono/METADATA.pb
Labels: --- to sandbox, I Description/Metadata/OFL

#6307 Lam Bao (BeVietnam Pro)
  catalog/designers/lambao/bio.html
  catalog/designers/lambao/info.pb
  catalog/designers/lambao/lambao.png
Labels: --- to sandbox, I Designer profile

#6283 Literata: Version 3.103;gftools[0.9.29] added
  ofl/literata/DESCRIPTION.en_us.html
  ofl/literata/Literata-Italic[opsz,wght].ttf
  ofl/literata/Literata[opsz,wght].ttf
  ofl/literata/METADATA.pb
  ofl/literata/upstream.yaml
Labels: - Ready for Review, I Small Fix

#6309 Vina Sans: Version 1.002; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.28] added
  ofl/vinasans/DESCRIPTION.en_us.html
  ofl/vinasans/METADATA.pb
  ofl/vinasans/VinaSans-Regular.ttf
  ofl/vinasans/upstream.yaml
Labels: --- to sandbox, I Small Fix

#6312 Be Vietnam Pro: designer name
  ofl/bevietnampro/METADATA.pb
Labels: --- to sandbox, I Description/Metadata/OFL

#6311 Viaoda Libre: designer name
  ofl/viaodalibre/METADATA.pb
Labels: --- to sandbox, I Description/Metadata/OFL

#6277 Orbit: Version 1.000; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.29] added
  ofl/orbit/DESCRIPTION.en_us.html
  ofl/orbit/METADATA.pb
  ofl/orbit/OFL.txt
  ofl/orbit/Orbit-Regular.ttf
  ofl/orbit/upstream.yaml
Labels: II CJK, - Ready for Review, I New Font

#6276 Moirai One: Version 1.000; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.28] added
  ofl/moiraione/DESCRIPTION.en_us.html
  ofl/moiraione/METADATA.pb
  ofl/moiraione/MoiraiOne-Regular.ttf
  ofl/moiraione/OFL.txt
  ofl/moiraione/upstream.yaml
Labels: II CJK, --- to sandbox, I New Font

#6274 Gasoek One: Version 1.000; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.28] added
  ofl/gasoekone/DESCRIPTION.en_us.html
  ofl/gasoekone/GasoekOne-Regular.ttf
  ofl/gasoekone/METADATA.pb
  ofl/gasoekone/OFL.txt
  ofl/gasoekone/upstream.yaml
Labels: II CJK, --- to sandbox, I New Font

#6273 Diphylleia: Version 1.000; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.28] added
  ofl/diphylleia/DESCRIPTION.en_us.html
  ofl/diphylleia/Diphylleia-Regular.ttf
  ofl/diphylleia/METADATA.pb
  ofl/diphylleia/OFL.txt
  ofl/diphylleia/upstream.yaml
Labels: II CJK, --- to sandbox, I New Font

#6272 Bagel Fat One: Version 1.000; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.28] added
  ofl/bagelfatone/BagelFatOne-Regular.ttf
  ofl/bagelfatone/DESCRIPTION.en_us.html
  ofl/bagelfatone/METADATA.pb
  ofl/bagelfatone/OFL.txt
  ofl/bagelfatone/upstream.yaml
Labels: II CJK, --- to sandbox, I New Font

#6275 Grandiflora One: Version 1.000; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.28] added
  ofl/grandifloraone/DESCRIPTION.en_us.html
  ofl/grandifloraone/GrandifloraOne-Regular.ttf
  ofl/grandifloraone/METADATA.pb
  ofl/grandifloraone/OFL.txt
  ofl/grandifloraone/upstream.yaml
Labels: II CJK, --- to sandbox, I New Font

#6316 Rethink Sans: Version 1.000;gftools[0.9.29] added
  ofl/rethinksans/DESCRIPTION.en_us.html
  ofl/rethinksans/METADATA.pb
  ofl/rethinksans/OFL.txt
  ofl/rethinksans/RethinkSans-Italic[wght].ttf
  ofl/rethinksans/RethinkSans[wght].ttf
  ofl/rethinksans/upstream.yaml
Labels: - Ready for Review, I New Font

#6317 Designer added: Hans Thiessen
  catalog/designers/hansthiessen/bio.html
  catalog/designers/hansthiessen/hansthiessen.png
  catalog/designers/hansthiessen/info.pb
Labels: - Ready for Review, I Designer profile

#5365 Noto Sans Sogdian: Version 2.002; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosanssogdian/METADATA.pb
  ofl/notosanssogdian/NotoSansSogdian-Regular.ttf
  ofl/notosanssogdian/OFL.txt
  ofl/notosanssogdian/upstream.yaml
Labels: - Ready for Review, I Font Upgrade

#5322 Noto Sans Psalter Pahlavi: Version 2.002; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosanspsalterpahlavi/METADATA.pb
  ofl/notosanspsalterpahlavi/NotoSansPsalterPahlavi-Regular.ttf
  ofl/notosanspsalterpahlavi/OFL.txt
  ofl/notosanspsalterpahlavi/upstream.yaml
Labels: --- to sandbox, I Font Upgrade

#5321 Noto Sans Palmyrene: Version 2.001; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosanspalmyrene/METADATA.pb
  ofl/notosanspalmyrene/NotoSansPalmyrene-Regular.ttf
  ofl/notosanspalmyrene/OFL.txt
  ofl/notosanspalmyrene/upstream.yaml
Labels: --- to sandbox, I Font Upgrade
