Repository google/fonts, pull requests merged in 2024-03, with the labels that each got.

#7333 Ojuju article
  ofl/ojuju/DESCRIPTION.en_us.html
  ofl/ojuju/article/ARTICLE.en_us.html
  ofl/ojuju/article/image1.png
  ofl/ojuju/article/image2.png
  ofl/ojuju/article/image3.gif
  ofl/ojuju/article/image4.png
  ofl/ojuju/article/image5.gif
Labels: I Description/Metadata/OFL

#7332 Frank Ruhl Libre: Version 6.004 added
  ofl/frankruhllibre/DESCRIPTION.en_us.html
  ofl/frankruhllibre/FrankRuhlLibre[wght].ttf
  ofl/frankruhllibre/METADATA.pb
  ofl/frankruhllibre/OFL.txt
Labels: I Small Fix

#7340 Sedan: Version 1.100; ttfautohint (v1.8.4.7-5d5b) added
  ofl/sedan/DESCRIPTION.en_us.html
  ofl/sedan/METADATA.pb
  ofl/sedan/OFL.txt
  ofl/sedan/Sedan-Italic.ttf
  ofl/sedan/Sedan-Regular.ttf
  ofl/sedan/upstream.yaml
Labels: I New Font

#7341 Sedan SC: Version 1.100; ttfautohint (v1.8.4.7-5d5b) added
  ofl/sedansc/DESCRIPTION.en_us.html
  ofl/sedansc/METADATA.pb
  ofl/sedansc/OFL.txt
  ofl/sedansc/SedanSC-Regular.ttf
  ofl/sedansc/upstream.yaml
Labels: I New Font

#7339 Designer info for Sebastian Salazar (Sedan)
  catalog/designers/sebastiansalazar/info.pb
Labels: I Designer profile

#7337 Add designer: OrangeRed
  catalog/designers/orangered/bio.html
  catalog/designers/orangered/info.pb
  catalog/designers/orangered/orangered.png
Labels: I Designer profile

#7336 Jersey 15 Charted: Version 1.000; ttfautohint (v1.8.4.7-5d5b) added
  ofl/jersey15charted/DESCRIPTION.en_us.html
  ofl/jersey15charted/Jersey15Charted-Regular.ttf
  ofl/jersey15charted/METADATA.pb
  ofl/jersey15charted/OFL.txt
  ofl/jersey15charted/upstream.yaml
Labels: I New Font

#7335 Jersey 15: Version 1.000; ttfautohint (v1.8.4.7-5d5b) added
  ofl/jersey15/DESCRIPTION.en_us.html
  ofl/jersey15/Jersey15-Regular.ttf
  ofl/jersey15/METADATA.pb
  ofl/jersey15/OFL.txt
  ofl/jersey15/upstream.yaml
Labels: I New Font

#7320 Jersey 10 Charted: Version 1.000; ttfautohint (v1.8.4.7-5d5b) added
  ofl/jersey10charted/DESCRIPTION.en_us.html
  ofl/jersey10charted/Jersey10Charted-Regular.ttf
  ofl/jersey10charted/METADATA.pb
  ofl/jersey10charted/OFL.txt
  ofl/jersey10charted/upstream.yaml
Labels: I New Font

#7319 Jersey 10: Version 1.000; ttfautohint (v1.8.4.7-5d5b) added
  ofl/jersey10/DESCRIPTION.en_us.html
  ofl/jersey10/Jersey10-Regular.ttf
  ofl/jersey10/METADATA.pb
  ofl/jersey10/OFL.txt
  ofl/jersey10/upstream.yaml
Labels: I New Font

#7327 Noto Serif Hentaigana: Version 1.000 added
  ofl/notoserifhentaigana/DESCRIPTION.en_us.html
  ofl/notoserifhentaigana/METADATA.pb
  ofl/notoserifhentaigana/NotoSerifHentaigana[wght].ttf
  ofl/notoserifhentaigana/OFL.txt
  ofl/notoserifhentaigana/article/ARTICLE.en_us.html
  ofl/notoserifhentaigana/upstream.yaml
Labels: II CJK, I New Font

#7346 Add latin-ext to ofl/loveyalikeasister/METADATA.pb
  ofl/loveyalikeasister/METADATA.pb
Labels: I Description/Metadata/OFL

#7343 Update more upstreams (1/2)
  ofl/laila/METADATA.pb
  ofl/lakkireddy/METADATA.pb
  ofl/lancelot/METADATA.pb
  ofl/lato/METADATA.pb
  ofl/leaguescript/METADATA.pb
  ofl/librebaskerville/METADATA.pb
  ofl/lindenhill/METADATA.pb
  ofl/lohitbengali/METADATA.pb
  ofl/lohittamil/METADATA.pb
  ofl/maitree/METADATA.pb
Labels: I Description/Metadata/OFL

#7344 Update upstreams (2/2)
  ofl/mallanna/METADATA.pb
  ofl/mandali/METADATA.pb
  ofl/manjari/METADATA.pb
  ofl/markoone/METADATA.pb
  ofl/martel/METADATA.pb
  ofl/martelsans/METADATA.pb
  ofl/mavenpro/METADATA.pb
Labels: I Description/Metadata/OFL

#7351 Joan: Category updated in metadata.pb
  ofl/joan/METADATA.pb
Labels: I Description/Metadata/OFL

#7362 Update ofl/creteround/DESCRIPTION.en_us.html
  ofl/creteround/DESCRIPTION.en_us.html
Labels: I Description/Metadata/OFL

#7360 Update ofl/gabriela/DESCRIPTION.en_us.html
  ofl/gabriela/DESCRIPTION.en_us.html
  ofl/kurale/DESCRIPTION.en_us.html
Labels: I Description/Metadata/OFL

#7357 Update ofl/gfsdidot/DESCRIPTION.en_us.html
  ofl/gfsdidot/DESCRIPTION.en_us.html
Labels: I Description/Metadata/OFL

#7356 Update ofl/lekton/METADATA.pb category to MONOSPACE
  ofl/lekton/METADATA.pb
Labels: I Description/Metadata/OFL

#7321 Platypi: Version 1.200 added
  ofl/platypi/DESCRIPTION.en_us.html
  ofl/platypi/METADATA.pb
  ofl/platypi/OFL.txt
  ofl/platypi/Platypi-Italic[wght].ttf
  ofl/platypi/Platypi[wght].ttf
  ofl/platypi/upstream.yaml
Labels: I New Font

#7314 Reddit Sans Condensed: Version 1.014 added
  ofl/redditsanscondensed/DESCRIPTION.en_us.html
  ofl/redditsanscondensed/METADATA.pb
  ofl/redditsanscondensed/OFL.txt
  ofl/redditsanscondensed/RedditSansCondensed[wght].ttf
  ofl/redditsanscondensed/upstream.yaml
Labels: I New Font

#7310 Reddit Sans: Version 1.014 added
  ofl/redditsans/DESCRIPTION.en_us.html
  ofl/redditsans/METADATA.pb
  ofl/redditsans/OFL.txt
  ofl/redditsans/RedditSans-Bold.ttf
  ofl/redditsans/RedditSans-BoldItalic.ttf
  ofl/redditsans/RedditSans-ExtraBold.ttf
  ofl/redditsans/RedditSans-ExtraBoldItalic.ttf
  ofl/redditsans/RedditSans-Italic.ttf
  ofl/redditsans/RedditSans-Italic[wght].ttf
  ofl/redditsans/RedditSans-Light.ttf
  ofl/redditsans/RedditSans-LightItalic.ttf
  ofl/redditsans/RedditSans-Regular.ttf
  ofl/redditsans/RedditSans-SemiBold.ttf
  ofl/redditsans/RedditSans-SemiBoldItalic.ttf
  ofl/redditsans/RedditSans[wght].ttf
  ofl/redditsans/upstream.yaml
Labels: I New Font

#7370 update family tags
  tags/all/families.csv
Labels: I Description/Metadata/OFL

#7365 Update ofl/domine/DESCRIPTION.en_us.html
  ofl/domine/DESCRIPTION.en_us.html
Labels: I Description/Metadata/OFL

#7374 Update README.md
  README.md
Labels: I Tools / workflow / repo

#7345 update push lists
  to_production.txt
  to_sandbox.txt
Labels: I Tools / workflow / repo

#7082 Micro 5 Charted: Version 1.000; ttfautohint (v1.8.4.7-5d5b) added
  ofl/micro5charted/DESCRIPTION.en_us.html
  ofl/micro5charted/METADATA.pb
  ofl/micro5charted/Micro5Charted-Regular.ttf
  ofl/micro5charted/OFL.txt
  ofl/micro5charted/upstream.yaml
Labels: I New Font

#7379 URL updated in designer profile
  catalog/designers/andreasrasmussen/bio.html
Labels: I Designer profile

#7372 RocknRoll One metadata
  ofl/rocknrollone/METADATA.pb
Labels: I Description/Metadata/OFL

#7369 Add designer: Seyi Olusanya
  catalog/designers/seyiolusanya/bio.html
  catalog/designers/seyiolusanya/info.pb
  catalog/designers/seyiolusanya/seyiolusanya.png
Labels: I Designer profile

#7347 Noto Sans Oriya: Version 2.006 added
  ofl/notosansoriya/DESCRIPTION.en_us.html
  ofl/notosansoriya/METADATA.pb
  ofl/notosansoriya/NotoSansOriya[wdth,wght].ttf
  ofl/notosansoriya/article/ARTICLE.en_us.html
  ofl/notosansoriya/upstream.yaml
Labels: I Font Upgrade

#7386 Jersey 25: Version 1.000; ttfautohint (v1.8.4.7-5d5b) added
  ofl/jersey25/DESCRIPTION.en_us.html
  ofl/jersey25/Jersey25-Regular.ttf
  ofl/jersey25/METADATA.pb
  ofl/jersey25/OFL.txt
  ofl/jersey25/upstream.yaml
Labels: I New Font

#7385 Jersey 20 Charted: Version 1.000; ttfautohint (v1.8.4.7-5d5b) added
  ofl/jersey20charted/DESCRIPTION.en_us.html
  ofl/jersey20charted/Jersey20Charted-Regular.ttf
  ofl/jersey20charted/METADATA.pb
  ofl/jersey20charted/OFL.txt
  ofl/jersey20charted/upstream.yaml
Labels: I New Font

#7384 Jersey 20: Version 1.000; ttfautohint (v1.8.4.7-5d5b) added
  ofl/jersey20/DESCRIPTION.en_us.html
  ofl/jersey20/Jersey20-Regular.ttf
  ofl/jersey20/METADATA.pb
  ofl/jersey20/OFL.txt
  ofl/jersey20/upstream.yaml
Labels: I New Font

#7307 Jacquard 24 Charted: Version 1.000 added
  ofl/jacquard24charted/DESCRIPTION.en_us.html
  ofl/jacquard24charted/Jacquard24Charted-Regular.ttf
  ofl/jacquard24charted/METADATA.pb
  ofl/jacquard24charted/OFL.txt
  ofl/jacquard24charted/upstream.yaml
Labels: I New Font

#7305 Jacquard 24: Version 1.000; ttfautohint (v1.8.4.7-5d5b) added
  ofl/jacquard24/DESCRIPTION.en_us.html
  ofl/jacquard24/Jacquard24-Regular.ttf
  ofl/jacquard24/METADATA.pb
  ofl/jacquard24/OFL.txt
  ofl/jacquard24/upstream.yaml
Labels: I New Font

#7376 Sawarabi Mincho: Version 1.082 added; ttfautohint (v1.8.4.7-5d5b) added
  ofl/sawarabimincho/DESCRIPTION.en_us.html
  ofl/sawarabimincho/METADATA.pb
  ofl/sawarabimincho/OFL.txt
  ofl/sawarabimincho/SawarabiMincho-Regular.ttf
Labels: II CJK, I Font Upgrade

#7402 Edu VIC WA NT Hand: Version 1.000 added
  ofl/eduvicwanthand/DESCRIPTION.en_us.html
  ofl/eduvicwanthand/EduVICWANTHand[wght].ttf
  ofl/eduvicwanthand/METADATA.pb
  ofl/eduvicwanthand/OFL.txt
Labels: I New Font

#7389 Danfo: Version 1.000 added
  ofl/danfo/DESCRIPTION.en_us.html
  ofl/danfo/Danfo[ELSH].ttf
  ofl/danfo/METADATA.pb
  ofl/danfo/OFL.txt
  ofl/danfo/upstream.yaml
Labels: I New Font, II African

#7405 Edu SA Hand: Version 2.000 added
  ofl/edusahand/DESCRIPTION.en_us.html
  ofl/edusahand/EduSAHand[wght].ttf
  ofl/edusahand/METADATA.pb
  ofl/edusahand/OFL.txt
Labels: I New Font

#7404 Edu QLD Hand: Version 2.000 added
  ofl/eduqldhand/DESCRIPTION.en_us.html
  ofl/eduqldhand/EduQLDHand[wght].ttf
  ofl/eduqldhand/METADATA.pb
  ofl/eduqldhand/OFL.txt
Labels: I New Font

#7403 Edu NSW ACT Hand: Version 2.000 added
  ofl/edunswacthand/DESCRIPTION.en_us.html
  ofl/edunswacthand/EduNSWACTHand[wght].ttf
  ofl/edunswacthand/METADATA.pb
  ofl/edunswacthand/OFL.txt
Labels: I New Font

#7459 Playwrite Colombia article update
  ofl/playwriteco/article/ARTICLE.en_us.html
  ofl/playwriteco/article/Playwrite-Colombia_1.jpg
  ofl/playwriteco/article/Playwrite-Colombia_2.jpg
  ofl/playwriteco/article/Playwrite-Colombia_3.jpg
Labels: I Description/Metadata/OFL

#7352 Ubuntu Sans: Version 1.006 added
  ufl/ubuntusans/DESCRIPTION.en_us.html
  ufl/ubuntusans/LICENCE.txt
  ufl/ubuntusans/METADATA.pb
  ufl/ubuntusans/UbuntuSans-Italic[wdth,wght].ttf
  ufl/ubuntusans/UbuntuSans[wdth,wght].ttf
Labels: I Font Upgrade

#7474 Lists of the 27th of March
  to_production.txt
  to_sandbox.txt
Labels: I Tools / workflow / repo

#7462 Add designer: Chank Diesel
  catalog/designers/chankdiesel/bio.html
  catalog/designers/chankdiesel/chankdiesel.png
  catalog/designers/chankdiesel/info.pb
Labels: I Designer profile

#7480 Restore symbols samples
  ofl/notosanssymbols/METADATA.pb
Labels: I Description/Metadata/OFL

#7040 Briem Hand: Version 1.002 added
  ofl/briemhand/BriemHand[wght].ttf
  ofl/briemhand/DESCRIPTION.en_us.html
  ofl/briemhand/METADATA.pb
  ofl/briemhand/OFL.txt
Labels: I New Font

#7475 Add designer: Gunnlaugur SE Briem
  catalog/designers/gunnlaugurbriem/bio.html
  catalog/designers/gunnlaugurbriem/gunnlaugursebriem.png
  catalog/designers/gunnlaugurbriem/info.pb
Labels: I Designer profile

#7472 Noto Sans Mongolian: Remove chinese subset
  ofl/notosansmongolian/METADATA.pb
Labels: I Description/Metadata/OFL

#7477 Designer added: Céline Hurka
  catalog/designers/celinehurka/bio.html
  catalog/designers/celinehurka/celinehurka.png
  catalog/designers/celinehurka/info.pb
Labels: I Designer profile

#7392 Teachers: Version 1.001 added
  ofl/teachers/DESCRIPTION.en_us.html
  ofl/teachers/METADATA.pb
  ofl/teachers/OFL.txt
  ofl/teachers/Teachers-Italic[wght].ttf
  ofl/teachers/Teachers[wght].ttf
  ofl/teachers/upstream.yaml
Labels: I New Font

#7391 Jaro: Version 1.000 added
  ofl/jaro/DESCRIPTION.en_us.html
  ofl/jaro/Jaro[opsz].ttf
  ofl/jaro/METADATA.pb
  ofl/jaro/OFL.txt
  ofl/jaro/upstream.yaml
Labels: I New Font, II African

#7499 Add designer: Afrotype
  catalog/designers/afrotype/afrotype.png
  catalog/designers/afrotype/bio.html
  catalog/designers/afrotype/info.pb
Labels: I Designer profile

#7497 Reddit: Add OrangeRed to the designer list
  ofl/redditmono/METADATA.pb
  ofl/redditsans/METADATA.pb
  ofl/redditsanscondensed/METADATA.pb
Labels: I Description/Metadata/OFL

#7498 Tacone and Danfo metadatas: Add Afrotype
  ofl/danfo/METADATA.pb
  ofl/tacone/METADATA.pb
Labels: I Description/Metadata/OFL
