Repository google/fonts, pull requests merged in 2024-12, with the labels that each got.

#8431 Kanchenjunga: Version 2.001 added
  ofl/kanchenjunga/Kanchenjunga-Bold.ttf
  ofl/kanchenjunga/Kanchenjunga-Medium.ttf
  ofl/kanchenjunga/Kanchenjunga-Regular.ttf
  ofl/kanchenjunga/Kanchenjunga-SemiBold.ttf
  ofl/kanchenjunga/METADATA.pb
  ofl/kanchenjunga/OFL.txt
  ofl/kanchenjunga/article/ARTICLE.en_us.html
Labels: -- Needs confirmation, I New Font, II Indic / Brahmic / Thai / Tai, -- Needs lang/glyphset update

#8689 PW subsets fix
  ofl/playwritearguides/METADATA.pb
  ofl/playwritecoguides/METADATA.pb
Labels: I Metadata/OFL

#8691 PW Guides various small fixes
  ofl/playwritebevlgguides/article/ARTICLE.en_us.html
  ofl/playwriteclguides/article/ARTICLE.en_us.html
  ofl/playwritedelaguides/article/ARTICLE.en_us.html
  ofl/playwritefrmoderneguides/article/ARTICLE.en_us.html
  ofl/playwritegbjguides/article/ARTICLE.en_us.html
  ofl/playwriteittradguides/article/ARTICLE.en_us.html
  ofl/playwriteptguides/article/ARTICLE.en_us.html
Labels: I Article/Description

#8696 Designer bio for Aleksandr Adreev
  catalog/designers/aleksandrandreev/aleksandrandreev.png
  catalog/designers/aleksandrandreev/bio.html
  catalog/designers/aleksandrandreev/info.pb
Labels: I Designer profile

#8697 Lists of the 6th of December
  to_production.txt
  to_sandbox.txt
Labels: I Tools / workflow / repo

#8686 Add tags for Lunar New Year
  tags/all/families.csv
Labels: -- Needs category tag data

#8698 Triodion: Version 1.200; ttfautohint (v1.8.4.7-5d5b) added
  ofl/triodion/DESCRIPTION.en_us.html
  ofl/triodion/METADATA.pb
  ofl/triodion/OFL.txt
  ofl/triodion/Triodion-Regular.ttf
Labels: I New Font, II Accepted, P3, sub-issue

#8692 [Nanum Myeongjo] Hotfixed fonts to add a space character
  ofl/nanummyeongjo/NanumMyeongjo-Bold.ttf
  ofl/nanummyeongjo/NanumMyeongjo-ExtraBold.ttf
  ofl/nanummyeongjo/NanumMyeongjo-Regular.ttf
  ofl/nanummyeongjo/hotfix-space.py
Labels: I Small Fix

#8603 Add Designer: Red Stone
  catalog/designers/redstone/bio.html
  catalog/designers/redstone/info.pb
  catalog/designers/redstone/redstone.png
Labels: I Designer profile

#8688 Englebert: hotfixed v-metrics
  ofl/englebert/DESCRIPTION.en_us.html
  ofl/englebert/Englebert-Regular.ttf
  ofl/englebert/METADATA.pb
  ofl/englebert/OFL.txt
Labels: I Font Upgrade, I Small Fix

#8741 Triodion: Version 1.201; ttfautohint (v1.8.4.7-5d5b) added
  ofl/triodion/DESCRIPTION.en_us.html
  ofl/triodion/METADATA.pb
  ofl/triodion/Triodion-Regular.ttf
Labels: I New Font, II Accepted, P3, sub-issue

#8735 Tagesschrift: Version 2.000; ttfautohint (v1.8.4.7-5d5b) added
  ofl/tagesschrift/DESCRIPTION.en_us.html
  ofl/tagesschrift/METADATA.pb
  ofl/tagesschrift/OFL.txt
  ofl/tagesschrift/Tagesschrift-Regular.ttf
Labels: I New Font, II Submission

#8726 Shafarik: Version 1.001; ttfautohint (v1.8.4.7-5d5b) added
  ofl/shafarik/DESCRIPTION.en_us.html
  ofl/shafarik/METADATA.pb
  ofl/shafarik/OFL.txt
  ofl/shafarik/Shafarik-Regular.ttf
Labels: I New Font, II Accepted, sub-issue

#8725 Ponomar: Version 1.301; ttfautohint (v1.8.4.7-5d5b) added
  ofl/ponomar/DESCRIPTION.en_us.html
  ofl/ponomar/METADATA.pb
  ofl/ponomar/OFL.txt
  ofl/ponomar/Ponomar-Regular.ttf
Labels: I New Font, II Accepted, P3, sub-issue

#8768 Added primary_language to all four Church Slavonic fonts
  ofl/pochaevsk/METADATA.pb
  ofl/ponomar/METADATA.pb
  ofl/shafarik/METADATA.pb
  ofl/triodion/METADATA.pb
Labels: I Metadata/OFL
