Repository google/fonts, pull requests merged in 2024-06, with the labels that each got.

#7800 Zain: Version 1.02; ttfautohint (v1.8.4) added
  ofl/zain/DESCRIPTION.en_us.html
  ofl/zain/METADATA.pb
  ofl/zain/OFL.txt
  ofl/zain/Zain-Black.ttf
  ofl/zain/Zain-Bold.ttf
  ofl/zain/Zain-ExtraBold.ttf
  ofl/zain/Zain-ExtraLight.ttf
  ofl/zain/Zain-Light.ttf
  ofl/zain/Zain-Regular.ttf
Labels: I New Font, II Accepted, II Arabic / Hebrew / Semitic / RTL

#7795 Bungee Hairline: Version 2.000 added
  ofl/bungeehairline/BungeeHairline-Regular.ttf
  ofl/bungeehairline/DESCRIPTION.en_us.html
  ofl/bungeehairline/METADATA.pb
  ofl/bungeehairline/OFL.txt
Labels: I Font Upgrade

#7712 Playwrite DK Uloopet: Version 1.002 added
  ofl/playwritedkuloopet/METADATA.pb
  ofl/playwritedkuloopet/OFL.txt
  ofl/playwritedkuloopet/PlaywriteDKUloopet[wght].ttf
  ofl/playwritedkuloopet/article/ARTICLE.en_us.html
  ofl/playwritedkuloopet/article/Playwrite-Danmark-Uloopet-1.png
  ofl/playwritedkuloopet/article/Playwrite-Danmark-Uloopet-2.png
  ofl/playwritedkuloopet/article/Playwrite-Danmark-Uloopet-3.png
Labels: I New Font

#7719 Playwrite HU: Version 1.002 added
  ofl/playwritehu/METADATA.pb
  ofl/playwritehu/OFL.txt
  ofl/playwritehu/PlaywriteHU[wght].ttf
  ofl/playwritehu/article/ARTICLE.en_us.html
  ofl/playwritehu/article/Playwrite-Magyarorszag-1.png
  ofl/playwritehu/article/Playwrite-Magyarorszag-2.png
  ofl/playwritehu/article/Playwrite-Magyarorszag-3.png
Labels: -- Needs Meta/Desc/License changes, I New Font

#7717 Playwrite HR Lijeva: Version 1.002 added
  ofl/playwritehrlijeva/METADATA.pb
  ofl/playwritehrlijeva/OFL.txt
  ofl/playwritehrlijeva/PlaywriteHRLijeva[wght].ttf
  ofl/playwritehrlijeva/article/ARTICLE.en_us.html
  ofl/playwritehrlijeva/article/Playwrite-Hrvatska-Lijeva-1.png
  ofl/playwritehrlijeva/article/Playwrite-Hrvatska-Lijeva-2.png
  ofl/playwritehrlijeva/article/Playwrite-Hrvatska-Lijeva-3.png
Labels: I New Font

#7731 Playwrite PE: Version 1.002 added
  ofl/playwritepe/METADATA.pb
  ofl/playwritepe/OFL.txt
  ofl/playwritepe/PlaywritePE[wght].ttf
  ofl/playwritepe/article/ARTICLE.en_us.html
  ofl/playwritepe/article/Playwrite-Peru-1.png
  ofl/playwritepe/article/Playwrite-Peru-2.png
  ofl/playwritepe/article/Playwrite-Peru-3.png
Labels: I New Font

#7711 Playwrite DK Loopet: Version 1.002 added
  ofl/playwritedkloopet/METADATA.pb
  ofl/playwritedkloopet/OFL.txt
  ofl/playwritedkloopet/PlaywriteDKLoopet[wght].ttf
  ofl/playwritedkloopet/article/ARTICLE.en_us.html
  ofl/playwritedkloopet/article/Playwrite-Danmark-Loopet-1.png
  ofl/playwritedkloopet/article/Playwrite-Danmark-Loopet-2.png
  ofl/playwritedkloopet/article/Playwrite-Danmark-Loopet-3.png
Labels: I New Font

#7707 Playwrite CZ: Version 1.002 added
  ofl/playwritecz/METADATA.pb
  ofl/playwritecz/OFL.txt
  ofl/playwritecz/PlaywriteCZ[wght].ttf
  ofl/playwritecz/article/ARTICLE.en_us.html
  ofl/playwritecz/article/Playwrite-Cesko-1.png
  ofl/playwritecz/article/Playwrite-Cesko-2.png
  ofl/playwritecz/article/Playwrite-Cesko-3.png
Labels: I New Font

#7706 Playwrite CU: Version 1.002 added
  ofl/playwritecu/METADATA.pb
  ofl/playwritecu/OFL.txt
  ofl/playwritecu/PlaywriteCU[wght].ttf
  ofl/playwritecu/article/ARTICLE.en_us.html
  ofl/playwritecu/article/Playwrite-Cuba-1.png
  ofl/playwritecu/article/Playwrite-Cuba-2.png
  ofl/playwritecu/article/Playwrite-Cuba-3.png
Labels: I New Font

#7705 Playwrite CL: Version 1.002 added
  ofl/playwritecl/METADATA.pb
  ofl/playwritecl/OFL.txt
  ofl/playwritecl/PlaywriteCL[wght].ttf
  ofl/playwritecl/article/ARTICLE.en_us.html
  ofl/playwritecl/article/Playwrite-Chile-1.png
  ofl/playwritecl/article/Playwrite-Chile-2.png
  ofl/playwritecl/article/Playwrite-Chile-3.png
Labels: I New Font

#7703 Playwrite BE WAL: Version 1.002 added
  ofl/playwritebewal/METADATA.pb
  ofl/playwritebewal/OFL.txt
  ofl/playwritebewal/PlaywriteBEWAL[wght].ttf
  ofl/playwritebewal/article/ARTICLE.en_us.html
  ofl/playwritebewal/article/Playwrite-Belgie-Walloon-1.png
  ofl/playwritebewal/article/Playwrite-Belgie-Walloon-2.png
  ofl/playwritebewal/article/Playwrite-Belgie-Walloon-3.png
Labels: I New Font

#7702 Playwrite BE VLG: Version 1.002 added
  ofl/playwritebevlg/METADATA.pb
  ofl/playwritebevlg/OFL.txt
  ofl/playwritebevlg/PlaywriteBEVLG[wght].ttf
  ofl/playwritebevlg/article/ARTICLE.en_us.html
  ofl/playwritebevlg/article/Playwrite-Belgie-Vlaams-Gewest-1.png
  ofl/playwritebevlg/article/Playwrite-Belgie-Vlaams-Gewest-2.png
  ofl/playwritebevlg/article/Playwrite-Belgie-Vlaams-Gewest-3.png
Labels: I New Font

#7696 Playwrite AT: Version 1.002 added
  ofl/playwriteat/METADATA.pb
  ofl/playwriteat/OFL.txt
  ofl/playwriteat/PlaywriteAT-Italic[wght].ttf
  ofl/playwriteat/PlaywriteAT[wght].ttf
  ofl/playwriteat/article/ARTICLE.en_us.html
  ofl/playwriteat/article/Playwrite-Osterreich-1.png
  ofl/playwriteat/article/Playwrite-Osterreich-2.png
  ofl/playwriteat/article/Playwrite-Osterreich-3.png
  ofl/playwriteat/article/Playwrite-Osterreich-4.png
Labels: I New Font

#7695 Playwrite AR: Version 1.002 added
  ofl/playwritear/METADATA.pb
  ofl/playwritear/OFL.txt
  ofl/playwritear/PlaywriteAR[wght].ttf
  ofl/playwritear/article/ARTICLE.en_us.html
  ofl/playwritear/article/Playwrite-Argentina-1.png
  ofl/playwritear/article/Playwrite-Argentina-2.png
  ofl/playwritear/article/Playwrite-Argentina-3.png
Labels: I New Font

#7628 Edu AU VIC WA NT Hand: Version 1.001 added
  ofl/eduauvicwanthand/DESCRIPTION.en_us.html
  ofl/eduauvicwanthand/EduAUVICWANTHand[wght].ttf
  ofl/eduauvicwanthand/METADATA.pb
  ofl/eduauvicwanthand/OFL.txt
Labels: -- Needs Upstream Resolution, I New Font

#7825 Zain: Version 1.10; ttfautohint (v1.8.4) added
  ofl/zain/METADATA.pb
  ofl/zain/Zain-Black.ttf
  ofl/zain/Zain-Bold.ttf
  ofl/zain/Zain-ExtraBold.ttf
  ofl/zain/Zain-ExtraLight.ttf
  ofl/zain/Zain-Light.ttf
  ofl/zain/Zain-Regular.ttf
Labels: I New Font, II Accepted, II Arabic / Hebrew / Semitic / RTL

#7818 Wittgenstein: Version 1.500 added
  ofl/wittgenstein/METADATA.pb
  ofl/wittgenstein/OFL.txt
  ofl/wittgenstein/Wittgenstein-Italic[wght].ttf
  ofl/wittgenstein/Wittgenstein[wght].ttf
  ofl/wittgenstein/article/ARTICLE.en_us.html
  ofl/wittgenstein/article/about1.png
  ofl/wittgenstein/article/about2.png
  ofl/wittgenstein/article/about3.png
  ofl/wittgenstein/article/about4.png
  ofl/wittgenstein/article/about5.png
  ofl/wittgenstein/article/about6.png
  ofl/wittgenstein/article/about7.png
  ofl/wittgenstein/article/about8.png
  ofl/wittgenstein/article/about9.png
Labels: I New Font

#7817 Add designer: Jörg Drees
  catalog/designers/jorgdrees/bio.html
  catalog/designers/jorgdrees/info.pb
  catalog/designers/jorgdrees/jorgdrees.png
Labels: I Designer profile

#7826 Ga Maamli: Version 1.000; ttfautohint (v1.8.4.7-5d5b) added
  ofl/gamaamli/DESCRIPTION.en_us.html
  ofl/gamaamli/GaMaamli-Regular.ttf
  ofl/gamaamli/METADATA.pb
  ofl/gamaamli/OFL.txt
Labels: I New Font, II African

#7778 Shantell Sans: Version 1.010;[586c7102b] added
  ofl/shantellsans/DESCRIPTION.en_us.html
  ofl/shantellsans/METADATA.pb
  ofl/shantellsans/ShantellSans-Italic[BNCE,INFM,SPAC,wght].ttf
  ofl/shantellsans/ShantellSans[BNCE,INFM,SPAC,wght].ttf
  ofl/shantellsans/article/ARTICLE.en_us.html
Labels: I Font Upgrade

#7806 Noto Sans Hebrew: Version 3.001 added
  ofl/notosanshebrew/DESCRIPTION.en_us.html
  ofl/notosanshebrew/METADATA.pb
  ofl/notosanshebrew/NotoSansHebrew[wdth,wght].ttf
  ofl/notosanshebrew/article/ARTICLE.en_us.html
Labels: I Font Upgrade, II Arabic / Hebrew / Semitic / RTL

#7776 Inter: Version 4.001;git-66647c0bb added
  ofl/inter/DESCRIPTION.en_us.html
  ofl/inter/Inter-Italic[opsz,wght].ttf
  ofl/inter/Inter[opsz,wght].ttf
  ofl/inter/Inter[slnt,wght].ttf
  ofl/inter/METADATA.pb
Labels: -- Regressions, I Font Upgrade

#7837 Beiruti: Version 1.00 added
  ofl/beiruti/Beiruti[wght].ttf
  ofl/beiruti/DESCRIPTION.en_us.html
  ofl/beiruti/METADATA.pb
  ofl/beiruti/OFL.txt
Labels: I New Font, II Accepted, II Arabic / Hebrew / Semitic / RTL

#7840 Add arabic subset for Zain
  ofl/zain/METADATA.pb
Labels: I Metadata/OFL

#7850 Laura Garcia Mut designer info
  catalog/designers/lauragarciamut/bio.html
  catalog/designers/lauragarciamut/info.pb
  catalog/designers/lauragarciamut/lauragarciamut.png
  ofl/fustat/METADATA.pb
Labels: I Designer profile, I Metadata/OFL

#7863 Add Designer: David Abbey-Thompson
  catalog/designers/davidannerteyabbeythompson/bio.html
  catalog/designers/davidannerteyabbeythompson/davidabbeythompson.png
  catalog/designers/davidannerteyabbeythompson/info.pb
Labels: I Designer profile

#7862 Add Designer: Ama Diaka
  catalog/designers/amaasantewadiaka/amadiaka.png
  catalog/designers/amaasantewadiaka/bio.html
  catalog/designers/amaasantewadiaka/info.pb
Labels: I Designer profile

#7861 Add designer: Afotey Clement Nii Odai
  catalog/designers/afoteyclementniiodai/afoteyclementniiodai.png
  catalog/designers/afoteyclementniiodai/bio.html
  catalog/designers/afoteyclementniiodai/info.pb
Labels: I Designer profile

#7858 Noto Serif Toto: Version 2.002 added
  ofl/notoseriftoto/METADATA.pb
  ofl/notoseriftoto/NotoSerifToto[wght].ttf
  ofl/notoseriftoto/OFL.txt
Labels: I Font Upgrade

#7857 Noto Sans Psalter Pahlavi: Version 2.003; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosanspsalterpahlavi/METADATA.pb
  ofl/notosanspsalterpahlavi/NotoSansPsalterPahlavi-Regular.ttf
  ofl/notosanspsalterpahlavi/OFL.txt
Labels: I Font Upgrade

#7854 Rammetto One: Version 1.100; ttfautohint (v1.8.4.7-5d5b) added
  ofl/rammettoone/DESCRIPTION.en_us.html
  ofl/rammettoone/METADATA.pb
  ofl/rammettoone/OFL.txt
  ofl/rammettoone/RammettoOne-Regular.ttf
Labels: III Expand glyphset, I Font Upgrade

#7836 Cutive: Version 1.100; ttfautohint (v1.8.4.7-5d5b) added
  ofl/cutive/Cutive-Regular.ttf
  ofl/cutive/METADATA.pb
  ofl/cutive/OFL.txt
Labels: -- Needs confirmation, I Font Upgrade

#7864 Kalnia Glaze: Version 1.110 added
  ofl/kalniaglaze/DESCRIPTION.en_us.html
  ofl/kalniaglaze/KalniaGlaze[wdth,wght].ttf
  ofl/kalniaglaze/METADATA.pb
  ofl/kalniaglaze/article/ARTICLE.en_us.html
  ofl/kalniaglaze/article/Kalnia-Glaze-FridaMedrano-01_Cover.png
  ofl/kalniaglaze/article/Kalnia-Glaze-FridaMedrano-02_Cards.png
  ofl/kalniaglaze/article/Kalnia-Glaze-FridaMedrano-03_Cards.png
  ofl/kalniaglaze/article/Kalnia-Glaze-FridaMedrano-06_Design.png
  ofl/kalniaglaze/article/Kalnia-Glaze-FridaMedrano-GF-01.png
  ofl/kalniaglaze/article/Kalnia-Glaze-FridaMedrano-GF-02.png
  ofl/kalniaglaze/article/Kalnia-Glaze-FridaMedrano-GF-03.png
  ofl/kalniaglaze/article/Kalnia-Glaze-FridaMedrano-GF-04.png
Labels: I New Font, II Color font

#7855 Noto Sans Kaithi: Version 2.006; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosanskaithi/METADATA.pb
  ofl/notosanskaithi/NotoSansKaithi-Regular.ttf
  ofl/notosanskaithi/OFL.txt
Labels: I Font Upgrade

#7684 Noto Serif Balinese: Version 2.006; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notoserifbalinese/DESCRIPTION.en_us.html
  ofl/notoserifbalinese/METADATA.pb
  ofl/notoserifbalinese/NotoSerifBalinese-Regular.ttf
Labels: I Font Upgrade

#7685 Noto Sans Cham: Version 2.005 added
  ofl/notosanscham/DESCRIPTION.en_us.html
  ofl/notosanscham/METADATA.pb
  ofl/notosanscham/NotoSansCham[wght].ttf
Labels: I Font Upgrade

#7768 Alumni Sans SC: Version 1.016 added
  ofl/alumnisanssc/AlumniSansSC-Italic[wght].ttf
  ofl/alumnisanssc/AlumniSansSC[wght].ttf
  ofl/alumnisanssc/DESCRIPTION.en_us.html
  ofl/alumnisanssc/METADATA.pb
  ofl/alumnisanssc/OFL.txt
Labels: I New Font, II Small Caps

#7852 playwrite: fix html formatting
  ofl/playwritear/article/ARTICLE.en_us.html
  ofl/playwriteat/article/ARTICLE.en_us.html
  ofl/playwriteaunsw/article/ARTICLE.en_us.html
  ofl/playwriteauqld/article/ARTICLE.en_us.html
  ofl/playwriteausa/article/ARTICLE.en_us.html
  ofl/playwriteautas/article/ARTICLE.en_us.html
  ofl/playwriteauvic/article/ARTICLE.en_us.html
  ofl/playwritebevlg/article/ARTICLE.en_us.html
  ofl/playwritebewal/article/ARTICLE.en_us.html
  ofl/playwritebr/article/ARTICLE.en_us.html
  ofl/playwriteca/article/ARTICLE.en_us.html
  ofl/playwritecl/article/ARTICLE.en_us.html
  ofl/playwriteco/article/ARTICLE.en_us.html
  ofl/playwritecu/article/ARTICLE.en_us.html
  ofl/playwritecz/article/ARTICLE.en_us.html
  ofl/playwritedegrund/article/ARTICLE.en_us.html
  ofl/playwritedela/article/ARTICLE.en_us.html
  ofl/playwritedesas/article/ARTICLE.en_us.html
  ofl/playwritedeva/article/ARTICLE.en_us.html
  ofl/playwritedkloopet/article/ARTICLE.en_us.html
  ofl/playwritedkuloopet/article/ARTICLE.en_us.html
  ofl/playwritees/article/ARTICLE.en_us.html
  ofl/playwriteesdeco/article/ARTICLE.en_us.html
  ofl/playwritefrmoderne/article/ARTICLE.en_us.html
  ofl/playwritefrtrad/article/ARTICLE.en_us.html
  ofl/playwritegbj/article/ARTICLE.en_us.html
  ofl/playwritegbs/article/ARTICLE.en_us.html
  ofl/playwritehr/article/ARTICLE.en_us.html
  ofl/playwritehrlijeva/article/ARTICLE.en_us.html
  ofl/playwritehu/article/ARTICLE.en_us.html
  ofl/playwriteid/article/ARTICLE.en_us.html
  ofl/playwriteie/article/ARTICLE.en_us.html
  ofl/playwritein/article/ARTICLE.en_us.html
  ofl/playwriteis/article/ARTICLE.en_us.html
  ofl/playwriteitmoderna/article/ARTICLE.en_us.html
  ofl/playwriteittrad/article/ARTICLE.en_us.html
  ofl/playwritemx/article/ARTICLE.en_us.html
  ofl/playwritengmodern/article/ARTICLE.en_us.html
  ofl/playwritenl/article/ARTICLE.en_us.html
  ofl/playwriteno/article/ARTICLE.en_us.html
  ofl/playwritenz/article/ARTICLE.en_us.html
  ofl/playwritepe/article/ARTICLE.en_us.html
  ofl/playwritepl/article/ARTICLE.en_us.html
  ofl/playwritept/article/ARTICLE.en_us.html
  ofl/playwritero/article/ARTICLE.en_us.html
  ofl/playwritesk/article/ARTICLE.en_us.html
  ofl/playwritetz/article/ARTICLE.en_us.html
  ofl/playwriteusmodern/article/ARTICLE.en_us.html
  ofl/playwriteustrad/article/ARTICLE.en_us.html
  ofl/playwritevn/article/ARTICLE.en_us.html
  ofl/playwriteza/article/ARTICLE.en_us.html
Labels: I Article/Description

#7866 Life Savers: Version 3.100; ttfautohint (v1.8.4.7-5d5b) added
  ofl/lifesavers/DESCRIPTION.en_us.html
  ofl/lifesavers/LifeSavers-Bold.ttf
  ofl/lifesavers/LifeSavers-ExtraBold.ttf
  ofl/lifesavers/LifeSavers-Regular.ttf
  ofl/lifesavers/METADATA.pb
  ofl/lifesavers/OFL.txt
Labels: I Font Upgrade

#7869 Maname: Version 1.000; ttfautohint (v1.8.4.7-5d5b) added
  ofl/maname/METADATA.pb
  ofl/maname/Maname-Regular.ttf
  ofl/maname/OFL.txt
  ofl/maname/article/ARTICLE.en_us.html
Labels: I New Font, II Commissioned

#7848 Noto Sans Old Turkic: Version 2.004; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosansoldturkic/METADATA.pb
  ofl/notosansoldturkic/NotoSansOldTurkic-Regular.ttf
  ofl/notosansoldturkic/OFL.txt
Labels: I Font Upgrade

#7874 Playwrite: subsets removal part 2
  ofl/playwritear/METADATA.pb
  ofl/playwriteat/METADATA.pb
  ofl/playwritebevlg/METADATA.pb
  ofl/playwritebewal/METADATA.pb
  ofl/playwritecl/METADATA.pb
  ofl/playwritecu/METADATA.pb
  ofl/playwritecz/METADATA.pb
  ofl/playwritedkloopet/METADATA.pb
  ofl/playwritedkuloopet/METADATA.pb
  ofl/playwritehr/METADATA.pb
  ofl/playwritehrlijeva/METADATA.pb
  ofl/playwritehu/METADATA.pb
  ofl/playwritepe/METADATA.pb
Labels: I Metadata/OFL

#7847 Noto Sans Old Sogdian: Version 2.003; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosansoldsogdian/METADATA.pb
  ofl/notosansoldsogdian/NotoSansOldSogdian-Regular.ttf
  ofl/notosansoldsogdian/OFL.txt
Labels: I Font Upgrade

#7853 Playwrite: `primary_language` added
  ofl/playwritear/METADATA.pb
  ofl/playwriteat/METADATA.pb
  ofl/playwriteaunsw/METADATA.pb
  ofl/playwriteauqld/METADATA.pb
  ofl/playwriteausa/METADATA.pb
  ofl/playwriteautas/METADATA.pb
  ofl/playwriteauvic/METADATA.pb
  ofl/playwritebevlg/METADATA.pb
  ofl/playwritebewal/METADATA.pb
  ofl/playwritebr/METADATA.pb
  ofl/playwriteca/METADATA.pb
  ofl/playwritecl/METADATA.pb
  ofl/playwriteco/METADATA.pb
  ofl/playwritecu/METADATA.pb
  ofl/playwritecz/METADATA.pb
  ofl/playwritedegrund/METADATA.pb
  ofl/playwritedela/METADATA.pb
  ofl/playwritedesas/METADATA.pb
  ofl/playwritedeva/METADATA.pb
  ofl/playwritedkloopet/METADATA.pb
  ofl/playwritedkuloopet/METADATA.pb
  ofl/playwritees/METADATA.pb
  ofl/playwriteesdeco/METADATA.pb
  ofl/playwritefrmoderne/METADATA.pb
  ofl/playwritefrtrad/METADATA.pb
  ofl/playwritegbj/METADATA.pb
  ofl/playwritegbs/METADATA.pb
  ofl/playwritehr/METADATA.pb
  ofl/playwritehrlijeva/METADATA.pb
  ofl/playwritehu/METADATA.pb
  ofl/playwriteid/METADATA.pb
  ofl/playwriteie/METADATA.pb
  ofl/playwritein/METADATA.pb
  ofl/playwriteis/METADATA.pb
  ofl/playwriteitmoderna/METADATA.pb
  ofl/playwriteittrad/METADATA.pb
  ofl/playwritemx/METADATA.pb
  ofl/playwritengmodern/METADATA.pb
  ofl/playwritenl/METADATA.pb
  ofl/playwriteno/METADATA.pb
  ofl/playwritenz/METADATA.pb
  ofl/playwritepe/METADATA.pb
  ofl/playwritepl/METADATA.pb
  ofl/playwritept/METADATA.pb
  ofl/playwritero/METADATA.pb
  ofl/playwritesk/METADATA.pb
  ofl/playwritetz/METADATA.pb
  ofl/playwriteusmodern/METADATA.pb
  ofl/playwriteustrad/METADATA.pb
  ofl/playwritevn/METADATA.pb
  ofl/playwriteza/METADATA.pb
Labels: I Metadata/OFL

#7845 Noto Sans Nag Mundari: Version 1.001 added
  ofl/notosansnagmundari/METADATA.pb
  ofl/notosansnagmundari/NotoSansNagMundari[wght].ttf
  ofl/notosansnagmundari/OFL.txt
Labels: I Font Upgrade

#7846 Noto Sans Old Italic: Version 2.004; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosansolditalic/METADATA.pb
  ofl/notosansolditalic/NotoSansOldItalic-Regular.ttf
  ofl/notosansolditalic/OFL.txt
  ofl/notosansolditalic/article/ARTICLE.en_us.html
Labels: I Font Upgrade

#7534 Miriam Libre: Version 2.000 added
  ofl/miriamlibre/DESCRIPTION.en_us.html
  ofl/miriamlibre/METADATA.pb
  ofl/miriamlibre/MiriamLibre-Bold.ttf
  ofl/miriamlibre/MiriamLibre-Regular.ttf
  ofl/miriamlibre/MiriamLibre[wght].ttf
  ofl/miriamlibre/OFL.txt
Labels: III VF Replacement, I Font Upgrade, II Arabic / Hebrew / Semitic / RTL

#7877 Lang v062
  lang/Lib/gflanguages/data/languages/cjy_Hans.textproto
  lang/Lib/gflanguages/data/languages/cjy_Hant.textproto
  lang/Lib/gflanguages/data/languages/gan_Hans.textproto
  lang/Lib/gflanguages/data/languages/gan_Hant.textproto
  lang/Lib/gflanguages/data/languages/hak_Hans.textproto
  lang/Lib/gflanguages/data/languages/hak_Hant.textproto
  lang/Lib/gflanguages/data/languages/hak_Latn.textproto
  lang/Lib/gflanguages/data/languages/hsn_Hans.textproto
  lang/Lib/gflanguages/data/languages/hsn_Hant.textproto
  lang/Lib/gflanguages/data/languages/lzh_Hans.textproto
  lang/Lib/gflanguages/data/languages/lzh_Hant.textproto
  lang/Lib/gflanguages/data/languages/nan_Hans.textproto
  lang/Lib/gflanguages/data/languages/nan_Hant.textproto
  lang/Lib/gflanguages/data/languages/nan_Latn.textproto
  lang/Lib/gflanguages/data/languages/wuu_Hans.textproto
  lang/Lib/gflanguages/data/languages/wuu_Hant.textproto
  lang/Lib/gflanguages/data/languages/yue_Hani.textproto
  lang/Lib/gflanguages/data/languages/yue_Hans.textproto
  lang/Lib/gflanguages/data/languages/yue_Hant.textproto
  lang/Lib/gflanguages/data/languages/za_Hans.textproto
  lang/Lib/gflanguages/data/languages/za_Hant.textproto
Labels: I Lang

#7783 Big Shoulders Display SC: Version 2.002 added
  ofl/bigshouldersdisplay/config.yaml
  ofl/bigshouldersdisplaysc/BigShouldersDisplaySC[wght].ttf
  ofl/bigshouldersdisplaysc/DESCRIPTION.en_us.html
  ofl/bigshouldersdisplaysc/METADATA.pb
  ofl/bigshouldersdisplaysc/OFL.txt
  ofl/bigshouldersdisplaysc/config.yaml
Labels: I New Font, II Small Caps

#7790 Big Shoulders Text SC: Version 2.002 added
  ofl/bigshoulderstext/config.yaml
  ofl/bigshoulderstextsc/BigShouldersTextSC[wght].ttf
  ofl/bigshoulderstextsc/DESCRIPTION.en_us.html
  ofl/bigshoulderstextsc/METADATA.pb
  ofl/bigshoulderstextsc/OFL.txt
  ofl/bigshoulderstextsc/config.yaml
Labels: I New Font, II Small Caps

#7786 Big Shoulders Inline Display SC: Version 2.002 added
  ofl/bigshouldersinlinedisplay/config.yaml
  ofl/bigshouldersinlinedisplaysc/BigShouldersInlineDisplaySC[wght].ttf
  ofl/bigshouldersinlinedisplaysc/DESCRIPTION.en_us.html
  ofl/bigshouldersinlinedisplaysc/METADATA.pb
  ofl/bigshouldersinlinedisplaysc/OFL.txt
  ofl/bigshouldersinlinedisplaysc/config.yaml
Labels: I New Font, II Small Caps

#7787 Big Shoulders Inline Text SC: Version 2.002 added
  ofl/bigshouldersinlinetext/config.yaml
  ofl/bigshouldersinlinetextsc/BigShouldersInlineTextSC[wght].ttf
  ofl/bigshouldersinlinetextsc/DESCRIPTION.en_us.html
  ofl/bigshouldersinlinetextsc/METADATA.pb
  ofl/bigshouldersinlinetextsc/OFL.txt
  ofl/bigshouldersinlinetextsc/config.yaml
Labels: I New Font, II Small Caps

#7788 Big Shoulders Stencil Display SC: Version 2.002 added
  ofl/bigshouldersstencildisplay/config.yaml
  ofl/bigshouldersstencildisplaysc/BigShouldersStencilDisplaySC[wght].ttf
  ofl/bigshouldersstencildisplaysc/DESCRIPTION.en_us.html
  ofl/bigshouldersstencildisplaysc/METADATA.pb
  ofl/bigshouldersstencildisplaysc/OFL.txt
  ofl/bigshouldersstencildisplaysc/config.yaml
Labels: I New Font, II Small Caps

#7789 Big Shoulders Stencil Text SC: Version 2.001 added
  ofl/bigshouldersstenciltext/config.yaml
  ofl/bigshouldersstenciltextsc/BigShouldersStencilTextSC[wght].ttf
  ofl/bigshouldersstenciltextsc/DESCRIPTION.en_us.html
  ofl/bigshouldersstenciltextsc/METADATA.pb
  ofl/bigshouldersstenciltextsc/OFL.txt
  ofl/bigshouldersstenciltextsc/config.yaml
Labels: I New Font, II Small Caps

#7832 Noto Sans Masaram Gondi: Version 1.005; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosansmasaramgondi/METADATA.pb
  ofl/notosansmasaramgondi/NotoSansMasaramGondi-Regular.ttf
  ofl/notosansmasaramgondi/OFL.txt
Labels: I Font Upgrade

#7828 Noto Sans Mandaic: Version 2.003; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosansmandaic/METADATA.pb
  ofl/notosansmandaic/NotoSansMandaic-Regular.ttf
  ofl/notosansmandaic/OFL.txt
Labels: I Font Upgrade

#7829 Noto Sans Marchen: Version 2.004; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosansmarchen/DESCRIPTION.en_us.html
  ofl/notosansmarchen/METADATA.pb
  ofl/notosansmarchen/NotoSansMarchen-Regular.ttf
  ofl/notosansmarchen/OFL.txt
Labels: I Font Upgrade

#7887 Philosopher: Version 2.001; ttfautohint (v1.8.4.7-5d5b) added
  ofl/philosopher/DESCRIPTION.en_us.html
  ofl/philosopher/METADATA.pb
  ofl/philosopher/OFL.txt
  ofl/philosopher/Philosopher-Bold.ttf
  ofl/philosopher/Philosopher-BoldItalic.ttf
  ofl/philosopher/Philosopher-Italic.ttf
  ofl/philosopher/Philosopher-Regular.ttf
Labels: I Font Upgrade

#7890 Zain: Version 1.20; ttfautohint (v1.8.4) added
  ofl/zain/DESCRIPTION.en_us.html
  ofl/zain/METADATA.pb
  ofl/zain/Zain-Black.ttf
  ofl/zain/Zain-Bold.ttf
  ofl/zain/Zain-ExtraBold.ttf
  ofl/zain/Zain-ExtraLight.ttf
  ofl/zain/Zain-Light.ttf
  ofl/zain/Zain-Regular.ttf
Labels: I New Font, II Accepted, II Arabic / Hebrew / Semitic / RTL

#7819 Noto Sans Math: Version 3.000; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosansmath/METADATA.pb
  ofl/notosansmath/NotoSansMath-Regular.ttf
  ofl/notosansmath/OFL.txt
  ofl/notosansmath/article/ARTICLE.en_us.html
Labels: -- Needs confirmation, I Font Upgrade

#7897 Update for zain project (to_lists)
  to_production.txt
  to_sandbox.txt
Labels: I Tools / workflow / repo

#7870 Update content.md with additional preconnect to `https://fonts.googleapis.com`
  cc-by-sa/knowledge/modules/using_type/lessons/using_web_fonts_from_a_font_delivery_service/content.md
Labels: I Knowledge
