Repository google/fonts, pull requests merged in 2024-05, with the labels that each got.

#7623 Graduate: Version 1.100; ttfautohint (v1.8.4.7-5d5b) added
  ofl/graduate/DESCRIPTION.en_us.html
  ofl/graduate/Graduate-Regular.ttf
  ofl/graduate/METADATA.pb
  ofl/graduate/OFL.txt
Labels: III Expand glyphset, I Font Upgrade, II Commissioned

#7603 Jaro: add article
  ofl/jaro/DESCRIPTION.en_us.html
  ofl/jaro/article/ARTICLE.en_us.html
  ofl/jaro/article/Jaro-01.png
  ofl/jaro/article/Jaro-02.png
  ofl/jaro/article/Jaro-03.png
  ofl/jaro/article/Jaro-04.png
Labels: I Description/Article/Metadata/OFL

#7627 Update bethellen/DESCRIPTION.en_us.html
  ofl/bethellen/DESCRIPTION.en_us.html
Labels: I Description/Article/Metadata/OFL

#7639 Playwrite VN: Version 1.001 added
  ofl/playwritevn/DESCRIPTION.en_us.html
  ofl/playwritevn/METADATA.pb
  ofl/playwritevn/OFL.txt
  ofl/playwritevn/PlaywriteVN[wght].ttf
  ofl/playwritevn/article/ARTICLE.en_us.html
  ofl/playwritevn/article/Playwrite-Viet-Nam-1.png
  ofl/playwritevn/article/Playwrite-Viet-Nam-2.png
  ofl/playwritevn/article/Playwrite-Viet-Nam-3.png
Labels: I New Font

#7640 Playwrite VN: TypeTogether added as designer
  ofl/playwritevn/METADATA.pb
Labels: I Metadata/OFL

#7630 Cutive Mono: Version 1.110; ttfautohint (v1.8.4.7-5d5b) added
  ofl/cutivemono/CutiveMono-Regular.ttf
  ofl/cutivemono/DESCRIPTION.en_us.html
  ofl/cutivemono/METADATA.pb
  ofl/cutivemono/OFL.txt
Labels: I Font Upgrade

#7600 Alatsi: Version 1.008; ttfautohint (v1.8.4.7-5d5b) added
  ofl/alatsi/Alatsi-Regular.ttf
  ofl/alatsi/DESCRIPTION.en_us.html
  ofl/alatsi/METADATA.pb
  ofl/alatsi/OFL.txt
Labels: I Font Upgrade

#7622 lang v0.6.0
  lang/.github/workflows/publish-release.yml
  lang/.github/workflows/test.yml
  lang/.github/workflows/tox.yml
  lang/Lib/gflanguages/__init__.py
  lang/Lib/gflanguages/data/languages/ati_Latn.textproto
  lang/Lib/gflanguages/data/languages/dow_Latn.textproto
  lang/Lib/gflanguages/data/languages/en_Dsrt.textproto
  lang/Lib/gflanguages/data/languages/eto_Latn.textproto
  lang/Lib/gflanguages/data/languages/giz_Latn.textproto
  lang/Lib/gflanguages/data/languages/gnd_Latn.textproto
  lang/Lib/gflanguages/data/languages/grc_Linb.textproto
  lang/Lib/gflanguages/data/languages/idu_Latn.textproto
  lang/Lib/gflanguages/data/languages/ja_Jpan.textproto
  lang/Lib/gflanguages/data/languages/mfd_Latn.textproto
  lang/Lib/gflanguages/data/languages/neb_Latn.textproto
  lang/Lib/gflanguages/data/languages/oaa_Cyrl.textproto
  lang/Lib/gflanguages/data/languages/peo_Xpeo.textproto
  lang/Lib/gflanguages/data/languages/sa_Modi.textproto
  lang/Lib/gflanguages/data/languages/sa_Ranj.textproto
  lang/Lib/gflanguages/data/languages/sa_Sind.textproto
  lang/Lib/gflanguages/data/languages/sa_Sund.textproto
  lang/Lib/gflanguages/data/languages/sd_Sind.textproto
  lang/Lib/gflanguages/data/languages/sq_Vith.textproto
  lang/Lib/gflanguages/data/languages/uma_Latn.textproto
  lang/Lib/gflanguages/data/languages/vut_Latn.textproto
  lang/pyproject.toml
  lang/requirements.txt
  lang/setup.py
  lang/tests/test_data_languages.py
  lang/tox.ini
Labels: I Lang

#7614 Sankofa Display: Version 1.000; ttfautohint (v1.8.4.7-5d5b) added
  ofl/sankofadisplay/DESCRIPTION.en_us.html
  ofl/sankofadisplay/METADATA.pb
  ofl/sankofadisplay/OFL.txt
  ofl/sankofadisplay/SankofaDisplay-Regular.ttf
Labels: I New Font

#7566 Danfo: add article
  ofl/danfo/DESCRIPTION.en_us.html
  ofl/danfo/article/01.mp4
  ofl/danfo/article/2.1.jpg
  ofl/danfo/article/2.2.mp4
  ofl/danfo/article/2.3.mp4
  ofl/danfo/article/2.4.jpg
  ofl/danfo/article/3.1.jpg
  ofl/danfo/article/3.2.mp4
  ofl/danfo/article/3.3.jpg
  ofl/danfo/article/3.4.jpg
  ofl/danfo/article/ARTICLE.en_us.html
Labels: I Article/Description

#7646 Playwrite BR: Version 1.002 added
  ofl/playwritebr/METADATA.pb
  ofl/playwritebr/OFL.txt
  ofl/playwritebr/PlaywriteBR[wght].ttf
  ofl/playwritebr/article/ARTICLE.en_us.html
  ofl/playwritebr/article/Playwrite-Brasil-1.png
  ofl/playwritebr/article/Playwrite-Brasil-2.png
  ofl/playwritebr/article/Playwrite-Brasil-3.png
Labels: I New Font

#7682 PWBR: added an empty description
  ofl/playwritebr/DESCRIPTION.en_us.html
Labels: I Article/Description

#7668 Playwrite VN: Version 1.002 added
  ofl/playwritevn/DESCRIPTION.en_us.html
  ofl/playwritevn/METADATA.pb
  ofl/playwritevn/PlaywriteVN[wght].ttf
  ofl/playwritevn/article/ARTICLE.en_us.html
Labels: I New Font

#7669 Playwrite CO: Version 1.002 added
  ofl/playwriteco/DESCRIPTION.en_us.html
  ofl/playwriteco/METADATA.pb
  ofl/playwriteco/OFL.txt
  ofl/playwriteco/PlaywriteCO[wght].ttf
  ofl/playwriteco/article/ARTICLE.en_us.html
  ofl/playwriteco/article/Playwrite-Colombia-1.png
  ofl/playwriteco/article/Playwrite-Colombia-2.png
  ofl/playwriteco/article/Playwrite-Colombia-3.png
  ofl/playwriteco/article/Playwrite-Colombia_1.jpg
  ofl/playwriteco/article/Playwrite-Colombia_2.jpg
  ofl/playwriteco/article/Playwrite-Colombia_3.jpg
Labels: I New Font

#7643 Playwrite GB S: Version 1.002 added
  ofl/playwritegbs/DESCRIPTION.en_us.html
  ofl/playwritegbs/METADATA.pb
  ofl/playwritegbs/OFL.txt
  ofl/playwritegbs/PlaywriteGBS-Italic[wght].ttf
  ofl/playwritegbs/PlaywriteGBS[wght].ttf
  ofl/playwritegbs/article/ARTICLE.en_us.html
  ofl/playwritegbs/article/Playwrite-England-SemiSemiJoined-1.png
  ofl/playwritegbs/article/Playwrite-England-SemiSemiJoined-2.png
  ofl/playwritegbs/article/Playwrite-England-SemiSemiJoined-3.png
  ofl/playwritegbs/article/Playwrite-England-SemiSemiJoined-4.png
Labels: I New Font

#7670 Playwrite FR Trad: Version 1.002 added
  ofl/playwritefrtrad/DESCRIPTION.en_us.html
  ofl/playwritefrtrad/METADATA.pb
  ofl/playwritefrtrad/OFL.txt
  ofl/playwritefrtrad/PlaywriteFRTrad[wght].ttf
  ofl/playwritefrtrad/article/ARTICLE.en_us.html
  ofl/playwritefrtrad/article/Playwrite-France-Traditionnelle-1.png
  ofl/playwritefrtrad/article/Playwrite-France-Traditionnelle-2.png
  ofl/playwritefrtrad/article/Playwrite-France-Traditionnelle-3.png
Labels: I New Font

#7680 lang v0.6.1
  lang/CONTRIBUTORS.txt
  lang/Lib/gflanguages/data/languages/bdh_Latn.textproto
  lang/Lib/gflanguages/data/languages/beh_Latn.textproto
  lang/Lib/gflanguages/data/languages/bgn_Arab.textproto
  lang/Lib/gflanguages/data/languages/bkc_Latn.textproto
  lang/Lib/gflanguages/data/languages/bsc_Latn_GN.textproto
  lang/Lib/gflanguages/data/languages/bsq_Bass.textproto
  lang/Lib/gflanguages/data/languages/bsq_Latn.textproto
  lang/Lib/gflanguages/data/languages/crh_Cyrl.textproto
  lang/Lib/gflanguages/data/languages/dnj_Latn_LR.textproto
  lang/Lib/gflanguages/data/languages/evn_Latn.textproto
  lang/Lib/gflanguages/data/languages/kr_Arab.textproto
  lang/Lib/gflanguages/data/languages/mlt_Latn.textproto
  lang/Lib/gflanguages/data/languages/sa_Nand.textproto
  lang/Lib/gflanguages/data/languages/uma_Latn.textproto
  lang/Lib/gflanguages/data/languages/wal_Ethi.textproto
  lang/Lib/gflanguages/data/languages/wal_Latn.textproto
  lang/Lib/gflanguages/data/languages/xsm_Latn_BF.textproto
  lang/tests/test_data_languages.py
  lang/tests/test_parsable.py
Labels: I Lang

#7689 Danfo: add minisite url
  ofl/danfo/METADATA.pb
Labels: I Metadata/OFL

#7652 Briem Hand: Version 1.004 added
  ofl/briemhand/BriemHand[wght].ttf
  ofl/briemhand/DESCRIPTION.en_us.html
  ofl/briemhand/METADATA.pb
  ofl/briemhand/upstream.yaml
Labels: -- Needs confirmation, I Font Upgrade

#7709 Playwrite DE SAS: Version 1.002 added
  ofl/playwritedesas/METADATA.pb
  ofl/playwritedesas/OFL.txt
  ofl/playwritedesas/PlaywriteDESAS[wght].ttf
  ofl/playwritedesas/article/ARTICLE.en_us.html
  ofl/playwritedesas/article/Playwrite-Deutschland-SAS-1.png
  ofl/playwritedesas/article/Playwrite-Deutschland-SAS-2.png
  ofl/playwritedesas/article/Playwrite-Deutschland-SAS-3.png
Labels: I New Font

#7710 Playwrite DE VA: Version 1.002 added
  ofl/playwritedeva/METADATA.pb
  ofl/playwritedeva/OFL.txt
  ofl/playwritedeva/PlaywriteDEVA[wght].ttf
  ofl/playwritedeva/article/ARTICLE.en_us.html
  ofl/playwritedeva/article/Playwrite-Deutschland-VA-1.png
  ofl/playwritedeva/article/Playwrite-Deutschland-VA-2.png
  ofl/playwritedeva/article/Playwrite-Deutschland-VA-3.png
Labels: I New Font

#7688 Noto Sans Inscriptional Pahlavi: Version 2.004; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosansinscriptionalpahlavi/DESCRIPTION.en_us.html
  ofl/notosansinscriptionalpahlavi/METADATA.pb
  ofl/notosansinscriptionalpahlavi/NotoSansInscriptionalPahlavi-Regular.ttf
Labels: I Font Upgrade

#7692 Noto Sans Devanagari: Version 2.005 added
  ofl/notosansdevanagari/DESCRIPTION.en_us.html
  ofl/notosansdevanagari/METADATA.pb
  ofl/notosansdevanagari/NotoSansDevanagari[wdth,wght].ttf
Labels: I Font Upgrade

#7716 Playwrite GB J: Version 1.002 added
  ofl/playwritegbj/METADATA.pb
  ofl/playwritegbj/OFL.txt
  ofl/playwritegbj/PlaywriteGBJ-Italic[wght].ttf
  ofl/playwritegbj/PlaywriteGBJ[wght].ttf
  ofl/playwritegbj/article/ARTICLE.en_us.html
  ofl/playwritegbj/article/Playwrite-England-Joined-1.png
  ofl/playwritegbj/article/Playwrite-England-Joined-2.png
  ofl/playwritegbj/article/Playwrite-England-Joined-3.png
  ofl/playwritegbj/article/Playwrite-England-Joined-4.png
Labels: I New Font

#7750 GB S image names fix
  ofl/playwritegbs/article/Playwrite-England-SemiJoined-1.png
  ofl/playwritegbs/article/Playwrite-England-SemiJoined-2.png
  ofl/playwritegbs/article/Playwrite-England-SemiJoined-3.png
  ofl/playwritegbs/article/Playwrite-England-SemiJoined-4.png
Labels: I Article/Description

#7761 Bricolage: Cyrillic-ext subset removed
  ofl/bricolagegrotesque/METADATA.pb
Labels: I Metadata/OFL

#7751 Noto Sans Duployan: Version 3.002 added
  ofl/notosansduployan/DESCRIPTION.en_us.html
  ofl/notosansduployan/METADATA.pb
  ofl/notosansduployan/NotoSansDuployan-Bold.ttf
  ofl/notosansduployan/NotoSansDuployan-Regular.ttf
Labels: I Font Upgrade

#7752 Noto Sans Devanagari: Version 2.006 added
  ofl/notosansdevanagari/METADATA.pb
  ofl/notosansdevanagari/NotoSansDevanagari[wdth,wght].ttf
Labels: I Font Upgrade

#7754 Noto Serif Grantha: Version 2.005; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notoserifgrantha/DESCRIPTION.en_us.html
  ofl/notoserifgrantha/METADATA.pb
  ofl/notoserifgrantha/NotoSerifGrantha-Regular.ttf
Labels: I Font Upgrade

#7739 Playwrite ZA: Version 1.002 added
  ofl/playwriteza/METADATA.pb
  ofl/playwriteza/OFL.txt
  ofl/playwriteza/PlaywriteZA[wght].ttf
  ofl/playwriteza/article/ARTICLE.en_us.html
  ofl/playwriteza/article/Playwrite-South-Africa-1.png
  ofl/playwriteza/article/Playwrite-South-Africa-2.png
  ofl/playwriteza/article/Playwrite-South-Africa-3.png
Labels: I New Font

#7708 Playwrite DE LA: Version 1.002 added
  ofl/playwritedela/METADATA.pb
  ofl/playwritedela/OFL.txt
  ofl/playwritedela/PlaywriteDELA[wght].ttf
  ofl/playwritedela/article/ARTICLE.en_us.html
  ofl/playwritedela/article/Playwrite-Deutschland-LA-1.png
  ofl/playwritedela/article/Playwrite-Deutschland-LA-2.png
  ofl/playwritedela/article/Playwrite-Deutschland-LA-3.png
Labels: I New Font

#7714 Playwrite ES: Version 1.002 added
  ofl/playwritees/METADATA.pb
  ofl/playwritees/OFL.txt
  ofl/playwritees/PlaywriteES[wght].ttf
  ofl/playwritees/article/ARTICLE.en_us.html
  ofl/playwritees/article/Playwrite-Espana-1.png
  ofl/playwritees/article/Playwrite-Espana-2.png
  ofl/playwritees/article/Playwrite-Espana-3.png
Labels: I New Font

#7713 Playwrite ES Deco: Version 1.002 added
  ofl/playwriteesdeco/METADATA.pb
  ofl/playwriteesdeco/OFL.txt
  ofl/playwriteesdeco/PlaywriteESDeco[wght].ttf
  ofl/playwriteesdeco/article/ARTICLE.en_us.html
  ofl/playwriteesdeco/article/Playwrite-Espana-Decorativa-1.png
  ofl/playwriteesdeco/article/Playwrite-Espana-Decorativa-2.png
  ofl/playwriteesdeco/article/Playwrite-Espana-Decorativa-3.png
Labels: I New Font

#7715 Playwrite FR Moderne: Version 1.002 added
  ofl/playwritefrmoderne/METADATA.pb
  ofl/playwritefrmoderne/OFL.txt
  ofl/playwritefrmoderne/PlaywriteFRModerne[wght].ttf
  ofl/playwritefrmoderne/article/ARTICLE.en_us.html
  ofl/playwritefrmoderne/article/Playwrite-France-Moderne-1.png
  ofl/playwritefrmoderne/article/Playwrite-France-Moderne-2.png
  ofl/playwritefrmoderne/article/Playwrite-France-Moderne-3.png
Labels: I New Font

#7720 Playwrite ID: Version 1.002 added
  ofl/playwriteid/METADATA.pb
  ofl/playwriteid/OFL.txt
  ofl/playwriteid/PlaywriteID[wght].ttf
  ofl/playwriteid/article/ARTICLE.en_us.html
  ofl/playwriteid/article/Playwrite-Indonesia-1.png
  ofl/playwriteid/article/Playwrite-Indonesia-2.png
  ofl/playwriteid/article/Playwrite-Indonesia-3.png
Labels: I New Font

#7722 Playwrite IN: Version 1.002 added
  ofl/playwritein/METADATA.pb
  ofl/playwritein/OFL.txt
  ofl/playwritein/PlaywriteIN[wght].ttf
  ofl/playwritein/article/ARTICLE.en_us.html
  ofl/playwritein/article/Playwrite-India-1.png
  ofl/playwritein/article/Playwrite-India-2.png
  ofl/playwritein/article/Playwrite-India-3.png
Labels: I New Font

#7724 Playwrite IT moderna: Version 1.002 added
  ofl/playwriteitmoderna/METADATA.pb
  ofl/playwriteitmoderna/OFL.txt
  ofl/playwriteitmoderna/PlaywriteITModerna[wght].ttf
  ofl/playwriteitmoderna/article/ARTICLE.en_us.html
  ofl/playwriteitmoderna/article/Playwrite-Italia-Moderna-1.png
  ofl/playwriteitmoderna/article/Playwrite-Italia-Moderna-2.png
  ofl/playwriteitmoderna/article/Playwrite-Italia-Moderna-3.png
Labels: I New Font

#7725 Playwrite IT Trad: Version 1.002 added
  ofl/playwriteittrad/METADATA.pb
  ofl/playwriteittrad/OFL.txt
  ofl/playwriteittrad/PlaywriteITTrad[wght].ttf
  ofl/playwriteittrad/article/ARTICLE.en_us.html
  ofl/playwriteittrad/article/Playwrite-Italia-Tradizionale-1.png
  ofl/playwriteittrad/article/Playwrite-Italia-Tradizionale-2.png
  ofl/playwriteittrad/article/Playwrite-Italia-Tradizionale-3.png
Labels: I New Font

#7726 Playwrite MX: Version 1.002 added
  ofl/playwritemx/METADATA.pb
  ofl/playwritemx/OFL.txt
  ofl/playwritemx/PlaywriteMX[wght].ttf
  ofl/playwritemx/article/ARTICLE.en_us.html
  ofl/playwritemx/article/Playwrite-Mexico-1.png
  ofl/playwritemx/article/Playwrite-Mexico-2.png
  ofl/playwritemx/article/Playwrite-Mexico-3.png
Labels: I New Font

#7727 Playwrite NG Modern: Version 1.002 added
  ofl/playwritengmodern/METADATA.pb
  ofl/playwritengmodern/OFL.txt
  ofl/playwritengmodern/PlaywriteNGModern[wght].ttf
  ofl/playwritengmodern/article/ARTICLE.en_us.html
  ofl/playwritengmodern/article/Playwrite-Nigeria-Modern-1.png
  ofl/playwritengmodern/article/Playwrite-Nigeria-Modern-2.png
  ofl/playwritengmodern/article/Playwrite-Nigeria-Modern-3.png
Labels: I New Font

#7736 Playwrite TZ: Version 1.002 added
  ofl/playwritetz/METADATA.pb
  ofl/playwritetz/OFL.txt
  ofl/playwritetz/PlaywriteTZ[wght].ttf
  ofl/playwritetz/article/ARTICLE.en_us.html
  ofl/playwritetz/article/Playwrite-Tanzania-1.png
  ofl/playwritetz/article/Playwrite-Tanzania-2.png
  ofl/playwritetz/article/Playwrite-Tanzania-3.png
Labels: I New Font

#7737 Playwrite US Modern: Version 1.002 added
  ofl/playwriteusmodern/METADATA.pb
  ofl/playwriteusmodern/OFL.txt
  ofl/playwriteusmodern/PlaywriteUSModern[wght].ttf
  ofl/playwriteusmodern/article/ARTICLE.en_us.html
  ofl/playwriteusmodern/article/Playwrite-USA-Modern-1.png
  ofl/playwriteusmodern/article/Playwrite-USA-Modern-2.png
  ofl/playwriteusmodern/article/Playwrite-USA-Modern-3.png
Labels: I New Font

#7738 Playwrite US Trad: Version 1.002 added
  ofl/playwriteustrad/METADATA.pb
  ofl/playwriteustrad/OFL.txt
  ofl/playwriteustrad/PlaywriteUSTrad[wght].ttf
  ofl/playwriteustrad/article/ARTICLE.en_us.html
  ofl/playwriteustrad/article/Playwrite-USA-Traditional-1.png
  ofl/playwriteustrad/article/Playwrite-USA-Traditional-2.png
  ofl/playwriteustrad/article/Playwrite-USA-Traditional-3.png
Labels: I New Font

#7763 Turning Markdown in `figcaptions` into HTML
  cc-by-sa/knowledge/glossary/terms/bled_axis/content.md
  cc-by-sa/knowledge/glossary/terms/bnce_axis/content.md
  cc-by-sa/knowledge/glossary/terms/edpt_axis/content.md
  cc-by-sa/knowledge/glossary/terms/ehlt_axis/content.md
  cc-by-sa/knowledge/glossary/terms/elgr_axis/content.md
  cc-by-sa/knowledge/glossary/terms/elsh_axis/content.md
  cc-by-sa/knowledge/glossary/terms/hexp_axis/content.md
  cc-by-sa/knowledge/glossary/terms/infm_axis/content.md
  cc-by-sa/knowledge/glossary/terms/scan_axis/content.md
  cc-by-sa/knowledge/glossary/terms/shrp_axis/content.md
  cc-by-sa/knowledge/glossary/terms/spac_axis/content.md
  cc-by-sa/knowledge/glossary/terms/volm_axis/content.md
  cc-by-sa/knowledge/glossary/terms/xrot_axis/content.md
  cc-by-sa/knowledge/glossary/terms/yela_axis/content.md
  cc-by-sa/knowledge/glossary/terms/yrot_axis/content.md
Labels: I Knowledge

#7697 Playwrite AU NSW: Version 1.002 added
  ofl/playwriteaunsw/METADATA.pb
  ofl/playwriteaunsw/OFL.txt
  ofl/playwriteaunsw/PlaywriteAUNSW[wght].ttf
  ofl/playwriteaunsw/article/ARTICLE.en_us.html
  ofl/playwriteaunsw/article/Playwrite-Australia-NSW-1.png
  ofl/playwriteaunsw/article/Playwrite-Australia-NSW-2.png
  ofl/playwriteaunsw/article/Playwrite-Australia-NSW-3.png
Labels: I New Font

#7698 Playwrite AU QLD: Version 1.002 added
  ofl/playwriteauqld/METADATA.pb
  ofl/playwriteauqld/OFL.txt
  ofl/playwriteauqld/PlaywriteAUQLD[wght].ttf
  ofl/playwriteauqld/article/ARTICLE.en_us.html
  ofl/playwriteauqld/article/Playwrite-Australia-QLD-1.png
  ofl/playwriteauqld/article/Playwrite-Australia-QLD-2.png
  ofl/playwriteauqld/article/Playwrite-Australia-QLD-3.png
Labels: I New Font

#7699 Playwrite AU SA: Version 1.002 added
  ofl/playwriteausa/METADATA.pb
  ofl/playwriteausa/OFL.txt
  ofl/playwriteausa/PlaywriteAUSA[wght].ttf
  ofl/playwriteausa/article/ARTICLE.en_us.html
  ofl/playwriteausa/article/Playwrite-Australia-SA-1.png
  ofl/playwriteausa/article/Playwrite-Australia-SA-2.png
  ofl/playwriteausa/article/Playwrite-Australia-SA-3.png
Labels: I New Font

#7700 Playwrite AU TAS: Version 1.002 added
  ofl/playwriteautas/METADATA.pb
  ofl/playwriteautas/OFL.txt
  ofl/playwriteautas/PlaywriteAUTAS[wght].ttf
  ofl/playwriteautas/article/ARTICLE.en_us.html
  ofl/playwriteautas/article/Playwrite-Australia-TAS-1.png
  ofl/playwriteautas/article/Playwrite-Australia-TAS-2.png
  ofl/playwriteautas/article/Playwrite-Australia-TAS-3.png
Labels: I New Font

#7701 Playwrite AU VIC: Version 1.002 added
  ofl/playwriteauvic/METADATA.pb
  ofl/playwriteauvic/OFL.txt
  ofl/playwriteauvic/PlaywriteAUVIC[wght].ttf
  ofl/playwriteauvic/article/ARTICLE.en_us.html
  ofl/playwriteauvic/article/Playwrite-Australia-VIC-1.png
  ofl/playwriteauvic/article/Playwrite-Australia-VIC-2.png
  ofl/playwriteauvic/article/Playwrite-Australia-VIC-3.png
Labels: I New Font

#7704 Playwrite CA: Version 1.002 added
  ofl/playwriteca/METADATA.pb
  ofl/playwriteca/OFL.txt
  ofl/playwriteca/PlaywriteCA[wght].ttf
  ofl/playwriteca/article/ARTICLE.en_us.html
  ofl/playwriteca/article/Playwrite-Canada-1.png
  ofl/playwriteca/article/Playwrite-Canada-2.png
  ofl/playwriteca/article/Playwrite-Canada-3.png
Labels: I New Font

#7721 Playwrite IE: Version 1.002 added
  ofl/playwriteie/METADATA.pb
  ofl/playwriteie/OFL.txt
  ofl/playwriteie/PlaywriteIE[wght].ttf
  ofl/playwriteie/article/ARTICLE.en_us.html
  ofl/playwriteie/article/Playwrite-Ireland-1.png
  ofl/playwriteie/article/Playwrite-Ireland-2.png
  ofl/playwriteie/article/Playwrite-Ireland-3.png
Labels: I New Font

#7730 Playwrite NZ: Version 1.002 added
  ofl/playwritenz/METADATA.pb
  ofl/playwritenz/OFL.txt
  ofl/playwritenz/PlaywriteNZ[wght].ttf
  ofl/playwritenz/article/ARTICLE.en_us.html
  ofl/playwritenz/article/Playwrite-New-Zealand-1.png
  ofl/playwritenz/article/Playwrite-New-Zealand-2.png
  ofl/playwritenz/article/Playwrite-New-Zealand-3.png
Labels: I New Font

#7686 Noto Sans Imperial Aramaic: Version 2.002; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosansimperialaramaic/DESCRIPTION.en_us.html
  ofl/notosansimperialaramaic/METADATA.pb
  ofl/notosansimperialaramaic/NotoSansImperialAramaic-Regular.ttf
Labels: I Font Upgrade

#7765 Noto Sans Khudawadi: Version 2.004; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosanskhudawadi/DESCRIPTION.en_us.html
  ofl/notosanskhudawadi/METADATA.pb
  ofl/notosanskhudawadi/NotoSansKhudawadi-Regular.ttf
  ofl/notosanskhudawadi/article/ARTICLE.en_us.html
Labels: I Font Upgrade

#7687 Noto Sans Inscriptional Parthian: Version 2.004; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosansinscriptionalparthian/DESCRIPTION.en_us.html
  ofl/notosansinscriptionalparthian/METADATA.pb
  ofl/notosansinscriptionalparthian/NotoSansInscriptionalParthian-Regular.ttf
Labels: I Font Upgrade

#7683 Noto Sans Balinese: Version 2.006 added
  ofl/notosansbalinese/DESCRIPTION.en_us.html
  ofl/notosansbalinese/METADATA.pb
  ofl/notosansbalinese/NotoSansBalinese[wght].ttf
Labels: I Font Upgrade

#7774 Bona Nova SC: Version 4.001; ttfautohint (v1.8.4.7-5d5b) added
  ofl/bonanovasc/BonaNovaSC-Bold.ttf
  ofl/bonanovasc/BonaNovaSC-Italic.ttf
  ofl/bonanovasc/BonaNovaSC-Regular.ttf
  ofl/bonanovasc/DESCRIPTION.en_us.html
  ofl/bonanovasc/METADATA.pb
  ofl/bonanovasc/OFL.txt
Labels: I New Font

#7772 Baskervville SC: Version 1.003; ttfautohint (v1.8.4.7-5d5b) added
  ofl/baskervvillesc/BaskervvilleSC-Regular.ttf
  ofl/baskervvillesc/DESCRIPTION.en_us.html
  ofl/baskervvillesc/METADATA.pb
  ofl/baskervvillesc/OFL.txt
Labels: I New Font

#7681 Noto Sans Adlam Unjoined: Version 3.002 added
  ofl/notosansadlamunjoined/METADATA.pb
  ofl/notosansadlamunjoined/NotoSansAdlamUnjoined[wght].ttf
  ofl/notosansadlamunjoined/article/ARTICLE.en_us.html
Labels: I Font Upgrade

#7779 [HOTFIX] Concert One v-metrics
  ofl/concertone/ConcertOne-Regular.ttf
Labels: I Small Fix

#7735 Playwrite SK: Version 1.002 added
  ofl/playwritesk/METADATA.pb
  ofl/playwritesk/OFL.txt
  ofl/playwritesk/PlaywriteSK[wght].ttf
  ofl/playwritesk/article/ARTICLE.en_us.html
  ofl/playwritesk/article/Playwrite-Slovensko-1.png
  ofl/playwritesk/article/Playwrite-Slovensko-2.png
  ofl/playwritesk/article/Playwrite-Slovensko-3.png
Labels: I New Font

#7781 PW url fixes in articles
  .github/workflows/test.yaml
  ofl/playwriteaunsw/article/ARTICLE.en_us.html
  ofl/playwriteauqld/article/ARTICLE.en_us.html
  ofl/playwriteausa/article/ARTICLE.en_us.html
  ofl/playwriteautas/article/ARTICLE.en_us.html
  ofl/playwriteauvic/article/ARTICLE.en_us.html
  ofl/playwriteco/article/ARTICLE.en_us.html
  ofl/playwritefrmoderne/article/ARTICLE.en_us.html
  ofl/playwritefrtrad/article/ARTICLE.en_us.html
Labels: I Tools / workflow / repo

#7734 Playwrite RO: Version 1.002 added
  ofl/playwritero/METADATA.pb
  ofl/playwritero/OFL.txt
  ofl/playwritero/PlaywriteRO[wght].ttf
  ofl/playwritero/article/ARTICLE.en_us.html
  ofl/playwritero/article/Playwrite-Romania-1.png
  ofl/playwritero/article/Playwrite-Romania-2.png
  ofl/playwritero/article/Playwrite-Romania-3.png
Labels: I New Font

#7773 Bodoni Moda SC: Version 2.005 added
  ofl/bodonimodasc/BodoniModaSC-Italic[opsz,wght].ttf
  ofl/bodonimodasc/BodoniModaSC[opsz,wght].ttf
  ofl/bodonimodasc/DESCRIPTION.en_us.html
  ofl/bodonimodasc/METADATA.pb
  ofl/bodonimodasc/OFL.txt
Labels: -- Needs confirmation, I New Font, II Small Caps

#7771 Arsenal SC: Version 2.001; ttfautohint (v1.8.4.7-5d5b) added
  ofl/arsenalsc/ArsenalSC-Bold.ttf
  ofl/arsenalsc/ArsenalSC-BoldItalic.ttf
  ofl/arsenalsc/ArsenalSC-Italic.ttf
  ofl/arsenalsc/ArsenalSC-Regular.ttf
  ofl/arsenalsc/DESCRIPTION.en_us.html
  ofl/arsenalsc/METADATA.pb
  ofl/arsenalsc/OFL.txt
  ofl/arsenalsc/config.yaml
Labels: I New Font, II Small Caps

#7770 Anton SC: Version 2.116; ttfautohint (v1.8.4.7-5d5b) added
  ofl/antonsc/AntonSC-Regular.ttf
  ofl/antonsc/DESCRIPTION.en_us.html
  ofl/antonsc/METADATA.pb
  ofl/antonsc/OFL.txt
Labels: I New Font, II Small Caps

#7769 Alumni Sans Collegiate One SC: Version 1.100 added
  ofl/alumnisanscollegiateonesc/AlumniSansCollegiateOneSC-Italic.ttf
  ofl/alumnisanscollegiateonesc/AlumniSansCollegiateOneSC-Regular.ttf
  ofl/alumnisanscollegiateonesc/DESCRIPTION.en_us.html
  ofl/alumnisanscollegiateonesc/METADATA.pb
  ofl/alumnisanscollegiateonesc/OFL.txt
Labels: I New Font, II Small Caps

#7793 Add designer Stefan Schimdt
  catalog/designers/stefanschmidt/bio.html
  catalog/designers/stefanschmidt/info.pb
  catalog/designers/stefanschmidt/stefanschmidt.png
Labels: I Designer profile

#7794 Bungee: Version 2.000 added
  ofl/bungee/Bungee-Regular.ttf
  ofl/bungee/DESCRIPTION.en_us.html
  ofl/bungee/METADATA.pb
  ofl/bungee/OFL.txt
Labels: I Font Upgrade

#7796 Bungee Outline: Version 2.000 added
  ofl/bungeeoutline/BungeeOutline-Regular.ttf
  ofl/bungeeoutline/DESCRIPTION.en_us.html
  ofl/bungeeoutline/METADATA.pb
  ofl/bungeeoutline/OFL.txt
Labels: I Font Upgrade

#7797 Bungee Inline: Version 2.000 added
  ofl/bungeeinline/BungeeInline-Regular.ttf
  ofl/bungeeinline/DESCRIPTION.en_us.html
  ofl/bungeeinline/METADATA.pb
  ofl/bungeeinline/OFL.txt
Labels: I Font Upgrade

#7798 Bungee Shade: Version 2.000 added
  ofl/bungeeshade/BungeeShade-Regular.ttf
  ofl/bungeeshade/DESCRIPTION.en_us.html
  ofl/bungeeshade/METADATA.pb
  ofl/bungeeshade/OFL.txt
Labels: I Font Upgrade

#7732 Playwrite PL: Version 1.002 added
  ofl/playwritepl/METADATA.pb
  ofl/playwritepl/OFL.txt
  ofl/playwritepl/PlaywritePL[wght].ttf
  ofl/playwritepl/article/ARTICLE.en_us.html
  ofl/playwritepl/article/Playwrite-Polska-1.png
  ofl/playwritepl/article/Playwrite-Polska-2.png
  ofl/playwritepl/article/Playwrite-Polska-3.png
Labels: I New Font

#7729 Playwrite NO: Version 1.002 added
  ofl/playwriteno/METADATA.pb
  ofl/playwriteno/OFL.txt
  ofl/playwriteno/PlaywriteNO[wght].ttf
  ofl/playwriteno/article/ARTICLE.en_us.html
  ofl/playwriteno/article/Playwrite-Norge-1.png
  ofl/playwriteno/article/Playwrite-Norge-2.png
  ofl/playwriteno/article/Playwrite-Norge-3.png
Labels: I New Font

#7791 Noto Naskh Arabic: Version 2.019 added
  ofl/notonaskharabic/METADATA.pb
  ofl/notonaskharabic/NotoNaskhArabic[wght].ttf
  ofl/notonaskharabic/article/ARTICLE.en_us.html
Labels: I Font Upgrade

#7728 Playwrite NL: Version 1.002 added
  ofl/playwritenl/METADATA.pb
  ofl/playwritenl/OFL.txt
  ofl/playwritenl/PlaywriteNL[wght].ttf
  ofl/playwritenl/article/ARTICLE.en_us.html
  ofl/playwritenl/article/Playwrite-Netherland-1.png
  ofl/playwritenl/article/Playwrite-Netherland-2.png
  ofl/playwritenl/article/Playwrite-Netherland-3.png
Labels: I New Font

#7799 Bungee Spice: Version 2.000 added
  ofl/bungeespice/BungeeSpice-Regular.ttf
  ofl/bungeespice/DESCRIPTION.en_us.html
  ofl/bungeespice/METADATA.pb
  ofl/bungeespice/OFL.txt
Labels: -- Needs confirmation, I Font Upgrade, II Color font

#7723 Playwrite IS: Version 1.002 added
  ofl/playwriteis/METADATA.pb
  ofl/playwriteis/OFL.txt
  ofl/playwriteis/PlaywriteIS[wght].ttf
  ofl/playwriteis/article/ARTICLE.en_us.html
  ofl/playwriteis/article/Playwrite-Island-1.png
  ofl/playwriteis/article/Playwrite-Island-2.png
  ofl/playwriteis/article/Playwrite-Island-3.png
Labels: I New Font

#7801 Playwrite: subsets deleted on merged fonts
  ofl/playwriteaunsw/METADATA.pb
  ofl/playwriteauqld/METADATA.pb
  ofl/playwriteausa/METADATA.pb
  ofl/playwriteautas/METADATA.pb
  ofl/playwriteauvic/METADATA.pb
  ofl/playwritebr/METADATA.pb
  ofl/playwriteca/METADATA.pb
  ofl/playwriteco/METADATA.pb
  ofl/playwritedegrund/METADATA.pb
  ofl/playwritedela/METADATA.pb
  ofl/playwritedesas/METADATA.pb
  ofl/playwritedeva/METADATA.pb
  ofl/playwritees/METADATA.pb
  ofl/playwriteesdeco/METADATA.pb
  ofl/playwritefrmoderne/METADATA.pb
  ofl/playwritefrtrad/METADATA.pb
  ofl/playwritegbj/METADATA.pb
  ofl/playwritegbs/METADATA.pb
  ofl/playwriteid/METADATA.pb
  ofl/playwriteie/METADATA.pb
  ofl/playwritein/METADATA.pb
  ofl/playwriteis/METADATA.pb
  ofl/playwriteitmoderna/METADATA.pb
  ofl/playwriteittrad/METADATA.pb
  ofl/playwritemx/METADATA.pb
  ofl/playwritengmodern/METADATA.pb
  ofl/playwritenl/METADATA.pb
  ofl/playwriteno/METADATA.pb
  ofl/playwritenz/METADATA.pb
  ofl/playwritepl/METADATA.pb
  ofl/playwritept/METADATA.pb
  ofl/playwritero/METADATA.pb
  ofl/playwritesk/METADATA.pb
  ofl/playwritetz/METADATA.pb
  ofl/playwriteusmodern/METADATA.pb
  ofl/playwriteustrad/METADATA.pb
  ofl/playwritevn/METADATA.pb
  ofl/playwriteza/METADATA.pb
Labels: I Metadata/OFL
