Repository google/fonts, pull requests merged in 2024-07, with the labels that each got.

#7920 Wittgenstein article - updated
  ofl/wittgenstein/article/ARTICLE.en_us.html
Labels: I Article/Description

#7851 Afacad Flux: Version 1.100 added
  ofl/afacadflux/AfacadFlux[slnt,wght].ttf
  ofl/afacadflux/METADATA.pb
  ofl/afacadflux/OFL.txt
  ofl/afacadflux/article/ARTICLE.en_us.html
  ofl/afacadflux/article/afacad_02_promo.png
  ofl/afacadflux/article/afacad_03_kapitael.png
  ofl/afacadflux/article/afacad_04_promo.png
  ofl/afacadflux/article/afacad_flux_01_promo.png
  ofl/afacadflux/article/afacad_flux_04_promo.png
Labels: I New Font

#7934 Jaro: metadatas updated
  ofl/jaro/METADATA.pb
Labels: I Metadata/OFL

#7919 Sixtyfour Convergence: Version 2.001 added
  ofl/sixtyfourconvergence/METADATA.pb
  ofl/sixtyfourconvergence/OFL.txt
  ofl/sixtyfourconvergence/SixtyfourConvergence[BLED,SCAN,XELA,YELA].ttf
  ofl/sixtyfourconvergence/article/ARTICLE.en_us.html
  ofl/sixtyfourconvergence/article/sixtyfour-1.gif
  ofl/sixtyfourconvergence/article/sixtyfour-2.png
Labels: I New Font, II Color font

#7935 Danfo: update article
  ofl/danfo/article/3.1.jpg
Labels: I Article/Description

#7930 Update Boutros fonts credits
  ofl/almarai/METADATA.pb
  ofl/beiruti/METADATA.pb
  ofl/tajawal/METADATA.pb
Labels: I Designer profile, II Accepted, P2

#7942 Anuphan: Version 3.002 added
  ofl/anuphan/Anuphan[wght].ttf
  ofl/anuphan/DESCRIPTION.en_us.html
  ofl/anuphan/METADATA.pb
Labels: I Font Upgrade

#7927 Update installing_and_managing_fonts/content.md for affinity 2.5
  cc-by-sa/knowledge/modules/using_type/lessons/installing_and_managing_fonts/content.md
Labels: I Knowledge

#7875 Matemasie: Version 1.001; ttfautohint (v1.8.4.7-5d5b) added
  ofl/matemasie/METADATA.pb
  ofl/matemasie/Matemasie-Regular.ttf
  ofl/matemasie/OFL.txt
  ofl/matemasie/article/ARTICLE.en_us.html
Labels: -- Needs Upstream Resolution, I New Font

#7936 Moderustic: Version 2.120 added
  ofl/moderustic/DESCRIPTION.en_us.html
  ofl/moderustic/METADATA.pb
  ofl/moderustic/Moderustic[wght].ttf
  ofl/moderustic/OFL.txt
Labels: I New Font

#7952 Bungee Tint: Version 2.001 added
  ofl/bungeetint/BungeeTint-Regular.ttf
  ofl/bungeetint/METADATA.pb
  ofl/bungeetint/OFL.txt
  ofl/bungeetint/article/ARTICLE.en_us.html
  ofl/bungeetint/article/bungee-01-vertical.png
  ofl/bungeetint/article/bungee-02-horizontal.png
  ofl/bungeetint/article/bungee-05-basic-family-c.png
  ofl/bungeetint/article/bungee-07-layers.gif
Labels: I New Font, II Color font

#7924 Add designer: Tural Alisoy
  catalog/designers/turalalisoy/bio.html
  catalog/designers/turalalisoy/info.pb
  catalog/designers/turalalisoy/turalalisoy.png
Labels: I Designer profile

#7970 New Amsterdam: Version 1.000; ttfautohint (v1.8.4.7-5d5b) added
  ofl/newamsterdam/METADATA.pb
  ofl/newamsterdam/NewAmsterdam-Regular.ttf
  ofl/newamsterdam/OFL.txt
  ofl/newamsterdam/article/ARTICLE.en_us.html
  ofl/newamsterdam/article/image1.png
  ofl/newamsterdam/article/image2.png
  ofl/newamsterdam/article/image3.png
Labels: I New Font

#7980 Remove the monospace classification on Wellfleet
  ofl/wellfleet/METADATA.pb
Labels: I Metadata/OFL
