Repository google/fonts, pull requests merged in 2024-10, with the labels that each got.

#8208 Matemasie: Update article
  ofl/matemasie/METADATA.pb
  ofl/matemasie/article/1.png
  ofl/matemasie/article/2.png
  ofl/matemasie/article/3.gif
  ofl/matemasie/article/4.png
  ofl/matemasie/article/ARTICLE.en_us.html
Labels: I Article/Description

#8209 Exo 2: Version 2.010 added
  ofl/exo2/Exo2-Italic[wght].ttf
  ofl/exo2/Exo2[wght].ttf
  ofl/exo2/METADATA.pb
  ofl/exo2/OFL.txt
Labels: I Font Upgrade

#8233 Add Element Type designer
  catalog/designers/elementtype/bio.html
  catalog/designers/elementtype/info.pb
Labels: I Designer profile

#8234 Add designer Ibrahim Kactıoglu
  catalog/designers/ibrahimkactioglu/bio.html
  catalog/designers/ibrahimkactioglu/info.pb
Labels: I Designer profile

#8022 Edu AU VIC WA NT Pre: Version 1.001 added
  ofl/eduauvicwantpre/DESCRIPTION.en_us.html
  ofl/eduauvicwantpre/EduAUVICWANTPre[wght].ttf
  ofl/eduauvicwantpre/METADATA.pb
  ofl/eduauvicwantpre/OFL.txt
Labels: I New Font

#8201 Funnel Display: Version 1.000 added
  ofl/funneldisplay/FunnelDisplay[wght].ttf
  ofl/funneldisplay/METADATA.pb
  ofl/funneldisplay/OFL.txt
  ofl/funneldisplay/article/ARTICLE.en_us.html
  ofl/funneldisplay/article/image1.jpg
  ofl/funneldisplay/article/image2.jpg
  ofl/funneldisplay/article/image3.jpg
Labels: -- Needs Upstream Resolution, I New Font

#8211 Funnel Sans: Version 1.000 added
  ofl/funnelsans/FunnelSans-Italic[wght].ttf
  ofl/funnelsans/FunnelSans[wght].ttf
  ofl/funnelsans/METADATA.pb
  ofl/funnelsans/OFL.txt
  ofl/funnelsans/article/ARTICLE.en_us.html
  ofl/funnelsans/article/image1.jpg
  ofl/funnelsans/article/image2.jpg
Labels: I New Font

#8224 Adds QA updates as agreed upon for tag: Stiff
  tags/all/families.csv
Labels: I API / Website / Platform

#8223 Adds QA updates as agreed upon for tag: Loud
  tags/all/families.csv
Labels: I API / Website / Platform

#8248 Add designer Andrés Briganti
  catalog/designers/andresbriganti/andresbriganti.png
  catalog/designers/andresbriganti/bio.html
  catalog/designers/andresbriganti/info.pb
Labels: I Designer profile

#8254 Add designer José Rago
  catalog/designers/joserago/bio.html
  catalog/designers/joserago/info.pb
  catalog/designers/joserago/joserago.png
Labels: I Designer profile

#8249 Add designer Mateo Zaragoza
  catalog/designers/mateozaragoza/bio.html
  catalog/designers/mateozaragoza/info.pb
  catalog/designers/mateozaragoza/mateozaragoza.png
Labels: I Designer profile

#8255 Facundo Santana designer added
  catalog/designers/facundosantana/bio.html
  catalog/designers/facundosantana/facundosantana.png
  catalog/designers/facundosantana/info.pb
Labels: I Designer profile

#8226 Adds QA updates as agreed upon for tag: Fancy
  tags/all/families.csv
Labels: I API / Website / Platform

#8268 Adds QA updates as agreed upon for tag: Active
  tags/all/families.csv
Labels: I API / Website / Platform

#8270 Adds QA updates as agreed upon for tag: Business
  tags/all/families.csv
Labels: I API / Website / Platform

#8265 Adds QA updates as agreed upon for tag: Sophisticated
  tags/all/families.csv
Labels: I API / Website / Platform

#8227 Adds QA updates as agreed upon for tag: Futuristic
  tags/all/families.csv
Labels: I API / Website / Platform

#8221 Adds QA updates as agreed upon for tag: Playful
  tags/all/families.csv
Labels: I API / Website / Platform

#8225 Adds QA updates as agreed upon for tag: Cute
  tags/all/families.csv
Labels: I API / Website / Platform

#8228 Adds QA updates as agreed upon for tag: Childlike
  tags/all/families.csv
Labels: I API / Website / Platform

#8260 Adds QA updates as agreed upon for tag: Happy
  tags/all/families.csv
Labels: I API / Website / Platform

#8261 Adds QA updates as agreed upon for tag: Artistic
  tags/all/families.csv
Labels: I API / Website / Platform

#8267 Adds QA updates as agreed upon for tag: Awkward
  tags/all/families.csv
Labels: I API / Website / Platform

#8269 Adds QA updates as agreed upon for tag: Innovative
  tags/all/families.csv
Labels: I API / Website / Platform

#8271 Adds QA updates as agreed upon for tag: Calm
  tags/all/families.csv
Labels: I API / Website / Platform

#8273 Exo 2: Version 2.010 added
  ofl/exo2/DESCRIPTION.en_us.html
  ofl/exo2/Exo2-Italic[wght].ttf
  ofl/exo2/Exo2[wght].ttf
  ofl/exo2/METADATA.pb
  ofl/exo2/OFL.txt
Labels: I Font Upgrade

#8263 Update families.csv: Host Grotesk
  tags/all/families.csv
Labels: I API / Website / Platform

#8262 Update families.csv: Geist
  tags/all/families.csv
Labels: I API / Website / Platform

#8297 Update families.csv - Add Hubot Sans
  tags/all/families.csv
Labels: I API / Website / Platform

#8298 Update families.csv - Add Mona Sans
  tags/all/families.csv
Labels: I API / Website / Platform

#8247 Host Grotesk: Version 1.003 added
  ofl/hostgrotesk/HostGrotesk-Italic[wght].ttf
  ofl/hostgrotesk/HostGrotesk[wght].ttf
  ofl/hostgrotesk/METADATA.pb
  ofl/hostgrotesk/OFL.txt
  ofl/hostgrotesk/article/ARTICLE.en_us.html
  ofl/hostgrotesk/article/HostGrotesk-image-2.png
  ofl/hostgrotesk/article/HostGrotesk-image-3.png
  ofl/hostgrotesk/article/HostGrotesk-image-4.png
  ofl/hostgrotesk/article/HostGrotesk-image-5.png
Labels: I New Font

#8293 Afacad Flux: Article update
  ofl/afacadflux/article/ARTICLE.en_us.html
  ofl/afacadflux/article/afacad_02_promo.png
  ofl/afacadflux/article/afacad_03_kapitael.png
  ofl/afacadflux/article/afacad_04_promo.png
  ofl/afacadflux/article/afacad_flux_01_artwork.png
  ofl/afacadflux/article/afacad_flux_01_promo.png
  ofl/afacadflux/article/afacad_flux_02_artwork.png
  ofl/afacadflux/article/afacad_flux_03_artwork.png
  ofl/afacadflux/article/afacad_flux_04_artwork.png
  ofl/afacadflux/article/afacad_flux_04_promo.png
Labels: I Article/Description

#8292 Add designer: Oliver Lalan
  catalog/designers/oliverlalan/bio.html
  catalog/designers/oliverlalan/info.pb
  catalog/designers/oliverlalan/oliverlalan.png
Labels: I Designer profile

#8242 Mona Sans: Version 2.000 added
  ofl/monasans/METADATA.pb
  ofl/monasans/MonaSans-Italic[wdth,wght].ttf
  ofl/monasans/MonaSans[wdth,wght].ttf
  ofl/monasans/article/ARTICLE.en_us.html
Labels: I New Font

#8212 Doto: Version 1.000 added
  ofl/doto/Doto[ROND,wght].ttf
  ofl/doto/METADATA.pb
  ofl/doto/OFL.txt
  ofl/doto/article/ARTICLE.en_us.html
  ofl/doto/article/image1.jpg
  ofl/doto/article/image2.gif
  ofl/doto/article/image3.jpg
Labels: I New Font, P4

#8282 Noto Sans Nandinagari: Version 1.003; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosansnandinagari/METADATA.pb
  ofl/notosansnandinagari/NotoSansNandinagari-Regular.ttf
Labels: I Font Upgrade

#8351 Update families.csv - Faculty Glyphic
  tags/all/families.csv
Labels: I API / Website / Platform

#8344 Faculty Glyphic: Version 1.003; ttfautohint (v1.8.4.7-5d5b) added
  ofl/facultyglyphic/FacultyGlyphic-Regular.ttf
  ofl/facultyglyphic/METADATA.pb
  ofl/facultyglyphic/OFL.txt
  ofl/facultyglyphic/article/ARTICLE.en_us.html
Labels: I New Font

#8352 Designer added: NORD ID
  catalog/designers/nordid/bio.html
  catalog/designers/nordid/info.pb
  catalog/designers/nordid/nordid.png
Labels: I Designer profile

#8281 Montserrat: Version 9.000 added
  ofl/montserrat/METADATA.pb
  ofl/montserrat/Montserrat-Italic[wght].ttf
  ofl/montserrat/Montserrat[wght].ttf
  ofl/montserrat/OFL.txt
Labels: -- Upstream is working on it, I Font Upgrade, P2

#8413 Faculty Glyphic: Version 1.004; ttfautohint (v1.8.4.7-5d5b) added
  ofl/facultyglyphic/FacultyGlyphic-Regular.ttf
  ofl/facultyglyphic/METADATA.pb
Labels: I New Font

#8379 Spectral: Version 2.005; ttfautohint (v1.8.4.7-5d5b) added
  ofl/spectral/DESCRIPTION.en_us.html
  ofl/spectral/METADATA.pb
  ofl/spectral/OFL.txt
  ofl/spectral/Spectral-Bold.ttf
  ofl/spectral/Spectral-BoldItalic.ttf
  ofl/spectral/Spectral-ExtraBold.ttf
  ofl/spectral/Spectral-ExtraBoldItalic.ttf
  ofl/spectral/Spectral-ExtraLight.ttf
  ofl/spectral/Spectral-ExtraLightItalic.ttf
  ofl/spectral/Spectral-Italic.ttf
  ofl/spectral/Spectral-Light.ttf
  ofl/spectral/Spectral-LightItalic.ttf
  ofl/spectral/Spectral-Medium.ttf
  ofl/spectral/Spectral-MediumItalic.ttf
  ofl/spectral/Spectral-Regular.ttf
  ofl/spectral/Spectral-SemiBold.ttf
  ofl/spectral/Spectral-SemiBoldItalic.ttf
  ofl/spectral/article/hero.png
Labels: I Font Upgrade, P1

#8097 Set primary scripts (15/16)
  ofl/notoserifnyiakengpuachuehmong/METADATA.pb
  ofl/nototraditionalnushu/METADATA.pb
  ofl/ntr/METADATA.pb
  ofl/odormeanchey/METADATA.pb
  ofl/palanquin/METADATA.pb
  ofl/palanquindark/METADATA.pb
  ofl/peddana/METADATA.pb
  ofl/phetsarath/METADATA.pb
  ofl/ponnala/METADATA.pb
  ofl/poorstory/METADATA.pb
Labels: I Metadata/OFL

#8264 Geist Mono: Version 1.400 added
  ofl/geistmono/GeistMono[wght].ttf
  ofl/geistmono/METADATA.pb
  ofl/geistmono/OFL.txt
  ofl/geistmono/article/ARTICLE.en_us.html
  ofl/geistmono/article/geist-banner-light.png
Labels: I New Font, II Accepted, P3

#8418 Cyrillic subset delisted from Gesit fonts
  ofl/geist/METADATA.pb
  ofl/geistmono/METADATA.pb
Labels: I Metadata/OFL

#8427 Lists of the 25th of October
  to_production.txt
  to_sandbox.txt
Labels: I Tools / workflow / repo

#8414 Add Koto Studio
  catalog/designers/kotostudio/bio.html
  catalog/designers/kotostudio/info.pb
  catalog/designers/kotostudio/kotostudio.png
Labels: I Designer profile

#8353 Oi: Version 4.000 added
  ofl/oi/METADATA.pb
  ofl/oi/Oi-Regular.ttf
Labels: I Font Upgrade, P4

#8336 Update families.csv - Add Doto
  tags/all/families.csv
Labels: I API / Website / Platform

#8443 Harmattan: Version 4.300 added
  ofl/harmattan/Harmattan-Bold.ttf
  ofl/harmattan/Harmattan-Medium.ttf
  ofl/harmattan/Harmattan-Regular.ttf
  ofl/harmattan/Harmattan-SemiBold.ttf
  ofl/harmattan/METADATA.pb
  ofl/harmattan/OFL.txt
Labels: I Font Upgrade, II Arabic / Hebrew / Semitic / RTL

#8430 Scheherazade New: Version 4.300 added
  ofl/scheherazadenew/METADATA.pb
  ofl/scheherazadenew/OFL.txt
  ofl/scheherazadenew/ScheherazadeNew-Bold.ttf
  ofl/scheherazadenew/ScheherazadeNew-Medium.ttf
  ofl/scheherazadenew/ScheherazadeNew-Regular.ttf
  ofl/scheherazadenew/ScheherazadeNew-SemiBold.ttf
Labels: I Font Upgrade, II Arabic / Hebrew / Semitic / RTL
