Repository google/fonts, pull requests merged in 2024-11, with the labels that each got.

#8447 Faculty Glyphic: update article
  ofl/facultyglyphic/article/ARTICLE.en_us.html
  ofl/facultyglyphic/article/Faculty_Glyphic_01.jpg
  ofl/facultyglyphic/article/Faculty_Glyphic_02.mp4
  ofl/facultyglyphic/article/Faculty_Glyphic_03.jpg
  ofl/facultyglyphic/article/Faculty_Glyphic_04.jpg
Labels: I Article/Description

#8335 Zain: Version 1.51; ttfautohint (v1.8.4) added
  ofl/zain/DESCRIPTION.en_us.html
  ofl/zain/METADATA.pb
  ofl/zain/Zain-Black.ttf
  ofl/zain/Zain-Bold.ttf
  ofl/zain/Zain-ExtraBold.ttf
  ofl/zain/Zain-ExtraLight.ttf
  ofl/zain/Zain-Italic.ttf
  ofl/zain/Zain-Light.ttf
  ofl/zain/Zain-LightItalic.ttf
  ofl/zain/Zain-Regular.ttf
Labels: III Expand styles, I Font Upgrade, P4

#8450 upcycle gd article into choosing_type
  cc-by-sa/knowledge/modules/choosing_type/lessons/choosing_web_fonts_beginners_guide/content.md
  cc-by-sa/knowledge/modules/choosing_type/lessons/choosing_web_fonts_beginners_guide/images/thumbnail.svg
  cc-by-sa/knowledge/modules/choosing_type/lessons/choosing_web_fonts_beginners_guide/images/web-fonts2.mp4
  cc-by-sa/knowledge/modules/choosing_type/lessons/choosing_web_fonts_beginners_guide/images/web-fonts3.mp4
  cc-by-sa/knowledge/modules/choosing_type/lessons/choosing_web_fonts_beginners_guide/images/web-fonts4.mp4
  cc-by-sa/knowledge/modules/choosing_type/lessons/choosing_web_fonts_beginners_guide/images/web-fonts5.mp4
  cc-by-sa/knowledge/modules/choosing_type/lessons/choosing_web_fonts_beginners_guide/lesson.textproto
Labels: I Knowledge

#8452 Lists of the 1st of november
  to_production.txt
  to_sandbox.txt
Labels: I Tools / workflow / repo

#8444 Lateef: Version 4.300 added
  ofl/lateef/Lateef-Bold.ttf
  ofl/lateef/Lateef-ExtraBold.ttf
  ofl/lateef/Lateef-ExtraLight.ttf
  ofl/lateef/Lateef-Light.ttf
  ofl/lateef/Lateef-Medium.ttf
  ofl/lateef/Lateef-Regular.ttf
  ofl/lateef/Lateef-SemiBold.ttf
  ofl/lateef/METADATA.pb
  ofl/lateef/OFL.txt
Labels: I Font Upgrade, II Arabic / Hebrew / Semitic / RTL

#8472 Update families.csv - added Parkinsans
  tags/all/families.csv
Labels: I API / Website / Platform

#8470 Parkinsans: Version 1.000 added
  ofl/parkinsans/METADATA.pb
  ofl/parkinsans/OFL.txt
  ofl/parkinsans/Parkinsans[wght].ttf
  ofl/parkinsans/article/ARTICLE.en_us.html
  ofl/parkinsans/article/Parkinsans_Specimen_01.jpg
  ofl/parkinsans/article/Parkinsans_Specimen_02.jpg
  ofl/parkinsans/article/Parkinsans_Specimen_03.jpg
  ofl/parkinsans/article/Parkinsans_Specimen_04.jpg
  ofl/parkinsans/article/Parkinsans_Specimen_05.jpg
Labels: I New Font

#8319 Edu AU VIC WA NT Arrows: Version 1.001 added
  ofl/eduauvicwantarrows/EduAUVICWANTArrows[wght].ttf
  ofl/eduauvicwantarrows/METADATA.pb
Labels: -- Needs confirmation, I Font Upgrade

#8334 Update /ofl/gupter/DESCRIPTION.en_us.html
  ofl/gupter/DESCRIPTION.en_us.html
Labels: I Article/Description

#8476 Bad Script: Version 2.000; ttfautohint (v1.8.4.7-5d5b) added
  ofl/badscript/BadScript-Regular.ttf
  ofl/badscript/DESCRIPTION.en_us.html
  ofl/badscript/METADATA.pb
  ofl/badscript/OFL.txt
Labels: III Expand glyphset, I Font Upgrade

#8469 Montserrat Underline: Version 9.000 added
  ofl/montserratunderline/DESCRIPTION.en_us.html
  ofl/montserratunderline/METADATA.pb
  ofl/montserratunderline/MontserratUnderline-Italic[wght].ttf
  ofl/montserratunderline/MontserratUnderline[wght].ttf
  ofl/montserratunderline/OFL.txt
Labels: I New Font

#7892 Beiruti: Version 1.10 added
  ofl/beiruti/Beiruti[wght].ttf
  ofl/beiruti/METADATA.pb
Labels: I Font Upgrade, II Accepted, II Arabic / Hebrew / Semitic / RTL

#8492 Add Sebastian Carewe
  catalog/designers/sebastiancarewe/bio.html
  catalog/designers/sebastiancarewe/info.pb
  catalog/designers/sebastiancarewe/sebastiancarewe.png
Labels: I Designer profile

#8494 Add Tobias Bjerrome Ahlin
  catalog/designers/tobiasbjerromeahlin/bio.html
  catalog/designers/tobiasbjerromeahlin/info.pb
  catalog/designers/tobiasbjerromeahlin/tobiasbjerromeahlin.png
Labels: I Designer profile

#8493 Add Degarism Studio
  catalog/designers/degarismstudio/bio.html
  catalog/designers/degarismstudio/degarismstudio.png
  catalog/designers/degarismstudio/info.pb
Labels: I Designer profile

#8489 Mona Sans: Updated metadata (designers)
  ofl/monasans/METADATA.pb
Labels: I Metadata/OFL

#8490 Hubot Sans: update metadata (designers)
  ofl/hubotsans/METADATA.pb
Labels: I Metadata/OFL

#8206 Josefin Slab: Version 2.100 added
  ofl/josefinslab/JosefinSlab-Italic[wght].ttf
  ofl/josefinslab/JosefinSlab[wght].ttf
  ofl/josefinslab/METADATA.pb
Labels: I Font Upgrade, P3

#8509 lang v0.7.1
  lang/Cargo.toml
  lang/Lib/gflanguages/__init__.py
  lang/Lib/gflanguages/data/languages/bap_Krai.textproto
  lang/build.rs
  lang/pyproject.toml
  lang/src/lib.rs
  lang/tests/test_gflanguages_api.py
  lang/tests/test_parsable.py
  lang/tox.ini
Labels: I Lang

#8500 Red Hat Display: Version 1.030 added
  ofl/redhatdisplay/DESCRIPTION.en_us.html
  ofl/redhatdisplay/METADATA.pb
  ofl/redhatdisplay/OFL.txt
  ofl/redhatdisplay/RedHatDisplay-Italic[wght].ttf
  ofl/redhatdisplay/RedHatDisplay[wght].ttf
Labels: I Font Upgrade, P2

#8501 Red Hat Text: Version 1.030 added
  ofl/redhattext/DESCRIPTION.en_us.html
  ofl/redhattext/METADATA.pb
  ofl/redhattext/OFL.txt
  ofl/redhattext/RedHatText-Italic[wght].ttf
  ofl/redhattext/RedHatText[wght].ttf
Labels: I Font Upgrade, P2

#8502 Red Hat Mono: Version 1.030 added
  ofl/redhatmono/DESCRIPTION.en_us.html
  ofl/redhatmono/METADATA.pb
  ofl/redhatmono/OFL.txt
  ofl/redhatmono/RedHatMono-Italic[wght].ttf
  ofl/redhatmono/RedHatMono[wght].ttf
Labels: I Font Upgrade, P2

#8538 Playwrite GB J Guides: Version 1.002 added
  ofl/playwritegbjguides/METADATA.pb
  ofl/playwritegbjguides/OFL.txt
  ofl/playwritegbjguides/PlaywriteGBJGuides-Italic.ttf
  ofl/playwritegbjguides/PlaywriteGBJGuides-Regular.ttf
  ofl/playwritegbjguides/article/ARTICLE.en_us.html
  ofl/playwritegbjguides/article/Playwrite-England-Joined-Guides_1.png
  ofl/playwritegbjguides/article/Playwrite-England-Joined-Guides_2.png
  ofl/playwritegbjguides/article/Playwrite-England-Joined-Guides_3.png
  ofl/playwritegbjguides/article/Playwrite-England-Joined-Guides_4.png
Labels: I New Font, II Commissioned, P1

#8487 Agu Display: Version 1.103 added
  ofl/agudisplay/AguDisplay[MORF].ttf
  ofl/agudisplay/METADATA.pb
  ofl/agudisplay/OFL.txt
  ofl/agudisplay/article/ARTICLE.en_us.html
Labels: I New Font, II Commissioned, II African, II Custom axes, P2

#8604 Playwrite Belgie Models: Diplay name fix
  ofl/playwritebevlg/METADATA.pb
  ofl/playwritebewal/METADATA.pb
Labels: I Metadata/OFL, P2

#8597 Playwrite Guides families tags added
  tags/all/families.csv
Labels: I API / Website / Platform

#8665 Tiny5 Article with images added
  ofl/tiny5/article/ARTICLE.en_us.html
  ofl/tiny5/article/tiny5-presentation.png
  ofl/tiny5/article/tiny5-sample1.png
  ofl/tiny5/article/tiny5-sample2.png
Labels: I Article/Description

#8663 Playwrite GB J Guides: Version 1.003 added
  ofl/playwritegbjguides/METADATA.pb
  ofl/playwritegbjguides/PlaywriteGBJGuides-Italic.ttf
  ofl/playwritegbjguides/PlaywriteGBJGuides-Regular.ttf
  ofl/playwritegbjguides/article/Playwrite-England-Joined-Guides_1.png
  ofl/playwritegbjguides/article/Playwrite-England-Joined-Guides_2.png
  ofl/playwritegbjguides/article/Playwrite-England-Joined-Guides_3.png
  ofl/playwritegbjguides/article/Playwrite-England-Joined-Guides_4.png
Labels: I New Font, II Commissioned, P1

#8661 Playwrite ZA Guides: Version Version 1.003 added
  ofl/playwritezaguides/METADATA.pb
  ofl/playwritezaguides/OFL.txt
  ofl/playwritezaguides/PlaywriteZAGuides-Regular.ttf
  ofl/playwritezaguides/article/ARTICLE.en_us.html
  ofl/playwritezaguides/article/Playwrite-South-Africa-Guides_1.png
  ofl/playwritezaguides/article/Playwrite-South-Africa-Guides_2.png
  ofl/playwritezaguides/article/Playwrite-South-Africa-Guides_3.png
Labels: I New Font, II Commissioned, P1

#8659 Playwrite US Trad Guides: Version Version 1.003 added
  ofl/playwriteustradguides/METADATA.pb
  ofl/playwriteustradguides/OFL.txt
  ofl/playwriteustradguides/PlaywriteUSTradGuides-Regular.ttf
  ofl/playwriteustradguides/article/ARTICLE.en_us.html
  ofl/playwriteustradguides/article/Playwrite-USA-Traditional-Guides_1.png
  ofl/playwriteustradguides/article/Playwrite-USA-Traditional-Guides_2.png
  ofl/playwriteustradguides/article/Playwrite-USA-Traditional-Guides_3.png
Labels: I New Font, II Commissioned, P1

#8657 Playwrite TZ Guides: Version Version 1.003 added
  ofl/playwritetzguides/METADATA.pb
  ofl/playwritetzguides/OFL.txt
  ofl/playwritetzguides/PlaywriteTZGuides-Regular.ttf
  ofl/playwritetzguides/article/ARTICLE.en_us.html
  ofl/playwritetzguides/article/Playwrite-Tanzania-Guides_1.png
  ofl/playwritetzguides/article/Playwrite-Tanzania-Guides_2.png
  ofl/playwritetzguides/article/Playwrite-Tanzania-Guides_3.png
Labels: I New Font, II Commissioned, P1

#8656 Playwrite SK Guides: Version Version 1.003 added
  ofl/playwriteskguides/METADATA.pb
  ofl/playwriteskguides/OFL.txt
  ofl/playwriteskguides/PlaywriteSKGuides-Regular.ttf
  ofl/playwriteskguides/article/ARTICLE.en_us.html
  ofl/playwriteskguides/article/Playwrite-Slovensko-Guides_1.png
  ofl/playwriteskguides/article/Playwrite-Slovensko-Guides_2.png
  ofl/playwriteskguides/article/Playwrite-Slovensko-Guides_3.png
Labels: I New Font, II Commissioned, P1

#8655 Playwrite RO Guides: Version Version 1.003 added
  ofl/playwriteroguides/METADATA.pb
  ofl/playwriteroguides/OFL.txt
  ofl/playwriteroguides/PlaywriteROGuides-Regular.ttf
  ofl/playwriteroguides/article/ARTICLE.en_us.html
  ofl/playwriteroguides/article/Playwrite-Romania-Guides_1.png
  ofl/playwriteroguides/article/Playwrite-Romania-Guides_2.png
  ofl/playwriteroguides/article/Playwrite-Romania-Guides_3.png
Labels: I New Font, II Commissioned, P1

#8654 Playwrite PT Guides: Version Version 1.003 added
  ofl/playwriteptguides/METADATA.pb
  ofl/playwriteptguides/OFL.txt
  ofl/playwriteptguides/PlaywritePTGuides-Regular.ttf
  ofl/playwriteptguides/article/ARTICLE.en_us.html
  ofl/playwriteptguides/article/Playwrite-Portugal-Guides_1.png
  ofl/playwriteptguides/article/Playwrite-Portugal-Guides_2.png
  ofl/playwriteptguides/article/Playwrite-Portugal-Guides_3.png
Labels: I New Font, II Commissioned, P1

#8653 Playwrite PL Guides: Version Version 1.003 added
  ofl/playwriteplguides/METADATA.pb
  ofl/playwriteplguides/OFL.txt
  ofl/playwriteplguides/PlaywritePLGuides-Regular.ttf
  ofl/playwriteplguides/article/ARTICLE.en_us.html
  ofl/playwriteplguides/article/Playwrite-Polska-Guides_1.png
  ofl/playwriteplguides/article/Playwrite-Polska-Guides_2.png
  ofl/playwriteplguides/article/Playwrite-Polska-Guides_3.png
Labels: I New Font, II Commissioned, P1

#8652 Playwrite PE Guides: Version Version 1.003 added
  ofl/playwritepeguides/METADATA.pb
  ofl/playwritepeguides/OFL.txt
  ofl/playwritepeguides/PlaywritePEGuides-Regular.ttf
  ofl/playwritepeguides/article/ARTICLE.en_us.html
  ofl/playwritepeguides/article/Playwrite-Peru-Guides_1.png
  ofl/playwritepeguides/article/Playwrite-Peru-Guides_2.png
  ofl/playwritepeguides/article/Playwrite-Peru-Guides_3.png
Labels: I New Font, II Commissioned, P1

#8651 Playwrite NZ Guides: Version Version 1.003 added
  ofl/playwritenzguides/METADATA.pb
  ofl/playwritenzguides/OFL.txt
  ofl/playwritenzguides/PlaywriteNZGuides-Regular.ttf
  ofl/playwritenzguides/article/ARTICLE.en_us.html
  ofl/playwritenzguides/article/Playwrite-New-Zealand-Guides_1.png
  ofl/playwritenzguides/article/Playwrite-New-Zealand-Guides_2.png
  ofl/playwritenzguides/article/Playwrite-New-Zealand-Guides_3.png
Labels: I New Font, II Commissioned, P1

#8650 Playwrite NO Guides: Version Version 1.003 added
  ofl/playwritenoguides/METADATA.pb
  ofl/playwritenoguides/OFL.txt
  ofl/playwritenoguides/PlaywriteNOGuides-Regular.ttf
  ofl/playwritenoguides/article/ARTICLE.en_us.html
  ofl/playwritenoguides/article/Playwrite-Norge-Guides_1.png
  ofl/playwritenoguides/article/Playwrite-Norge-Guides_2.png
  ofl/playwritenoguides/article/Playwrite-Norge-Guides_3.png
Labels: I New Font, II Commissioned, P1

#8649 Playwrite NL Guides: Version Version 1.003 added
  ofl/playwritenlguides/METADATA.pb
  ofl/playwritenlguides/OFL.txt
  ofl/playwritenlguides/PlaywriteNLGuides-Regular.ttf
  ofl/playwritenlguides/article/ARTICLE.en_us.html
  ofl/playwritenlguides/article/Playwrite-Netherland-Guides_1.png
  ofl/playwritenlguides/article/Playwrite-Netherland-Guides_2.png
  ofl/playwritenlguides/article/Playwrite-Netherland-Guides_3.png
Labels: I New Font, II Commissioned, P1

#8648 Playwrite NG Modern Guides: Version Version 1.003 added
  ofl/playwritengmodernguides/METADATA.pb
  ofl/playwritengmodernguides/OFL.txt
  ofl/playwritengmodernguides/PlaywriteNGModernGuides-Regular.ttf
  ofl/playwritengmodernguides/article/ARTICLE.en_us.html
  ofl/playwritengmodernguides/article/Playwrite-Nigeria-Modern-Guides_1.png
  ofl/playwritengmodernguides/article/Playwrite-Nigeria-Modern-Guides_2.png
  ofl/playwritengmodernguides/article/Playwrite-Nigeria-Modern-Guides_3.png
Labels: I New Font, II Commissioned, P1

#8647 Playwrite MX Guides: Version Version 1.003 added
  ofl/playwritemxguides/METADATA.pb
  ofl/playwritemxguides/OFL.txt
  ofl/playwritemxguides/PlaywriteMXGuides-Regular.ttf
  ofl/playwritemxguides/article/ARTICLE.en_us.html
  ofl/playwritemxguides/article/Playwrite-Mexico-Guides_1.png
  ofl/playwritemxguides/article/Playwrite-Mexico-Guides_2.png
  ofl/playwritemxguides/article/Playwrite-Mexico-Guides_3.png
Labels: I New Font, II Commissioned, P1

#8646 Playwrite IT Trad Guides: Version Version 1.003 added
  ofl/playwriteittradguides/METADATA.pb
  ofl/playwriteittradguides/OFL.txt
  ofl/playwriteittradguides/PlaywriteITTradGuides-Regular.ttf
  ofl/playwriteittradguides/article/ARTICLE.en_us.html
  ofl/playwriteittradguides/article/Playwrite-Italia-Tradizionale-Guides_1.png
  ofl/playwriteittradguides/article/Playwrite-Italia-Tradizionale-Guides_2.png
  ofl/playwriteittradguides/article/Playwrite-Italia-Tradizionale-Guides_3.png
Labels: I New Font, II Commissioned, P1

#8645 Playwrite IT Moderna Guides: Version Version 1.003 added
  ofl/playwriteitmodernaguides/METADATA.pb
  ofl/playwriteitmodernaguides/OFL.txt
  ofl/playwriteitmodernaguides/PlaywriteITModernaGuides-Regular.ttf
  ofl/playwriteitmodernaguides/article/ARTICLE.en_us.html
  ofl/playwriteitmodernaguides/article/Playwrite-Italia-Moderna-Guides_1.png
  ofl/playwriteitmodernaguides/article/Playwrite-Italia-Moderna-Guides_2.png
  ofl/playwriteitmodernaguides/article/Playwrite-Italia-Moderna-Guides_3.png
Labels: I New Font, II Commissioned, P1

#8644 Playwrite IS Guides: Version Version 1.003 added
  ofl/playwriteisguides/METADATA.pb
  ofl/playwriteisguides/OFL.txt
  ofl/playwriteisguides/PlaywriteISGuides-Regular.ttf
  ofl/playwriteisguides/article/ARTICLE.en_us.html
  ofl/playwriteisguides/article/Playwrite-Island-Guides_1.png
  ofl/playwriteisguides/article/Playwrite-Island-Guides_2.png
  ofl/playwriteisguides/article/Playwrite-Island-Guides_3.png
Labels: I New Font, II Commissioned, P1

#8643 Playwrite IN Guides: Version Version 1.003 added
  ofl/playwriteinguides/METADATA.pb
  ofl/playwriteinguides/OFL.txt
  ofl/playwriteinguides/PlaywriteINGuides-Regular.ttf
  ofl/playwriteinguides/article/ARTICLE.en_us.html
  ofl/playwriteinguides/article/Playwrite-India-Guides_1.png
  ofl/playwriteinguides/article/Playwrite-India-Guides_2.png
  ofl/playwriteinguides/article/Playwrite-India-Guides_3.png
Labels: I New Font, II Commissioned, P1

#8642 Playwrite IE Guides: Version Version 1.003 added
  ofl/playwriteieguides/METADATA.pb
  ofl/playwriteieguides/OFL.txt
  ofl/playwriteieguides/PlaywriteIEGuides-Regular.ttf
  ofl/playwriteieguides/article/ARTICLE.en_us.html
  ofl/playwriteieguides/article/Playwrite-Ireland-Guides_1.png
  ofl/playwriteieguides/article/Playwrite-Ireland-Guides_2.png
  ofl/playwriteieguides/article/Playwrite-Ireland-Guides_3.png
Labels: I New Font, II Commissioned, P1

#8641 Playwrite ID Guides: Version Version 1.003 added
  ofl/playwriteidguides/METADATA.pb
  ofl/playwriteidguides/OFL.txt
  ofl/playwriteidguides/PlaywriteIDGuides-Regular.ttf
  ofl/playwriteidguides/article/ARTICLE.en_us.html
  ofl/playwriteidguides/article/Playwrite-Indonesia-Guides_1.png
  ofl/playwriteidguides/article/Playwrite-Indonesia-Guides_2.png
  ofl/playwriteidguides/article/Playwrite-Indonesia-Guides_3.png
Labels: I New Font, II Commissioned, P1

#8640 Playwrite HU Guides: Version Version 1.003 added
  ofl/playwritehuguides/METADATA.pb
  ofl/playwritehuguides/OFL.txt
  ofl/playwritehuguides/PlaywriteHUGuides-Regular.ttf
  ofl/playwritehuguides/article/ARTICLE.en_us.html
  ofl/playwritehuguides/article/Playwrite-Magyarorszag-Guides_1.png
  ofl/playwritehuguides/article/Playwrite-Magyarorszag-Guides_2.png
  ofl/playwritehuguides/article/Playwrite-Magyarorszag-Guides_3.png
Labels: I New Font, II Commissioned, P1

#8639 Playwrite HR Lijeva Guides: Version Version 1.003 added
  ofl/playwritehrlijevaguides/METADATA.pb
  ofl/playwritehrlijevaguides/OFL.txt
  ofl/playwritehrlijevaguides/PlaywriteHRLijevaGuides-Regular.ttf
  ofl/playwritehrlijevaguides/article/ARTICLE.en_us.html
  ofl/playwritehrlijevaguides/article/Playwrite-Hrvatska-Lijeva-Guides_1.png
  ofl/playwritehrlijevaguides/article/Playwrite-Hrvatska-Lijeva-Guides_2.png
  ofl/playwritehrlijevaguides/article/Playwrite-Hrvatska-Lijeva-Guides_3.png
Labels: I New Font, II Commissioned, P1

#8638 Playwrite HR Guides: Version Version 1.003 added
  ofl/playwritehrguides/METADATA.pb
  ofl/playwritehrguides/OFL.txt
  ofl/playwritehrguides/PlaywriteHRGuides-Regular.ttf
  ofl/playwritehrguides/article/ARTICLE.en_us.html
  ofl/playwritehrguides/article/Playwrite-Hrvatska-Guides_1.png
  ofl/playwritehrguides/article/Playwrite-Hrvatska-Guides_2.png
  ofl/playwritehrguides/article/Playwrite-Hrvatska-Guides_3.png
Labels: I New Font, II Commissioned, P1

#8637 Playwrite GB S Guides: Version Version 1.003 added
  ofl/playwritegbsguides/METADATA.pb
  ofl/playwritegbsguides/OFL.txt
  ofl/playwritegbsguides/PlaywriteGBSGuides-Italic.ttf
  ofl/playwritegbsguides/PlaywriteGBSGuides-Regular.ttf
  ofl/playwritegbsguides/article/ARTICLE.en_us.html
  ofl/playwritegbsguides/article/Playwrite-England-SemiJoined-Guides_1.png
  ofl/playwritegbsguides/article/Playwrite-England-SemiJoined-Guides_2.png
  ofl/playwritegbsguides/article/Playwrite-England-SemiJoined-Guides_3.png
  ofl/playwritegbsguides/article/Playwrite-England-SemiJoined-Guides_4.png
Labels: I New Font, II Commissioned, P1

#8636 Playwrite FR Trad Guides: Version Version 1.003 added
  ofl/playwritefrtradguides/METADATA.pb
  ofl/playwritefrtradguides/OFL.txt
  ofl/playwritefrtradguides/PlaywriteFRTradGuides-Regular.ttf
  ofl/playwritefrtradguides/article/ARTICLE.en_us.html
  ofl/playwritefrtradguides/article/Playwrite-France-Traditionnelle-Guides_1.png
  ofl/playwritefrtradguides/article/Playwrite-France-Traditionnelle-Guides_2.png
  ofl/playwritefrtradguides/article/Playwrite-France-Traditionnelle-Guides_3.png
Labels: I New Font, II Commissioned, P1

#8635 Playwrite FR Moderne Guides: Version Version 1.003 added
  ofl/playwritefrmoderneguides/METADATA.pb
  ofl/playwritefrmoderneguides/OFL.txt
  ofl/playwritefrmoderneguides/PlaywriteFRModerneGuides-Regular.ttf
  ofl/playwritefrmoderneguides/article/ARTICLE.en_us.html
  ofl/playwritefrmoderneguides/article/Playwrite-France-Moderne-Guides_1.png
  ofl/playwritefrmoderneguides/article/Playwrite-France-Moderne-Guides_2.png
  ofl/playwritefrmoderneguides/article/Playwrite-France-Moderne-Guides_3.png
Labels: I New Font, II Commissioned, P1

#8634 Playwrite ES Guides: Version Version 1.003 added
  ofl/playwriteesguides/METADATA.pb
  ofl/playwriteesguides/OFL.txt
  ofl/playwriteesguides/PlaywriteESGuides-Regular.ttf
  ofl/playwriteesguides/article/ARTICLE.en_us.html
  ofl/playwriteesguides/article/Playwrite-Espana-Guides_1.png
  ofl/playwriteesguides/article/Playwrite-Espana-Guides_2.png
  ofl/playwriteesguides/article/Playwrite-Espana-Guides_3.png
Labels: I New Font, II Commissioned, P1

#8632 Playwrite DK Uloopet Guides: Version Version 1.003 added
  ofl/playwritedkuloopetguides/METADATA.pb
  ofl/playwritedkuloopetguides/OFL.txt
  ofl/playwritedkuloopetguides/PlaywriteDKUloopetGuides-Regular.ttf
  ofl/playwritedkuloopetguides/article/ARTICLE.en_us.html
  ofl/playwritedkuloopetguides/article/Playwrite-Danmark-Uloopet-Guides_1.png
  ofl/playwritedkuloopetguides/article/Playwrite-Danmark-Uloopet-Guides_2.png
  ofl/playwritedkuloopetguides/article/Playwrite-Danmark-Uloopet-Guides_3.png
Labels: I New Font, II Commissioned, P1

#8631 Playwrite DK Loopet Guides: Version Version 1.003 added
  ofl/playwritedkloopetguides/METADATA.pb
  ofl/playwritedkloopetguides/OFL.txt
  ofl/playwritedkloopetguides/PlaywriteDKLoopetGuides-Regular.ttf
  ofl/playwritedkloopetguides/article/ARTICLE.en_us.html
  ofl/playwritedkloopetguides/article/Playwrite-Danmark-Loopet-Guides_1.png
  ofl/playwritedkloopetguides/article/Playwrite-Danmark-Loopet-Guides_2.png
  ofl/playwritedkloopetguides/article/Playwrite-Danmark-Loopet-Guides_3.png
Labels: I New Font, II Commissioned, P1

#8630 Playwrite DE VA Guides: Version Version 1.003 added
  ofl/playwritedevaguides/METADATA.pb
  ofl/playwritedevaguides/OFL.txt
  ofl/playwritedevaguides/PlaywriteDEVAGuides-Regular.ttf
  ofl/playwritedevaguides/article/ARTICLE.en_us.html
  ofl/playwritedevaguides/article/Playwrite-Deutschland-VA-Guides_1.png
  ofl/playwritedevaguides/article/Playwrite-Deutschland-VA-Guides_2.png
  ofl/playwritedevaguides/article/Playwrite-Deutschland-VA-Guides_3.png
Labels: I New Font, II Commissioned, P1

#8629 Playwrite DE SAS Guides: Version Version 1.003 added
  ofl/playwritedesasguides/METADATA.pb
  ofl/playwritedesasguides/OFL.txt
  ofl/playwritedesasguides/PlaywriteDESASGuides-Regular.ttf
  ofl/playwritedesasguides/article/ARTICLE.en_us.html
  ofl/playwritedesasguides/article/Playwrite-Deutschland-SAS-Guides_1.png
  ofl/playwritedesasguides/article/Playwrite-Deutschland-SAS-Guides_2.png
  ofl/playwritedesasguides/article/Playwrite-Deutschland-SAS-Guides_3.png
Labels: I New Font, II Commissioned, P1

#8627 Playwrite DE Grund Guides: Version Version 1.003 added
  ofl/playwritedegrundguides/METADATA.pb
  ofl/playwritedegrundguides/OFL.txt
  ofl/playwritedegrundguides/PlaywriteDEGrundGuides-Regular.ttf
  ofl/playwritedegrundguides/article/ARTICLE.en_us.html
  ofl/playwritedegrundguides/article/Playwrite-Deutschland-Grundschrift-Guides_1.png
  ofl/playwritedegrundguides/article/Playwrite-Deutschland-Grundschrift-Guides_2.png
  ofl/playwritedegrundguides/article/Playwrite-Deutschland-Grundschrift-Guides_3.png
Labels: I New Font, II Commissioned, P1

#8626 Playwrite CZ Guides: Version Version 1.003 added
  ofl/playwriteczguides/METADATA.pb
  ofl/playwriteczguides/OFL.txt
  ofl/playwriteczguides/PlaywriteCZGuides-Regular.ttf
  ofl/playwriteczguides/article/ARTICLE.en_us.html
  ofl/playwriteczguides/article/Playwrite-Cesko-Guides_1.png
  ofl/playwriteczguides/article/Playwrite-Cesko-Guides_2.png
  ofl/playwriteczguides/article/Playwrite-Cesko-Guides_3.png
Labels: I New Font, II Commissioned, P1

#8625 Playwrite CU Guides: Version Version 1.003 added
  ofl/playwritecuguides/METADATA.pb
  ofl/playwritecuguides/OFL.txt
  ofl/playwritecuguides/PlaywriteCUGuides-Regular.ttf
  ofl/playwritecuguides/article/ARTICLE.en_us.html
  ofl/playwritecuguides/article/Playwrite-Cuba-Guides_1.png
  ofl/playwritecuguides/article/Playwrite-Cuba-Guides_2.png
  ofl/playwritecuguides/article/Playwrite-Cuba-Guides_3.png
Labels: I New Font, II Commissioned, P1

#8624 Playwrite CL Guides: Version Version 1.003 added
  ofl/playwriteclguides/METADATA.pb
  ofl/playwriteclguides/OFL.txt
  ofl/playwriteclguides/PlaywriteCLGuides-Regular.ttf
  ofl/playwriteclguides/article/ARTICLE.en_us.html
  ofl/playwriteclguides/article/Playwrite-Chile-Guides_1.png
  ofl/playwriteclguides/article/Playwrite-Chile-Guides_2.png
  ofl/playwriteclguides/article/Playwrite-Chile-Guides_3.png
Labels: I New Font, II Commissioned, P1

#8623 Playwrite CA Guides: Version Version 1.003 added
  ofl/playwritecaguides/METADATA.pb
  ofl/playwritecaguides/OFL.txt
  ofl/playwritecaguides/PlaywriteCAGuides-Regular.ttf
  ofl/playwritecaguides/article/ARTICLE.en_us.html
  ofl/playwritecaguides/article/Playwrite-Canada-Guides_1.png
  ofl/playwritecaguides/article/Playwrite-Canada-Guides_2.png
  ofl/playwritecaguides/article/Playwrite-Canada-Guides_3.png
Labels: I New Font, II Commissioned, P1

#8622 Playwrite BR Guides: Version Version 1.003 added
  ofl/playwritebrguides/METADATA.pb
  ofl/playwritebrguides/OFL.txt
  ofl/playwritebrguides/PlaywriteBRGuides-Regular.ttf
  ofl/playwritebrguides/article/ARTICLE.en_us.html
  ofl/playwritebrguides/article/Playwrite-Brasil-Guides_1.png
  ofl/playwritebrguides/article/Playwrite-Brasil-Guides_2.png
  ofl/playwritebrguides/article/Playwrite-Brasil-Guides_3.png
Labels: I New Font, II Commissioned, P1

#8621 Playwrite BE WAL Guides: Version Version 1.003 added
  ofl/playwritebewalguides/METADATA.pb
  ofl/playwritebewalguides/OFL.txt
  ofl/playwritebewalguides/PlaywriteBEWALGuides-Regular.ttf
  ofl/playwritebewalguides/article/ARTICLE.en_us.html
  ofl/playwritebewalguides/article/Playwrite-Belgique-Wallonie-Bruxelles-Guides_1.png
  ofl/playwritebewalguides/article/Playwrite-Belgique-Wallonie-Bruxelles-Guides_2.png
  ofl/playwritebewalguides/article/Playwrite-Belgique-Wallonie-Bruxelles-Guides_3.png
Labels: I New Font, II Commissioned, P1

#8620 Playwrite BE VLG Guides: Version Version 1.003 added
  ofl/playwritebevlgguides/METADATA.pb
  ofl/playwritebevlgguides/OFL.txt
  ofl/playwritebevlgguides/PlaywriteBEVLGGuides-Regular.ttf
  ofl/playwritebevlgguides/article/ARTICLE.en_us.html
  ofl/playwritebevlgguides/article/Playwrite-Belgie-Vlaanderen-Guides_1.png
  ofl/playwritebevlgguides/article/Playwrite-Belgie-Vlaanderen-Guides_2.png
  ofl/playwritebevlgguides/article/Playwrite-Belgie-Vlaanderen-Guides_3.png
Labels: I New Font, II Commissioned, P1

#8619 Playwrite AU VIC Guides: Version Version 1.003 added
  ofl/playwriteauvicguides/METADATA.pb
  ofl/playwriteauvicguides/OFL.txt
  ofl/playwriteauvicguides/PlaywriteAUVICGuides-Regular.ttf
  ofl/playwriteauvicguides/article/ARTICLE.en_us.html
  ofl/playwriteauvicguides/article/Playwrite-Australia-VIC-Guides_1.png
  ofl/playwriteauvicguides/article/Playwrite-Australia-VIC-Guides_2.png
  ofl/playwriteauvicguides/article/Playwrite-Australia-VIC-Guides_3.png
Labels: I New Font, II Commissioned, P1

#8618 Playwrite AU TAS Guides: Version Version 1.003 added
  ofl/playwriteautasguides/METADATA.pb
  ofl/playwriteautasguides/OFL.txt
  ofl/playwriteautasguides/PlaywriteAUTASGuides-Regular.ttf
  ofl/playwriteautasguides/article/ARTICLE.en_us.html
  ofl/playwriteautasguides/article/Playwrite-Australia-TAS-Guides_1.png
  ofl/playwriteautasguides/article/Playwrite-Australia-TAS-Guides_2.png
  ofl/playwriteautasguides/article/Playwrite-Australia-TAS-Guides_3.png
Labels: I New Font, II Commissioned, P1

#8616 Playwrite AU QLD Guides: Version Version 1.003 added
  ofl/playwriteauqldguides/METADATA.pb
  ofl/playwriteauqldguides/OFL.txt
  ofl/playwriteauqldguides/PlaywriteAUQLDGuides-Regular.ttf
  ofl/playwriteauqldguides/article/ARTICLE.en_us.html
  ofl/playwriteauqldguides/article/Playwrite-Australia-QLD-Guides_1.png
  ofl/playwriteauqldguides/article/Playwrite-Australia-QLD-Guides_2.png
  ofl/playwriteauqldguides/article/Playwrite-Australia-QLD-Guides_3.png
Labels: I New Font, II Commissioned, P1

#8615 Playwrite AU NSW Guides: Version Version 1.003 added
  ofl/playwriteaunswguides/METADATA.pb
  ofl/playwriteaunswguides/OFL.txt
  ofl/playwriteaunswguides/PlaywriteAUNSWGuides-Regular.ttf
  ofl/playwriteaunswguides/article/ARTICLE.en_us.html
  ofl/playwriteaunswguides/article/Playwrite-Australia-NSW-Guides_1.png
  ofl/playwriteaunswguides/article/Playwrite-Australia-NSW-Guides_2.png
  ofl/playwriteaunswguides/article/Playwrite-Australia-NSW-Guides_3.png
Labels: I New Font, II Commissioned, P1

#8614 Playwrite AT Guides: Version Version 1.003 added
  ofl/playwriteatguides/METADATA.pb
  ofl/playwriteatguides/OFL.txt
  ofl/playwriteatguides/PlaywriteATGuides-Italic.ttf
  ofl/playwriteatguides/PlaywriteATGuides-Regular.ttf
  ofl/playwriteatguides/article/ARTICLE.en_us.html
  ofl/playwriteatguides/article/Playwrite-Osterreich-Guides_1.png
  ofl/playwriteatguides/article/Playwrite-Osterreich-Guides_2.png
  ofl/playwriteatguides/article/Playwrite-Osterreich-Guides_3.png
  ofl/playwriteatguides/article/Playwrite-Osterreich-Guides_4.png
Labels: I New Font, II Commissioned, P1

#8669 Playwrite CO Guides: Version 1.003 added
  ofl/playwritecoguides/METADATA.pb
  ofl/playwritecoguides/OFL.txt
  ofl/playwritecoguides/PlaywriteCOGuides-Regular.ttf
  ofl/playwritecoguides/article/ARTICLE.en_us.html
  ofl/playwritecoguides/article/Playwrite-Colombia-Guides_1.png
  ofl/playwritecoguides/article/Playwrite-Colombia-Guides_2.png
  ofl/playwritecoguides/article/Playwrite-Colombia-Guides_3.png
Labels: I New Font, II Commissioned, P1

#8668 TypeTogether profile pic updated
  catalog/designers/typetogether/info.pb
  catalog/designers/typetogether/type_together.png
  catalog/designers/typetogether/typetogether.png
Labels: I Designer profile
