Repository google/fonts, pull requests merged in 2024-08, with the labels that each got.

#7989 Matemasie description
  ofl/matemasie/OFL.txt
  ofl/matemasie/article/ARTICLE.en_us.html
Labels: I Article/Description, I Metadata/OFL

#7969 Add designer: Vladimir Nikolic
  catalog/designers/vladimirnikolic/bio.html
  catalog/designers/vladimirnikolic/info.pb
  catalog/designers/vladimirnikolic/vladimirnikolic.png
Labels: I Designer profile

#7988 Cutive: Version 1.110; ttfautohint (v1.8.4.7-5d5b) added
  ofl/cutive/Cutive-Regular.ttf
  ofl/cutive/DESCRIPTION.en_us.html
  ofl/cutive/METADATA.pb
Labels: I Font Upgrade

#7991 To_lists of the 02nd of August
  to_production.txt
  to_sandbox.txt
Labels: I Tools / workflow / repo

#8002 Lists of the 8th of August
  to_production.txt
  to_sandbox.txt
Labels: I Tools / workflow / repo

#7918 [Knowledge] `sizecalc.com` broken link deleted
  cc-by-sa/knowledge/modules/using_type/lessons/the_complications_of_typographic_size/content.md
Labels: -- Needs confirmation

#7447 Edu VIC WA NT Arrows: Version 1.000 added
  ofl/eduauvicwantarrows/DESCRIPTION.en_us.html
  ofl/eduauvicwantarrows/EduAUVICWANTArrows[wght].ttf
  ofl/eduauvicwantarrows/METADATA.pb
  ofl/eduauvicwantarrows/OFL.txt
Labels: I New Font

#7992 Update tiny5/METADATA.pb
  ofl/tiny5/METADATA.pb
Labels: I Metadata/OFL

#8035 Add designer: Adam Yeo
  catalog/designers/adamyeo/adamyeo.png
  catalog/designers/adamyeo/bio.html
  catalog/designers/adamyeo/info.pb
Labels: I Designer profile

#8005 Add designer: Batsirai Madzonga
  catalog/designers/batsiraimadzonga/batsiraimadzonga.png
  catalog/designers/batsiraimadzonga/bio.html
  catalog/designers/batsiraimadzonga/info.pb
Labels: I Designer profile

#8013 Add sample text for Hentaigana
  ofl/notoserifhentaigana/METADATA.pb
Labels: I Lang, I Metadata/OFL

#8043 `families.csv` adding families
  tags/all/families.csv
Labels: I API / Website / Platform

#8044 SUSE: Version 1.000 added
  ofl/suse/METADATA.pb
  ofl/suse/OFL.txt
  ofl/suse/SUSE[wght].ttf
  ofl/suse/article/ARTICLE.en_us.html
  ofl/suse/article/Google-Fonts-SUSE-Specimen-01.svg
  ofl/suse/article/Google-Fonts-SUSE-Specimen-02.svg
  ofl/suse/article/Google-Fonts-SUSE-Specimen-03.svg
  ofl/suse/article/Google-Fonts-SUSE-Specimen-04.svg
Labels: I New Font, P2

#8045 Add designer: René Bieder
  catalog/designers/renebieder/bio.html
  catalog/designers/renebieder/info.pb
  catalog/designers/renebieder/renebieder.png
Labels: I Designer profile

#8046 SUSE: designer typo fix
  ofl/suse/METADATA.pb
Labels: I Metadata/OFL

#8063 Update fasthand, taprom and seaweedscript credits
  ofl/fasthand/DESCRIPTION.en_us.html
  ofl/fasthand/METADATA.pb
  ofl/seaweedscript/DESCRIPTION.en_us.html
  ofl/taprom/DESCRIPTION.en_us.html
  ofl/taprom/METADATA.pb
Labels: I Article/Description, I Metadata/OFL, P3

#8021 Edu AU VIC WA NT Guides: Version 1.001 added
  ofl/eduauvicwantguides/DESCRIPTION.en_us.html
  ofl/eduauvicwantguides/EduAUVICWANTGuides[wght].ttf
  ofl/eduauvicwantguides/METADATA.pb
  ofl/eduauvicwantguides/OFL.txt
Labels: I New Font

#8020 Edu AU VIC WA NT Dots: Version 1.001 added
  ofl/eduauvicwantdots/DESCRIPTION.en_us.html
  ofl/eduauvicwantdots/EduAUVICWANTDots[wght].ttf
  ofl/eduauvicwantdots/METADATA.pb
  ofl/eduauvicwantdots/OFL.txt
Labels: I New Font

#8070 Edu AU VIC WA NT Arrows display_name fix
  ofl/eduauvicwantarrows/METADATA.pb
Labels: I Metadata/OFL

#8071 families.csv: Edu AU VIC WA NT families tagging added
  tags/all/families.csv
Labels: I API / Website / Platform

#7964 Noto Sans Mongolian: Version 3.002; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosansmongolian/METADATA.pb
  ofl/notosansmongolian/NotoSansMongolian-Regular.ttf
  ofl/notosansmongolian/article/ARTICLE.en_us.html
Labels: I Font Upgrade

#7849 Noto Serif Old Uyghur: Version 1.004; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notoserifolduyghur/METADATA.pb
  ofl/notoserifolduyghur/NotoSerifOldUyghur-Regular.ttf
  ofl/notoserifolduyghur/OFL.txt
Labels: I Font Upgrade

#8077 tags: Remove families not in dev or upcoming in the pipeline
  tags/all/families.csv
Labels: I API / Website / Platform
