Repository google/fonts, pull requests merged in 2024-04, with the labels that each got.

#6407 Noto Sans Canadian Aboriginal: Version 2.003 added
  ofl/notosanscanadianaboriginal/METADATA.pb
  ofl/notosanscanadianaboriginal/NotoSansCanadianAboriginal[wght].ttf
  ofl/notosanscanadianaboriginal/upstream.yaml
Labels: I Font Upgrade

#7516 Playwrite VN: Version 1.000 added
  ofl/playwritevn/DESCRIPTION.en_us.html
  ofl/playwritevn/METADATA.pb
  ofl/playwritevn/OFL.txt
  ofl/playwritevn/PlaywriteVN[wght].ttf
Labels: I New Font

#7501 Lists of the 29th of March
  to_production.txt
  to_sandbox.txt
Labels: I Tools / workflow / repo

#7410 Edu NSW ACT Cursive: Version 2.000 added
  ofl/edunswactcursive/DESCRIPTION.en_us.html
  ofl/edunswactcursive/EduNSWACTCursive[wght].ttf
  ofl/edunswactcursive/METADATA.pb
  ofl/edunswactcursive/OFL.txt
Labels: I New Font

#7415 Edu NSW ACT Hand Pre: Version 2.000 added
  ofl/edunswacthandpre/DESCRIPTION.en_us.html
  ofl/edunswacthandpre/EduNSWACTHandPre[wght].ttf
  ofl/edunswacthandpre/METADATA.pb
  ofl/edunswacthandpre/OFL.txt
Labels: I New Font

#7208 Jaini: Version 2.000; ttfautohint (v1.8.4.7-5d5b) added
  ofl/jaini/DESCRIPTION.en_us.html
  ofl/jaini/Jaini-Regular.ttf
  ofl/jaini/METADATA.pb
  ofl/jaini/OFL.txt
Labels: I New Font, II Indic / Brahmic / Thai / Tai

#7209 Jaini Purva: Version 2.000; ttfautohint (v1.8.4.7-5d5b) added
  ofl/jainipurva/DESCRIPTION.en_us.html
  ofl/jainipurva/JainiPurva-Regular.ttf
  ofl/jainipurva/METADATA.pb
  ofl/jainipurva/OFL.txt
Labels: I New Font, II Commissioned, II Indic / Brahmic / Thai / Tai

#7453 Edu VIC WA NT Hand Pre: Version 1.000 added
  ofl/eduvicwanthandpre/DESCRIPTION.en_us.html
  ofl/eduvicwanthandpre/EduVICWANTHandPre[wght].ttf
  ofl/eduvicwanthandpre/METADATA.pb
  ofl/eduvicwanthandpre/OFL.txt
Labels: I New Font

#7452 Edu VIC WA NT Guide: Version 1.000 added
  ofl/eduvicwantguide/DESCRIPTION.en_us.html
  ofl/eduvicwantguide/EduVICWANTGuide[wght].ttf
  ofl/eduvicwantguide/METADATA.pb
  ofl/eduvicwantguide/OFL.txt
Labels: -- Needs confirmation, I New Font

#7456 Edu VIC WA NT Pre Guide: Version 1.000 added
  ofl/eduvicwantpreguide/DESCRIPTION.en_us.html
  ofl/eduvicwantpreguide/EduVICWANTPreGuide[wght].ttf
  ofl/eduvicwantpreguide/METADATA.pb
  ofl/eduvicwantpreguide/OFL.txt
Labels: I New Font

#7524 Add designer: Étienne Aubert Bonn
  catalog/designers/etienneaubertbonn/bio.html
  catalog/designers/etienneaubertbonn/etienneaubertbonn.png
  catalog/designers/etienneaubertbonn/info.pb
Labels: I Designer profile

#7513 Bubber One hotfixes
  ofl/bubblerone/BubblerOne-Regular.ttf
Labels: I Font Bug

#7500 Description Sedan SC
  ofl/sedansc/DESCRIPTION.en_us.html
Labels: I Description/Metadata/OFL

#7522 Hotfix fi and fj for ElsieSwashCaps-Regular.ttf
  ofl/elsieswashcaps/ElsieSwashCaps-Black.ttf
  ofl/elsieswashcaps/ElsieSwashCaps-Regular.ttf
Labels: I Font Bug

#7525 Jacquard 24 Charted: Version 1.001 added
  ofl/jacquard24charted/DESCRIPTION.en_us.html
  ofl/jacquard24charted/Jacquard24Charted-Regular.ttf
  ofl/jacquard24charted/METADATA.pb
Labels: I New Font

#7530 Add mina upstream details
  ofl/mina/METADATA.pb
Labels: I Description/Metadata/OFL

#7538 Update ofl/kodemono/METADATA.pb with minisite_url
  ofl/kodemono/METADATA.pb
Labels: I Description/Metadata/OFL

#7535 Update Orbitron upstream information
  ofl/orbitron/METADATA.pb
Labels: I Description/Article/Metadata/OFL

#7539 Kalnia Glaze: Version 1.107 added
  ofl/kalniaglaze/DESCRIPTION.en_us.html
  ofl/kalniaglaze/KalniaGlaze[wdth,wght].ttf
  ofl/kalniaglaze/METADATA.pb
  ofl/kalniaglaze/OFL.txt
  ofl/kalniaglaze/article/ARTICLE.en_us.html
  ofl/kalniaglaze/article/Kalnia-Glaze-FridaMedrano-GF-01.png
  ofl/kalniaglaze/article/Kalnia-Glaze-FridaMedrano-GF-02.png
  ofl/kalniaglaze/article/Kalnia-Glaze-FridaMedrano-GF-03.png
  ofl/kalniaglaze/article/Kalnia-Glaze-FridaMedrano-GF-04.png
Labels: I New Font, II Color font

#7378 Tac One article
  ofl/tacone/DESCRIPTION.en_us.html
  ofl/tacone/article/1.mp4
  ofl/tacone/article/2.1.jpg
  ofl/tacone/article/2.2.mp4
  ofl/tacone/article/2.3.mp4
  ofl/tacone/article/2.4.jpg
  ofl/tacone/article/3.1.mp4
  ofl/tacone/article/3.2.jpg
  ofl/tacone/article/3.3.jpg
  ofl/tacone/article/3.4.jpg
  ofl/tacone/article/ARTICLE.en_us.html
Labels: -- Needs Upstream Resolution, I Description/Article/Metadata/OFL

#7547 Update Buenard font designer credit
  catalog/designers/gustavoibarra/bio.html
  catalog/designers/gustavoibarra/gustavo_ibarra.png
  catalog/designers/gustavoibarra/gustavoibarra.png
  catalog/designers/gustavoibarra/info.pb
  ofl/buenard/METADATA.pb
Labels: I Designer profile

#7559 Don't use Sanskrit language for Sundanese
  ofl/notosanssundanese/METADATA.pb
Labels: z_Noto, I Description/Article/Metadata/OFL

#7548 Freeman: Version 1.000; ttfautohint (v1.8.4.7-5d5b) added
  ofl/freeman/DESCRIPTION.en_us.html
  ofl/freeman/Freeman-Regular.ttf
  ofl/freeman/METADATA.pb
  ofl/freeman/OFL.txt
Labels: I New Font, II African

#7563 Tac One Article: update <img> to <video> for mp4 formats
  ofl/tacone/article/ARTICLE.en_us.html
Labels: I Description/Article/Metadata/OFL

#7562 Radio Canada Big: Version 1.001 added
  ofl/radiocanadabig/DESCRIPTION.en_us.html
  ofl/radiocanadabig/METADATA.pb
  ofl/radiocanadabig/OFL.txt
  ofl/radiocanadabig/RadioCanadaBig-Italic[wght].ttf
  ofl/radiocanadabig/RadioCanadaBig[wght].ttf
Labels: I New Font

#7556 Noto Sans Egyptian Hieroglyphs: Version 2.002; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosansegyptianhieroglyphs/METADATA.pb
  ofl/notosansegyptianhieroglyphs/NotoSansEgyptianHieroglyphs-Regular.ttf
Labels: I Font Upgrade

#7576 Update ofl/tacone/article/ARTICLE.en_us.html
  ofl/tacone/article/ARTICLE.en_us.html
Labels: I Description/Article/Metadata/OFL

#7579 Add-Font template update
  .github/ISSUE_TEMPLATE/1_add-font.md
Labels: I Tools / workflow / repo

#7569 Anaheim: Version 2.001 added
  ofl/anaheim/Anaheim-Regular.ttf
  ofl/anaheim/Anaheim[wght].ttf
  ofl/anaheim/DESCRIPTION.en_us.html
  ofl/anaheim/METADATA.pb
  ofl/anaheim/OFL.txt
Labels: III VF Replacement, I Font Upgrade

#7590 Noto Rashi Hebrew: Version 1.007 added
  ofl/notorashihebrew/DESCRIPTION.en_us.html
  ofl/notorashihebrew/METADATA.pb
  ofl/notorashihebrew/NotoRashiHebrew[wght].ttf
Labels: I Font Upgrade

#7589 Noto Serif Hebrew: Version 2.004 added
  ofl/notoserifhebrew/DESCRIPTION.en_us.html
  ofl/notoserifhebrew/METADATA.pb
  ofl/notoserifhebrew/NotoSerifHebrew[wdth,wght].ttf
Labels: I Font Upgrade

#7580 Damion: Version 1.100; ttfautohint (v1.8.4.7-5d5b) added
  ofl/damion/DESCRIPTION.en_us.html
  ofl/damion/Damion-Regular.ttf
  ofl/damion/METADATA.pb
  ofl/damion/OFL.txt
Labels: III Expand glyphset, I Font Upgrade

#7543 Voltaire: Version 1.009; ttfautohint (v1.8.4.7-5d5b) added
  ofl/voltaire/DESCRIPTION.en_us.html
  ofl/voltaire/METADATA.pb
  ofl/voltaire/OFL.txt
  ofl/voltaire/Voltaire-Regular.ttf
Labels: III Expand glyphset, I Font Upgrade, II African

#7571 Add articles
  ofl/gabarito/DESCRIPTION.en_us.html
  ofl/gabarito/article/ARTICLE.en_us.html
  ofl/gabarito/article/Image1.jpg
  ofl/gabarito/article/Image2.jpg
  ofl/gabarito/article/Image3.jpg
  ofl/gabarito/article/Image4.jpg
  ofl/gabarito/article/Image5.jpg
  ofl/gabarito/article/Image6.jpg
  ofl/platypi/DESCRIPTION.en_us.html
  ofl/platypi/article/1.png
  ofl/platypi/article/2.png
  ofl/platypi/article/3.png
  ofl/platypi/article/4.png
  ofl/platypi/article/5.png
  ofl/platypi/article/6.png
  ofl/platypi/article/ARTICLE.en_us.html
  ofl/rethinksans/DESCRIPTION.en_us.html
  ofl/rethinksans/article/ARTICLE.en_us.html
  ofl/rethinksans/article/RethinkSans-01.png
  ofl/rethinksans/article/RethinkSans-02.png
  ofl/rethinksans/article/RethinkSans-03.png
  ofl/rethinksans/article/RethinkSans-04.png
  ofl/rethinksans/article/RethinkSans-05.png
  ofl/rethinksans/article/RethinkSans-06.png
  ofl/rethinksans/article/RethinkSans-07.png
  ofl/rethinksans/article/RethinkSans-08.png
  ofl/rethinksans/article/RethinkSans-09.png
  ofl/rethinksans/article/RethinkSans-10.png
  ofl/rethinksans/article/RethinkSans-11.png
  ofl/rethinksans/article/RethinkSans-12.png
  ofl/rethinksans/article/RethinkSans-13.png
  ofl/teachers/DESCRIPTION.en_us.html
  ofl/teachers/article/1.png
  ofl/teachers/article/2.png
  ofl/teachers/article/3.png
  ofl/teachers/article/4.png
  ofl/teachers/article/ARTICLE.en_us.html
Labels: I Description/Article/Metadata/OFL

#7601 Designer added: Agyei Archer
  catalog/designers/agyeiarcher/agyeiarcher.png
  catalog/designers/agyeiarcher/bio.html
  catalog/designers/agyeiarcher/info.pb
Labels: I Designer profile

#7599 Holtwood One SC: Version 1.100; ttfautohint (v1.8.4.7-5d5b) added
  ofl/holtwoodonesc/DESCRIPTION.en_us.html
  ofl/holtwoodonesc/HoltwoodOneSC-Regular.ttf
  ofl/holtwoodonesc/HoltwoodOneSC.ttf
  ofl/holtwoodonesc/METADATA.pb
  ofl/holtwoodonesc/OFL.txt
Labels: III Expand glyphset, I Font Upgrade

#7549 Monda: Version 2.200 added
  ofl/monda/DESCRIPTION.en_us.html
  ofl/monda/METADATA.pb
  ofl/monda/Monda-Bold.ttf
  ofl/monda/Monda-Regular.ttf
  ofl/monda/Monda[wght].ttf
  ofl/monda/OFL.txt
Labels: -- Needs confirmation, III VF Replacement, I Font Upgrade

#7567 Calistoga: Version 1.010; ttfautohint (v1.8.4.7-5d5b) added
  ofl/calistoga/Calistoga-Regular.ttf
  ofl/calistoga/DESCRIPTION.en_us.html
  ofl/calistoga/METADATA.pb
  ofl/calistoga/OFL.txt
Labels: III Expand glyphset, I Font Upgrade, II Commissioned, II African

#7588 Noto Sans Hebrew: Version 2.004 added
  ofl/notosanshebrew/DESCRIPTION.en_us.html
  ofl/notosanshebrew/METADATA.pb
  ofl/notosanshebrew/NotoSansHebrew[wdth,wght].ttf
Labels: I Font Upgrade
