Repository google/fonts, pull requests merged in 2024-02, with the labels that each got.

#7136 Gftools packager ofl kodemono
  ofl/kodemono/DESCRIPTION.en_us.html
  ofl/kodemono/KodeMono[wght].ttf
  ofl/kodemono/METADATA.pb
  ofl/kodemono/OFL.txt
  ofl/kodemono/upstream.yaml
Labels: -- Needs confirmation, I New Font

#7248 Lang v0517
  lang/Lib/gflanguages/data/languages/sa_Sylo.textproto
Labels: I Lang

#7249 Updated lists 02nd of February
  to_delist.txt
  to_production.txt
  to_sandbox.txt
Labels: I Tools / workflow / repo

#7242 Jacquarda Bastarda 9 description updated
  ofl/jacquardabastarda9/DESCRIPTION.en_us.html
Labels: I Description/Metadata/OFL

#7240 Designer added: Isa Ozler
  catalog/designers/isaozler/bio.html
  catalog/designers/isaozler/info.pb
  catalog/designers/isaozler/isaozler.png
Labels: I Designer profile

#7265 Add designer: Chisaokwu Joboson
  catalog/designers/chisaokwujoboson/bio.html
  catalog/designers/chisaokwujoboson/chisaokwujoboson.png
  catalog/designers/chisaokwujoboson/info.pb
Labels: I Designer profile

#7268 Update ofl/climatecrisis/METADATA.pb minisite URL bugs
  ofl/climatecrisis/METADATA.pb
Labels: I Description/Metadata/OFL, I Small Fix

#7231 Roboto: Version 3.009; 2024 added
  ofl/roboto/METADATA.pb
  ofl/roboto/OFL.txt
  ofl/roboto/Roboto-Italic[wdth,wght].ttf
  ofl/roboto/Roboto[wdth,wght].ttf
  ofl/roboto/upstream.yaml
Labels: I Font Upgrade

#6767 Noto Sans Kaithi: Version 2.005; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosanskaithi/METADATA.pb
  ofl/notosanskaithi/NotoSansKaithi-Regular.ttf
  ofl/notosanskaithi/upstream.yaml
Labels: I Font Upgrade

#7270 Updated lists 09th of February
  to_production.txt
  to_sandbox.txt
Labels: I Tools / workflow / repo

#6860 Noto Kufi Arabic: Version 2.108 added
  ofl/notokufiarabic/METADATA.pb
  ofl/notokufiarabic/NotoKufiArabic[wght].ttf
  ofl/notokufiarabic/OFL.txt
  ofl/notokufiarabic/article/ARTICLE.en_us.html
  ofl/notokufiarabic/upstream.yaml
Labels: I Font Upgrade

#7212 Noto Sans Brahmi: Version 2.004; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosansbrahmi/METADATA.pb
  ofl/notosansbrahmi/NotoSansBrahmi-Regular.ttf
  ofl/notosansbrahmi/upstream.yaml
Labels: I Font Upgrade, II Indic / Brahmic / Thai / Tai

#6757 Noto Sans Batak: Version 2.003; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosansbatak/METADATA.pb
  ofl/notosansbatak/NotoSansBatak-Regular.ttf
  ofl/notosansbatak/upstream.yaml
Labels: I Font Upgrade

#7267 Designer added: Ụdị Foundry
  catalog/designers/udifoundry/bio.html
  catalog/designers/udifoundry/info.pb
  catalog/designers/udifoundry/udifoundry.png
Labels: I Designer profile

#6766 Noto Sans Georgian: Version 2.003 added
  ofl/notosansgeorgian/METADATA.pb
  ofl/notosansgeorgian/NotoSansGeorgian[wdth,wght].ttf
  ofl/notosansgeorgian/upstream.yaml
Labels: -- Needs Upstream Resolution, I Font Upgrade

#7278 Tac One: Version 1.002; ttfautohint (v1.8.4.7-5d5b) added
  ofl/tacone/DESCRIPTION.en_us.html
  ofl/tacone/METADATA.pb
  ofl/tacone/OFL.txt
  ofl/tacone/TacOne-Regular.ttf
  ofl/tacone/upstream.yaml
Labels: I New Font, II African

#7251 Ojuju: Version 1.000 added
  ofl/ojuju/DESCRIPTION.en_us.html
  ofl/ojuju/METADATA.pb
  ofl/ojuju/OFL.txt
  ofl/ojuju/Ojuju[wght].ttf
  ofl/ojuju/upstream.yaml
Labels: I New Font, II African

#7282 Madimi One: Version 1.000; ttfautohint (v1.8.4.7-5d5b) added
  ofl/madimione/DESCRIPTION.en_us.html
  ofl/madimione/METADATA.pb
  ofl/madimione/MadimiOne-Regular.ttf
  ofl/madimione/OFL.txt
  ofl/madimione/upstream.yaml
Labels: I New Font, II African

#7219 Yarndings 20: Version 1.000; ttfautohint (v1.8.4.7-5d5b) added
  ofl/yarndings20/DESCRIPTION.en_us.html
  ofl/yarndings20/METADATA.pb
  ofl/yarndings20/OFL.txt
  ofl/yarndings20/Yarndings20-Regular.ttf
  ofl/yarndings20/upstream.yaml
Labels: I New Font, II Icon / symbols / not text

#7220 Yarndings 20 Charted: Version 1.000; ttfautohint (v1.8.4.7-5d5b) added
  ofl/yarndings20charted/DESCRIPTION.en_us.html
  ofl/yarndings20charted/METADATA.pb
  ofl/yarndings20charted/OFL.txt
  ofl/yarndings20charted/Yarndings20Charted-Regular.ttf
  ofl/yarndings20charted/upstream.yaml
Labels: I New Font, II Icon / symbols / not text

#7216 Yarndings 12 Charted: Version 1.000; ttfautohint (v1.8.4.7-5d5b) added
  ofl/yarndings12charted/DESCRIPTION.en_us.html
  ofl/yarndings12charted/METADATA.pb
  ofl/yarndings12charted/OFL.txt
  ofl/yarndings12charted/Yarndings12Charted-Regular.ttf
  ofl/yarndings12charted/upstream.yaml
Labels: I New Font, II Icon / symbols / not text

#7215 Yarndings 12: Version 1.000; ttfautohint (v1.8.4.7-5d5b) added
  ofl/yarndings12/DESCRIPTION.en_us.html
  ofl/yarndings12/METADATA.pb
  ofl/yarndings12/OFL.txt
  ofl/yarndings12/Yarndings12-Regular.ttf
  ofl/yarndings12/upstream.yaml
Labels: I New Font, II Icon / symbols / not text

#7084 Jacquarda Bastarda 9 Charted: Version 1.000; ttfautohint (v1.8.4.7-5d5b) added
  ofl/jacquardabastarda9charted/DESCRIPTION.en_us.html
  ofl/jacquardabastarda9charted/JacquardaBastarda9Charted-Regular.ttf
  ofl/jacquardabastarda9charted/METADATA.pb
  ofl/jacquardabastarda9charted/OFL.txt
  ofl/jacquardabastarda9charted/upstream.yaml
Labels: I New Font, -- Needs github issue labels/tags

#7052 David Libre: Version 1.100; ttfautohint (v1.8.4.7-5d5b) added
  ofl/davidlibre/DavidLibre-Bold.ttf
  ofl/davidlibre/DavidLibre-Medium.ttf
  ofl/davidlibre/DavidLibre-Regular.ttf
  ofl/davidlibre/METADATA.pb
  ofl/davidlibre/OFL.txt
  ofl/davidlibre/upstream.yaml
Labels: I Font Upgrade, II Arabic / Hebrew / Semitic / RTL

#6951 Bodoni Moda: Version 2.005 added
  ofl/bodonimoda/BodoniModa-Italic[opsz,wght].ttf
  ofl/bodonimoda/BodoniModa[opsz,wght].ttf
  ofl/bodonimoda/METADATA.pb
  ofl/bodonimoda/OFL.txt
  ofl/bodonimoda/upstream.yaml
Labels: I Font Upgrade

#7300 Jacquard 12 Charted: Version 1.000 added
  ofl/jacquard12charted/DESCRIPTION.en_us.html
  ofl/jacquard12charted/Jacquard12Charted-Regular.ttf
  ofl/jacquard12charted/METADATA.pb
  ofl/jacquard12charted/OFL.txt
  ofl/jacquard12charted/upstream.yaml
Labels: I New Font

#7302 Jacquard12: description
  ofl/jacquard12/DESCRIPTION.en_us.html
Labels: I Description/Metadata/OFL

#7303 Taurai Valerie Mtake: designer added
  catalog/designers/tauraivaleriemtake/bio.html
  catalog/designers/tauraivaleriemtake/info.pb
  catalog/designers/tauraivaleriemtake/tauraivaleriemtake.png
Labels: I Designer profile

#7304 Eyiyemi Adegbite: designer added
  catalog/designers/eyiyemiadegbite/bio.html
  catalog/designers/eyiyemiadegbite/eyiyemiadegbite.png
  catalog/designers/eyiyemiadegbite/info.pb
Labels: I Designer profile

#7308 Gelasio: Version 1.008 added
  ofl/gelasio/DESCRIPTION.en_us.html
  ofl/gelasio/Gelasio-Bold.ttf
  ofl/gelasio/Gelasio-BoldItalic.ttf
  ofl/gelasio/Gelasio-Italic.ttf
  ofl/gelasio/Gelasio-Italic[wght].ttf
  ofl/gelasio/Gelasio-Medium.ttf
  ofl/gelasio/Gelasio-MediumItalic.ttf
  ofl/gelasio/Gelasio-Regular.ttf
  ofl/gelasio/Gelasio-SemiBold.ttf
  ofl/gelasio/Gelasio-SemiBoldItalic.ttf
  ofl/gelasio/Gelasio[wght].ttf
  ofl/gelasio/METADATA.pb
  ofl/gelasio/OFL.txt
  ofl/gelasio/upstream.yaml
Labels: III Expand glyphset, III VF Replacement, I Font Upgrade, II African

#7306 Tac One: Version 1.003; ttfautohint (v1.8.4.7-5d5b) added
  ofl/tacone/DESCRIPTION.en_us.html
  ofl/tacone/METADATA.pb
  ofl/tacone/TacOne-Regular.ttf
Labels: I New Font, II African

#7315 Reddit Mono: Version 1.014 added
  ofl/redditmono/DESCRIPTION.en_us.html
  ofl/redditmono/METADATA.pb
  ofl/redditmono/OFL.txt
  ofl/redditmono/RedditMono[wght].ttf
  ofl/redditmono/upstream.yaml
Labels: I New Font

#7293 Add classification data to Noto Sans Symbols
  ofl/notosanssymbols/METADATA.pb
Labels: I Description/Metadata/OFL

#7331 Add designer: Stephen Hutchings
  catalog/designers/stephenhutchings/bio.html
  catalog/designers/stephenhutchings/info.pb
  catalog/designers/stephenhutchings/stephenhutchings.png
Labels: I Designer profile

#7330 Add designer: David Sargent
  catalog/designers/davidsargent/bio.html
  catalog/designers/davidsargent/davidsargent.png
  catalog/designers/davidsargent/info.pb
Labels: I Designer profile
