Repository google/fonts, pull requests merged in 2025-06, with the labels that each got.

#9344 Agbalumo: Version 2.000; ttfautohint (v1.8.4.7-5d5b) added
  ofl/agbalumo/Agbalumo-Regular.ttf
  ofl/agbalumo/DESCRIPTION.en_us.html
  ofl/agbalumo/METADATA.pb
Labels: I Font Upgrade, II Commissioned, II African

#8968 Bitcount Single: Version 1.0 added
  ofl/bitcountsingle/BitcountSingle[CRSV,ELSH,ELXP,slnt,wght].ttf
  ofl/bitcountsingle/METADATA.pb
  ofl/bitcountsingle/OFL.txt
  ofl/bitcountsingle/article/ARTICLE.en_us.html
Labels: I New Font, II Commissioned, II Color font, II Custom axes, P3

#8966 Bitcount Prop Single: Version 1.0 added
  ofl/bitcountpropsingle/BitcountPropSingle[CRSV,ELSH,ELXP,slnt,wght].ttf
  ofl/bitcountpropsingle/METADATA.pb
  ofl/bitcountpropsingle/OFL.txt
  ofl/bitcountpropsingle/article/ARTICLE.en_us.html
Labels: I New Font, II Commissioned, II Color font, II Custom axes, P3

#8961 Bitcount Grid Single: Version 1.0 added
  ofl/bitcountgridsingle/BitcountGridSingle[CRSV,ELSH,ELXP,slnt,wght].ttf
  ofl/bitcountgridsingle/METADATA.pb
  ofl/bitcountgridsingle/OFL.txt
  ofl/bitcountgridsingle/article/ARTICLE.en_us.html
Labels: I New Font, II Commissioned, II Color font, II Custom axes, P3

#9524 Add links to the Sheep book PDF download
  cc-by-sa/knowledge/modules/choosing_type/lessons/emotive_considerations_for_choosing_typefaces/content.md
  cc-by-sa/knowledge/modules/choosing_type/lessons/pairing_typefaces/content.md
Labels: I Knowledge

#9520 lang v0.7.5
  lang/.github/workflows/publish-release.yml
  lang/Lib/gflanguages/data/languages/suz_Sunu.textproto
Labels: I Lang

#9506 Reem Kufi Ink: Version 1.899 added
  ofl/reemkufiink/METADATA.pb
  ofl/reemkufiink/ReemKufiInk-Regular.ttf
Labels: I Font Upgrade

#9547 Update glory/DESCRIPTION.en_us.html
  ofl/glory/DESCRIPTION.en_us.html
Labels: I Article/Description

#9554 Update METADATA.pb - Uoq Mun Then Kung
  ofl/uoqmunthenkhung/METADATA.pb
Labels: I Metadata/OFL

#9549 Noto Sans Sunuwar: Version 1.000; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosanssunuwar/DESCRIPTION.en_us.html
  ofl/notosanssunuwar/METADATA.pb
  ofl/notosanssunuwar/NotoSansSunuwar-Regular.ttf
  ofl/notosanssunuwar/OFL.txt
  ofl/notosanssunuwar/article/ARTICLE.en_us.html
Labels: z_Noto, I New Font

#9492 Parastoo: Version 3.000 added
  ofl/parastoo/METADATA.pb
  ofl/parastoo/OFL.txt
  ofl/parastoo/Parastoo[wght].ttf
  ofl/parastoo/article/ARTICLE.en_us.html
  ofl/parastoo/article/sample.png
Labels: I New Font, II Arabic / Hebrew / Semitic / RTL

#9569 Fix tofu in Dives Akuru article
  ofl/notoserifdivesakuru/article/ARTICLE.en_us.html
Labels: I Article/Description

#9587 [bitcountgriddouble] Version 1.001
  ofl/bitcountgriddouble/BitcountGridDouble[CRSV,ELSH,ELXP,slnt,wght].ttf
Labels: I Font Upgrade

#9594 Lists of the 20th of June
  to_delist.txt
  to_production.txt
  to_sandbox.txt
Labels: I Tools / workflow / repo

#9588 Special Gothic: Version 1.011 added
  ofl/specialgothic/METADATA.pb
  ofl/specialgothic/SpecialGothic-Regular.ttf
  ofl/specialgothic/SpecialGothic[wdth,wght].ttf
Labels: III VF Replacement, I Font Upgrade
