Repository google/fonts, pull requests merged in 2025-09, with the labels that each got.

#8963 Bitcount Ink: Version 1.001 added
  ofl/bitcountink/BitcountInk[CRSV,ELSH,ELXP,SZP1,SZP2,XPN1,XPN2,YPN1,YPN2,slnt,wght].ttf
  ofl/bitcountink/METADATA.pb
  ofl/bitcountink/OFL.txt
  ofl/bitcountink/article/ARTICLE.en_us.html
  ofl/bitcountink/article/image0.mp4
  ofl/bitcountink/article/image1.png
  ofl/bitcountink/article/image12.png
  ofl/bitcountink/article/image13.png
  ofl/bitcountink/article/image14.png
  ofl/bitcountink/article/image15.png
  ofl/bitcountink/article/image16.png
  ofl/bitcountink/article/image17.png
  ofl/bitcountink/article/image18.png
  ofl/bitcountink/article/image19.png
  ofl/bitcountink/article/image2.png
  ofl/bitcountink/article/image20.png
  ofl/bitcountink/article/image21.png
  ofl/bitcountink/article/image22.png
  ofl/bitcountink/article/image23.png
  ofl/bitcountink/article/image24.png
  ofl/bitcountink/article/image25.png
  ofl/bitcountink/article/image26.png
  ofl/bitcountink/article/image27.png
  ofl/bitcountink/article/image28.png
  ofl/bitcountink/article/image29.png
  ofl/bitcountink/article/image3.mp4
  ofl/bitcountink/article/image30.png
  ofl/bitcountink/article/image31.png
  ofl/bitcountink/article/image32.png
  ofl/bitcountink/article/image33.png
  ofl/bitcountink/article/image34.png
  ofl/bitcountink/article/image35.png
  ofl/bitcountink/article/image36.png
  ofl/bitcountink/article/image37.png
  ofl/bitcountink/article/image38.png
  ofl/bitcountink/article/image39.png
  ofl/bitcountink/article/image4.png
  ofl/bitcountink/article/image40.png
  ofl/bitcountink/article/image41.png
  ofl/bitcountink/article/image42.png
  ofl/bitcountink/article/image43.png
  ofl/bitcountink/article/image44.png
  ofl/bitcountink/article/image45.png
  ofl/bitcountink/article/image46.png
  ofl/bitcountink/article/image47.png
  ofl/bitcountink/article/image48.png
  ofl/bitcountink/article/image49.png
  ofl/bitcountink/article/image5.mp4
  ofl/bitcountink/article/image50.png
  ofl/bitcountink/article/image51.png
  ofl/bitcountink/article/image52.png
  ofl/bitcountink/article/image53.png
  ofl/bitcountink/article/image54.png
  ofl/bitcountink/article/image55.png
  ofl/bitcountink/article/image56.png
  ofl/bitcountink/article/image57.png
  ofl/bitcountink/article/image6.png
  ofl/bitcountink/article/image7.mp4
  ofl/bitcountink/article/image8.mp4
  ofl/bitcountink/article/image9.png
Labels: I New Font, II Commissioned, II Color font, II Custom axes, P3

#8965 Bitcount Prop Double Ink: Version 1.001 added
  ofl/bitcountpropdoubleink/BitcountPropDoubleInk[CRSV,ELSH,ELXP,SZP1,SZP2,XPN1,XPN2,YPN1,YPN2,slnt,wght].ttf
  ofl/bitcountpropdoubleink/METADATA.pb
  ofl/bitcountpropdoubleink/OFL.txt
  ofl/bitcountpropdoubleink/article/ARTICLE.en_us.html
  ofl/bitcountpropdoubleink/article/image0.mp4
  ofl/bitcountpropdoubleink/article/image1.png
  ofl/bitcountpropdoubleink/article/image12.png
  ofl/bitcountpropdoubleink/article/image13.png
  ofl/bitcountpropdoubleink/article/image14.png
  ofl/bitcountpropdoubleink/article/image15.png
  ofl/bitcountpropdoubleink/article/image16.png
  ofl/bitcountpropdoubleink/article/image17.png
  ofl/bitcountpropdoubleink/article/image18.png
  ofl/bitcountpropdoubleink/article/image19.png
  ofl/bitcountpropdoubleink/article/image2.png
  ofl/bitcountpropdoubleink/article/image20.png
  ofl/bitcountpropdoubleink/article/image21.png
  ofl/bitcountpropdoubleink/article/image22.png
  ofl/bitcountpropdoubleink/article/image23.png
  ofl/bitcountpropdoubleink/article/image24.png
  ofl/bitcountpropdoubleink/article/image25.png
  ofl/bitcountpropdoubleink/article/image26.png
  ofl/bitcountpropdoubleink/article/image27.png
  ofl/bitcountpropdoubleink/article/image28.png
  ofl/bitcountpropdoubleink/article/image29.png
  ofl/bitcountpropdoubleink/article/image3.mp4
  ofl/bitcountpropdoubleink/article/image30.png
  ofl/bitcountpropdoubleink/article/image31.png
  ofl/bitcountpropdoubleink/article/image32.png
  ofl/bitcountpropdoubleink/article/image33.png
  ofl/bitcountpropdoubleink/article/image34.png
  ofl/bitcountpropdoubleink/article/image35.png
  ofl/bitcountpropdoubleink/article/image36.png
  ofl/bitcountpropdoubleink/article/image37.png
  ofl/bitcountpropdoubleink/article/image38.png
  ofl/bitcountpropdoubleink/article/image39.png
  ofl/bitcountpropdoubleink/article/image4.png
  ofl/bitcountpropdoubleink/article/image40.png
  ofl/bitcountpropdoubleink/article/image41.png
  ofl/bitcountpropdoubleink/article/image42.png
  ofl/bitcountpropdoubleink/article/image43.png
  ofl/bitcountpropdoubleink/article/image44.png
  ofl/bitcountpropdoubleink/article/image45.png
  ofl/bitcountpropdoubleink/article/image46.png
  ofl/bitcountpropdoubleink/article/image47.png
  ofl/bitcountpropdoubleink/article/image48.png
  ofl/bitcountpropdoubleink/article/image49.png
  ofl/bitcountpropdoubleink/article/image5.mp4
  ofl/bitcountpropdoubleink/article/image50.png
  ofl/bitcountpropdoubleink/article/image51.png
  ofl/bitcountpropdoubleink/article/image52.png
  ofl/bitcountpropdoubleink/article/image53.png
  ofl/bitcountpropdoubleink/article/image54.png
  ofl/bitcountpropdoubleink/article/image55.png
  ofl/bitcountpropdoubleink/article/image56.png
  ofl/bitcountpropdoubleink/article/image57.png
  ofl/bitcountpropdoubleink/article/image6.png
  ofl/bitcountpropdoubleink/article/image7.mp4
  ofl/bitcountpropdoubleink/article/image8.mp4
  ofl/bitcountpropdoubleink/article/image9.png
Labels: I New Font, II Commissioned, II Color font, II Custom axes, P3

#9799 Scheherazade New: Version 4.400 added
  ofl/scheherazadenew/METADATA.pb
  ofl/scheherazadenew/OFL.txt
  ofl/scheherazadenew/ScheherazadeNew-Bold.ttf
  ofl/scheherazadenew/ScheherazadeNew-Medium.ttf
  ofl/scheherazadenew/ScheherazadeNew-Regular.ttf
  ofl/scheherazadenew/ScheherazadeNew-SemiBold.ttf
Labels: I Font Upgrade, II Arabic / Hebrew / Semitic / RTL

#9802 Lists of the 5th of September
  to_production.txt
  to_sandbox.txt
Labels: I Tools / workflow / repo

#9837 Update ofl/parastoo/METADATA.pb with arabic subset
  ofl/parastoo/METADATA.pb
Labels: I Metadata/OFL

#9869 BBH Sans Bogle: Version 1.000 added
  ofl/bbhsansbogle/BBHSansBogle-Regular.ttf
  ofl/bbhsansbogle/METADATA.pb
  ofl/bbhsansbogle/OFL.txt
  ofl/bbhsansbogle/article/ARTICLE.en_us.html
Labels: I New Font

#9878 Add designer: Studio DRAMA
  catalog/designers/studiodrama/bio.html
  catalog/designers/studiodrama/info.pb
  catalog/designers/studiodrama/studiodrama.png
Labels: I Designer profile

#9882 Tags update first batch
  tags/all/families.csv
Labels: I Tools / workflow / repo

#9876 Momo Signature: Version 1.000; ttfautohint (v1.8.4.7-5d5b) added
  ofl/momosignature/METADATA.pb
  ofl/momosignature/MomoSignature-Regular.ttf
  ofl/momosignature/OFL.txt
  ofl/momosignature/article/ARTICLE.en_us.html
  ofl/momosignature/article/image00.jpg
  ofl/momosignature/article/image01.mp4
  ofl/momosignature/article/image02.mp4
  ofl/momosignature/article/image03.mp4
Labels: I New Font

#9848 Add designer: Type Associates
  catalog/designers/typeassociates/bio.html
  catalog/designers/typeassociates/info.pb
  catalog/designers/typeassociates/typeassociates.png
Labels: I Designer profile
