Repository google/fonts, pull requests merged in 2025-03, with the labels that each got.

#9105 Add designer: Typofactur
  catalog/designers/typofactur/bio.html
  catalog/designers/typofactur/info.pb
  catalog/designers/typofactur/typofactur.png
Labels: I Designer profile

#9152 [notoserifhentaigana] Fix sample text
  ofl/notoserifhentaigana/METADATA.pb
Labels: I Lang

#9154 to_lists of the 5th of March
  to_production.txt
  to_sandbox.txt
Labels: I Tools / workflow / repo

#9172 Special Gothic Family - Update families.csv
  tags/all/families.csv
Labels: I Tools / workflow / repo

#9166 Add designer: Yorlmar Campos
  catalog/designers/yorlmarcampos/bio.html
  catalog/designers/yorlmarcampos/info.pb
  catalog/designers/yorlmarcampos/yorlmarcampos.png
Labels: I Designer profile

#9165 Special Gothic Condensed One: Version 1.010; ttfautohint (v1.8.4.7-5d5b) added
  ofl/specialgothiccondensedone/METADATA.pb
  ofl/specialgothiccondensedone/OFL.txt
  ofl/specialgothiccondensedone/SpecialGothicCondensedOne-Regular.ttf
  ofl/specialgothiccondensedone/article/ARTICLE.en_us.html
  ofl/specialgothiccondensedone/article/image1.png
Labels: I New Font

#8676 New Tag: `/Purpose/Educational`
  tags/all/families.csv
Labels: tag tool

#9161 Update to_delist.txt
  to_delist.txt
Labels: I Tools / workflow / repo

#9190 Liter- Author spelling
  ofl/liter/METADATA.pb
Labels: I Designer profile

#9187 Playpen Sans Hebrew: Version 2.000 added
  ofl/playpensanshebrew/METADATA.pb
  ofl/playpensanshebrew/OFL.txt
  ofl/playpensanshebrew/PlaypenSansHebrew[wght].ttf
  ofl/playpensanshebrew/article/2025_PPS-Heb_01.jpg
  ofl/playpensanshebrew/article/2025_PPS-Heb_02.jpg
  ofl/playpensanshebrew/article/2025_PPS-Heb_03.jpg
  ofl/playpensanshebrew/article/ARTICLE.en_us.html
Labels: I New Font, II Commissioned, P2

#9193 PPS Hebrew emojis small fix
  ofl/playpensanshebrew/article/ARTICLE.en_us.html
Labels: I Article/Description

#9199 Add designer: Sirin Gunkloy
  catalog/designers/siringunkloy/bio.html
  catalog/designers/siringunkloy/info.pb
  catalog/designers/siringunkloy/siringunkloy.png
Labels: I Designer profile

#9191 Roboto: Version 3.011; 2025 added
  ofl/roboto/METADATA.pb
  ofl/roboto/Roboto-Italic[wdth,wght].ttf
  ofl/roboto/Roboto[wdth,wght].ttf
Labels: I Font Upgrade

#9157 Playpen Sans: Version 2.000 added
  ofl/playpensans/DESCRIPTION.en_us.html
  ofl/playpensans/METADATA.pb
  ofl/playpensans/OFL.txt
  ofl/playpensans/PlaypenSans[wght].ttf
Labels: I Font Upgrade, II Commissioned, P2

#9192 lists of the 12th of March
  cc-by-sa/knowledge/glossary/terms/edpt_axis/content.md
  cc-by-sa/knowledge/glossary/terms/ehlt_axis/content.md
  cc-by-sa/knowledge/modules/readability_and_accessibility/lessons/how_type_influences_readability/content.md
  cc-by-sa/knowledge/modules/readability_and_accessibility/lessons/introducing_accessibility_in_typography/content.md
  cc-by-sa/knowledge/modules/using_type/lessons/switching_from_static_to_variable_fonts/content.md
  cc-by-sa/knowledge/modules/using_type_in_ar_and_vr/lessons/designing_for_ar_vr/content.md
  to_delist.txt
  to_production.txt
  to_sandbox.txt
Labels: I Tools / workflow / repo

#9209 PPS article update witg LGC added
  ofl/playpensans/article/2025_PPS-LGC_01.jpg
  ofl/playpensans/article/2025_PPS-LGC_02.jpg
  ofl/playpensans/article/2025_PPS-LGC_03.jpg
  ofl/playpensans/article/ARTICLE.en_us.html
  ofl/playpensans/article/PlaypenSans-about1a.png
  ofl/playpensans/article/PlaypenSans-about2a.png
Labels: I Article/Description

#9211 PPS i18n families tags added
  tags/all/families.csv
Labels: tag tool

#9202 National Park: Update families.csv
  tags/all/families.csv
Labels: I Tools / workflow / repo

#9229 Update designer: Pooja Saxena
  catalog/designers/poojasaxena/bio.html
  catalog/designers/poojasaxena/info.pb
  catalog/designers/poojasaxena/pooja_saxena.png
  catalog/designers/poojasaxena/poojasaxena.png
Labels: I Designer profile

#9227 Cascadia Mono: version 2407.024
  ofl/cascadiamono/CascadiaMono-Italic[wght].ttf
  ofl/cascadiamono/CascadiaMono[wght].ttf
  ofl/cascadiamono/METADATA.pb
  ofl/cascadiamono/OFL.txt
  ofl/cascadiamono/article/ARTICLE.en_us.html
Labels: I New Font

#9226 Cascadia Code: version 2407.024
  ofl/cascadiacode/CascadiaCode-Italic[wght].ttf
  ofl/cascadiacode/CascadiaCode[wght].ttf
  ofl/cascadiacode/METADATA.pb
  ofl/cascadiacode/OFL.txt
  ofl/cascadiacode/article/ARTICLE.en_us.html
Labels: I New Font

#9198 Playpen Sans Thai: Version 2.000 added
  ofl/playpensansthai/METADATA.pb
  ofl/playpensansthai/OFL.txt
  ofl/playpensansthai/PlaypenSansThai[wght].ttf
  ofl/playpensansthai/article/2025_PPS-Thai_01.jpg
  ofl/playpensansthai/article/2025_PPS-Thai_02.jpg
  ofl/playpensansthai/article/2025_PPS-Thai_03.jpg
  ofl/playpensansthai/article/ARTICLE.en_us.html
Labels: I New Font, II Commissioned, P2

#9206 Add designer: Tom Grace
  catalog/designers/tomgrace/bio.html
  catalog/designers/tomgrace/info.pb
Labels: I Designer profile

#9207 Add designer: Vera Evstafieva
  catalog/designers/veraevstafieva/bio.html
  catalog/designers/veraevstafieva/info.pb
  catalog/designers/veraevstafieva/veraevstafieva.png
Labels: I Designer profile

#9194 Add designer: Andrea Herstowski
  catalog/designers/andreaherstowski/andreaherstowski.png
  catalog/designers/andreaherstowski/bio.html
  catalog/designers/andreaherstowski/info.pb
Labels: I Designer profile

#9174 National Park: Version 1.009 added
  ofl/nationalpark/METADATA.pb
  ofl/nationalpark/NationalPark[wght].ttf
  ofl/nationalpark/OFL.txt
  ofl/nationalpark/article/ARTICLE.en_us.html
  ofl/nationalpark/article/Image1.png
  ofl/nationalpark/article/Image2.png
  ofl/nationalpark/article/Image3.png
  ofl/nationalpark/article/Image4.png
  ofl/nationalpark/article/Image5.png
  ofl/nationalpark/article/Image6.png
Labels: I New Font

#9162 Special Gothic: Version 1.010; ttfautohint (v1.8.4.7-5d5b) added
  ofl/specialgothic/METADATA.pb
  ofl/specialgothic/OFL.txt
  ofl/specialgothic/SpecialGothic-Regular.ttf
  ofl/specialgothic/article/ARTICLE.en_us.html
  ofl/specialgothic/article/image1.png
Labels: I New Font

#9237 PPS i18n articles
  ofl/playpensans/article/ARTICLE.en_us.html
  ofl/playpensansarabic/article/ARTICLE.en_us.html
  ofl/playpensanshebrew/article/ARTICLE.en_us.html
  ofl/playpensansthai/article/ARTICLE.en_us.html
Labels: I Article/Description

#9247 Libre Baskerville: Version 1.051; ttfautohint (v1.8.4.7-5d5b) added
  ofl/librebaskerville/LibreBaskerville-Bold.ttf
  ofl/librebaskerville/LibreBaskerville-Italic.ttf
  ofl/librebaskerville/LibreBaskerville-Regular.ttf
  ofl/librebaskerville/METADATA.pb
  ofl/librebaskerville/OFL.txt
Labels: I Font Upgrade, II African

#9259 [METADATA.pb] Populate font sources related fields for a few font families.
  ofl/arima/METADATA.pb
  ofl/artifika/METADATA.pb
  ofl/aubrey/METADATA.pb
  ofl/bhutukaexpandedone/METADATA.pb
  ofl/blaka/METADATA.pb
  ofl/blakahollow/METADATA.pb
  ofl/blakaink/METADATA.pb
  ofl/cactusclassicalserif/METADATA.pb
  ofl/cairo/METADATA.pb
  ofl/cairoplay/METADATA.pb
  ofl/chocolateclassicalsans/METADATA.pb
  ofl/diplomata/METADATA.pb
  ofl/diplomatasc/METADATA.pb
  ofl/hedvigletterssans/METADATA.pb
  ofl/hedviglettersserif/METADATA.pb
  ofl/lxgwwenkaimonotc/METADATA.pb
  ofl/lxgwwenkaitc/METADATA.pb
  ofl/mate/METADATA.pb
  ofl/matesc/METADATA.pb
  ofl/playpensansarabic/METADATA.pb
  ofl/playpensanshebrew/METADATA.pb
  ofl/playpensansthai/METADATA.pb
  ofl/wireone/METADATA.pb
Labels: I Tools / workflow / repo, I Metadata/OFL

#9262 PPS i18n: add YouTube video to articles
  ofl/playpensans/article/ARTICLE.en_us.html
  ofl/playpensans/article/Playpen-Sans-Multiscript.png
  ofl/playpensansarabic/article/ARTICLE.en_us.html
  ofl/playpensansarabic/article/Playpen-Sans-Multiscript.png
  ofl/playpensanshebrew/article/ARTICLE.en_us.html
  ofl/playpensanshebrew/article/Playpen-Sans-Multiscript.png
  ofl/playpensansthai/article/ARTICLE.en_us.html
  ofl/playpensansthai/article/Playpen-Sans-Multiscript.png
Labels: I Article/Description

#9272 Add designer: Gunjan Panchal
  catalog/designers/gunjanpanchal/bio.html
  catalog/designers/gunjanpanchal/gunjanpanchal.png
  catalog/designers/gunjanpanchal/info.pb
Labels: I Designer profile

#9271 Playpen Sans Deva: Version 2.000 added
  ofl/playpensansdeva/METADATA.pb
  ofl/playpensansdeva/OFL.txt
  ofl/playpensansdeva/PlaypenSansDeva[wght].ttf
  ofl/playpensansdeva/article/2025_PPS-Deva_01.jpg
  ofl/playpensansdeva/article/2025_PPS-Deva_02.jpg
  ofl/playpensansdeva/article/2025_PPS-Deva_03.jpg
  ofl/playpensansdeva/article/ARTICLE.en_us.html
  ofl/playpensansdeva/article/Playpen-Sans-Multiscript.png
Labels: I New Font, II Commissioned

#9273 Playpen Sans Hebrew: Version 2.000 added
  ofl/playpensanshebrew/METADATA.pb
  ofl/playpensanshebrew/PlaypenSansHebrew[wght].ttf
Labels: I New Font, II Commissioned

#9277 Lists of the 28th of March
  to_production.txt
  to_sandbox.txt
Labels: I Tools / workflow / repo

#9248 Epunda Sans - Update families.csv
  tags/all/families.csv
Labels: I Tools / workflow / repo
