Repository google/fonts, pull requests merged in 2025-04, with the labels that each got.

#9250 Add designer: Cal.com Inc.
  catalog/designers/cal.com,inc./bio.html
  catalog/designers/cal.com,inc./calcominc.png
  catalog/designers/cal.com,inc./info.pb
Labels: I Designer profile

#9274 Coral Pixels: Version 1.000; ttfautohint (v1.8.4.7-5d5b) added
  ofl/coralpixels/CoralPixels-Regular.ttf
  ofl/coralpixels/METADATA.pb
  ofl/coralpixels/OFL.txt
  ofl/coralpixels/article/ARTICLE.en_us.html
  ofl/coralpixels/article/image0.png
  ofl/coralpixels/article/image1.png
  ofl/coralpixels/article/image2.png
  ofl/coralpixels/article/image3.png
  ofl/coralpixels/article/image4.png
Labels: I New Font, II Color font

#9246 Epunda Sans: Version 2.204 added
  ofl/epundasans/EpundaSans-Italic[wght].ttf
  ofl/epundasans/EpundaSans[wght].ttf
  ofl/epundasans/METADATA.pb
  ofl/epundasans/OFL.txt
  ofl/epundasans/article/ARTICLE.en_us.html
  ofl/epundasans/article/image1.png
  ofl/epundasans/article/image2.png
  ofl/epundasans/article/image3.png
  ofl/epundasans/article/image4.png
Labels: I New Font

#9241 Epunda Slab: Version 1.102 added
  ofl/epundaslab/EpundaSlab-Italic[wght].ttf
  ofl/epundaslab/EpundaSlab[wght].ttf
  ofl/epundaslab/METADATA.pb
  ofl/epundaslab/OFL.txt
  ofl/epundaslab/article/ARTICLE.en_us.html
  ofl/epundaslab/article/image1.png
  ofl/epundaslab/article/image2.png
  ofl/epundaslab/article/image3.png
  ofl/epundaslab/article/image4.png
  ofl/epundaslab/article/image5.png
  ofl/epundaslab/article/image6.png
  ofl/epundaslab/article/image7.png
  ofl/epundaslab/article/image8.png
Labels: I New Font

#9240 Cal Sans: Add designer: Mark Davis
  catalog/designers/markdavis/bio.html
  catalog/designers/markdavis/info.pb
  catalog/designers/markdavis/markdavis.png
Labels: I Designer profile

#9232 Cal Sans: Version 1.000; ttfautohint (v1.8.4.7-5d5b) added
  ofl/calsans/CalSans-Regular.ttf
  ofl/calsans/METADATA.pb
  ofl/calsans/OFL.txt
  ofl/calsans/article/ARTICLE.en_us.html
  ofl/calsans/article/image1.jpg
  ofl/calsans/article/image2.gif
  ofl/calsans/article/image3.jpg
  ofl/calsans/article/image4.jpg
  ofl/calsans/article/image5.gif
Labels: I New Font

#9308 Special Gothic article
  ofl/specialgothic/article/ARTICLE.en_us.html
  ofl/specialgothic/article/SpecialGothic_GF1.jpg
  ofl/specialgothic/article/SpecialGothic_GF2.jpg
  ofl/specialgothic/article/SpecialGothic_GF3.jpg
  ofl/specialgothic/article/SpecialGothic_GF4.jpg
  ofl/specialgothic/article/SpecialGothic_GF5.jpg
  ofl/specialgothic/article/SpecialGothic_GF6.jpg
  ofl/specialgothic/article/SpecialGothic_GF7.jpg
  ofl/specialgothic/article/SpecialGothic_GF8.jpg
  ofl/specialgothic/article/SpecialGothic_GF9.jpg
  ofl/specialgothic/article/image1.png
  ofl/specialgothiccondensedone/article/ARTICLE.en_us.html
  ofl/specialgothiccondensedone/article/SpecialGothic_GF1.jpg
  ofl/specialgothiccondensedone/article/SpecialGothic_GF2.jpg
  ofl/specialgothiccondensedone/article/SpecialGothic_GF3.jpg
  ofl/specialgothiccondensedone/article/SpecialGothic_GF4.jpg
  ofl/specialgothiccondensedone/article/SpecialGothic_GF5.jpg
  ofl/specialgothiccondensedone/article/SpecialGothic_GF6.jpg
  ofl/specialgothiccondensedone/article/SpecialGothic_GF7.jpg
  ofl/specialgothiccondensedone/article/SpecialGothic_GF8.jpg
  ofl/specialgothiccondensedone/article/SpecialGothic_GF9.jpg
  ofl/specialgothiccondensedone/article/image1.png
  ofl/specialgothicexpandedone/article/ARTICLE.en_us.html
  ofl/specialgothicexpandedone/article/SpecialGothic_GF1.jpg
  ofl/specialgothicexpandedone/article/SpecialGothic_GF2.jpg
  ofl/specialgothicexpandedone/article/SpecialGothic_GF3.jpg
  ofl/specialgothicexpandedone/article/SpecialGothic_GF4.jpg
  ofl/specialgothicexpandedone/article/SpecialGothic_GF5.jpg
  ofl/specialgothicexpandedone/article/SpecialGothic_GF6.jpg
  ofl/specialgothicexpandedone/article/SpecialGothic_GF7.jpg
  ofl/specialgothicexpandedone/article/SpecialGothic_GF8.jpg
  ofl/specialgothicexpandedone/article/SpecialGothic_GF9.jpg
  ofl/specialgothicexpandedone/article/image1.png
Labels: I Article/Description

#9325 045a1e Add designer (2)
  catalog/designers/grillitype/bio.html
  catalog/designers/grillitype/grillitype.png
  catalog/designers/grillitype/info.pb
Labels: I Designer profile

#9327 Add designer: Alistair McCready
  catalog/designers/alistairmccready/alistairmccready.png
  catalog/designers/alistairmccready/bio.html
  catalog/designers/alistairmccready/info.pb
Labels: I Designer profile

#9326 045a1e Add designer (3)
  catalog/designers/contrastfoundry(cofo)/bio.html
  catalog/designers/contrastfoundry(cofo)/contrastfoundry.png
  catalog/designers/contrastfoundry(cofo)/info.pb
Labels: I Designer profile

#9324 045a1e Add designer (1)
  catalog/designers/typenetwork/bio.html
  catalog/designers/typenetwork/info.pb
  catalog/designers/typenetwork/typenetwork.png
Labels: I Designer profile

#9328 Figtree: Version 2.002 added
  ofl/figtree/Figtree-Italic[wght].ttf
  ofl/figtree/Figtree[wght].ttf
  ofl/figtree/METADATA.pb
  ofl/figtree/article/ARTICLE.en_us.html
  ofl/figtree/article/image1.png
  ofl/figtree/article/image2.png
  ofl/figtree/article/image3.png
  ofl/figtree/article/image4.png
  ofl/figtree/article/image5.png
Labels: I Font Upgrade

#9297 Akatab: Version 4.000 added
  ofl/akatab/Akatab-Black.ttf
  ofl/akatab/Akatab-Bold.ttf
  ofl/akatab/Akatab-ExtraBold.ttf
  ofl/akatab/Akatab-Medium.ttf
  ofl/akatab/Akatab-Regular.ttf
  ofl/akatab/Akatab-SemiBold.ttf
  ofl/akatab/METADATA.pb
  ofl/akatab/OFL.txt
Labels: I Font Upgrade, II African

#9281 Exile: Version 1.000; ttfautohint (v1.8.4.7-5d5b) added
  ofl/exile/Exile-Regular.ttf
  ofl/exile/METADATA.pb
  ofl/exile/OFL.txt
  ofl/exile/article/ARTICLE.en_us.html
  ofl/exile/article/exile_1.jpg
  ofl/exile/article/exile_2.jpg
  ofl/exile/article/exile_3.jpg
  ofl/exile/article/exile_4.jpg
  ofl/exile/article/exile_5.jpg
Labels: I New Font, II Accepted

#9275 Coral Pixels - Update families.csv
  tags/all/families.csv
Labels: I Tools / workflow / repo

#9242 Epunda Slab - Update families.csv
  tags/all/families.csv
Labels: I Tools / workflow / repo

#9239 Cal Sans- Update families.csv
  tags/all/families.csv
Labels: I Tools / workflow / repo

#9331 Add remaining Primary Script definitions
  apache/kosugi/METADATA.pb
  apache/kosugimaru/METADATA.pb
  ofl/alef/METADATA.pb
  ofl/arya/METADATA.pb
  ofl/eczar/METADATA.pb
  ofl/hindmadurai/METADATA.pb
  ofl/kurale/METADATA.pb
  ofl/miriamlibre/METADATA.pb
  ofl/pattaya/METADATA.pb
  ofl/reggaeone/METADATA.pb
  ofl/shipporiantique/METADATA.pb
  ofl/shipporiantiqueb1/METADATA.pb
  ofl/shipporimincho/METADATA.pb
  ofl/shipporiminchob1/METADATA.pb
  ofl/stick/METADATA.pb
  ofl/trainone/METADATA.pb
  ofl/yujiboku/METADATA.pb
  ofl/yujimai/METADATA.pb
  ofl/yujisyuku/METADATA.pb
Labels: I Metadata/OFL

#9337 Update Noto Znamenny Musical Notation metadata to classify as symbols
  ofl/notoznamennymusicalnotation/METADATA.pb
Labels: -- Needs Meta/Desc/License changes

#9359 Cascadia Code and Mono: Add additional designers
  ofl/cascadiacode/METADATA.pb
  ofl/cascadiamono/METADATA.pb
Labels: I Metadata/OFL

#9361 Update lists 17th of April
  to_production.txt
  to_sandbox.txt
Labels: I Tools / workflow / repo

#9047 Noto Serif Dives Akuru: Version 2.000; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notoserifdivesakuru/DESCRIPTION.en_us.html
  ofl/notoserifdivesakuru/METADATA.pb
  ofl/notoserifdivesakuru/NotoSerifDivesAkuru-Regular.ttf
  ofl/notoserifdivesakuru/OFL.txt
  ofl/notoserifdivesakuru/article/ARTICLE.en_us.html
Labels: I New Font, -- Needs lang/glyphset update

#9362 Hotfix: Source Code Pro v.1.026
  ofl/sourcecodepro/METADATA.pb
  ofl/sourcecodepro/SourceCodePro-Italic[wght].ttf
  ofl/sourcecodepro/SourceCodePro[wght].ttf
Labels: I Small Fix

#8592 Kapakana: 1.002
  ofl/kapakana/Kapakana[wght].ttf
Labels: I Small Fix

#9368 National Park: Adds Jeremy Shellhorn to metadata.pb
  ofl/nationalpark/METADATA.pb
Labels: I Metadata/OFL

#9369 Add designer Jeremy Sheelhorn
  catalog/designers/jeremyshellhorn/bio.html
  catalog/designers/jeremyshellhorn/info.pb
  catalog/designers/jeremyshellhorn/jeremyshellhorn.png
Labels: I Designer profile

#9386 ANRT [designer]: bio updated
  catalog/designers/anrt/bio.html
Labels: I Designer profile

#9400 WDXL Lubrifont metadata.pb
  ofl/wdxllubrifontjpn/METADATA.pb
Labels: I Metadata/OFL

#9398 Update Iansui METADATA to add localized name
  ofl/iansui/METADATA.pb
Labels: I Small Fix
