Repository google/fonts, pull requests merged in 2025-07, with the labels that each got.

#9624 Mozilla Text: Version 1.000 added
  ofl/mozillatext/METADATA.pb
  ofl/mozillatext/MozillaText[wght].ttf
  ofl/mozillatext/OFL.txt
  ofl/mozillatext/article/ARTICLE.en_us.html
Labels: I New Font

#9632 Add Designer Profile: Universal Thirst
  catalog/designers/universalthirst/bio.html
  catalog/designers/universalthirst/info.pb
  catalog/designers/universalthirst/universalthirst.png
Labels: I Designer profile

#9637 Update article GSC font: add intro headline
  ofl/googlesanscode/article/ARTICLE.en_us.html
Labels: I Article/Description

#9636 Add tags for GSC
  tags/all/families.csv
Labels: I Tools / workflow / repo

#9644 Noto Sans Bengali: Version 3.000 added
  ofl/notosansbengali/METADATA.pb
  ofl/notosansbengali/NotoSansBengali[wdth,wght].ttf
  ofl/notosansbengali/article/ARTICLE.en_us.html
Labels: I Font Upgrade, II Indic / Brahmic / Thai / Tai

#9604 Noto Sans Batak: Version 2.004; ttfautohint (v1.8.4.7-5d5b) added
  ofl/notosansbatak/METADATA.pb
  ofl/notosansbatak/NotoSansBatak-Regular.ttf
  ofl/notosansbatak/article/ARTICLE.en_us.html
Labels: I Font Upgrade, II Indic / Brahmic / Thai / Tai

#9565 Story Script: Version 1.000; ttfautohint (v1.8.4.7-5d5b) added
  ofl/storyscript/METADATA.pb
  ofl/storyscript/OFL.txt
  ofl/storyscript/StoryScript-Regular.ttf
  ofl/storyscript/article/ARTICLE.en_us.html
  ofl/storyscript/article/Story-Script-01.png
  ofl/storyscript/article/Story-Script-02.png
  ofl/storyscript/article/Story-Script-03.png
  ofl/storyscript/article/Story-Script-04.png
  ofl/storyscript/article/Story-Script-05.png
  ofl/storyscript/article/Story-Script-06.png
Labels: I New Font

#9658 Matangi: Version 3.004 added
  ofl/matangi/METADATA.pb
  ofl/matangi/Matangi[wght].ttf
  ofl/matangi/article/ARTICLE.en_us.html
Labels: I Font Upgrade, II Indic / Brahmic / Thai / Tai

#9562 Epunda Slab: Version 1.103 added
  ofl/epundaslab/EpundaSlab-Italic[wght].ttf
  ofl/epundaslab/EpundaSlab[wght].ttf
  ofl/epundaslab/METADATA.pb
Labels: I New Font

#9650 Initial push of TikTok Sans
  ofl/tiktoksans/METADATA.pb
  ofl/tiktoksans/OFL.txt
  ofl/tiktoksans/TikTokSans[opsz,slnt,wdth,wght].ttf
  ofl/tiktoksans/article/ARTICLE.en_us.html
  ofl/tiktoksans/article/article-1.png
  ofl/tiktoksans/article/article-2.png
  ofl/tiktoksans/article/article-3.png
  ofl/tiktoksans/article/article-4.png
Labels: I Tools / workflow / repo

#9679 Update Google profile
  catalog/designers/google/bio.html
  catalog/designers/google/google.png
  catalog/designers/google/info.pb
Labels: I Designer profile

#9665 Sirivennela: Version 1.000; ttfautohint (v1.8.4.7-5d5b) added
  ofl/sirivennela/METADATA.pb
  ofl/sirivennela/OFL.txt
  ofl/sirivennela/Sirivennela-Regular.ttf
  ofl/sirivennela/article/ARTICLE.en_us.html
Labels: -- Needs confirmation, I New Font, II Indic / Brahmic / Thai / Tai

#9504 Reem Kufi: Version 2.000 added
  ofl/reemkufi/DESCRIPTION.en_us.html
  ofl/reemkufi/METADATA.pb
  ofl/reemkufi/OFL.txt
  ofl/reemkufi/ReemKufi[wght].ttf
Labels: I Font Upgrade, II Arabic / Hebrew / Semitic / RTL

#9420 Amiri Quran: Version 1.003 added
  ofl/amiriquran/AmiriQuran-Regular.ttf
  ofl/amiriquran/DESCRIPTION.en_us.html
  ofl/amiriquran/METADATA.pb
  ofl/amiriquran/OFL.txt
Labels: -- Needs confirmation, I Font Upgrade, II Arabic / Hebrew / Semitic / RTL

#9695 Designer: update Google profile
  catalog/designers/google/bio.html
  catalog/designers/google/info.pb
Labels: I Designer profile

#9684 Add designer: Petr van Blokland
  catalog/designers/petrvanblokland/bio.html
  catalog/designers/petrvanblokland/info.pb
  catalog/designers/petrvanblokland/petrvanblokland.png
Labels: I Designer profile

#9680 Add designer: KH Type
  catalog/designers/khtype/bio.html
  catalog/designers/khtype/info.pb
  catalog/designers/khtype/khtype.png
Labels: I Designer profile

#9682 Add designer: Ben Buysse
  catalog/designers/benbuysse/benbuysse.png
  catalog/designers/benbuysse/bio.html
  catalog/designers/benbuysse/info.pb
Labels: I Designer profile

#9688 Story Script article
  ofl/storyscript/article/ARTICLE.en_us.html
  ofl/storyscript/article/Story-Script-01.png
  ofl/storyscript/article/Story-Script-02.png
  ofl/storyscript/article/Story-Script-03.png
  ofl/storyscript/article/Story-Script-04.png
  ofl/storyscript/article/Story-Script-05.png
  ofl/storyscript/article/Story-Script-06.png
Labels: I Article/Description

#9703 Add designer: Local Remote
  catalog/designers/localremote/bio.html
  catalog/designers/localremote/info.pb
  catalog/designers/localremote/localremote.png
Labels: I Designer profile

#9563 Epunda Sans: Version 2.205 added
  ofl/epundasans/EpundaSans-Italic[wght].ttf
  ofl/epundasans/EpundaSans[wght].ttf
  ofl/epundasans/METADATA.pb
Labels: I New Font

#9702 Add designer: Weizhong Zhang
  catalog/designers/weizhongzhang/bio.html
  catalog/designers/weizhongzhang/info.pb
  catalog/designers/weizhongzhang/weizhongzhang.png
Labels: I Designer profile

#9693 Tirra: Version 4.100 added
  ofl/tirra/METADATA.pb
  ofl/tirra/OFL.txt
  ofl/tirra/Tirra-Black.ttf
  ofl/tirra/Tirra-Bold.ttf
  ofl/tirra/Tirra-ExtraBold.ttf
  ofl/tirra/Tirra-Medium.ttf
  ofl/tirra/Tirra-Regular.ttf
  ofl/tirra/Tirra-SemiBold.ttf
  ofl/tirra/article/ARTICLE.en_us.html
Labels: I New Font, II African

#9708 Asimovian: Version 3.000; ttfautohint (v1.8.4.7-5d5b) added
  ofl/asimovian/Asimovian-Regular.ttf
  ofl/asimovian/METADATA.pb
  ofl/asimovian/OFL.txt
  ofl/asimovian/article/ARTICLE.en_us.html
  ofl/asimovian/article/asimovian1.png
  ofl/asimovian/article/asimovian2.png
  ofl/asimovian/article/asimovian3.png
  ofl/asimovian/article/asimovian4.png
  ofl/asimovian/article/asimovian5.png
Labels: I New Font
