Repository google/fonts, pull requests merged in 2025-10, with the labels that each got.

#9890 Cossette Texte: Version 1.002; ttfautohint (v1.8.4.7-5d5b) added
  ofl/cossettetexte/CossetteTexte-Bold.ttf
  ofl/cossettetexte/CossetteTexte-Regular.ttf
  ofl/cossettetexte/METADATA.pb
  ofl/cossettetexte/OFL.txt
Labels: I Font Upgrade

#9820 Kedebideri: Version 3.001 added
  ofl/kedebideri/Kedebideri-Black.ttf
  ofl/kedebideri/Kedebideri-Bold.ttf
  ofl/kedebideri/Kedebideri-ExtraBold.ttf
  ofl/kedebideri/Kedebideri-Medium.ttf
  ofl/kedebideri/Kedebideri-Regular.ttf
  ofl/kedebideri/Kedebideri-SemiBold.ttf
  ofl/kedebideri/METADATA.pb
  ofl/kedebideri/OFL.txt
  ofl/kedebideri/article/ARTICLE.en_us.html
Labels: I New Font, II Arabic / Hebrew / Semitic / RTL

#9892 Update to_sandbox.txt
  to_sandbox.txt
Labels: I Tools / workflow / repo

#9893 to_production list – 01/10/25
  to_production.txt
Labels: I Tools / workflow / repo

#9895 Fix Kedebideri OFL
  ofl/kedebideri/OFL.txt
Labels: I Metadata/OFL

#9416 Noto Sans Syriac Western: Version 3.000 added
  ofl/notosanssyriacwestern/DESCRIPTION.en_us.html
  ofl/notosanssyriacwestern/METADATA.pb
  ofl/notosanssyriacwestern/NotoSansSyriacWestern[wght].ttf
  ofl/notosanssyriacwestern/OFL.txt
  ofl/notosanssyriacwestern/article/ARTICLE.en_us.html
Labels: I New Font, II Arabic / Hebrew / Semitic / RTL

#9902 Stack Sans Text: Version 1.000 added
  ofl/stacksanstext/METADATA.pb
  ofl/stacksanstext/OFL.txt
  ofl/stacksanstext/StackSansText[wght].ttf
  ofl/stacksanstext/article/ARTICLE.en_us.html
  ofl/stacksanstext/article/stacksans01.jpg
  ofl/stacksanstext/article/stacksans02.jpg
  ofl/stacksanstext/article/stacksans03.jpg
  ofl/stacksanstext/article/stacksans04.jpg
Labels: I New Font
