Repository google/fonts, pull requests merged in 2025-02, with the labels that each got.

#9046 Adding designer info for 42dot
  catalog/designers/42dot/42dot.jpg
  catalog/designers/42dot/bio.html
  catalog/designers/42dot/info.pb
Labels: I Designer profile

#9050 Playwrite BE WAL: Version 1.003 added
  ofl/playwritebewal/METADATA.pb
  ofl/playwritebewal/PlaywriteBEWAL[wght].ttf
  ofl/playwritebewal/article/ARTICLE.en_us.html
  ofl/playwritebewal/article/Playwrite-Belgie-Walloon-1.png
  ofl/playwritebewal/article/Playwrite-Belgie-Walloon-2.png
  ofl/playwritebewal/article/Playwrite-Belgique-Wallonie-B-1.png
  ofl/playwritebewal/article/Playwrite-Belgique-Wallonie-B-2.png
  ofl/playwritebewal/article/Playwrite-Belgique-Wallonie-B-3.png
Labels: I Font Upgrade, P2

#8908 Colorfonts description
  ofl/amiriquran/DESCRIPTION.en_us.html
  ofl/arefruqaaink/DESCRIPTION.en_us.html
  ofl/blakaink/DESCRIPTION.en_us.html
  ofl/bungeespice/article/ARTICLE.en_us.html
  ofl/bungeetint/article/ARTICLE.en_us.html
  ofl/cairoplay/DESCRIPTION.en_us.html
  ofl/foldit/DESCRIPTION.en_us.html
  ofl/honk/DESCRIPTION.en_us.html
  ofl/kalnia/DESCRIPTION.en_us.html
  ofl/kalnia/article/ARTICLE.en_us.html
  ofl/kalniaglaze/article/ARTICLE.en_us.html
  ofl/nabla/DESCRIPTION.en_us.html
  ofl/notocoloremoji/DESCRIPTION.en_us.html
  ofl/notoznamennymusicalnotation/DESCRIPTION.en_us.html
  ofl/reemkufifun/DESCRIPTION.en_us.html
  ofl/reemkufiink/DESCRIPTION.en_us.html
  ofl/sixtyfourconvergence/article/ARTICLE.en_us.html
Labels: -- Needs manager's opinion, I Article/Description

#9051 Maven Pro: Version 2.103 added
  ofl/mavenpro/METADATA.pb
  ofl/mavenpro/MavenPro[wght].ttf
  ofl/mavenpro/OFL.txt
Labels: I Font Upgrade

#9054 lang v0.7.3
  lang/.github/workflows/test.yml
  lang/.gitignore
  lang/Cargo.toml
  lang/Lib/gflanguages/data/languages/agq_Latn.textproto
  lang/Lib/gflanguages/data/languages/apd_Latn.textproto
  lang/Lib/gflanguages/data/languages/bax_Latn.textproto
  lang/Lib/gflanguages/data/languages/buc_Latn.textproto
  lang/Lib/gflanguages/data/languages/cu_Cyrl.textproto
  lang/Lib/gflanguages/data/languages/djc_Latn.textproto
  lang/Lib/gflanguages/data/languages/dv_Diak.textproto
  lang/Lib/gflanguages/data/languages/dzg_Latn.textproto
  lang/Lib/gflanguages/data/languages/ema_Latn.textproto
  lang/Lib/gflanguages/data/languages/en_Latn.textproto
  lang/Lib/gflanguages/data/languages/gby_Latn.textproto
  lang/Lib/gflanguages/data/languages/gvl_Latn.textproto
  lang/Lib/gflanguages/data/languages/lom_Latn.textproto
  lang/Lib/gflanguages/data/languages/mg_Latn.textproto
  lang/Lib/gflanguages/data/languages/nl_Latn.textproto
  lang/Lib/gflanguages/data/languages/nmn_Latn.textproto
  lang/Lib/gflanguages/data/languages/shu_Latn.textproto
  lang/Lib/gflanguages/data/languages/snk_Latn.textproto
  lang/Lib/gflanguages/data/languages/tda_Latn.textproto
  lang/Lib/gflanguages/data/languages/ttq_Latn.textproto
  lang/Lib/gflanguages/data/languages/tum_Latn.textproto
  lang/Lib/gflanguages/data/languages/wdt_Latn.textproto
  lang/Lib/gflanguages/data/languages/yo_Latn.textproto
  lang/Lib/gflanguages/data/scripts/Diak.textproto
  lang/build.rs
  lang/pyproject.toml
Labels: I Lang

#9066 Bitter: Version 3.021 added
  ofl/bitter/Bitter-Italic[wght].ttf
  ofl/bitter/Bitter[wght].ttf
  ofl/bitter/METADATA.pb
Labels: I Font Upgrade, I Small Fix

#9068 Add Designer: Seun Badejo
  catalog/designers/seunbadejo/bio.html
  catalog/designers/seunbadejo/info.pb
  catalog/designers/seunbadejo/seunbadejo.png
Labels: I Designer profile

#9028 Big Shoulders Inline: Version 2.002 added
  ofl/bigshouldersinline/BigShouldersInline[opsz,wght].ttf
  ofl/bigshouldersinline/DESCRIPTION.en_us.html
  ofl/bigshouldersinline/METADATA.pb
  ofl/bigshouldersinline/OFL.txt
Labels: I New Font, I Font Upgrade, P3

#9029 Big Shoulders Stencil: Version 2.001 added
  ofl/bigshouldersstencil/BigShouldersStencil[opsz,wght].ttf
  ofl/bigshouldersstencil/DESCRIPTION.en_us.html
  ofl/bigshouldersstencil/METADATA.pb
  ofl/bigshouldersstencil/OFL.txt
Labels: I New Font, I Font Upgrade, P3

#9027 Big Shoulders: Version 2.002 added
  ofl/bigshoulders/BigShoulders[opsz,wght].ttf
  ofl/bigshoulders/DESCRIPTION.en_us.html
  ofl/bigshoulders/METADATA.pb
  ofl/bigshoulders/OFL.txt
Labels: I New Font, I Font Upgrade, P3

#9069 Montagu Slab: minisite url added to metadata
  ofl/montaguslab/METADATA.pb
Labels: I Metadata/OFL

#9072 Liter: designer updated in metadata.pb
  ofl/liter/METADATA.pb
Labels: I Metadata/OFL

#9074 Bio Jeff Davis (Comic Relief)
  catalog/designers/jeffdavis/bio.html
  catalog/designers/jeffdavis/info.pb
  catalog/designers/jeffdavis/loudifier.png
Labels: I Designer profile

#9073 lists of the 13th of February
  to_delist.txt
  to_production.txt
  to_sandbox.txt
Labels: I Tools / workflow / repo

#9075 Comic Relief: Version 1.200; ttfautohint (v1.8.4.7-5d5b) added
  ofl/comicrelief/ComicRelief-Bold.ttf
  ofl/comicrelief/ComicRelief-Regular.ttf
  ofl/comicrelief/DESCRIPTION.en_us.html
  ofl/comicrelief/METADATA.pb
  ofl/comicrelief/OFL.txt
Labels: I New Font, II Accepted, -- fontforge/fontlab/fontcreator

#9076 Readex Pro: Version 1.205 added
  ofl/readexpro/DESCRIPTION.en_us.html
  ofl/readexpro/METADATA.pb
  ofl/readexpro/ReadexPro[HEXP,wght].ttf
Labels: I Font Upgrade, I Font Bug

#9084 PPS emojis list updated
  ofl/playpensans/article/ARTICLE.en_us.html
Labels: I Article/Description

#9092 Boldonse: Version 1.000; ttfautohint (v1.8.4.7-5d5b) added
  ofl/boldonse/Boldonse-Regular.ttf
  ofl/boldonse/METADATA.pb
  ofl/boldonse/OFL.txt
  ofl/boldonse/article/ARTICLE.en_us.html
  ofl/boldonse/article/image1.jpg
  ofl/boldonse/article/image2.jpg
  ofl/boldonse/article/image3.jpg
  ofl/boldonse/article/image4.jpg
Labels: I New Font

#9090 Noto Sans Thai Looped: Version 2.000 added
  ofl/notosansthailooped/METADATA.pb
  ofl/notosansthailooped/NotoSansThaiLooped-Black.ttf
  ofl/notosansthailooped/NotoSansThaiLooped-Bold.ttf
  ofl/notosansthailooped/NotoSansThaiLooped-ExtraBold.ttf
  ofl/notosansthailooped/NotoSansThaiLooped-ExtraLight.ttf
  ofl/notosansthailooped/NotoSansThaiLooped-Light.ttf
  ofl/notosansthailooped/NotoSansThaiLooped-Medium.ttf
  ofl/notosansthailooped/NotoSansThaiLooped-Regular.ttf
  ofl/notosansthailooped/NotoSansThaiLooped-SemiBold.ttf
  ofl/notosansthailooped/NotoSansThaiLooped-Thin.ttf
  ofl/notosansthailooped/NotoSansThaiLooped[wdth,wght].ttf
  ofl/notosansthailooped/OFL.txt
Labels: III VF Replacement, I Font Upgrade

#9077 Bytesized: Version 1.000 added
  ofl/bytesized/Bytesized-Regular.ttf
  ofl/bytesized/METADATA.pb
  ofl/bytesized/OFL.txt
  ofl/bytesized/article/ARTICLE.en_us.html
  ofl/bytesized/article/Image1.png
Labels: I New Font

#9102 Winky Sans: Version 1.205 added
  .github/workflows/test.yaml
  ofl/winkysans/METADATA.pb
  ofl/winkysans/OFL.txt
  ofl/winkysans/WinkySans-Italic[wght].ttf
  ofl/winkysans/WinkySans[wght].ttf
  ofl/winkysans/article/ARTICLE.en_us.html
  ofl/winkysans/article/image1.png
  ofl/winkysans/article/image10.png
  ofl/winkysans/article/image2.png
  ofl/winkysans/article/image3.png
  ofl/winkysans/article/image4.png
  ofl/winkysans/article/image5.png
  ofl/winkysans/article/image6.png
  ofl/winkysans/article/image7.png
  ofl/winkysans/article/image8.png
  ofl/winkysans/article/image9.png
Labels: I New Font

#9122 Gidole: Version 2.100; ttfautohint (v1.8.4.7-5d5b) added
  ofl/gidole/Gidole-Regular.ttf
  ofl/gidole/METADATA.pb
  ofl/gidole/OFL.txt
  ofl/gidole/article/1Gidole.png
  ofl/gidole/article/2GidoleCapital.png
  ofl/gidole/article/3GidoleLowercase.png
  ofl/gidole/article/4GidoleNumbers.png
  ofl/gidole/article/ARTICLE.en_us.html
Labels: I New Font, II Submission

#9104 Update families.csv - Winky
  tags/all/families.csv
Labels: I Tools / workflow / repo
