Repository google/fonts, pull requests merged in 2025-01, with the labels that each got.

#8519 AHM: Version 2.001 added
  ofl/atkinsonhyperlegiblemono/AtkinsonHyperlegibleMono-Italic[wght].ttf
  ofl/atkinsonhyperlegiblemono/AtkinsonHyperlegibleMono[wght].ttf
  ofl/atkinsonhyperlegiblemono/METADATA.pb
  ofl/atkinsonhyperlegiblemono/OFL.txt
  ofl/atkinsonhyperlegiblemono/article/ARTICLE.en_us.html
  ofl/atkinsonhyperlegiblemono/article/image1.png
  ofl/atkinsonhyperlegiblemono/article/image2.png
Labels: I New Font

#8813 AHN: Version 2.001 added
  ofl/atkinsonhyperlegiblenext/AtkinsonHyperlegibleNext-Italic[wght].ttf
  ofl/atkinsonhyperlegiblenext/AtkinsonHyperlegibleNext[wght].ttf
  ofl/atkinsonhyperlegiblenext/METADATA.pb
  ofl/atkinsonhyperlegiblenext/OFL.txt
  ofl/atkinsonhyperlegiblenext/article/ARTICLE.en_us.html
  ofl/atkinsonhyperlegiblenext/article/image1.png
  ofl/atkinsonhyperlegiblenext/article/image2.png
Labels: I New Font

#8817 Atkinson: metadatas update
  ofl/atkinsonhyperlegiblemono/METADATA.pb
  ofl/atkinsonhyperlegiblenext/METADATA.pb
Labels: I Designer profile

#8818 Inclusive Sans: Version 2.004; ttfautohint (v1.8.4.7-5d5b) added
  ofl/inclusivesans/InclusiveSans-Italic.ttf
  ofl/inclusivesans/InclusiveSans-Regular.ttf
  ofl/inclusivesans/METADATA.pb
Labels: III Expand styles, III VF Replacement, I Font Upgrade

#8821 Primary language added to Playwrite AR and CO Guides
  ofl/playwritearguides/METADATA.pb
  ofl/playwritecoguides/METADATA.pb
Labels: I Metadata/OFL

#8593 Cormorant Garamond: Version 4.001 added
  ofl/cormorantgaramond/CormorantGaramond-Bold.ttf
  ofl/cormorantgaramond/CormorantGaramond-BoldItalic.ttf
  ofl/cormorantgaramond/CormorantGaramond-Italic.ttf
  ofl/cormorantgaramond/CormorantGaramond-Italic[wght].ttf
  ofl/cormorantgaramond/CormorantGaramond-Light.ttf
  ofl/cormorantgaramond/CormorantGaramond-LightItalic.ttf
  ofl/cormorantgaramond/CormorantGaramond-Medium.ttf
  ofl/cormorantgaramond/CormorantGaramond-MediumItalic.ttf
  ofl/cormorantgaramond/CormorantGaramond-Regular.ttf
  ofl/cormorantgaramond/CormorantGaramond-SemiBold.ttf
  ofl/cormorantgaramond/CormorantGaramond-SemiBoldItalic.ttf
  ofl/cormorantgaramond/CormorantGaramond[wght].ttf
  ofl/cormorantgaramond/METADATA.pb
Labels: III VF Replacement, I Font Upgrade

#8881 Inclusive Sans: Version 2.004 added
  ofl/inclusivesans/InclusiveSans-Italic.ttf
  ofl/inclusivesans/InclusiveSans-Italic[wght].ttf
  ofl/inclusivesans/InclusiveSans-Regular.ttf
  ofl/inclusivesans/InclusiveSans[wght].ttf
  ofl/inclusivesans/METADATA.pb
Labels: III VF Replacement, I Font Upgrade

#8882 Add designer: Anton Skugarov
  catalog/designers/antonskugarov/antonskugarov.png
  catalog/designers/antonskugarov/bio.html
  catalog/designers/antonskugarov/info.pb
Labels: I Designer profile

#8883 Add designer: Alexandr Ivanin
  catalog/designers/alexandrivanin/alexandrivanin.png
  catalog/designers/alexandrivanin/bio.html
  catalog/designers/alexandrivanin/info.pb
Labels: I Designer profile

#8819 Liter: Version 1.004; ttfautohint (v1.8.4.7-5d5b) added
  ofl/liter/Liter-Regular.ttf
  ofl/liter/METADATA.pb
  ofl/liter/OFL.txt
  ofl/liter/article/ARTICLE.en_us.html
  ofl/liter/article/image1.png
  ofl/liter/article/image2.png
  ofl/liter/article/image3.png
  ofl/liter/article/image4.png
Labels: I New Font

#8907 Yarndings 20 Charted: Version 1.001; ttfautohint (v1.8.4.7-5d5b) added
  ofl/yarndings20charted/METADATA.pb
  ofl/yarndings20charted/Yarndings20Charted-Regular.ttf
Labels: I Font Upgrade

#8906 Yarndings 12 Charted: Version 1.001; ttfautohint (v1.8.4.7-5d5b) added
  ofl/yarndings12charted/METADATA.pb
  ofl/yarndings12charted/Yarndings12Charted-Regular.ttf
Labels: I Font Upgrade

#8905 Yarndings 20: Version 1.001; ttfautohint (v1.8.4.7-5d5b) added
  ofl/yarndings20/METADATA.pb
  ofl/yarndings20/Yarndings20-Regular.ttf
Labels: I Font Upgrade

#8904 Yarndings 12: Version 1.001; ttfautohint (v1.8.4.7-5d5b) added
  ofl/yarndings12/METADATA.pb
  ofl/yarndings12/Yarndings12-Regular.ttf
Labels: I Font Upgrade

#8903 Micro 5 Charted: Version 1.001; ttfautohint (v1.8.4.7-5d5b) added
  ofl/micro5charted/METADATA.pb
  ofl/micro5charted/Micro5Charted-Regular.ttf
Labels: I Font Upgrade

#8902 Micro 5: Version 1.001; ttfautohint (v1.8.4.7-5d5b) added
  ofl/micro5/METADATA.pb
  ofl/micro5/Micro5-Regular.ttf
Labels: I Font Upgrade

#8900 Jersey 20 Charted: Version 1.001; ttfautohint (v1.8.4.7-5d5b) added
  ofl/jersey20charted/Jersey20Charted-Regular.ttf
  ofl/jersey20charted/METADATA.pb
Labels: I Font Upgrade

#8899 Jersey 15 Charted: Version 1.001; ttfautohint (v1.8.4.7-5d5b) added
  ofl/jersey15charted/Jersey15Charted-Regular.ttf
  ofl/jersey15charted/METADATA.pb
Labels: I Font Upgrade

#8898 Jersey 10 Charted: Version 1.001; ttfautohint (v1.8.4.7-5d5b) added
  ofl/jersey10charted/Jersey10Charted-Regular.ttf
  ofl/jersey10charted/METADATA.pb
Labels: I Font Upgrade

#8897 Jersey 25: Version 1.001; ttfautohint (v1.8.4.7-5d5b) added
  ofl/jersey25/Jersey25-Regular.ttf
  ofl/jersey25/METADATA.pb
Labels: I Font Upgrade

#8896 Jersey 20: Version 1.001; ttfautohint (v1.8.4.7-5d5b) added
  ofl/jersey20/Jersey20-Regular.ttf
  ofl/jersey20/METADATA.pb
Labels: I Font Upgrade

#8895 Jersey 15: Version 1.001; ttfautohint (v1.8.4.7-5d5b) added
  ofl/jersey15/Jersey15-Regular.ttf
  ofl/jersey15/METADATA.pb
Labels: I Font Upgrade

#8894 Jersey 10: Version 1.001; ttfautohint (v1.8.4.7-5d5b) added
  ofl/jersey10/Jersey10-Regular.ttf
  ofl/jersey10/METADATA.pb
Labels: I Font Upgrade

#8893 Jacquarda Bastarda 9 Charted: Version 1.001; ttfautohint (v1.8.4.7-5d5b) added
  ofl/jacquardabastarda9charted/JacquardaBastarda9Charted-Regular.ttf
  ofl/jacquardabastarda9charted/METADATA.pb
Labels: I Font Upgrade

#8892 Jacquarda Bastarda 9: Version 1.001; ttfautohint (v1.8.4.7-5d5b) added
  ofl/jacquardabastarda9/JacquardaBastarda9-Regular.ttf
  ofl/jacquardabastarda9/METADATA.pb
Labels: I Font Upgrade

#8891 Jacquard 24 Charted: Version 1.002 added
  ofl/jacquard24charted/Jacquard24Charted-Regular.ttf
  ofl/jacquard24charted/METADATA.pb
Labels: I Font Upgrade

#8889 Jacquard 12 Charted: Version 1.002 added
  ofl/jacquard12charted/Jacquard12Charted-Regular.ttf
  ofl/jacquard12charted/METADATA.pb
Labels: I Font Upgrade

#8888 Jacquard 12: Version 1.002; ttfautohint (v1.8.4.7-5d5b) added
  ofl/jacquard12/Jacquard12-Regular.ttf
  ofl/jacquard12/METADATA.pb
Labels: I Font Upgrade

#8909 [notoserifhentaigana] Remove primary script and language
  ofl/notoserifhentaigana/METADATA.pb
Labels: --- API Tofu, I Metadata/OFL

#8922 Playwrite AU NSW: Version 1.003 added
  ofl/playwriteaunsw/METADATA.pb
  ofl/playwriteaunsw/PlaywriteAUNSW[wght].ttf
  ofl/playwriteaunsw/article/ARTICLE.en_us.html
Labels: I Font Upgrade, P2

#8921 Playwrite AT: Version 1.003 added
  ofl/playwriteat/METADATA.pb
  ofl/playwriteat/PlaywriteAT-Italic[wght].ttf
  ofl/playwriteat/PlaywriteAT[wght].ttf
  ofl/playwriteat/article/ARTICLE.en_us.html
Labels: I Font Upgrade, P2

#8918 42 Dots Sans: primary script update
  ofl/42dotsans/METADATA.pb
Labels: I Metadata/OFL

#7573 Buenard: Version 2.000 added
  ofl/buenard/Buenard-Bold.ttf
  ofl/buenard/Buenard-Regular.ttf
  ofl/buenard/Buenard[wght].ttf
  ofl/buenard/DESCRIPTION.en_us.html
  ofl/buenard/FONTLOG.txt
  ofl/buenard/METADATA.pb
  ofl/buenard/OFL.txt
Labels: III VF Replacement, I Font Upgrade

#8923 Playwrite AU QLD: Version 1.003 added
  ofl/playwriteauqld/METADATA.pb
  ofl/playwriteauqld/PlaywriteAUQLD[wght].ttf
  ofl/playwriteauqld/article/ARTICLE.en_us.html
Labels: I Font Upgrade, P2

#8924 Playwrite AU SA: Version 1.003 added
  ofl/playwriteausa/METADATA.pb
  ofl/playwriteausa/PlaywriteAUSA[wght].ttf
  ofl/playwriteausa/article/ARTICLE.en_us.html
Labels: I Font Upgrade, P2

#8926 Playwrite AU TAS: Version 1.003 added
  ofl/playwriteautas/METADATA.pb
  ofl/playwriteautas/PlaywriteAUTAS[wght].ttf
  ofl/playwriteautas/article/ARTICLE.en_us.html
Labels: I Font Upgrade, P2

#8928 Playwrite AU VIC: Version 1.003 added
  ofl/playwriteauvic/METADATA.pb
  ofl/playwriteauvic/PlaywriteAUVIC[wght].ttf
  ofl/playwriteauvic/article/ARTICLE.en_us.html
Labels: I Font Upgrade, P2

#8930 Playwrite CA: Version 1.003 added
  ofl/playwriteca/METADATA.pb
  ofl/playwriteca/PlaywriteCA[wght].ttf
  ofl/playwriteca/article/ARTICLE.en_us.html
Labels: I Font Upgrade, P2

#8929 Playwrite BR: Version 1.003 added
  ofl/playwritebr/DESCRIPTION.en_us.html
  ofl/playwritebr/METADATA.pb
  ofl/playwritebr/PlaywriteBR[wght].ttf
  ofl/playwritebr/article/ARTICLE.en_us.html
Labels: I Font Upgrade, P2

#8933 Lists of the 16th of January 25
  to_production.txt
  to_sandbox.txt
Labels: I Tools / workflow / repo

#8974 Update families.csv with updated Valentine's tag data
  tags/all/families.csv
Labels: I API / Website / Platform

#8971 Maname: Version 1.002; ttfautohint (v1.8.4.7-5d5b) added
  ofl/maname/METADATA.pb
  ofl/maname/Maname-Regular.ttf
Labels: I Font Upgrade, P3

#8985 atkinson article - update
  ofl/atkinsonhyperlegiblemono/article/ARTICLE.en_us.html
  ofl/atkinsonhyperlegiblemono/article/image1.gif
  ofl/atkinsonhyperlegiblemono/article/image1.png
  ofl/atkinsonhyperlegiblemono/article/image2.gif
  ofl/atkinsonhyperlegiblemono/article/image2.png
  ofl/atkinsonhyperlegiblemono/article/image3.png
  ofl/atkinsonhyperlegiblemono/article/image4.png
  ofl/atkinsonhyperlegiblemono/article/image5.png
  ofl/atkinsonhyperlegiblenext/article/ARTICLE.en_us.html
  ofl/atkinsonhyperlegiblenext/article/image1.gif
  ofl/atkinsonhyperlegiblenext/article/image1.png
  ofl/atkinsonhyperlegiblenext/article/image2.gif
  ofl/atkinsonhyperlegiblenext/article/image2.png
  ofl/atkinsonhyperlegiblenext/article/image3.png
  ofl/atkinsonhyperlegiblenext/article/image4.png
  ofl/atkinsonhyperlegiblenext/article/image5.png
Labels: I Article/Description

#8988 Space Mono: Version 1.003; ttfautohint (v1.8.4.7-5d5b) added
  ofl/spacemono/DESCRIPTION.en_us.html
  ofl/spacemono/METADATA.pb
  ofl/spacemono/OFL.txt
  ofl/spacemono/SpaceMono-Bold.ttf
  ofl/spacemono/SpaceMono-BoldItalic.ttf
  ofl/spacemono/SpaceMono-Italic.ttf
  ofl/spacemono/SpaceMono-Regular.ttf
Labels: I Font Upgrade

#8979 Playwrite IT Trad: Version 1.003 added
  ofl/playwriteittrad/METADATA.pb
  ofl/playwriteittrad/PlaywriteITTrad[wght].ttf
  ofl/playwriteittrad/article/ARTICLE.en_us.html
Labels: I Font Upgrade, P2

#8977 Playwrite NG Modern: Version 1.003 added
  ofl/playwritengmodern/METADATA.pb
  ofl/playwritengmodern/PlaywriteNGModern[wght].ttf
  ofl/playwritengmodern/article/ARTICLE.en_us.html
Labels: I Font Upgrade, P2

#8976 Playwrite MX: Version 1.003 added
  ofl/playwritemx/METADATA.pb
  ofl/playwritemx/PlaywriteMX[wght].ttf
  ofl/playwritemx/article/ARTICLE.en_us.html
Labels: I Font Upgrade, P2

#8973 Playwrite IT Moderna: Version 1.003 added
  ofl/playwriteitmoderna/METADATA.pb
  ofl/playwriteitmoderna/PlaywriteITModerna[wght].ttf
  ofl/playwriteitmoderna/article/ARTICLE.en_us.html
Labels: I Font Upgrade, P2

#8956 Playwrite IN: Version 1.003 added
  ofl/playwritein/METADATA.pb
  ofl/playwritein/PlaywriteIN[wght].ttf
  ofl/playwritein/article/ARTICLE.en_us.html
Labels: I Font Upgrade, P2

#8955 Playwrite IE: Version 1.003 added
  ofl/playwriteie/METADATA.pb
  ofl/playwriteie/PlaywriteIE[wght].ttf
  ofl/playwriteie/article/ARTICLE.en_us.html
Labels: I Font Upgrade, P2

#8954 Playwrite ID: Version 1.003 added
  ofl/playwriteid/METADATA.pb
  ofl/playwriteid/PlaywriteID[wght].ttf
  ofl/playwriteid/article/ARTICLE.en_us.html
Labels: I Font Upgrade, P2

#8953 Playwrite HU: Version 1.003 added
  ofl/playwritehu/METADATA.pb
  ofl/playwritehu/PlaywriteHU[wght].ttf
  ofl/playwritehu/article/ARTICLE.en_us.html
Labels: I Font Upgrade, P2

#8952 Playwrite HR Lijeva: Version 1.003 added
  ofl/playwritehrlijeva/METADATA.pb
  ofl/playwritehrlijeva/PlaywriteHRLijeva[wght].ttf
  ofl/playwritehrlijeva/article/ARTICLE.en_us.html
Labels: I Font Upgrade, P2

#8951 Playwrite HR: Version 1.003 added
  ofl/playwritehr/METADATA.pb
  ofl/playwritehr/PlaywriteHR[wght].ttf
  ofl/playwritehr/article/ARTICLE.en_us.html
Labels: I Font Upgrade, P2

#8950 Playwrite GB S: Version 1.003 added
  ofl/playwritegbs/METADATA.pb
  ofl/playwritegbs/PlaywriteGBS-Italic[wght].ttf
  ofl/playwritegbs/PlaywriteGBS[wght].ttf
  ofl/playwritegbs/article/ARTICLE.en_us.html
Labels: I Font Upgrade, P2

#8948 Playwrite FR Trad: Version 1.003 added
  ofl/playwritefrtrad/METADATA.pb
  ofl/playwritefrtrad/PlaywriteFRTrad[wght].ttf
  ofl/playwritefrtrad/article/ARTICLE.en_us.html
Labels: I Font Upgrade, P2

#8945 Playwrite ES: Version 1.003 added
  ofl/playwritees/METADATA.pb
  ofl/playwritees/PlaywriteES[wght].ttf
  ofl/playwritees/article/ARTICLE.en_us.html
Labels: I Font Upgrade, P2

#8944 Playwrite DK Uloopet: Version 1.003 added
  ofl/playwritedkuloopet/METADATA.pb
  ofl/playwritedkuloopet/PlaywriteDKUloopet[wght].ttf
  ofl/playwritedkuloopet/article/ARTICLE.en_us.html
Labels: I Font Upgrade, P2

#8943 Playwrite DK Loopet: Version 1.003 added
  ofl/playwritedkloopet/METADATA.pb
  ofl/playwritedkloopet/PlaywriteDKLoopet[wght].ttf
  ofl/playwritedkloopet/article/ARTICLE.en_us.html
Labels: I Font Upgrade, P2

#8942 Playwrite DE VA: Version 1.003 added
  ofl/playwritedeva/METADATA.pb
  ofl/playwritedeva/PlaywriteDEVA[wght].ttf
  ofl/playwritedeva/article/ARTICLE.en_us.html
Labels: I Font Upgrade, P2

#8941 Playwrite DE SAS: Version 1.003 added
  ofl/playwritedesas/METADATA.pb
  ofl/playwritedesas/PlaywriteDESAS[wght].ttf
  ofl/playwritedesas/article/ARTICLE.en_us.html
Labels: I Font Upgrade, P2

#8939 Playwrite DE Grund: Version 1.003 added
  ofl/playwritedegrund/METADATA.pb
  ofl/playwritedegrund/PlaywriteDEGrund[wght].ttf
  ofl/playwritedegrund/article/ARTICLE.en_us.html
Labels: I Font Upgrade, P2

#8936 Playwrite CU: Version 1.003 added
  ofl/playwritecu/METADATA.pb
  ofl/playwritecu/PlaywriteCU[wght].ttf
  ofl/playwritecu/article/ARTICLE.en_us.html
Labels: I Font Upgrade, P2

#8935 Playwrite CO: Version 1.003 added
  ofl/playwriteco/METADATA.pb
  ofl/playwriteco/PlaywriteCO[wght].ttf
  ofl/playwriteco/article/ARTICLE.en_us.html
Labels: I Font Upgrade, P2

#8934 Playwrite CL: Version 1.003 added
  ofl/playwritecl/METADATA.pb
  ofl/playwritecl/PlaywriteCL[wght].ttf
  ofl/playwritecl/article/ARTICLE.en_us.html
Labels: I Font Upgrade, P2

#9004 Playwrite VN: Version 1.003 added
  ofl/playwritevn/METADATA.pb
  ofl/playwritevn/PlaywriteVN[wght].ttf
  ofl/playwritevn/article/ARTICLE.en_us.html
Labels: I Font Upgrade, P2

#9003 Playwrite US Trad: Version 1.003 added
  ofl/playwriteustrad/METADATA.pb
  ofl/playwriteustrad/PlaywriteUSTrad[wght].ttf
  ofl/playwriteustrad/article/ARTICLE.en_us.html
Labels: I Font Upgrade, P2

#9002 Playwrite US Modern: Version 1.003 added
  ofl/playwriteusmodern/METADATA.pb
  ofl/playwriteusmodern/PlaywriteUSModern[wght].ttf
  ofl/playwriteusmodern/article/ARTICLE.en_us.html
Labels: I Font Upgrade, P2

#9001 Playwrite TZ: Version 1.003 added
  ofl/playwritetz/METADATA.pb
  ofl/playwritetz/PlaywriteTZ[wght].ttf
  ofl/playwritetz/article/ARTICLE.en_us.html
Labels: I Font Upgrade, P2

#9000 Playwrite SK: Version 1.003 added
  ofl/playwritesk/METADATA.pb
  ofl/playwritesk/PlaywriteSK[wght].ttf
  ofl/playwritesk/article/ARTICLE.en_us.html
Labels: I Font Upgrade, P2

#8999 Playwrite RO: Version 1.003 added
  ofl/playwritero/METADATA.pb
  ofl/playwritero/PlaywriteRO[wght].ttf
  ofl/playwritero/article/ARTICLE.en_us.html
Labels: I Font Upgrade, P2

#8998 Playwrite PT: Version 1.003 added
  ofl/playwritept/METADATA.pb
  ofl/playwritept/PlaywritePT[wght].ttf
  ofl/playwritept/article/ARTICLE.en_us.html
Labels: I Font Upgrade, P2

#8997 Playwrite PL: Version 1.003 added
  ofl/playwritepl/METADATA.pb
  ofl/playwritepl/PlaywritePL[wght].ttf
  ofl/playwritepl/article/ARTICLE.en_us.html
Labels: I Font Upgrade, P2

#8996 Playwrite PE: Version 1.003 added
  ofl/playwritepe/METADATA.pb
  ofl/playwritepe/PlaywritePE[wght].ttf
  ofl/playwritepe/article/ARTICLE.en_us.html
Labels: I Font Upgrade, P2

#8995 Playwrite NZ: Version 1.003 added
  ofl/playwritenz/METADATA.pb
  ofl/playwritenz/PlaywriteNZ[wght].ttf
  ofl/playwritenz/article/ARTICLE.en_us.html
Labels: I Font Upgrade, P2

#8994 Playwrite NO: Version 1.003 added
  ofl/playwriteno/METADATA.pb
  ofl/playwriteno/PlaywriteNO[wght].ttf
  ofl/playwriteno/article/ARTICLE.en_us.html
Labels: I Font Upgrade, P2

#8992 Playwrite NL: Version 1.003 added
  ofl/playwritenl/METADATA.pb
  ofl/playwritenl/PlaywriteNL[wght].ttf
  ofl/playwritenl/article/ARTICLE.en_us.html
Labels: I Font Upgrade, P2

#8990 Shafarik: Version 1.002; ttfautohint (v1.8.4.7-5d5b) added
  ofl/shafarik/METADATA.pb
  ofl/shafarik/OFL.txt
  ofl/shafarik/Shafarik-Regular.ttf
Labels: I New Font, II Accepted, sub-issue

#8991 Monomakh: Version 1.200; ttfautohint (v1.8.4.7-5d5b) added
  ofl/monomakh/DESCRIPTION.en_us.html
  ofl/monomakh/METADATA.pb
  ofl/monomakh/Monomakh-Regular.ttf
  ofl/monomakh/OFL.txt
Labels: I New Font, II Submission, P3

#9010 yellowtype: update url
  catalog/designers/yellowtype/bio.html
Labels: I Designer profile

#9016 Pochaevsk: Version 1.210; ttfautohint (v1.8.4.7-5d5b) added
  ofl/pochaevsk/DESCRIPTION.en_us.html
  ofl/pochaevsk/METADATA.pb
  ofl/pochaevsk/OFL.txt
  ofl/pochaevsk/Pochaevsk-Regular.ttf
Labels: I New Font, I Font Upgrade, II Submission

#9017 Ponomar: Version 1.302; ttfautohint (v1.8.4.7-5d5b) added
  ofl/ponomar/METADATA.pb
  ofl/ponomar/OFL.txt
  ofl/ponomar/Ponomar-Regular.ttf
Labels: I New Font, II Accepted, P3, sub-issue

#9026 Triodion: Version 1.202; ttfautohint (v1.8.4.7-5d5b) added
  ofl/triodion/METADATA.pb
  ofl/triodion/OFL.txt
  ofl/triodion/Triodion-Regular.ttf
Labels: I New Font, I Font Upgrade, II Accepted, P3, sub-issue
